# Interpolation
This notebook runs a linear interpolation of SLA data in the month of Jan 2020.

In [1]:
import pandas as pd
import numpy as np
import os

import matplotlib.pyplot as plt
import matplotlib.font_manager as fm

font_path = "/home/mhen/.local/share/fonts/IBMPlexSerif-Regular.ttf"
font_prop = fm.FontProperties(fname=font_path)

plt.rcParams["font.family"] = font_prop.get_name()
plt.rcParams["font.sans-serif"] = [font_prop.get_name()]

from GPSat.utils import WGS84toEASE2
from GPSat.local_experts import LocalExpertOI, get_results_from_h5file
from GPSat.postprocessing import smooth_hyperparameters, glue_local_predictions_1d

2026-05-18 19:07:26.563042: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2026-05-18 19:07:26.595744: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2026-05-18 19:07:26.595778: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2026-05-18 19:07:26.597075: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2026-05-18 19:07:26.603053: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI AVX512_BF16 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2026-05-18 19:07:27.750076: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT

In [2]:
data_df = pd.read_csv('/home/mhen/geol0069_data/jan20.csv')

In [3]:
#keep data from january

data_df = data_df.loc[data_df['date_string'].str.contains('2020-01', na=False)]

In [4]:
data_df.head()

,x,y,lon,lat,t,z,track,date_string,satellite,lead_mask,dist_along_track,z_track_avg
2573650,-585146.902831,-432100.026835,-53.556094,83.483790,18262.0,NaN,1243,2020-01-01,cs2,0.0,0.000000,0.040157
2573651,-584280.987782,-430861.767792,-53.594113,83.496633,18262.0,-0.034818,1243,2020-01-01,cs2,1.0,1502.990248,0.040157
2573652,-584107.820675,-430614.140368,-53.601734,83.499201,18262.0,-0.018846,1243,2020-01-01,cs2,1.0,1803.558120,0.040157
2573653,-583934.553028,-430366.439101,-53.609361,83.501770,18262.0,NaN,1243,2020-01-01,cs2,0.0,2104.243152,0.040157
2573654,-583588.157115,-429871.156267,-53.624632,83.506906,18262.0,NaN,1243,2020-01-01,cs2,0.0,2705.434872,0.040157

In [5]:
test_track = data_df.loc[data_df['track'] == 1257]
test_track.head()

,x,y,lon,lat,t,z,track,date_string,satellite,lead_mask,dist_along_track,z_track_avg
2601689,-638579.271484,2.242111e+06,-164.10243,69.001559,18262.0,-0.746479,1257,2020-01-01,cs2,1.0,0.000000,-0.026275
2601690,-638462.214874,2.241838e+06,-164.10336,69.004244,18262.0,-0.798415,1257,2020-01-01,cs2,1.0,300.176217,-0.026275
2601691,-638111.488080,2.241019e+06,-164.10614,69.012299,18262.0,-0.665761,1257,2020-01-01,cs2,1.0,1200.652652,-0.026275
2601692,-637409.906412,2.239382e+06,-164.11171,69.028408,18262.0,-0.714593,1257,2020-01-01,cs2,1.0,3001.529271,-0.026275
2601693,-637292.936222,2.239109e+06,-164.11264,69.031093,18262.0,-0.669882,1257,2020-01-01,cs2,1.0,3301.699913,-0.026275

In [9]:
def random_holdout_test(data_df, holdout_fraction=0.2, seed=42):
    rng = np.random.default_rng(seed)

    #separate into tracks and iterate over each
    tracks = data_df['track'].unique()
    
    results_df = pd.DataFrame()
    results_metrics_df = pd.DataFrame()
    for i, track in enumerate(tracks):
        print(f'Interpolating track {track}, {i+1} of {len(tracks)}...')
        track_df = data_df.loc[data_df['track']==track]
        #locate leads
        leads_df = track_df.loc[track_df['lead_mask']==1.0]
        #create test (holdout) indices of length 1 or of holdout fraction, whichever is larger
        n_test = max(1, int(len(leads_df) * holdout_fraction))

        #exclude tracks with insufficient leads
        if len(leads_df) < 5:
            print(f"Insufficient leads ({len(leads_df)}) for random holdout, skipping...")
            continue

        #find lead indices and randomly select 80% for training
        leads_idx = leads_df.index
        test_lead_idx = rng.choice(leads_df.index, size=n_test, replace=False)
        train_lead_idx = np.array(leads_df.index.difference(test_lead_idx))

        # Compute distances before interpolation - nearest distance to a train lead of each test lead
        lead_D = leads_df.loc[leads_idx, 'dist_along_track'].to_numpy()
        train_D = leads_df.loc[train_lead_idx, 'dist_along_track'].to_numpy()
        test_D = leads_df.loc[test_lead_idx, 'dist_along_track'].to_numpy()
        if train_D.size > 0 and test_D.size > 0:
            nearest_dists_km = np.min(np.abs(test_D[:, None] - train_D[None, :]), axis=1) / 1000.0
        else:
            nearest_dists_km = np.array([])

        #run linear interpolation
        result_track_lin = linear_interpolation(track_df, train_lead_idx)
        result_track_gpsat = gpsat_interpolation(track_df, train_lead_idx)
        print(f'lin:')
        print(result_track_lin.head())
        print('gpsat:')
        print(result_track_gpsat.head())
        result_track = result_track_lin.join(result_track_gpsat[['f_gpsat','f_var_gpsat']])

        #find test values - withheld leads
        linear_preds = result_track_lin.loc[test_lead_idx,'f_lin'].to_numpy()
        gpsat_preds = result_track_gpsat.loc[test_lead_idx, 'f_gpsat'].to_numpy()
        gpsat_var = result_track_gpsat.loc[test_lead_idx,'f_var_gpsat'].to_numpy()
        targets = result_track_lin.loc[test_lead_idx, 'z'].to_numpy()

        print(f"Test NaNs — Linear: {np.sum(~np.isfinite(linear_preds))}, GPSat: {np.sum(~np.isfinite(gpsat_preds))}")
        both_valid = (np.isfinite(linear_preds) & np.isfinite(gpsat_preds) & np.isfinite(targets))
        if np.sum(both_valid) == 0:
            print(f"FAILED: No valid predictions from both methods on random holdout")
            continue

        #find metrics for the prediction
        lin_res = linear_preds[both_valid] - targets[both_valid]
        gp_res = gpsat_preds[both_valid] - targets[both_valid]

        def _r2(a, b):
            return np.corrcoef(a, b)[0,1]**2 if len(a) > 1 else np.nan
        
        # Calculate GPSat uncertainty at test leads for calibration check
        if gpsat_var is not None:
            gpsat_std = np.sqrt(gpsat_var[both_valid])
            avg_gpsat_uncertainty = float(np.mean(gpsat_std))
        else:
            avg_gpsat_uncertainty = None
        
        # Distance and lead spacing stats
        dist_mean = float(np.nanmean(nearest_dists_km)) if nearest_dists_km.size else np.nan
        dist_median = float(np.nanmedian(nearest_dists_km)) if nearest_dists_km.size else np.nan
        dist_max = float(np.nanmax(nearest_dists_km)) if nearest_dists_km.size else np.nan
        dist_min = float(np.nanmin(nearest_dists_km)) if nearest_dists_km.size else np.nan
        spacing_km = np.diff(lead_D) / 1000.0 if lead_D.size > 1 else np.array([])
        sp_med = float(np.nanmedian(spacing_km)) if spacing_km.size else np.nan
        sp_p90 = float(np.nanpercentile(spacing_km, 90)) if spacing_km.size else np.nan
        sp_max = float(np.nanmax(spacing_km)) if spacing_km.size else np.nan

        #add metrics to dataframe
        metrics_dict = {
            'track' : track,
            'n_predictions': int(np.sum(both_valid)),
            'n_train': int(len(train_lead_idx)),
            'n_test': int(len(test_lead_idx)),
            'nearest_train_km': {
                'mean': dist_mean, 'median': dist_median, 'max': dist_max, 'min': dist_min
            },
            'lead_spacing_km': {
                'median': sp_med, 'p90': sp_p90, 'max': sp_max
            },
            'linear': {
                'rmse': float(np.sqrt(np.mean(lin_res**2))),
                'bias': float(np.mean(lin_res)),
                'mae': float(np.mean(np.abs(lin_res))),
                'r2': float(_r2(linear_preds[both_valid], targets[both_valid]))
            },
            'gpsat_along': {
                'rmse': float(np.sqrt(np.mean(gp_res**2))),
                'bias': float(np.mean(gp_res)),
                'mae': float(np.mean(np.abs(gp_res))),
                'r2': float(_r2(gpsat_preds[both_valid], targets[both_valid])),
                'avg_uncertainty': avg_gpsat_uncertainty
                },
        }
        track_metrics_df = pd.DataFrame(metrics_dict)
        results_metrics_df = pd.concat([results_metrics_df, track_metrics_df])
        results_df = pd.concat([results_df, result_track])
        print(f'Track interpolated!')
    print('All tracks interpolated')

    return results_df, results_metrics_df


def linear_interpolation(track_df, train_lead_idx, filter_width_km=100):
    obs_df = track_df['z']
    train_leads_df = track_df.loc[train_lead_idx]

    # Filter leads by height
    height_valid = (train_leads_df['z']>= -0.5) & (train_leads_df['z'] <= 0.5)
    train_leads_df = train_leads_df.loc[height_valid]

    #terminate if too short for linear interpolation
    if len(train_leads_df) < 2:
        print('Too few leads for linear interpolation, returning NaN')
        obs_df['f_lin'] = np.nan
        track_df = pd.merge(track_df, obs_df['f_lin'], left_index=True, right_index=True)
        
        return track_df
    
    # apply 100 km box filter to smooth lead observations
    smoothed_obs_df = obs_df.copy()

    # For each lead point, smooth with nearby leads within filter_width_km
    for idx, lead in train_leads_df.iterrows():
        lead_distances = np.abs(train_leads_df['dist_along_track'] - train_leads_df['dist_along_track'].loc[idx])
        within_window = lead_distances <= (filter_width_km * 1000 / 2)  # ±50 km    
        if np.sum(within_window) > 0:
            smoothed_obs_df.loc[idx] = (train_leads_df['z'][within_window]).mean()

    # linear interpolation between smoothed lead values - covers all obs points
    obs_df = obs_df.to_frame()
    obs_df['f_lin'] = np.nan
        
    for i0, i1 in zip(train_leads_df.index[:-1], train_leads_df.index[1:]):
        v0, v1 = smoothed_obs_df.loc[i0], smoothed_obs_df.loc[i1]
        span = i1 - i0
        if span <= 0:
            obs_df['f_lin'].loc[i0] = v0
            continue
        ii = np.arange(i0, i1 + 1)
        obs_df['f_lin'].loc[ii] = v0 + (v1 - v0) * (ii - i0) / span

    # flat extrapolation beyond the first/last training lead
    first_idx, last_idx = train_leads_df.index[0], train_leads_df.index[-1]
    obs_df.loc[:first_idx, 'f_lin'] = smoothed_obs_df.loc[first_idx]
    obs_df.loc[last_idx:, 'f_lin'] = smoothed_obs_df.loc[last_idx]

    track_df = pd.merge(track_df, obs_df['f_lin'], left_index=True, right_index=True)
    track_df.head()

    return track_df

def gpsat_interpolation(track_df, train_lead_idx):
    
    obs_df = track_df['z']
    train_leads_df = track_df.loc[train_lead_idx]

    # Filter leads by height
    height_valid = (train_leads_df['z']>= -0.5) & (train_leads_df['z'] <= 0.5)
    train_leads_df = train_leads_df.loc[height_valid]

    #if too short, terminate and return NaN
    if len(train_leads_df)<3:
        print('Too few leads for GPSat interpolation, returning NaN')
        track_df['f_gpsat'] = np.nan
        
        return track_df
    
    #select experts
    experts_df = select_experts(train_leads_df)

    if len(experts_df) < 2:
        print('Too few experts for GPSat, returning NaN')
        track_df['f_gpsat'] = np.nan
        
        return track_df
    
    #run gpsat interpolation
    track = track_df['track'].iloc[0]

    store_path = f'/home/mhen/geol0069_data/gpsat/jan20/{track}.h5'

    if os.path.exists(store_path):
        os.remove(store_path)
    
    ssha, ssha_var = run_gpsat(track_df, train_leads_df, experts_df, store_path)

    track_df['f_gpsat'] = ssha
    track_df['f_var_gpsat'] = ssha_var

    return track_df

def select_experts(leads_df, spacing=25e3, max_experts=40):
    try:
        dist_along_track = leads_df['dist_along_track']
    except KeyError as ke:
        print(f'{ke}: Make sure distance along track is calculated')
        return
    
    grid = np.arange(0, dist_along_track.iloc[-1], spacing)
    selected = []
    used = set()

    for target in grid:
        if len(selected) >= max_experts:
            print('Expert limit reached.')
            break
        #subtract each target dist from the dist of each lead, and so find
        #the closest lead to target from the smallest value
        idx = (dist_along_track-target).abs().idxmin()
        #select lead and add to selected and used
        if idx not in used:
            selected.append(idx)
            used.add(idx)
    
    if len(selected) < 3:
        #if we have too few experts
        #find the unselected leads
        remaining_idx = leads_df.index.difference(selected)
        #find no. experts to add
        n_to_add = max_experts-len(remaining_idx)
        #add indices evenly spaced from remaining unselected indices
        step = max(1, len(remaining_idx) // n_to_add)
        idx_added = remaining_idx[::step][:n_to_add]

        selected.extend(list(idx_added))

    experts_df = leads_df.loc[selected]

    return experts_df

def run_gpsat(track_df, leads_df, experts_df, store_path):

    # Notebook-style config: 3D coords, 400km, 100-200km lengthscales
    coords_col = ["x", "y", "t"]
    local_select = [
        {"col": ["x", "y"], "comp": "<=", "val": 400_000},
        {"col": "t", "comp": "<=", "val": 1.0},
        {"col": "t", "comp": ">=", "val": -1.0}
    ]
    data_config = {
        "data_source": leads_df,
        "obs_col": "z",
        "coords_col": coords_col,
        "local_select": local_select,
        "global_select": [{"col": "lat", "comp": ">=", "val": 45}]
    }
    expert_config = {"source" : experts_df}
    pred_config = {"method": "from_dataframe", "df": track_df,
                   "max_dist" : 400_000}
    # Notebook-style: 100-200km lengthscales for 3D
    length_low = [100_000, 100_000, 1e-08]
    length_high = [200_000, 200_000, 4]
    coords_scale = [10_000, 10_000, 1]

    model_config = {
    "oi_model": "GPflowGPRModel",
    "init_params": {"coords_scale": coords_scale, "minibatch_size": 100},
    "constraints": {
        "lengthscales": {"low": length_low, "high": length_high},
        "likelihood_variance": {"low": 0.001, "high": 10}  # Lower noise floor for better endpoint adherence
        }
    }
    # Full mode: enable smoothing (3D coords have x/y)
    locexp = LocalExpertOI(expert_config, data_config, model_config, pred_config)
    locexp.run(store_path=store_path, optimise=True)
    dfs, _ = get_results_from_h5file(store_path)
    run_details = dfs['run_details']
    smooth_hyperparameters(
        result_file=store_path,
        params_to_smooth=["lengthscales", "kernel_variance", "likelihood_variance"],
        smooth_config_dict={
            "lengthscales": dict(l_x=200_000, l_y=200_000, max=12),
            "likelihood_variance": dict(l_x=200_000, l_y=200_000),
            "kernel_variance": dict(l_x=200_000, l_y=200_000, max=0.1)
        },
        save_config_file=False
    )
    model_config['load_params'] = {"file": store_path, "table_suffix": "_SMOOTHED"}
    locexp = LocalExpertOI(expert_config, data_config, model_config, pred_config)
    locexp.run(store_path=store_path, optimise=False, predict=True, table_suffix='_SMOOTHED')

    # Extract results
    dfs, _ = get_results_from_h5file(store_path)
    preds = dfs["preds"]

    # Glue
    preds['xprt_locs'] = np.sqrt((preds['x'] - preds['x'].iloc[0])**2 + (preds['y'] - preds['y'].iloc[0])**2)
    preds['pred_locs'] = np.sqrt((preds['pred_loc_x'] - preds['pred_loc_x'].iloc[0])**2 + 
                                    (preds['pred_loc_y'] - preds['pred_loc_y'].iloc[0])**2)
    glue_max = 400_000  # Full mode uses 400km like notebook

    glued = glue_local_predictions_1d(preds, "pred_locs", "xprt_locs", ["f*", "f*_var"], glue_max)
    ssha = glued['f*'].values
    ssha_var = glued['f*_var'].values if 'f*_var' in glued.columns else None

    # Handle length mismatch
    if len(ssha) < len(track_df):
        full = np.full(len(track_df), np.nan)
        full_var = np.full(len(track_df), np.nan)
        full[:len(ssha)] = ssha
        full_var[:len(ssha_var)] = ssha

        return full, full_var
    
    return ssha[:len(track_df)], ssha_var[:len(track_df)]

In [10]:
tracks = data_df['track'].unique()

tracks = tracks[:15]

downsized_df = data_df.loc[data_df['track'].isin(tracks)]

In [11]:
linear_df, linear_metrics_df = random_holdout_test(downsized_df)

Interpolating track 1243, 1 of 15...
Expert limit reached.
'data_select': 0.000 seconds
'load': 0.000 seconds
in json_serializable - key: 'data_source' has value DataFrame/Series, but is too long: 1290 >  100
storing as str
in json_serializable - key: 'df' has value DataFrame/Series, but is too long: 5205 >  100
storing as str
---------
storing expert locations in 'expert_locs' table
exception occurred: 'No object named expert_locs in the file'
will now close object

---------
dropping expert locations that already exists in 'run_details' table
exception occurred: 'No object named run_details in the file'
will now close object

--------------------------------------------------
1 / 40
current local expert:
                     x              y        lon        lat        t  \
2573651 -584280.987782 -430861.767792 -53.594113  83.496633  18262.0

                z  track date_string satellite  lead_mask  dist_along_track  \
2573651 -0.034818   1243  2020-01-01       cs2        1.0       1502.990248

         z_track_avg
2573651     0.040157
'data_select': 0.000 seconds
'load': 0.000 seconds
'local_data_select': 0.001 seconds
number obs: 116
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.052 seconds
'get_parameters': 0.003 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:13:11.697374: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:13:11.698798: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.294 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.00997233, 10.00994317,  0.99822433])
kernel_variance: 0.0013667877537881785
likelihood_variance: 0.004187448605488844
'predict': 0.030 seconds
total run time : 0.72 seconds
--------------------------------------------------
2 / 40
current local expert:
                     x              y        lon        lat        t        z  \
2573685 -570418.599441 -411052.893457 -54.222867  83.701745  18262.0 -0.00557

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2573685   1243  2020-01-01       cs2        1.0      25551.212003     0.040157
'local_data_select': 0.001 seconds
number obs: 124
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.049 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:13:12.419808: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:13:12.421206: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'optimise_parameters': 0.283 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.0100683 , 10.0101367 ,  1.00053476])
kernel_variance: 0.001264155332275684
likelihood_variance: 0.003928569402151681
'predict': 0.030 seconds
total run time : 0.71 seconds
--------------------------------------------------
3 / 40
current local expert:
                     x              y        lon        lat        t  \
2573741 -555327.315351 -389517.775035 -54.953406  83.923938  18262.0

                z  track date_string satellite  lead_mask  dist_along_track  \
2573741  0.000517   1243  2020-01-01       cs2        1.0      51704.152824

         z_track_avg
2573741     0.040157
'local_data_select': 0.001 seconds
number obs: 133
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.050 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:13:13.135353: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:13:13.136776: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'optimise_parameters': 0.293 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01006612, 10.01013199,  0.99947316])
kernel_variance: 0.0013526719133063487
likelihood_variance: 0.003770484902949074
'predict': 0.031 seconds
total run time : 0.72 seconds
--------------------------------------------------
4 / 40
current local expert:
                    x              y        lon        lat        t         z  \
2573788 -542825.46463 -371701.254797 -55.598498  84.107068  18262.0  0.049702

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2573788   1243  2020-01-01       cs2        1.0      73348.337332     0.040157
'local_data_select': 0.001 seconds
number obs: 136
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:13:13.854756: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:13:13.856152: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'optimise_parameters': 0.261 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01006555, 10.01013097,  0.99839155])
kernel_variance: 0.0014427032250461632
likelihood_variance: 0.003943302140144742
'predict': 0.030 seconds
total run time : 0.68 seconds
--------------------------------------------------
5 / 40
current local expert:
                     x              y        lon        lat        t  \
2573829 -525095.068321 -346469.863559 -56.582249  84.365197  18262.0

                z  track date_string satellite  lead_mask  dist_along_track  \
2573829 -0.061733   1243  2020-01-01       cs2        1.0     104011.745256

         z_track_avg
2573829     0.040157
'local_data_select': 0.001 seconds
number obs: 139
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:13:14.540369: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:13:14.541789: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'optimise_parameters': 0.262 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01006583, 10.01013138,  0.99872121])
kernel_variance: 0.0013152415452337611
likelihood_variance: 0.0038731850812191155
'predict': 0.031 seconds
total run time : 0.69 seconds
--------------------------------------------------
6 / 40
current local expert:
                     x              y        lon        lat        t  \
2573870 -512914.085015 -329160.294527 -57.309865  84.541357  18262.0

                z  track date_string satellite  lead_mask  dist_along_track  \
2573870  0.100011   1243  2020-01-01       cs2        1.0      125055.67142

         z_track_avg
2573870     0.040157
'local_data_select': 0.001 seconds
number obs: 149
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.046 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:13:15.233126: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:13:15.234543: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'optimise_parameters': 0.323 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.0100676 , 10.01013456,  1.00192883])
kernel_variance: 0.0011826980437697882
likelihood_variance: 0.003815651442735142
'predict': 0.031 seconds
total run time : 0.75 seconds
--------------------------------------------------
7 / 40
current local expert:
                     x              y        lon        lat        t  \
2573906 -504729.486882 -317540.985005 -57.824728  84.659138  18262.0

                z  track date_string satellite  lead_mask  dist_along_track  \
2573906 -0.042135   1243  2020-01-01       cs2        1.0     139185.336734

         z_track_avg
2573906     0.040157
'local_data_select': 0.001 seconds
number obs: 163
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.046 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:13:15.984337: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:13:15.985747: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'optimise_parameters': 0.311 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01006679, 10.01013288,  1.00080771])
kernel_variance: 0.0015206541061740233
likelihood_variance: 0.0036663331511000035
'predict': 0.031 seconds
total run time : 0.74 seconds
--------------------------------------------------
8 / 40
current local expert:
                     x              y        lon        lat        t  \
2574018 -477354.932944 -278743.960207 -59.717875  85.049276  18262.0

                z  track date_string satellite  lead_mask  dist_along_track  \
2574018 -0.016747   1243  2020-01-01       cs2        1.0     186385.734629

         z_track_avg
2574018     0.040157
'local_data_select': 0.001 seconds
number obs: 181
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:13:16.724511: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:13:16.725925: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.317 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01006588, 10.01013048,  0.99976281])
kernel_variance: 0.0018320463897911615
likelihood_variance: 0.003496932557785863
'predict': 0.031 seconds
total run time : 0.75 seconds
--------------------------------------------------
9 / 40
current local expert:
                     x              y        lon        lat        t  \
2574037 -470372.132687 -268863.620471 -60.247815  85.147759  18262.0

                z  track date_string satellite  lead_mask  dist_along_track  \
2574037  0.026861   1243  2020-01-01       cs2        1.0      198411.46606

         z_track_avg
2574037     0.040157
'local_data_select': 0.001 seconds
number obs: 192
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.051 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:13:17.480320: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:13:17.481725: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'optimise_parameters': 0.272 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.0100483 , 10.01009514,  1.00158023])
kernel_variance: 0.0018561210979102796
likelihood_variance: 0.003347225427589806
'predict': 0.031 seconds
total run time : 0.71 seconds
--------------------------------------------------
10 / 40
current local expert:
                     x              y        lon        lat        t  \
2574101 -452725.410804 -243923.259725 -61.684722  85.394512  18262.0

                z  track date_string satellite  lead_mask  dist_along_track  \
2574101 -0.037159   1243  2020-01-01       cs2        1.0     228776.996751

         z_track_avg
2574101     0.040157
'local_data_select': 0.001 seconds
number obs: 199
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.050 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:13:18.188953: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:13:18.190368: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'optimise_parameters': 0.351 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([19.99903401, 20.        ,  1.02318636])
kernel_variance: 0.002983951458887414
likelihood_variance: 0.0033314190779667667
'predict': 0.031 seconds
SAVING RESULTS TO TABLES:
run_details
preds
lengthscales
kernel_variance
likelihood_variance
total run time : 0.93 seconds
--------------------------------------------------
11 / 40
current local expert:
                     x              y        lon       lat        t         z  \
2574102 -452550.615803 -243676.396091 -61.699706  85.39694  18262.0  0.060534

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2574102   1243  2020-01-01       cs2        1.0     229077.617022     0.040157
'local_data_select': 0.001 seconds
number obs: 199
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.047 seconds
'set_lengthscales_constraints': 0.006 seconds

2026-05-18 19:13:19.117846: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:13:19.119442: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'set_likelihood_variance_constraints': 0.011 seconds
'optimise_parameters': 0.348 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([19.99903401, 20.        ,  1.02318636])
kernel_variance: 0.002983951458887414
likelihood_variance: 0.0033314190779667667
'predict': 0.031 seconds
total run time : 0.78 seconds
--------------------------------------------------
12 / 40
current local expert:
                     x              y        lon        lat        t  \
2574214 -420871.898628 -199009.279656 -64.692874  85.830911  18262.0

                z  track date_string satellite  lead_mask  dist_along_track  \
2574214  0.063853   1243  2020-01-01       cs2        1.0     283496.695761

         z_track_avg
2574214     0.040157
'local_data_select': 0.001 seconds
number obs: 216
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.049 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:13:19.902230: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:13:19.905791: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.543 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([19.99976974, 20.        ,  0.89375251])
kernel_variance: 0.0026850502633316846
likelihood_variance: 0.003239475122768542
'predict': 0.031 seconds
total run time : 0.99 seconds
--------------------------------------------------
13 / 40
current local expert:
                     x              y        lon        lat        t  \
2574267 -408952.786503 -182237.687859 -65.981274  85.990666  18262.0

                z  track date_string satellite  lead_mask  dist_along_track  \
2574267  0.036357   1243  2020-01-01       cs2        1.0     303941.885792

         z_track_avg
2574267     0.040157
'local_data_select': 0.001 seconds
number obs: 228
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.047 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:13:20.891418: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:13:20.892939: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'optimise_parameters': 0.275 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01006297, 10.01012349,  1.00090839])
kernel_variance: 0.0018718980882377275
likelihood_variance: 0.0031384271617295434
'predict': 0.033 seconds
total run time : 0.72 seconds
--------------------------------------------------
14 / 40
current local expert:
                     x              y        lon       lat        t         z  \
2574320 -396497.404459 -164731.682898 -67.438716  86.15518  18262.0 -0.008582

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2574320   1243  2020-01-01       cs2        1.0     325289.481822     0.040157
'local_data_select': 0.001 seconds
number obs: 247
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.047 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:13:21.612897: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:13:21.614285: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'optimise_parameters': 0.370 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01007001, 10.01013747,  0.99825752])
kernel_variance: 0.0017550038002430359
likelihood_variance: 0.003380005756970293
'predict': 0.032 seconds
total run time : 0.81 seconds
--------------------------------------------------
15 / 40
current local expert:
                     x             y        lon        lat        t         z  \
2574387 -380518.277437 -142302.92867 -69.495644  86.362112  18262.0  0.076842

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2574387   1243  2020-01-01       cs2        1.0      352650.75453     0.040157
'local_data_select': 0.001 seconds
number obs: 256
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:13:22.428868: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:13:22.430280: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'optimise_parameters': 0.388 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([19.99981861, 20.        ,  1.06459326])
kernel_variance: 0.0025073596353005073
likelihood_variance: 0.0033884422201181552
'predict': 0.032 seconds
total run time : 0.83 seconds
--------------------------------------------------
16 / 40
current local expert:
                     x              y        lon        lat        t  \
2574441 -368918.235245 -126041.846636 -71.137138  86.509028  18262.0

                z  track date_string satellite  lead_mask  dist_along_track  \
2574441  0.069265   1243  2020-01-01       cs2        1.0     372495.574638

         z_track_avg
2574441     0.040157
'local_data_select': 0.001 seconds
number obs: 269
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:13:23.263439: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:13:23.264837: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'optimise_parameters': 0.544 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([19.99996752, 20.        ,  1.11175767])
kernel_variance: 0.002465797750058543
likelihood_variance: 0.00391457453849693
'predict': 0.034 seconds
total run time : 0.99 seconds
--------------------------------------------------
17 / 40
current local expert:
                     x              y        lon        lat        t  \
2574510 -350445.220745 -100182.470017 -74.046251  86.736288  18262.0

                z  track date_string satellite  lead_mask  dist_along_track  \
2574510  0.004462   1243  2020-01-01       cs2        1.0     404067.319848

         z_track_avg
2574510     0.040157
'local_data_select': 0.001 seconds
number obs: 284
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.046 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:13:24.252137: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:13:24.253549: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'optimise_parameters': 0.562 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([19.99993615, 20.        ,  1.11205442])
kernel_variance: 0.0025602141722778898
likelihood_variance: 0.0037667990131150034
'predict': 0.034 seconds
total run time : 1.01 seconds
--------------------------------------------------
18 / 40
current local expert:
                     x             y        lon        lat        t        z  \
2574543 -340935.979146 -86888.491681 -75.702367  86.849592  18262.0  0.03132

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2574543   1243  2020-01-01       cs2        1.0     420304.433846     0.040157
'local_data_select': 0.001 seconds
number obs: 270
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.047 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:13:25.261468: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:13:25.262885: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'optimise_parameters': 0.416 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([19.99997625, 20.        ,  0.88252273])
kernel_variance: 0.002034270555754966
likelihood_variance: 0.003291985501572125
'predict': 0.032 seconds
total run time : 0.87 seconds
--------------------------------------------------
19 / 40
current local expert:
                     x             y        lon        lat        t         z  \
2574609 -323487.114155 -62525.301333 -79.060468  87.049853  18262.0 -0.092577

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2574609   1243  2020-01-01       cs2        1.0     450072.752501     0.040157
'local_data_select': 0.001 seconds
number obs: 265
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.049 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:13:26.131444: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:13:26.132864: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'optimise_parameters': 0.265 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01007993, 10.01015491,  0.99977266])
kernel_variance: 0.00228563018702156
likelihood_variance: 0.0033779576041223576
'predict': 0.032 seconds
total run time : 0.72 seconds
--------------------------------------------------
20 / 40
current local expert:
                     x             y      lon        lat        t         z  \
2574659 -307783.556728 -40633.057123 -82.4794  87.220199  18262.0  0.023899

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2574659   1243  2020-01-01       cs2        1.0     476834.842904     0.040157
'local_data_select': 0.001 seconds
number obs: 260
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.047 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:13:26.853234: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:13:26.854656: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'optimise_parameters': 0.406 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([19.99997211, 20.        ,  0.99484113])
kernel_variance: 0.0017012926889296248
likelihood_variance: 0.0031536893013730206
'predict': 0.033 seconds
SAVING RESULTS TO TABLES:
run_details
preds
lengthscales
kernel_variance
likelihood_variance
total run time : 1.01 seconds
--------------------------------------------------
21 / 40
current local expert:
                     x             y        lon        lat        t         z  \
2574713 -294891.287183 -22683.741416 -85.601334  87.351774  18262.0  0.027276

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2574713   1243  2020-01-01       cs2        1.0     498786.021138     0.040157
'local_data_select': 0.001 seconds
number obs: 268
found GPU
setting lengthscales to: [1. 1. 1.]

2026-05-18 19:13:27.867488: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:13:27.868898: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'__init__': 0.052 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds
**********
optimization failed!
'optimise_parameters': 0.545 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([19.99724573, 20.        ,  0.9900163 ])
kernel_variance: 0.0016517561819126814
likelihood_variance: 0.003123930643576665
'predict': 0.032 seconds
total run time : 1.01 seconds
--------------------------------------------------
22 / 40
current local expert:
                     x           y        lon        lat        t         z  \
2574775 -278981.971308 -563.722197 -89.884226  87.502046  18262.0  0.062543

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2574775   1243  2020-01-01       cs2        1.0     525849.357254     0.040157
'local_data_select': 0.001 seconds
number obs: 258
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.047 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:13:28.872420: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:13:28.873820: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'optimise_parameters': 0.499 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([19.99981847, 20.        ,  0.89895132])
kernel_variance: 0.002631751385762899
likelihood_variance: 0.003200539541750523
'predict': 0.033 seconds
total run time : 0.95 seconds
--------------------------------------------------
23 / 40
current local expert:
                     x             y     lon       lat        t         z  \
2574836 -264826.828444  19089.880712 -94.123  87.62266  18262.0 -0.044907

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2574836   1243  2020-01-01       cs2        1.0     549905.878755     0.040157
'local_data_select': 0.001 seconds
number obs: 251
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.047 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:13:29.826397: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:13:29.827785: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.494 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([19.99993628, 20.        ,  0.8392271 ])
kernel_variance: 0.0030782190721591984
likelihood_variance: 0.0032152339422475066
'predict': 0.034 seconds
total run time : 0.95 seconds
--------------------------------------------------
24 / 40
current local expert:
                     x             y        lon        lat        t         z  \
2574881 -252430.620339  36280.264971 -98.178754  87.716594  18262.0  0.094376

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2574881   1243  2020-01-01       cs2        1.0     570955.717675     0.040157
'local_data_select': 0.001 seconds
number obs: 261
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.051 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:13:30.782829: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:13:30.784223: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'optimise_parameters': 0.563 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([19.9999026 , 20.        ,  0.86795315])
kernel_variance: 0.002893981567613615
likelihood_variance: 0.003165016965345032
'predict': 0.034 seconds
total run time : 1.03 seconds
--------------------------------------------------
25 / 40
current local expert:
                     x             y        lon       lat        t         z  \
2574955 -231512.175036  65243.985043 -105.73872  87.84639  18262.0  0.056894

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2574955   1243  2020-01-01       cs2        1.0     606440.197502     0.040157
'local_data_select': 0.001 seconds
number obs: 260
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.049 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:13:31.809735: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:13:31.811141: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'optimise_parameters': 0.471 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([19.99988448, 20.        ,  1.00143075])
kernel_variance: 0.0035687391275351925
likelihood_variance: 0.0031726860040897946
'predict': 0.033 seconds
total run time : 0.93 seconds
--------------------------------------------------
26 / 40
current local expert:
                     x             y        lon       lat        t         z  \
2574997 -220155.071035  80945.632261 -110.18724  87.89981  18262.0  0.112578

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2574997   1243  2020-01-01       cs2        1.0     625686.377367     0.040157
'local_data_select': 0.001 seconds
number obs: 259
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.049 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:13:32.739800: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:13:32.741216: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.392 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01004868, 10.01009341,  0.99945939])
kernel_variance: 0.0033017086081761453
likelihood_variance: 0.003076500773673104
'predict': 0.032 seconds
total run time : 0.85 seconds
--------------------------------------------------
27 / 40
current local expert:
                     x              y       lon        lat        t         z  \
2575069 -201504.912521  106694.511225 -117.9007  87.958514  18262.0  0.107098

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2575069   1243  2020-01-01       cs2        1.0     657262.605124     0.040157
'local_data_select': 0.001 seconds
number obs: 264
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.046 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:13:33.587307: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:13:33.588716: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'optimise_parameters': 0.261 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01006182, 10.01011788,  1.00032544])
kernel_variance: 0.0035142431737380363
likelihood_variance: 0.003046607739433385
'predict': 0.034 seconds
total run time : 0.72 seconds
--------------------------------------------------
28 / 40
current local expert:
                     x              y       lon        lat        t         z  \
2575115 -187992.366085  125322.710822 -123.6889  87.977077  18262.0  0.007034

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2575115   1243  2020-01-01       cs2        1.0     680118.133162     0.040157
'local_data_select': 0.001 seconds
number obs: 267
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.046 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:13:34.310170: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:13:34.311579: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'optimise_parameters': 0.419 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([19.99989662, 20.        ,  1.06595833])
kernel_variance: 0.0036793264039127246
likelihood_variance: 0.0030638351384396807
'predict': 0.033 seconds
total run time : 0.88 seconds
--------------------------------------------------
29 / 40
current local expert:
                     x              y        lon       lat        t         z  \
2575163 -176426.718742  141248.575148 -128.68103  87.97647  18262.0  0.054049

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2575163   1243  2020-01-01       cs2        1.0     699665.826003     0.040157
'local_data_select': 0.001 seconds
number obs: 269
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.051 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:13:35.196394: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:13:35.197812: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.463 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01005714, 10.01010868,  0.99882137])
kernel_variance: 0.003717952450235612
likelihood_variance: 0.0030594124180978663
'predict': 0.033 seconds
total run time : 0.93 seconds
--------------------------------------------------
30 / 40
current local expert:
                     x             y        lon        lat        t        z  \
2575216 -161468.271969  161821.03889 -135.06252  87.953217  18262.0  0.15831

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2575216   1243  2020-01-01       cs2        1.0      724927.60176     0.040157
'local_data_select': 0.001 seconds
number obs: 282
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.051 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:13:36.125887: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:13:36.127272: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.591 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([19.99947987, 20.        ,  0.96515484])
kernel_variance: 0.003510175679377472
likelihood_variance: 0.0034640692117518922
'predict': 0.034 seconds
SAVING RESULTS TO TABLES:
run_details
preds
lengthscales
kernel_variance
likelihood_variance
total run time : 1.28 seconds
--------------------------------------------------
31 / 40
current local expert:
                     x              y        lon        lat        t  \
2575261 -150062.318426  177488.986308 -139.78635  87.918974  18262.0

                z  track date_string satellite  lead_mask  dist_along_track  \
2575261  0.031646   1243  2020-01-01       cs2        1.0     744174.979017

         z_track_avg
2575261     0.040157
'local_data_select': 0.001 seconds
number obs: 288
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:13:37.402458: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:13:37.403864: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'optimise_parameters': 0.517 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([19.99992685, 20.        ,  1.02489468])
kernel_variance: 0.0035049407144011053
likelihood_variance: 0.003446941230767456
'predict': 0.032 seconds
total run time : 0.98 seconds
--------------------------------------------------
32 / 40
current local expert:
                     x              y        lon        lat        t  \
2575321 -134366.309295  199023.068569 -145.97556  87.849933  18262.0

                z  track date_string satellite  lead_mask  dist_along_track  \
2575321  0.157363   1243  2020-01-01       cs2        1.0     770640.347881

         z_track_avg
2575321     0.040157
'local_data_select': 0.001 seconds
number obs: 283
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.050 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:13:38.387735: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:13:38.389138: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'optimise_parameters': 0.557 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([19.99577726, 19.99999999,  1.10556328])
kernel_variance: 0.0036133688768175826
likelihood_variance: 0.003482232903745435
'predict': 0.032 seconds
total run time : 1.03 seconds
--------------------------------------------------
33 / 40
current local expert:
                     x              y        lon        lat        t        z  \
2575388 -116333.424483  223724.912572 -152.52628  87.742216  18262.0  0.01667

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2575388   1243  2020-01-01       cs2        1.0     801015.706294     0.040157
'local_data_select': 0.001 seconds
number obs: 299
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:13:39.415161: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:13:39.416575: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'optimise_parameters': 0.592 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([19.99991073, 20.        ,  0.93761946])
kernel_variance: 0.0050407903668554625
likelihood_variance: 0.0035665747201347048
'predict': 0.034 seconds
total run time : 1.07 seconds
--------------------------------------------------
34 / 40
current local expert:
                    x              y        lon      lat        t         z  \
2575448 -101857.51502  243524.969665 -157.30224  87.6365  18262.0  0.035483

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2575448   1243  2020-01-01       cs2        1.0     825376.477445     0.040157
'local_data_select': 0.001 seconds
number obs: 293
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.046 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:13:40.481391: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:13:40.482793: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'optimise_parameters': 0.389 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01006315, 10.01011876,  1.00070766])
kernel_variance: 0.006596336326644622
likelihood_variance: 0.003566973760848565
'predict': 0.033 seconds
total run time : 0.86 seconds
--------------------------------------------------
35 / 40
current local expert:
                    x              y        lon        lat        t         z  \
2575509 -86832.437751  264048.462412 -161.79653  87.511208  18262.0  0.067852

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2575509   1243  2020-01-01       cs2        1.0     850639.764451     0.040157
'local_data_select': 0.001 seconds
number obs: 286
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.051 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:13:41.348766: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:13:41.350737: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'optimise_parameters': 0.471 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([19.99979401, 20.        ,  0.99090187])
kernel_variance: 0.006855599038757986
likelihood_variance: 0.0036984808693362645
'predict': 0.033 seconds
total run time : 0.95 seconds
--------------------------------------------------
36 / 40
current local expert:
                    x              y        lon        lat        t         z  \
2575571 -72152.325617  284073.653488 -165.74871  87.375676  18262.0  0.099573

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2575571   1243  2020-01-01       cs2        1.0      875301.96702     0.040157
'local_data_select': 0.001 seconds
number obs: 292
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.045 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:13:42.295045: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:13:42.296491: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.525 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([19.99993774, 20.        ,  2.29928002])
kernel_variance: 0.006722055814719226
likelihood_variance: 0.0035755602518155816
'predict': 0.033 seconds
total run time : 1.00 seconds
--------------------------------------------------
37 / 40
current local expert:
                    x             y        lon        lat        t         z  \
2575615 -58893.782795  302136.70505 -168.96997  87.243762  18262.0  0.273628

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2575615   1243  2020-01-01       cs2        1.0     897558.209613     0.040157
'local_data_select': 0.001 seconds
number obs: 302
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.049 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:13:43.299637: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:13:43.301073: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'optimise_parameters': 0.263 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01007336, 10.01013837,  0.99987967])
kernel_variance: 0.005681169947247182
likelihood_variance: 0.003994086799537378
'predict': 0.038 seconds
total run time : 0.75 seconds
--------------------------------------------------
38 / 40
current local expert:
                    x              y        lon        lat        t         z  \
2575681 -42395.957839  324582.383903 -172.55833  87.068973  18262.0  0.099309

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2575681   1243  2020-01-01       cs2        1.0     925228.580333     0.040157
'local_data_select': 0.001 seconds
number obs: 303
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.047 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:13:44.045108: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:13:44.046528: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'optimise_parameters': 0.327 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([16.45001062, 19.99478343,  1.09642596])
kernel_variance: 0.008793028008683366
likelihood_variance: 0.0038976480329328384
'predict': 0.034 seconds
total run time : 0.80 seconds
--------------------------------------------------
39 / 40
current local expert:
                    x              y        lon        lat        t         z  \
2575739 -27139.655872  345308.953971 -175.50606  86.898494  18262.0  0.002256

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2575739   1243  2020-01-01       cs2        1.0     950793.711217     0.040157
'local_data_select': 0.001 seconds
number obs: 291
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.046 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:13:44.847650: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:13:44.849050: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.397 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01006275, 10.01011717,  1.00019726])
kernel_variance: 0.006799106459443853
likelihood_variance: 0.003997448123790003
'predict': 0.034 seconds
total run time : 0.88 seconds
--------------------------------------------------
40 / 40
current local expert:
                    x              y        lon        lat        t         z  \
2575778 -16901.524477  359202.028419 -177.30605  86.780036  18262.0  0.082655

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2575778   1243  2020-01-01       cs2        1.0     967937.655732     0.040157
'local_data_select': 0.001 seconds
number obs: 287
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.047 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:13:45.727268: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:13:45.728666: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.447 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01006465, 10.01012055,  1.00040463])
kernel_variance: 0.006794199454826655
likelihood_variance: 0.004036188699798523
'predict': 0.033 seconds
SAVING RESULTS TO TABLES:
run_details
preds
lengthscales
kernel_variance
likelihood_variance
total run time : 1.20 seconds
'run': 35.303 seconds
reading in results
getting all tables
merging on expert location data
table: 'oi_config' does not have all coords_col: ['x', 'y', 't'] in columns, not merging on expert_locations
h5 tables: ['expert_locs', 'kernel_variance', 'lengthscales', 'likelihood_variance', 'oi_config', 'preds', 'run_details']
found model_name: GPflowGPRModel
found GPU
setting lengthscales to: [1.]
'__init__': 0.046 seconds
reading in results
selecting only tables: ['lengthscales', 'kernel_variance', 'likelihood_variance']
'data_select': 0.000 seconds
'load': 0.001 seconds
expert_locations data will not be merged on results data
adding smoothed table: lengthscales_SMOOTHED
adding smoothed table: kernel_variance_SMOOTHED
adding smoothed table: likelihood_variance_SMOOTHED
writing (smoothed) hyper parameters to:
/home/mhen/geol0069_data/gpsat/jan20/1243.h5
table_suffix:_SMOOTHED
writing: lengthscales_SMOOTHED to table
writing: kernel_variance_SMOOTHED to table
writing: likelihood_variance_SMOOTHED to table

2026-05-18 19:13:47.123226: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:13:47.124627: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'data_select': 0.000 seconds
'load': 0.001 seconds
in json_serializable - key: 'data_source' has value DataFrame/Series, but is too long: 1290 >  100
storing as str
in json_serializable - key: 'df' has value DataFrame/Series, but is too long: 5205 >  100
storing as str
---------
storing expert locations in 'expert_locs' table
exception occurred: 'No object named expert_locs_SMOOTHED in the file'
will now close object

---------
dropping expert locations that already exists in 'run_details' table
exception occurred: 'No object named run_details_SMOOTHED in the file'
will now close object

--------------------------------------------------
1 / 40
current local expert:
                     x              y        lon        lat        t  \
2573651 -584280.987782 -430861.767792 -53.594113  83.496633  18262.0

                z  track date_string satellite  lead_mask  dist_along_track  \
2573651 -0.034818   1243  2020-01-01       cs2        1.0       1502.990248

         z_track_avg
2573651     0.040157
'data_select': 0.000 seconds
'load': 0.000 seconds
'local_data_select': 0.001 seconds
number obs: 116
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'get_parameters': 0.003 seconds
'_read_params_from_file': 0.050 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds

2026-05-18 19:13:47.384648: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:13:47.386047: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'set_likelihood_variance_constraints': 0.016 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.42850012, 10.42854213,  1.00087653])
kernel_variance: 0.0017310803201421366
likelihood_variance: 0.01100000000000001
'predict': 0.031 seconds
total run time : 0.54 seconds
--------------------------------------------------
2 / 40
current local expert:
                     x              y        lon        lat        t        z  \
2573685 -570418.599441 -411052.893457 -54.222867  83.701745  18262.0 -0.00557

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2573685   1243  2020-01-01       cs2        1.0      25551.212003     0.040157
'local_data_select': 0.001 seconds
number obs: 124
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.046 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.46903856, 10.46907998,  1.00091143])
kernel_variance: 0.0017624200672164817
likelihood_variance: 0.01100000000000001
'predict': 0.031 seconds

2026-05-18 19:13:47.924080: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:13:47.925493: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.53 seconds
--------------------------------------------------
3 / 40
current local expert:
                     x              y        lon        lat        t  \
2573741 -555327.315351 -389517.775035 -54.953406  83.923938  18262.0

                z  track date_string satellite  lead_mask  dist_along_track  \
2573741  0.000517   1243  2020-01-01       cs2        1.0      51704.152824

         z_track_avg
2573741     0.040157
'local_data_select': 0.001 seconds
number obs: 133
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.046 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.51620891, 10.51624957,  1.00091689])
kernel_variance: 0.0017982827180956444
likelihood_variance: 0.01100000000000001
'predict': 0.031 seconds

2026-05-18 19:13:48.452186: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:13:48.453603: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.52 seconds
--------------------------------------------------
4 / 40
current local expert:
                    x              y        lon        lat        t         z  \
2573788 -542825.46463 -371701.254797 -55.598498  84.107068  18262.0  0.049702

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2573788   1243  2020-01-01       cs2        1.0      73348.337332     0.040157
'local_data_select': 0.001 seconds
number obs: 136
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.047 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.55761216, 10.55765209,  1.0008878 ])
kernel_variance: 0.0018293434598605403
likelihood_variance: 0.01100000000000001
'predict': 0.031 seconds

2026-05-18 19:13:48.977932: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:13:48.979372: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.53 seconds
--------------------------------------------------
5 / 40
current local expert:
                     x              y        lon        lat        t  \
2573829 -525095.068321 -346469.863559 -56.582249  84.365197  18262.0

                z  track date_string satellite  lead_mask  dist_along_track  \
2573829 -0.061733   1243  2020-01-01       cs2        1.0     104011.745256

         z_track_avg
2573829     0.040157
'local_data_select': 0.001 seconds
number obs: 139
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.046 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.61972146, 10.6197602 ,  1.00077944])
kernel_variance: 0.0018754582468561687
likelihood_variance: 0.01100000000000001
'predict': 0.031 seconds

2026-05-18 19:13:49.506807: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:13:49.508216: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.52 seconds
--------------------------------------------------
6 / 40
current local expert:
                     x              y        lon        lat        t  \
2573870 -512914.085015 -329160.294527 -57.309865  84.541357  18262.0

                z  track date_string satellite  lead_mask  dist_along_track  \
2573870  0.100011   1243  2020-01-01       cs2        1.0      125055.67142

         z_track_avg
2573870     0.040157
'local_data_select': 0.001 seconds
number obs: 149
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.6644808 , 10.66451862,  1.00064949])
kernel_variance: 0.0019085330870892907
likelihood_variance: 0.01100000000000001
'predict': 0.031 seconds

2026-05-18 19:13:50.033391: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:13:50.034822: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.53 seconds
--------------------------------------------------
7 / 40
current local expert:
                     x              y        lon        lat        t  \
2573906 -504729.486882 -317540.985005 -57.824728  84.659138  18262.0

                z  track date_string satellite  lead_mask  dist_along_track  \
2573906 -0.042135   1243  2020-01-01       cs2        1.0     139185.336734

         z_track_avg
2573906     0.040157
'local_data_select': 0.001 seconds
number obs: 163
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.050 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.69539473, 10.69543189,  1.00053285])
kernel_variance: 0.0019313990527066946
likelihood_variance: 0.01100000000000001
'predict': 0.031 seconds

2026-05-18 19:13:50.568874: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:13:50.570269: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.53 seconds
--------------------------------------------------
8 / 40
current local expert:
                     x              y        lon        lat        t  \
2574018 -477354.932944 -278743.960207 -59.717875  85.049276  18262.0

                z  track date_string satellite  lead_mask  dist_along_track  \
2574018 -0.016747   1243  2020-01-01       cs2        1.0     186385.734629

         z_track_avg
2574018     0.040157
'local_data_select': 0.001 seconds
number obs: 181
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.054 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.802559  , 10.80259375,  0.9999476 ])
kernel_variance: 0.002011798863230917
likelihood_variance: 0.01100000000000001
'predict': 0.031 seconds

2026-05-18 19:13:51.101291: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:13:51.102698: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.54 seconds
--------------------------------------------------
9 / 40
current local expert:
                     x              y        lon        lat        t  \
2574037 -470372.132687 -268863.620471 -60.247815  85.147759  18262.0

                z  track date_string satellite  lead_mask  dist_along_track  \
2574037  0.026861   1243  2020-01-01       cs2        1.0      198411.46606

         z_track_avg
2574037     0.040157
'local_data_select': 0.001 seconds
number obs: 192
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.047 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.8305226 , 10.83055668,  0.99974685])
kernel_variance: 0.0020333445370051273
likelihood_variance: 0.01100000000000001
'predict': 0.031 seconds

2026-05-18 19:13:51.631178: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:13:51.632607: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.52 seconds
--------------------------------------------------
10 / 40
current local expert:
                     x              y        lon        lat        t  \
2574101 -452725.410804 -243923.259725 -61.684722  85.394512  18262.0

                z  track date_string satellite  lead_mask  dist_along_track  \
2574101 -0.037159   1243  2020-01-01       cs2        1.0     228776.996751

         z_track_avg
2574101     0.040157
'local_data_select': 0.001 seconds
number obs: 199
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.90154428, 10.90157662,  0.99914601])
kernel_variance: 0.0020899326757527373
likelihood_variance: 0.01100000000000001
'predict': 0.031 seconds

2026-05-18 19:13:52.157858: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:13:52.159828: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

SAVING RESULTS TO TABLES:
run_details
preds
total run time : 0.60 seconds
--------------------------------------------------
11 / 40
current local expert:
                     x              y        lon       lat        t         z  \
2574102 -452550.615803 -243676.396091 -61.699706  85.39694  18262.0  0.060534

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2574102   1243  2020-01-01       cs2        1.0     229077.617022     0.040157
'local_data_select': 0.001 seconds
number obs: 199
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.046 seconds
'_read_params_from_file': 0.050 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters

2026-05-18 19:13:52.761324: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:13:52.762721: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.90224735, 10.90227968,  0.99913942])
kernel_variance: 0.0020905098111470306
likelihood_variance: 0.01100000000000001
'predict': 0.032 seconds
total run time : 0.54 seconds
--------------------------------------------------
12 / 40
current local expert:
                     x              y        lon        lat        t  \
2574214 -420871.898628 -199009.279656 -64.692874  85.830911  18262.0

                z  track date_string satellite  lead_mask  dist_along_track  \
2574214  0.063853   1243  2020-01-01       cs2        1.0     283496.695761

         z_track_avg
2574214     0.040157
'local_data_select': 0.001 seconds
number obs: 216
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'_read_params_from_file': 0.045 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([11.02740741, 11.02743651,  0.99778198])
kernel_variance: 0.0022015462915807925
likelihood_variance: 0.01100000000000001
'predict': 0.031 seconds

2026-05-18 19:13:53.299419: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:13:53.300938: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.53 seconds
--------------------------------------------------
13 / 40
current local expert:
                     x              y        lon        lat        t  \
2574267 -408952.786503 -182237.687859 -65.981274  85.990666  18262.0

                z  track date_string satellite  lead_mask  dist_along_track  \
2574267  0.036357   1243  2020-01-01       cs2        1.0     303941.885792

         z_track_avg
2574267     0.040157
'local_data_select': 0.001 seconds
number obs: 228
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([11.07233843, 11.07236632,  0.99722493])
kernel_variance: 0.002247280079355469
likelihood_variance: 0.01100000000000001
'predict': 0.032 seconds

2026-05-18 19:13:53.828807: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:13:53.830211: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.53 seconds
--------------------------------------------------
14 / 40
current local expert:
                     x              y        lon       lat        t         z  \
2574320 -396497.404459 -164731.682898 -67.438716  86.15518  18262.0 -0.008582

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2574320   1243  2020-01-01       cs2        1.0     325289.481822     0.040157
'local_data_select': 0.001 seconds
number obs: 247
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.050 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([11.11727712, 11.11730377,  0.9966566 ])
kernel_variance: 0.0022979499688356637
likelihood_variance: 0.01100000000000001
'predict': 0.032 seconds

2026-05-18 19:13:54.356017: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:13:54.359583: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.53 seconds
--------------------------------------------------
15 / 40
current local expert:
                     x             y        lon        lat        t         z  \
2574387 -380518.277437 -142302.92867 -69.495644  86.362112  18262.0  0.076842

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2574387   1243  2020-01-01       cs2        1.0      352650.75453     0.040157
'local_data_select': 0.001 seconds
number obs: 256
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.052 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([11.17114848, 11.1711736 ,  0.99601107])
kernel_variance: 0.002367980814035607
likelihood_variance: 0.01100000000000001
'predict': 0.032 seconds

2026-05-18 19:13:54.891413: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:13:54.892950: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.53 seconds
--------------------------------------------------
16 / 40
current local expert:
                     x              y        lon        lat        t  \
2574441 -368918.235245 -126041.846636 -71.137138  86.509028  18262.0

                z  track date_string satellite  lead_mask  dist_along_track  \
2574441  0.069265   1243  2020-01-01       cs2        1.0     372495.574638

         z_track_avg
2574441     0.040157
'local_data_select': 0.001 seconds
number obs: 269
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.047 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([11.20710625, 11.20713031,  0.99565454])
kernel_variance: 0.002422893201134532
likelihood_variance: 0.01100000000000001
'predict': 0.033 seconds

2026-05-18 19:13:55.417112: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:13:55.418518: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.53 seconds
--------------------------------------------------
17 / 40
current local expert:
                     x              y        lon        lat        t  \
2574510 -350445.220745 -100182.470017 -74.046251  86.736288  18262.0

                z  track date_string satellite  lead_mask  dist_along_track  \
2574510  0.004462   1243  2020-01-01       cs2        1.0     404067.319848

         z_track_avg
2574510     0.040157
'local_data_select': 0.001 seconds
number obs: 284
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.046 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([11.25808051, 11.25810303,  0.99540582])
kernel_variance: 0.002518503896864089
likelihood_variance: 0.01100000000000001
'predict': 0.033 seconds

2026-05-18 19:13:55.951146: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:13:55.952554: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.53 seconds
--------------------------------------------------
18 / 40
current local expert:
                     x             y        lon        lat        t        z  \
2574543 -340935.979146 -86888.491681 -75.702367  86.849592  18262.0  0.03132

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2574543   1243  2020-01-01       cs2        1.0     420304.433846     0.040157
'local_data_select': 0.001 seconds
number obs: 270
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.047 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([11.28104735, 11.28106915,  0.99548704])
kernel_variance: 0.0025720620310896148
likelihood_variance: 0.01100000000000001
'predict': 0.032 seconds

2026-05-18 19:13:56.479137: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:13:56.480540: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.53 seconds
--------------------------------------------------
19 / 40
current local expert:
                     x             y        lon        lat        t         z  \
2574609 -323487.114155 -62525.301333 -79.060468  87.049853  18262.0 -0.092577

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2574609   1243  2020-01-01       cs2        1.0     450072.752501     0.040157
'local_data_select': 0.001 seconds
number obs: 265
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.047 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([11.31705814, 11.31707877,  0.99612544])
kernel_variance: 0.0026787939762020515
likelihood_variance: 0.01100000000000001
'predict': 0.033 seconds

2026-05-18 19:13:57.011913: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:13:57.013427: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.53 seconds
--------------------------------------------------
20 / 40
current local expert:
                     x             y      lon        lat        t         z  \
2574659 -307783.556728 -40633.057123 -82.4794  87.220199  18262.0  0.023899

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2574659   1243  2020-01-01       cs2        1.0     476834.842904     0.040157
'local_data_select': 0.001 seconds
number obs: 260
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.051 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([11.34253493, 11.34255468,  0.99736324])
kernel_variance: 0.002784845448645431
likelihood_variance: 0.01100000000000001
'predict': 0.033 seconds

2026-05-18 19:13:57.551127: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:13:57.552544: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

SAVING RESULTS TO TABLES:
run_details
preds
total run time : 0.64 seconds
--------------------------------------------------
21 / 40
current local expert:
                     x             y        lon        lat        t         z  \
2574713 -294891.287183 -22683.741416 -85.601334  87.351774  18262.0  0.027276

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2574713   1243  2020-01-01       cs2        1.0     498786.021138     0.040157
'local_data_select': 0.001 seconds
number obs: 268
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.047 seconds

2026-05-18 19:13:58.185152: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:13:58.186580: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'_read_params_from_file': 0.053 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([11.35857889, 11.35859804,  0.99893395])
kernel_variance: 0.0028793132858769576
likelihood_variance: 0.01100000000000001
'predict': 0.034 seconds
total run time : 0.54 seconds
--------------------------------------------------
22 / 40
current local expert:
                     x           y        lon        lat        t         z  \
2574775 -278981.971308 -563.722197 -89.884226  87.502046  18262.0  0.062543

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2574775   1243  2020-01-01       cs2        1.0     525849.357254     0.040157
'local_data_select': 0.001 seconds
number obs: 258
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.047 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([11.37254702, 11.37256559,  1.00164421])
kernel_variance: 0.0030052093078568563
likelihood_variance: 0.01100000000000001
'predict': 0.033 seconds

2026-05-18 19:13:58.729372: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:13:58.730789: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.53 seconds
--------------------------------------------------
23 / 40
current local expert:
                     x             y     lon       lat        t         z  \
2574836 -264826.828444  19089.880712 -94.123  87.62266  18262.0 -0.044907

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2574836   1243  2020-01-01       cs2        1.0     549905.878755     0.040157
'local_data_select': 0.001 seconds
number obs: 251
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([11.37989037, 11.37990858,  1.00482394])
kernel_variance: 0.0031257382911852273
likelihood_variance: 0.01100000000000001
'predict': 0.033 seconds

2026-05-18 19:13:59.259724: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:13:59.261136: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.53 seconds
--------------------------------------------------
24 / 40
current local expert:
                     x             y        lon        lat        t         z  \
2574881 -252430.620339  36280.264971 -98.178754  87.716594  18262.0  0.094376

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2574881   1243  2020-01-01       cs2        1.0     570955.717675     0.040157
'local_data_select': 0.001 seconds
number obs: 261
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.049 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([11.38271182, 11.38272981,  1.00822199])
kernel_variance: 0.0032375777409737743
likelihood_variance: 0.01100000000000001
'predict': 0.033 seconds

2026-05-18 19:13:59.788316: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:13:59.792010: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.53 seconds
--------------------------------------------------
25 / 40
current local expert:
                     x             y        lon       lat        t         z  \
2574955 -231512.175036  65243.985043 -105.73872  87.84639  18262.0  0.056894

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2574955   1243  2020-01-01       cs2        1.0     606440.197502     0.040157
'local_data_select': 0.001 seconds
number obs: 260
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.051 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([11.38071499, 11.38073283,  1.01524045])
kernel_variance: 0.0034384162542861487
likelihood_variance: 0.01100000000000001
'predict': 0.033 seconds

2026-05-18 19:14:00.327159: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:14:00.328596: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.54 seconds
--------------------------------------------------
26 / 40
current local expert:
                     x             y        lon       lat        t         z  \
2574997 -220155.071035  80945.632261 -110.18724  87.89981  18262.0  0.112578

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2574997   1243  2020-01-01       cs2        1.0     625686.377367     0.040157
'local_data_select': 0.001 seconds
number obs: 259
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.046 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([11.37653695, 11.37655482,  1.01969121])
kernel_variance: 0.0035530280441467147
likelihood_variance: 0.01100000000000001
'predict': 0.032 seconds

2026-05-18 19:14:00.864160: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:14:00.865566: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.52 seconds
--------------------------------------------------
27 / 40
current local expert:
                     x              y       lon        lat        t         z  \
2575069 -201504.912521  106694.511225 -117.9007  87.958514  18262.0  0.107098

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2575069   1243  2020-01-01       cs2        1.0     657262.605124     0.040157
'local_data_select': 0.001 seconds
number obs: 264
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.046 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([11.36574191, 11.36575995,  1.02786725])
kernel_variance: 0.0037480415792723507
likelihood_variance: 0.01100000000000001
'predict': 0.033 seconds

2026-05-18 19:14:01.389206: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:14:01.391327: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.53 seconds
--------------------------------------------------
28 / 40
current local expert:
                     x              y       lon        lat        t         z  \
2575115 -187992.366085  125322.710822 -123.6889  87.977077  18262.0  0.007034

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2575115   1243  2020-01-01       cs2        1.0     680118.133162     0.040157
'local_data_select': 0.001 seconds
number obs: 267
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.047 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([11.35535179, 11.35537004,  1.03436301])
kernel_variance: 0.0038933330512723303
likelihood_variance: 0.01100000000000001
'predict': 0.033 seconds

2026-05-18 19:14:01.926902: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:14:01.928317: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.53 seconds
--------------------------------------------------
29 / 40
current local expert:
                     x              y        lon       lat        t         z  \
2575163 -176426.718742  141248.575148 -128.68103  87.97647  18262.0  0.054049

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2575163   1243  2020-01-01       cs2        1.0     699665.826003     0.040157
'local_data_select': 0.001 seconds
number obs: 269
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.049 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([11.3450372 , 11.34505569,  1.04022423])
kernel_variance: 0.004019446233577721
likelihood_variance: 0.01100000000000001
'predict': 0.033 seconds

2026-05-18 19:14:02.454694: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:14:02.458383: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.53 seconds
--------------------------------------------------
30 / 40
current local expert:
                     x             y        lon        lat        t        z  \
2575216 -161468.271969  161821.03889 -135.06252  87.953217  18262.0  0.15831

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2575216   1243  2020-01-01       cs2        1.0      724927.60176     0.040157
'local_data_select': 0.001 seconds
number obs: 282
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.052 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([11.33006739, 11.33008626,  1.04810539])
kernel_variance: 0.004183786992135284
likelihood_variance: 0.01100000000000001
'predict': 0.033 seconds

2026-05-18 19:14:02.989455: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:14:02.990971: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

SAVING RESULTS TO TABLES:
run_details
preds
total run time : 0.65 seconds
--------------------------------------------------
31 / 40
current local expert:
                     x              y        lon        lat        t  \
2575261 -150062.318426  177488.986308 -139.78635  87.918974  18262.0

                z  track date_string satellite  lead_mask  dist_along_track  \
2575261  0.031646   1243  2020-01-01       cs2        1.0     744174.979017

         z_track_avg
2575261     0.040157
'local_data_select': 0.001 seconds
number obs: 288
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.046 seconds

2026-05-18 19:14:03.638281: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:14:03.639689: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'_read_params_from_file': 0.051 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([11.31760981, 11.317629  ,  1.05425919])
kernel_variance: 0.004309206589683213
likelihood_variance: 0.01100000000000001
'predict': 0.033 seconds
total run time : 0.53 seconds
--------------------------------------------------
32 / 40
current local expert:
                     x              y        lon        lat        t  \
2575321 -134366.309295  199023.068569 -145.97556  87.849933  18262.0

                z  track date_string satellite  lead_mask  dist_along_track  \
2575321  0.157363   1243  2020-01-01       cs2        1.0     770640.347881

         z_track_avg
2575321     0.040157
'local_data_select': 0.001 seconds
number obs: 283
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.047 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([11.29923976, 11.29925946,  1.06280047])
kernel_variance: 0.004480706680409468
likelihood_variance: 0.01100000000000001
'predict': 0.033 seconds

2026-05-18 19:14:04.173928: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:14:04.175422: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.53 seconds
--------------------------------------------------
33 / 40
current local expert:
                     x              y        lon        lat        t        z  \
2575388 -116333.424483  223724.912572 -152.52628  87.742216  18262.0  0.01667

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2575388   1243  2020-01-01       cs2        1.0     801015.706294     0.040157
'local_data_select': 0.001 seconds
number obs: 299
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.046 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([11.27668039, 11.27670073,  1.07252473])
kernel_variance: 0.004674419146366323
likelihood_variance: 0.01100000000000001
'predict': 0.033 seconds

2026-05-18 19:14:04.701085: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:14:04.702485: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.53 seconds
--------------------------------------------------
34 / 40
current local expert:
                    x              y        lon      lat        t         z  \
2575448 -101857.51502  243524.969665 -157.30224  87.6365  18262.0  0.035483

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2575448   1243  2020-01-01       cs2        1.0     825376.477445     0.040157
'local_data_select': 0.001 seconds
number obs: 293
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.050 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([11.25763852, 11.25765942,  1.08011568])
kernel_variance: 0.004826055520277058
likelihood_variance: 0.01100000000000001
'predict': 0.033 seconds

2026-05-18 19:14:05.233344: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:14:05.234771: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.53 seconds
--------------------------------------------------
35 / 40
current local expert:
                    x              y        lon        lat        t         z  \
2575509 -86832.437751  264048.462412 -161.79653  87.511208  18262.0  0.067852

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2575509   1243  2020-01-01       cs2        1.0     850639.764451     0.040157
'local_data_select': 0.001 seconds
number obs: 286
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.050 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([11.23713401, 11.23715552,  1.08767253])
kernel_variance: 0.004978772067302455
likelihood_variance: 0.01100000000000001
'predict': 0.033 seconds

2026-05-18 19:14:05.765301: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:14:05.766735: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.54 seconds
--------------------------------------------------
36 / 40
current local expert:
                    x              y        lon        lat        t         z  \
2575571 -72152.325617  284073.653488 -165.74871  87.375676  18262.0  0.099573

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2575571   1243  2020-01-01       cs2        1.0      875301.96702     0.040157
'local_data_select': 0.001 seconds
number obs: 292
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.049 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([11.2164718 , 11.21649393,  1.09464759])
kernel_variance: 0.005122612126024067
likelihood_variance: 0.01100000000000001
'predict': 0.033 seconds

2026-05-18 19:14:06.302203: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:14:06.303624: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.53 seconds
--------------------------------------------------
37 / 40
current local expert:
                    x             y        lon        lat        t         z  \
2575615 -58893.782795  302136.70505 -168.96997  87.243762  18262.0  0.273628

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2575615   1243  2020-01-01       cs2        1.0     897558.209613     0.040157
'local_data_select': 0.001 seconds
number obs: 302
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.046 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([11.19734629, 11.197369  ,  1.10053914])
kernel_variance: 0.005247450627581964
likelihood_variance: 0.01100000000000001
'predict': 0.034 seconds

2026-05-18 19:14:06.830913: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:14:06.832317: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.53 seconds
--------------------------------------------------
38 / 40
current local expert:
                    x              y        lon        lat        t         z  \
2575681 -42395.957839  324582.383903 -172.55833  87.068973  18262.0  0.099309

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2575681   1243  2020-01-01       cs2        1.0     925228.580333     0.040157
'local_data_select': 0.001 seconds
number obs: 303
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.049 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([11.17301805, 11.17304151,  1.10726546])
kernel_variance: 0.005395541708509735
likelihood_variance: 0.01100000000000001
'predict': 0.033 seconds

2026-05-18 19:14:07.363049: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:14:07.364441: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.53 seconds
--------------------------------------------------
39 / 40
current local expert:
                    x              y        lon        lat        t         z  \
2575739 -27139.655872  345308.953971 -175.50606  86.898494  18262.0  0.002256

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2575739   1243  2020-01-01       cs2        1.0     950793.711217     0.040157
'local_data_select': 0.001 seconds
number obs: 291
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([11.15007758, 11.15010173,  1.11284443])
kernel_variance: 0.005524976035885116
likelihood_variance: 0.01100000000000001
'predict': 0.034 seconds

2026-05-18 19:14:07.893994: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:14:07.895427: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.54 seconds
--------------------------------------------------
40 / 40
current local expert:
                    x              y        lon        lat        t         z  \
2575778 -16901.524477  359202.028419 -177.30605  86.780036  18262.0  0.082655

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2575778   1243  2020-01-01       cs2        1.0     967937.655732     0.040157
'local_data_select': 0.001 seconds
number obs: 287
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([11.13448349, 11.13450812,  1.11622877])
kernel_variance: 0.00560767734198191
likelihood_variance: 0.01100000000000001
'predict': 0.033 seconds

2026-05-18 19:14:08.434730: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:14:08.436129: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

SAVING RESULTS TO TABLES:
run_details
preds
total run time : 0.71 seconds
'run': 21.842 seconds
reading in results
getting all tables
merging on expert location data
table: 'oi_config' does not have all coords_col: ['x', 'y', 't'] in columns, not merging on expert_locations
table: 'oi_config_SMOOTHED' does not have all coords_col: ['x', 'y', 't'] in columns, not merging on expert_locations
lin:
                     x              y        lon        lat        t  \
2573650 -585146.902831 -432100.026835 -53.556094  83.483790  18262.0
2573651 -584280.987782 -430861.767792 -53.594113  83.496633  18262.0
2573652 -584107.820675 -430614.140368 -53.601734  83.499201  18262.0
2573653 -583934.553028 -430366.439101 -53.609361  83.501770  18262.0
2573654 -583588.157115 -429871.156267 -53.624632  83.506906  18262.0

                z  track date_string satellite  lead_mask  dist_along_track  \
2573650       NaN   1243  2020-01-01       cs2        0.0          0.000000
2573651 -0.034818   1243  2020-01-01       cs2        1.0       1502.990248
2573652 -0.018846   1243  2020-01-01       cs2        1.0       1803.558120
2573653       NaN   1243  2020-01-01       cs2        0.0       2104.243152
2573654       NaN   1243  2020-01-01       cs2        0.0       2705.434872

         z_track_avg     f_lin
2573650     0.040157 -0.061668
2573651     0.040157 -0.061668
2573652     0.040157 -0.060032
2573653     0.040157 -0.061120
2573654     0.040157 -0.062207
gpsat:
                     x              y        lon        lat        t  \
2573650 -585146.902831 -432100.026835 -53.556094  83.483790  18262.0
2573651 -584280.987782 -430861.767792 -53.594113  83.496633  18262.0
2573652 -584107.820675 -430614.140368 -53.601734  83.499201  18262.0
2573653 -583934.553028 -430366.439101 -53.609361  83.501770  18262.0
2573654 -583588.157115 -429871.156267 -53.624632  83.506906  18262.0

                z  track date_string satellite  lead_mask  dist_along_track  \
2573650       NaN   1243  2020-01-01       cs2        0.0          0.000000
2573651 -0.034818   1243  2020-01-01       cs2        1.0       1502.990248
2573652 -0.018846   1243  2020-01-01       cs2        1.0       1803.558120
2573653       NaN   1243  2020-01-01       cs2        0.0       2104.243152
2573654       NaN   1243  2020-01-01       cs2        0.0       2705.434872

         z_track_avg   f_gpsat  f_var_gpsat
2573650     0.040157 -0.066998    -0.066998
2573651     0.040157 -0.067032    -0.067032
2573652     0.040157 -0.067034    -0.067034
2573653     0.040157 -0.067034    -0.067034
2573654     0.040157 -0.067028    -0.067028
Test NaNs — Linear: 0, GPSat: 214
Track interpolated!
Interpolating track 1244, 2 of 15...
'data_select': 0.000 seconds
'load': 0.000 seconds
in json_serializable - key: 'data_source' has value DataFrame/Series, but is too long: 172 >  100
storing as str
in json_serializable - key: 'df' has value DataFrame/Series, but is too long: 214 >  100
storing as str
---------
storing expert locations in 'expert_locs' table
exception occurred: 'No object named expert_locs in the file'
will now close object

---------
dropping expert locations that already exists in 'run_details' table

/tmp/ipykernel_1171781/839927469.py:200: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  track_df['f_gpsat'] = ssha
/tmp/ipykernel_1171781/839927469.py:201: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  track_df['f_var_gpsat'] = ssha_var
/tmp/ipykernel_1171781/839927469.py:66: RuntimeWarning: invalid value encountered in sqrt
  gpsat_std = np.sqrt(gpsat_var[both_valid])
2026-05-18 19:14:09.673277: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:14:09.674709: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

exception occurred: 'No object named run_details in the file'
will now close object

--------------------------------------------------
1 / 4
current local expert:
                    x             y        lon        lat        t         z  \
2578855 -2.746371e+06 -1.415874e+06 -62.726921  62.038805  18262.0  0.194913

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2578855   1244  2020-01-01       cs2        1.0               0.0     0.217885
'data_select': 0.000 seconds
'load': 0.000 seconds
'local_data_select': 0.001 seconds
number obs: 172
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'get_parameters': 0.003 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds
'optimise_parameters': 0.251 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01006156, 10.01002737,  0.99938577])
kernel_variance: 0.0682434860276633
likelihood_variance: 0.0010000000950546645
'predict': 0.031 seconds
total run time : 0.73 seconds
--------------------------------------------------
2 / 4
current local expert:
                    x             y        lon        lat        t         z  \
2578924 -2.725701e+06 -1.402037e+06 -62.779759  62.267242  18262.0  0.250902

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2578924   1244  2020-01-01       cs2        1.0      25491.725756     0.217885
'local_data_select': 0.001 seconds
number obs: 172
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:14:10.403284: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:14:10.404686: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'optimise_parameters': 0.247 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01006156, 10.01002737,  0.99938577])
kernel_variance: 0.0682434860276633
likelihood_variance: 0.0010000000950546645
'predict': 0.031 seconds
total run time : 0.73 seconds
--------------------------------------------------
3 / 4
current local expert:
                    x             y        lon        lat        t         z  \
2578988 -2.705740e+06 -1.388695e+06 -62.831271  62.487615  18262.0  0.257484

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2578988   1244  2020-01-01       cs2        1.0      50084.449376     0.217885
'local_data_select': 0.001 seconds
number obs: 172
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.052 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:14:11.133746: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:14:11.135709: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'optimise_parameters': 0.246 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01006156, 10.01002737,  0.99938577])
kernel_variance: 0.0682434860276633
likelihood_variance: 0.0010000000950546645
'predict': 0.031 seconds
total run time : 0.73 seconds
--------------------------------------------------
4 / 4
current local expert:
                    x             y        lon        lat        t         z  \
2579042 -2.685273e+06 -1.375035e+06 -62.884601  62.713361  18262.0  0.284931

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2579042   1244  2020-01-01       cs2        1.0      75277.692995     0.217885
'local_data_select': 0.001 seconds
number obs: 172
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.049 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:14:11.860812: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:14:11.862203: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'optimise_parameters': 0.245 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01006156, 10.01002737,  0.99938577])
kernel_variance: 0.0682434860276633
likelihood_variance: 0.0010000000950546645
'predict': 0.031 seconds
total run time : 0.73 seconds
storing any remaining tables
SAVING RESULTS TO TABLES:
run_details
preds
lengthscales
kernel_variance
likelihood_variance
'run': 3.104 seconds
reading in results
getting all tables
merging on expert location data
table: 'oi_config' does not have all coords_col: ['x', 'y', 't'] in columns, not merging on expert_locations
h5 tables: ['expert_locs', 'kernel_variance', 'lengthscales', 'likelihood_variance', 'oi_config', 'preds', 'run_details']
found model_name: GPflowGPRModel
found GPU
setting lengthscales to: [1.]
'__init__': 0.049 seconds
reading in results
selecting only tables: ['lengthscales', 'kernel_variance', 'likelihood_variance']
'data_select': 0.000 seconds
'load': 0.000 seconds
expert_locations data will not be merged on results data
adding smoothed table: lengthscales_SMOOTHED
adding smoothed table: kernel_variance_SMOOTHED
adding smoothed table: likelihood_variance_SMOOTHED
writing (smoothed) hyper parameters to:
/home/mhen/geol0069_data/gpsat/jan20/1244.h5
table_suffix:_SMOOTHED
writing: lengthscales_SMOOTHED to table
writing: kernel_variance_SMOOTHED to table
writing: likelihood_variance_SMOOTHED to table
'data_select': 0.000 seconds
'load': 0.000 seconds
in json_serializable - key: 'data_source' has value DataFrame/Series, but is too long: 172 >  100
storing as str
in json_serializable - key: 'df' has value DataFrame/Series, but is too long: 214 >  100
storing as str
---------
storing expert locations in 'expert_locs' table

2026-05-18 19:14:12.822424: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:14:12.823952: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

exception occurred: 'No object named expert_locs_SMOOTHED in the file'
will now close object

---------
dropping expert locations that already exists in 'run_details' table
exception occurred: 'No object named run_details_SMOOTHED in the file'
will now close object

--------------------------------------------------
1 / 4
current local expert:
                    x             y        lon        lat        t         z  \
2578855 -2.746371e+06 -1.415874e+06 -62.726921  62.038805  18262.0  0.194913

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2578855   1244  2020-01-01       cs2        1.0               0.0     0.217885
'data_select': 0.000 seconds
'load': 0.000 seconds
'local_data_select': 0.001 seconds
number obs: 172
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'get_parameters': 0.003 seconds
'_read_params_from_file': 0.050 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01006156, 10.01002737,  0.99938577])
kernel_variance: 0.0682434860276633
likelihood_variance: 0.01100000000000001

2026-05-18 19:14:13.071371: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:14:13.072776: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'predict': 0.031 seconds
total run time : 0.55 seconds
--------------------------------------------------
2 / 4
current local expert:
                    x             y        lon        lat        t         z  \
2578924 -2.725701e+06 -1.402037e+06 -62.779759  62.267242  18262.0  0.250902

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2578924   1244  2020-01-01       cs2        1.0      25491.725756     0.217885
'local_data_select': 0.001 seconds
number obs: 172
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.046 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01006156, 10.01002737,  0.99938577])
kernel_variance: 0.0682434860276633
likelihood_variance: 0.01100000000000001
'predict': 0.031 seconds

2026-05-18 19:14:13.619410: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:14:13.620927: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.53 seconds
--------------------------------------------------
3 / 4
current local expert:
                    x             y        lon        lat        t         z  \
2578988 -2.705740e+06 -1.388695e+06 -62.831271  62.487615  18262.0  0.257484

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2578988   1244  2020-01-01       cs2        1.0      50084.449376     0.217885
'local_data_select': 0.001 seconds
number obs: 172
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.049 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01006156, 10.01002737,  0.99938577])
kernel_variance: 0.06824348602766328
likelihood_variance: 0.01100000000000001
'predict': 0.031 seconds

2026-05-18 19:14:14.152494: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:14:14.153900: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.53 seconds
--------------------------------------------------
4 / 4
current local expert:
                    x             y        lon        lat        t         z  \
2579042 -2.685273e+06 -1.375035e+06 -62.884601  62.713361  18262.0  0.284931

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2579042   1244  2020-01-01       cs2        1.0      75277.692995     0.217885
'local_data_select': 0.001 seconds
number obs: 172
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.050 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01006156, 10.01002737,  0.99938577])
kernel_variance: 0.06824348602766328
likelihood_variance: 0.01100000000000001
'predict': 0.031 seconds

2026-05-18 19:14:14.686065: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:14:14.687483: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.54 seconds
storing any remaining tables
SAVING RESULTS TO TABLES:
run_details
preds
'run': 2.295 seconds
reading in results
getting all tables
merging on expert location data
table: 'oi_config' does not have all coords_col: ['x', 'y', 't'] in columns, not merging on expert_locations
table: 'oi_config_SMOOTHED' does not have all coords_col: ['x', 'y', 't'] in columns, not merging on expert_locations
lin:
                    x             y        lon        lat        t         z  \
2578855 -2.746371e+06 -1.415874e+06 -62.726921  62.038805  18262.0  0.194913
2578856 -2.746128e+06 -1.415711e+06 -62.727540  62.041493  18262.0  0.224580
2578857 -2.745884e+06 -1.415548e+06 -62.728158  62.044180  18262.0  0.226227
2578858 -2.745641e+06 -1.415385e+06 -62.728777  62.046868  18262.0  0.142012
2578859 -2.745398e+06 -1.415223e+06 -62.729395  62.049555  18262.0  0.224326

         track date_string satellite  lead_mask  dist_along_track  \
2578855   1244  2020-01-01       cs2        1.0          0.000000
2578856   1244  2020-01-01       cs2        1.0        299.956725
2578857   1244  2020-01-01       cs2        1.0        599.797262
2578858   1244  2020-01-01       cs2        1.0        899.753373
2578859   1244  2020-01-01       cs2        1.0       1199.593297

         z_track_avg     f_lin
2578855     0.217885  0.209771
2578856     0.217885  0.210205
2578857     0.217885  0.210205
2578858     0.217885  0.210205
2578859     0.217885  0.210205
gpsat:
                    x             y        lon        lat        t         z  \
2578855 -2.746371e+06 -1.415874e+06 -62.726921  62.038805  18262.0  0.194913
2578856 -2.746128e+06 -1.415711e+06 -62.727540  62.041493  18262.0  0.224580
2578857 -2.745884e+06 -1.415548e+06 -62.728158  62.044180  18262.0  0.226227
2578858 -2.745641e+06 -1.415385e+06 -62.728777  62.046868  18262.0  0.142012
2578859 -2.745398e+06 -1.415223e+06 -62.729395  62.049555  18262.0  0.224326

         track date_string satellite  lead_mask  dist_along_track  \
2578855   1244  2020-01-01       cs2        1.0          0.000000
2578856   1244  2020-01-01       cs2        1.0        299.956725
2578857   1244  2020-01-01       cs2        1.0        599.797262
2578858   1244  2020-01-01       cs2        1.0        899.753373
2578859   1244  2020-01-01       cs2        1.0       1199.593297

         z_track_avg   f_gpsat  f_var_gpsat
2578855     0.217885  0.196467     0.000103
2578856     0.217885  0.197084     0.000094
2578857     0.217885  0.197700     0.000085
2578858     0.217885  0.198320     0.000078
2578859     0.217885  0.198947     0.000071
Test NaNs — Linear: 0, GPSat: 0
Track interpolated!
Interpolating track 1245, 3 of 15...

/tmp/ipykernel_1171781/839927469.py:200: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  track_df['f_gpsat'] = ssha
/tmp/ipykernel_1171781/839927469.py:201: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  track_df['f_var_gpsat'] = ssha_var

'data_select': 0.000 seconds
'load': 0.000 seconds
in json_serializable - key: 'data_source' has value DataFrame/Series, but is too long: 856 >  100
storing as str
in json_serializable - key: 'df' has value DataFrame/Series, but is too long: 1630 >  100
storing as str
---------
storing expert locations in 'expert_locs' table
exception occurred: 'No object named expert_locs in the file'
will now close object

---------
dropping expert locations that already exists in 'run_details' table
exception occurred: 'No object named run_details in the file'
will now close object

--------------------------------------------------
1 / 33
current local expert:
                    x             y        lon        lat        t         z  \
2579069 -2.123680e+06 -1.007852e+06 -64.612012  68.824449  18262.0  0.063925

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2579069   1245  2020-01-01       cs2        1.0               0.0     0.062252
'data_select': 0.000 seconds
'load': 0.000 seconds
'local_data_select': 0.001 seconds
number obs: 405
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.046 seconds
'get_parameters': 0.003 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:14:15.882471: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:14:15.883882: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'optimise_parameters': 0.410 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([19.99999849, 18.91242479,  1.00948387])
kernel_variance: 0.004534526764212834
likelihood_variance: 0.002985673680232433
'predict': 0.034 seconds
total run time : 0.90 seconds
--------------------------------------------------
2 / 33
current local expert:
                    x              y       lon        lat        t         z  \
2579128 -2.102930e+06 -994561.284823 -64.68862  69.047324  18262.0  0.109152

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2579128   1245  2020-01-01       cs2        1.0      24915.119643     0.062252
'local_data_select': 0.001 seconds
number obs: 419
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.049 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:14:16.784873: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:14:16.786269: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.556 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.0101304 , 10.01005225,  1.0002049 ])
kernel_variance: 0.0049821737796925305
likelihood_variance: 0.003300324366295419
'predict': 0.035 seconds
total run time : 1.05 seconds
--------------------------------------------------
3 / 33
current local expert:
                    x              y        lon       lat        t         z  \
2579176 -2.081411e+06 -980799.084911 -64.769324  69.27824  18262.0  0.122521

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2579176   1245  2020-01-01       cs2        1.0      50731.599712     0.062252
'local_data_select': 0.001 seconds
number obs: 445
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:14:17.831974: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:14:17.833357: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.551 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01012476, 10.01004985,  1.00493047])
kernel_variance: 0.0041259361612942195
likelihood_variance: 0.003258467918514343
'predict': 0.034 seconds
total run time : 1.04 seconds
--------------------------------------------------
4 / 33
current local expert:
                    x              y        lon        lat        t         z  \
2579218 -2.061627e+06 -968164.945632 -64.844688  69.490346  18262.0  0.113184

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2579218   1245  2020-01-01       cs2        1.0      74447.401822     0.062252
'local_data_select': 0.001 seconds
number obs: 486
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.049 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:14:18.879421: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:14:18.880940: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'optimise_parameters': 0.360 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01016223, 10.01006435,  0.99528858])
kernel_variance: 0.0038338048595240454
likelihood_variance: 0.0030990807782359576
'predict': 0.036 seconds
total run time : 0.86 seconds
--------------------------------------------------
5 / 33
current local expert:
                    x              y        lon        lat        t         z  \
2579278 -2.040324e+06 -954579.692607 -64.927135  69.718545  18262.0 -0.022537

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2579278   1245  2020-01-01       cs2        1.0      99965.119314     0.062252
'local_data_select': 0.001 seconds
number obs: 514
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.047 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:14:19.734129: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:14:19.735582: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'optimise_parameters': 0.347 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01015119, 10.01005986,  0.99459927])
kernel_variance: 0.0035873442090351626
likelihood_variance: 0.003084623892064982
'predict': 0.038 seconds
total run time : 0.85 seconds
--------------------------------------------------
6 / 33
current local expert:
                    x              y        lon        lat        t         z  \
2579332 -2.020258e+06 -941801.574826 -65.006059  69.933307  18262.0  0.105578

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2579332   1245  2020-01-01       cs2        1.0     123982.756275     0.062252
'local_data_select': 0.001 seconds
number obs: 536
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.046 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:14:20.581857: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:14:20.583257: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.657 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01013374, 10.01005287,  1.01466533])
kernel_variance: 0.0037168543588287934
likelihood_variance: 0.0029968224188949883
'predict': 0.041 seconds
total run time : 1.16 seconds
--------------------------------------------------
7 / 33
current local expert:
                    x             y        lon        lat        t         z  \
2579391 -1.998167e+06 -927754.77344 -65.094415  70.169525  18262.0  0.078899

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2579391   1245  2020-01-01       cs2        1.0     150402.792578     0.062252
'local_data_select': 0.001 seconds
number obs: 562
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:14:21.741478: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:14:21.742886: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.825 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01009334, 10.01003683,  0.99832494])
kernel_variance: 0.0034678146959646067
likelihood_variance: 0.003078145775202708
'predict': 0.042 seconds
total run time : 1.33 seconds
--------------------------------------------------
8 / 33
current local expert:
                    x              y        lon      lat        t        z  \
2579442 -1.978821e+06 -915471.710815 -65.173091  70.3762  18262.0  0.08744

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2579442   1245  2020-01-01       cs2        1.0     173521.121609     0.062252
'local_data_select': 0.001 seconds
number obs: 595
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.050 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:14:23.077440: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:14:23.080998: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'optimise_parameters': 0.588 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01014908, 10.01005875,  1.00261481])
kernel_variance: 0.003274046446518507
likelihood_variance: 0.003115758027207704
'predict': 0.042 seconds
total run time : 1.10 seconds
--------------------------------------------------
9 / 33
current local expert:
                    x              y        lon        lat        t         z  \
2579501 -1.956443e+06 -901283.612809 -65.265674  70.615063  18262.0  0.077447

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2579501   1245  2020-01-01       cs2        1.0     200243.055672     0.062252
'local_data_select': 0.001 seconds
number obs: 629
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:14:24.176295: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:14:24.177700: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'optimise_parameters': 0.750 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01014901, 10.01005857,  0.99963349])
kernel_variance: 0.0030611433315457853
likelihood_variance: 0.003137264706815673
'predict': 0.043 seconds
total run time : 1.26 seconds
--------------------------------------------------
10 / 33
current local expert:
                    x              y        lon        lat        t         z  \
2579552 -1.934801e+06 -887583.385654 -65.356868  70.845851  18262.0  0.082295

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2579552   1245  2020-01-01       cs2        1.0     226064.896766     0.062252
'local_data_select': 0.001 seconds
number obs: 646
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.045 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:14:25.435061: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:14:25.436463: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.864 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01015978, 10.01006267,  1.00159375])
kernel_variance: 0.0029156282341944017
likelihood_variance: 0.0030958253660762105
'predict': 0.044 seconds
SAVING RESULTS TO TABLES:
run_details
preds
lengthscales
kernel_variance
likelihood_variance
total run time : 1.51 seconds
--------------------------------------------------
11 / 33
current local expert:
                    x              y        lon        lat        t         z  \
2579594 -1.914905e+06 -875006.524427 -65.442196  71.057834  18262.0  0.053501

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2579594   1245  2020-01-01       cs2        1.0     249785.681433     0.062252
'local_data_select': 0.001 seconds
number obs: 672
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:14:26.949745: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:14:26.951173: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.990 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01015153, 10.01005919,  0.99770508])
kernel_variance: 0.0028642348864629883
likelihood_variance: 0.003032080920816019
'predict': 0.043 seconds
total run time : 1.50 seconds
--------------------------------------------------
12 / 33
current local expert:
                    x              y        lon        lat        t         z  \
2579650 -1.893985e+06 -861801.531034 -65.533506  71.280527  18262.0  0.082855

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2579650   1245  2020-01-01       cs2        1.0     274708.066537     0.062252
'local_data_select': 0.001 seconds
number obs: 709
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.050 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:14:28.455847: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:14:28.457265: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'optimise_parameters': 1.266 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([20.        , 19.99983688,  1.77668877])
kernel_variance: 0.003606334945679146
likelihood_variance: 0.0030224614155794287
'predict': 0.046 seconds
total run time : 1.79 seconds
--------------------------------------------------
13 / 33
current local expert:
                    x              y        lon        lat        t         z  \
2579690 -1.873302e+06 -848764.297981 -65.625447  71.500515  18262.0  0.118574

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2579690   1245  2020-01-01       cs2        1.0     299331.016666     0.062252
'local_data_select': 0.001 seconds
number obs: 734
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.049 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:14:30.244878: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:14:30.246981: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.971 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.0101523 , 10.01005928,  0.99763738])
kernel_variance: 0.002902217884407583
likelihood_variance: 0.0029195608608395254
'predict': 0.047 seconds
total run time : 1.50 seconds
--------------------------------------------------
14 / 33
current local expert:
                    x              y        lon        lat        t         z  \
2579735 -1.851844e+06 -835259.311605 -65.722634  71.728526  18262.0  0.054934

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2579735   1245  2020-01-01       cs2        1.0     324855.557974     0.062252
'local_data_select': 0.001 seconds
number obs: 765
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.046 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:14:31.742965: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:14:31.744384: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'optimise_parameters': 0.941 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01015359, 10.01005979,  1.0114741 ])
kernel_variance: 0.0028049460772540304
likelihood_variance: 0.002854217529715927
'predict': 0.049 seconds
total run time : 1.47 seconds
--------------------------------------------------
15 / 33
current local expert:
                    x             y       lon        lat        t         z  \
2579790 -1.827843e+06 -820176.78342 -65.83361  71.983328  18262.0  0.096107

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2579790   1245  2020-01-01       cs2        1.0     353383.701665     0.062252
'local_data_select': 0.001 seconds
number obs: 787
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.051 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:14:33.221277: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:14:33.222685: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'optimise_parameters': 1.337 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([20.        , 19.99977641,  1.30379296])
kernel_variance: 0.003972091283724903
likelihood_variance: 0.002933066191909187
'predict': 0.049 seconds
total run time : 1.87 seconds
--------------------------------------------------
16 / 33
current local expert:
                    x              y        lon        lat        t         z  \
2579839 -1.810144e+06 -809070.909705 -65.917034  72.171054  18262.0  0.114411

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2579839   1245  2020-01-01       cs2        1.0     374405.048551     0.062252
'local_data_select': 0.001 seconds
number obs: 817
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.049 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:14:35.089829: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:14:35.091233: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 1.557 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01015202, 10.01005896,  0.9956738 ])
kernel_variance: 0.0033000885100695505
likelihood_variance: 0.0028691779130013044
'predict': 0.052 seconds
total run time : 2.09 seconds
--------------------------------------------------
17 / 33
current local expert:
                    x              y        lon       lat        t         z  \
2579885 -1.788638e+06 -795593.940072 -66.020289  72.39898  18262.0 -0.050633

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2579885   1245  2020-01-01       cs2        1.0     399931.694525     0.062252
'local_data_select': 0.001 seconds
number obs: 852
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.050 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:14:37.180815: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:14:37.182413: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'optimise_parameters': 1.163 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01019212, 10.0100759 ,  0.99756976])
kernel_variance: 0.0034566710048219308
likelihood_variance: 0.0029091873713637355
'predict': 0.053 seconds
total run time : 1.70 seconds
--------------------------------------------------
18 / 33
current local expert:
                    x              y        lon        lat        t         z  \
2579932 -1.765848e+06 -781334.800279 -66.132042  72.640278  18262.0 -0.095678

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2579932   1245  2020-01-01       cs2        1.0     426960.602039     0.062252
'local_data_select': 0.001 seconds
number obs: 813
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:14:38.877499: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:14:38.878925: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'optimise_parameters': 1.616 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01013586, 10.01005253,  0.99996388])
kernel_variance: 0.0031212526699973078
likelihood_variance: 0.0030147983910452556
'predict': 0.053 seconds
total run time : 2.15 seconds
--------------------------------------------------
19 / 33
current local expert:
                    x              y        lon        lat        t         z  \
2579970 -1.746081e+06 -768985.649491 -66.230993  72.849373  18262.0  0.049758

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2579970   1245  2020-01-01       cs2        1.0      450386.34718     0.062252
'local_data_select': 0.001 seconds
number obs: 785
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.049 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:14:41.026618: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:14:41.028033: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 1.290 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01007916, 10.0100304 ,  1.00316234])
kernel_variance: 0.0035182691899729376
likelihood_variance: 0.0027463205695956727
'predict': 0.050 seconds
total run time : 1.82 seconds
--------------------------------------------------
20 / 33
current local expert:
                    x              y      lon        lat        t         z  \
2580023 -1.725286e+06 -756012.133513 -66.3372  73.069159  18262.0  0.042439

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2580023   1245  2020-01-01       cs2        1.0     475014.055822     0.062252
'local_data_select': 0.001 seconds
number obs: 757
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.046 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:14:42.848425: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:14:42.849927: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 1.222 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01015177, 10.01005881,  0.98563313])
kernel_variance: 0.0031160370624811486
likelihood_variance: 0.0027947934732302955
'predict': 0.048 seconds
SAVING RESULTS TO TABLES:
run_details
preds
lengthscales
kernel_variance
likelihood_variance
total run time : 1.92 seconds
--------------------------------------------------
21 / 33
current local expert:
                    x              y        lon       lat        t         z  \
2580074 -1.703968e+06 -742731.699927 -66.448408  73.29427  18262.0  0.100108

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2580074   1245  2020-01-01       cs2        1.0      500243.10991     0.062252
'local_data_select': 0.001 seconds
number obs: 716
found GPU
setting lengthscales to: [1. 1. 1.]

2026-05-18 19:14:44.780641: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:14:44.782077: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'__init__': 0.054 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds
**********
optimization failed!
'optimise_parameters': 0.931 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01014877, 10.0100574 ,  0.99608651])
kernel_variance: 0.0024932485771315444
likelihood_variance: 0.0028832458409375032
'predict': 0.047 seconds
total run time : 1.48 seconds
--------------------------------------------------
22 / 33
current local expert:
                    x              y        lon        lat        t         z  \
2580121 -1.683143e+06 -729776.796483 -66.559416  73.513985  18262.0  0.066472

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2580121   1245  2020-01-01       cs2        1.0     524872.156201     0.062252
'local_data_select': 0.001 seconds
number obs: 698
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:14:46.254961: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:14:46.256520: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.879 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01015156, 10.01005838,  0.99633199])
kernel_variance: 0.0025537525982073385
likelihood_variance: 0.0029188661964584806
'predict': 0.045 seconds
total run time : 1.41 seconds
--------------------------------------------------
23 / 33
current local expert:
                    x              y       lon       lat        t         z  \
2580168 -1.662048e+06 -716673.440025 -66.67434  73.73634  18262.0  0.067306

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2580168   1245  2020-01-01       cs2        1.0     549802.107473     0.062252
'local_data_select': 0.001 seconds
number obs: 671
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.049 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:14:47.670742: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:14:47.672205: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'optimise_parameters': 0.671 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01012142, 10.01004653,  0.99908333])
kernel_variance: 0.002463982898726268
likelihood_variance: 0.0030061826604252484
'predict': 0.045 seconds
total run time : 1.20 seconds
--------------------------------------------------
24 / 33
current local expert:
                    x              y        lon        lat        t         z  \
2580232 -1.640683e+06 -703421.875383 -66.793384  73.961334  18262.0  0.065528

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2580232   1245  2020-01-01       cs2        1.0     575033.255414     0.062252
'local_data_select': 0.001 seconds
number obs: 650
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:14:48.873244: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:14:48.874646: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.986 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01014844, 10.01005685,  0.99985833])
kernel_variance: 0.002494597532707603
likelihood_variance: 0.00307491035359959
'predict': 0.043 seconds
total run time : 1.52 seconds
--------------------------------------------------
25 / 33
current local expert:
                    x              y        lon        lat        t         z  \
2580287 -1.619303e+06 -690180.305368 -66.915293  74.186283  18262.0  0.129783

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2580287   1245  2020-01-01       cs2        1.0     600264.934524     0.062252
'local_data_select': 0.001 seconds
number obs: 633
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.049 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:14:50.393223: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:14:50.394643: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'optimise_parameters': 0.630 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01015646, 10.01006017,  0.99916086])
kernel_variance: 0.002045113986616646
likelihood_variance: 0.003050657797941141
'predict': 0.044 seconds
total run time : 1.16 seconds
--------------------------------------------------
26 / 33
current local expert:
                    x              y        lon       lat        t         z  \
2580333 -1.599945e+06 -678208.323541 -67.028166  74.38977  18262.0  0.082724

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2580333   1245  2020-01-01       cs2        1.0     623094.323442     0.062252
'local_data_select': 0.001 seconds
number obs: 613
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.049 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:14:51.558863: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:14:51.560267: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'optimise_parameters': 0.453 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01007269, 10.01002787,  1.00256799])
kernel_variance: 0.002201537031367294
likelihood_variance: 0.0027481076218892108
'predict': 0.048 seconds
total run time : 0.99 seconds
--------------------------------------------------
27 / 33
current local expert:
                    x              y        lon        lat        t         z  \
2580392 -1.577005e+06 -664041.665012 -67.165129  74.630689  18262.0  0.046723

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2580392   1245  2020-01-01       cs2        1.0     650129.685621     0.062252
'local_data_select': 0.001 seconds
number obs: 603
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.053 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:14:52.553977: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:14:52.557929: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'optimise_parameters': 0.567 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01015883, 10.01006097,  1.03787416])
kernel_variance: 0.0021948741987011457
likelihood_variance: 0.0027532892793069664
'predict': 0.042 seconds
total run time : 1.12 seconds
--------------------------------------------------
28 / 33
current local expert:
                    x              y        lon        lat        t         z  \
2580450 -1.556089e+06 -651144.315626 -67.293167  74.850143  18262.0 -0.008433

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2580450   1245  2020-01-01       cs2        1.0     674762.652175     0.062252
'local_data_select': 0.001 seconds
number obs: 583
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.047 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:14:53.668498: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:14:53.669904: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'optimise_parameters': 0.449 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01016174, 10.0100619 ,  0.99896434])
kernel_variance: 0.0024026841363712806
likelihood_variance: 0.00280866718840107
'predict': 0.041 seconds
total run time : 0.98 seconds
--------------------------------------------------
29 / 33
current local expert:
                    x              y        lon        lat        t         z  \
2580500 -1.535670e+06 -638570.856714 -67.421203  75.064195  18262.0  0.013205

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2580500   1245  2020-01-01       cs2        1.0     698795.381859     0.062252
'local_data_select': 0.001 seconds
number obs: 566
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.046 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:14:54.650119: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:14:54.651519: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.781 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01015004, 10.01005728,  0.99480571])
kernel_variance: 0.0026802935116575334
likelihood_variance: 0.002841917854918743
'predict': 0.041 seconds
total run time : 1.32 seconds
--------------------------------------------------
30 / 33
current local expert:
                    x              y        lon        lat        t         z  \
2580543 -1.513703e+06 -625064.751365 -67.562432  75.294244  18262.0  0.007827

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2580543   1245  2020-01-01       cs2        1.0     724631.223094     0.062252
'local_data_select': 0.001 seconds
number obs: 538
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.055 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:14:55.979949: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:14:55.981349: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.832 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.00208165, 10.00541528,  0.49014462])
kernel_variance: 0.0025840480294434466
likelihood_variance: 0.002651558893198177
'predict': 0.040 seconds
SAVING RESULTS TO TABLES:
run_details
preds
lengthscales
kernel_variance
likelihood_variance
total run time : 1.55 seconds
--------------------------------------------------
31 / 33
current local expert:
                    x              y        lon        lat        t         z  \
2580581 -1.492999e+06 -612353.665426 -67.699009  75.510862  18262.0  0.161727

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2580581   1245  2020-01-01       cs2        1.0     748965.684263     0.062252
'local_data_select': 0.001 seconds
number obs: 504

2026-05-18 19:14:57.529098: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:14:57.530513: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.051 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds
'optimise_parameters': 0.394 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01007591, 10.01002883,  1.00274736])
kernel_variance: 0.0026278205432463714
likelihood_variance: 0.0026939832806817574
'predict': 0.036 seconds
total run time : 0.94 seconds
--------------------------------------------------
32 / 33
current local expert:
                    x              y        lon        lat        t         z  \
2580629 -1.470702e+06 -598684.726212 -67.850031  75.743922  18262.0  0.075319

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2580629   1245  2020-01-01       cs2        1.0     775155.157913     0.062252
'local_data_select': 0.001 seconds
number obs: 485
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.049 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:14:58.467246: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:14:58.469204: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.710 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01016249, 10.01006198,  0.9938856 ])
kernel_variance: 0.0027852474775332493
likelihood_variance: 0.0027602054498561037
'predict': 0.035 seconds
total run time : 1.24 seconds
--------------------------------------------------
33 / 33
current local expert:
                    x              y        lon        lat        t         z  \
2580675 -1.449456e+06 -585679.690957 -67.997909  75.965774  18262.0  0.033903

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2580675   1245  2020-01-01       cs2        1.0     800093.202584     0.062252
'local_data_select': 0.001 seconds
number obs: 460
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.049 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:14:59.712650: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:14:59.714064: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'optimise_parameters': 0.437 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.0000007 , 10.00037025,  1.01822372])
kernel_variance: 0.002117083218135233
likelihood_variance: 0.0027907124595568412
'predict': 0.034 seconds
total run time : 0.97 seconds
storing any remaining tables
SAVING RESULTS TO TABLES:
run_details
preds
lengthscales
kernel_variance
likelihood_variance
'run': 45.051 seconds
reading in results
getting all tables
merging on expert location data
table: 'oi_config' does not have all coords_col: ['x', 'y', 't'] in columns, not merging on expert_locations
h5 tables: ['expert_locs', 'kernel_variance', 'lengthscales', 'likelihood_variance', 'oi_config', 'preds', 'run_details']
found model_name: GPflowGPRModel
found GPU
setting lengthscales to: [1.]
'__init__': 0.049 seconds
reading in results
selecting only tables: ['lengthscales', 'kernel_variance', 'likelihood_variance']
'data_select': 0.000 seconds
'load': 0.000 seconds
expert_locations data will not be merged on results data
adding smoothed table: lengthscales_SMOOTHED
adding smoothed table: kernel_variance_SMOOTHED
adding smoothed table: likelihood_variance_SMOOTHED
writing (smoothed) hyper parameters to:
/home/mhen/geol0069_data/gpsat/jan20/1245.h5
table_suffix:_SMOOTHED
writing: lengthscales_SMOOTHED to table
writing: kernel_variance_SMOOTHED to table
writing: likelihood_variance_SMOOTHED to table

2026-05-18 19:15:01.036944: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:15:01.038356: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'data_select': 0.000 seconds
'load': 0.000 seconds
in json_serializable - key: 'data_source' has value DataFrame/Series, but is too long: 856 >  100
storing as str
in json_serializable - key: 'df' has value DataFrame/Series, but is too long: 1630 >  100
storing as str
---------
storing expert locations in 'expert_locs' table
exception occurred: 'No object named expert_locs_SMOOTHED in the file'
will now close object

---------
dropping expert locations that already exists in 'run_details' table
exception occurred: 'No object named run_details_SMOOTHED in the file'
will now close object

--------------------------------------------------
1 / 33
current local expert:
                    x             y        lon        lat        t         z  \
2579069 -2.123680e+06 -1.007852e+06 -64.612012  68.824449  18262.0  0.063925

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2579069   1245  2020-01-01       cs2        1.0               0.0     0.062252
'data_select': 0.000 seconds
'load': 0.000 seconds
'local_data_select': 0.001 seconds
number obs: 405
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.050 seconds
'get_parameters': 0.003 seconds
'_read_params_from_file': 0.049 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds

2026-05-18 19:15:01.306072: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:15:01.307500: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.31231576, 10.31224403,  1.03678158])
kernel_variance: 0.0036987912299580486
likelihood_variance: 0.01100000000000001
'predict': 0.034 seconds
total run time : 0.60 seconds
--------------------------------------------------
2 / 33
current local expert:
                    x              y       lon        lat        t         z  \
2579128 -2.102930e+06 -994561.284823 -64.68862  69.047324  18262.0  0.109152

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2579128   1245  2020-01-01       cs2        1.0      24915.119643     0.062252
'local_data_select': 0.001 seconds
number obs: 419
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.049 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.30574993, 10.30567794,  1.03957786])
kernel_variance: 0.00366161992808616
likelihood_variance: 0.01100000000000001
'predict': 0.035 seconds

2026-05-18 19:15:01.904421: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:15:01.905971: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.60 seconds
--------------------------------------------------
3 / 33
current local expert:
                    x              y        lon       lat        t         z  \
2579176 -2.081411e+06 -980799.084911 -64.769324  69.27824  18262.0  0.122521

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2579176   1245  2020-01-01       cs2        1.0      50731.599712     0.062252
'local_data_select': 0.001 seconds
number obs: 445
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.047 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.29984518, 10.29977304,  1.04246704])
kernel_variance: 0.003622392126854913
likelihood_variance: 0.01100000000000001
'predict': 0.034 seconds

2026-05-18 19:15:02.499290: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:15:02.500698: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.58 seconds
--------------------------------------------------
4 / 33
current local expert:
                    x              y        lon        lat        t         z  \
2579218 -2.061627e+06 -968164.945632 -64.844688  69.490346  18262.0  0.113184

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2579218   1245  2020-01-01       cs2        1.0      74447.401822     0.062252
'local_data_select': 0.001 seconds
number obs: 486
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.29512816, 10.295056  ,  1.04505871])
kernel_variance: 0.003585775938377659
likelihood_variance: 0.01100000000000001
'predict': 0.036 seconds

2026-05-18 19:15:03.085415: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:15:03.087443: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.58 seconds
--------------------------------------------------
5 / 33
current local expert:
                    x              y        lon        lat        t         z  \
2579278 -2.040324e+06 -954579.692607 -64.927135  69.718545  18262.0 -0.022537

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2579278   1245  2020-01-01       cs2        1.0      99965.119314     0.062252
'local_data_select': 0.001 seconds
number obs: 514
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.050 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.29066606, 10.29059408,  1.04771187])
kernel_variance: 0.003545813498282555
likelihood_variance: 0.01100000000000001
'predict': 0.039 seconds

2026-05-18 19:15:03.672076: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:15:03.673484: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.60 seconds
--------------------------------------------------
6 / 33
current local expert:
                    x              y        lon        lat        t         z  \
2579332 -2.020258e+06 -941801.574826 -65.006059  69.933307  18262.0  0.105578

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2579332   1245  2020-01-01       cs2        1.0     123982.756275     0.062252
'local_data_select': 0.001 seconds
number obs: 536
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.2868817 , 10.28681009,  1.05000979])
kernel_variance: 0.003507709492203557
likelihood_variance: 0.01100000000000001
'predict': 0.041 seconds

2026-05-18 19:15:04.269395: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:15:04.270840: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.60 seconds
--------------------------------------------------
7 / 33
current local expert:
                    x             y        lon        lat        t         z  \
2579391 -1.998167e+06 -927754.77344 -65.094415  70.169525  18262.0  0.078899

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2579391   1245  2020-01-01       cs2        1.0     150402.792578     0.062252
'local_data_select': 0.001 seconds
number obs: 562
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.050 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.28295669, 10.28288578,  1.05222499])
kernel_variance: 0.0034652815164092536
likelihood_variance: 0.01100000000000001
'predict': 0.042 seconds

2026-05-18 19:15:04.871554: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:15:04.875251: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.60 seconds
--------------------------------------------------
8 / 33
current local expert:
                    x              y        lon      lat        t        z  \
2579442 -1.978821e+06 -915471.710815 -65.173091  70.3762  18262.0  0.08744

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2579442   1245  2020-01-01       cs2        1.0     173521.121609     0.062252
'local_data_select': 0.001 seconds
number obs: 595
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.047 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.27951356, 10.27944358,  1.05381714])
kernel_variance: 0.0034277337003429
likelihood_variance: 0.01100000000000001
'predict': 0.042 seconds

2026-05-18 19:15:05.474444: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:15:05.475889: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.60 seconds
--------------------------------------------------
9 / 33
current local expert:
                    x              y        lon        lat        t         z  \
2579501 -1.956443e+06 -901283.612809 -65.265674  70.615063  18262.0  0.077447

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2579501   1245  2020-01-01       cs2        1.0     200243.055672     0.062252
'local_data_select': 0.001 seconds
number obs: 629
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.046 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.27524821, 10.27517977,  1.05516128])
kernel_variance: 0.0033838494971088423
likelihood_variance: 0.01100000000000001
'predict': 0.043 seconds

2026-05-18 19:15:06.076788: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:15:06.078212: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.59 seconds
--------------------------------------------------
10 / 33
current local expert:
                    x              y        lon        lat        t         z  \
2579552 -1.934801e+06 -887583.385654 -65.356868  70.845851  18262.0  0.082295

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2579552   1245  2020-01-01       cs2        1.0     226064.896766     0.062252
'local_data_select': 0.001 seconds
number obs: 646
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.052 seconds
'_read_params_from_file': 0.045 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.27055262, 10.27048623,  1.05586506])
kernel_variance: 0.0033409458091672264
likelihood_variance: 0.01100000000000001
'predict': 0.044 seconds

2026-05-18 19:15:06.674278: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:15:06.675715: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

SAVING RESULTS TO TABLES:
run_details
preds
total run time : 0.67 seconds
--------------------------------------------------
11 / 33
current local expert:
                    x              y        lon        lat        t         z  \
2579594 -1.914905e+06 -875006.524427 -65.442196  71.057834  18262.0  0.053501

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2579594   1245  2020-01-01       cs2        1.0     249785.681433     0.062252
'local_data_select': 0.001 seconds
number obs: 672
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.049 seconds
'_read_params_from_file': 0.049 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters

2026-05-18 19:15:07.344001: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:15:07.345416: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.26550578, 10.26544188,  1.05592677])
kernel_variance: 0.0033010923937895694
likelihood_variance: 0.01100000000000001
'predict': 0.043 seconds
total run time : 0.60 seconds
--------------------------------------------------
12 / 33
current local expert:
                    x              y        lon        lat        t         z  \
2579650 -1.893985e+06 -861801.531034 -65.533506  71.280527  18262.0  0.082855

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2579650   1245  2020-01-01       cs2        1.0     274708.066537     0.062252
'local_data_select': 0.001 seconds
number obs: 709
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'_read_params_from_file': 0.045 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.25923671, 10.25917616,  1.0553324 ])
kernel_variance: 0.003258758654158441
likelihood_variance: 0.01100000000000001
'predict': 0.046 seconds

2026-05-18 19:15:07.942965: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:15:07.944367: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.60 seconds
--------------------------------------------------
13 / 33
current local expert:
                    x              y        lon        lat        t         z  \
2579690 -1.873302e+06 -848764.297981 -65.625447  71.500515  18262.0  0.118574

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2579690   1245  2020-01-01       cs2        1.0     299331.016666     0.062252
'local_data_select': 0.001 seconds
number obs: 734
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.047 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.2519055 , 10.25184915,  1.0540444 ])
kernel_variance: 0.003216475264880911
likelihood_variance: 0.01100000000000001
'predict': 0.046 seconds

2026-05-18 19:15:08.541809: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:15:08.543220: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.60 seconds
--------------------------------------------------
14 / 33
current local expert:
                    x              y        lon        lat        t         z  \
2579735 -1.851844e+06 -835259.311605 -65.722634  71.728526  18262.0  0.054934

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2579735   1245  2020-01-01       cs2        1.0     324855.557974     0.062252
'local_data_select': 0.001 seconds
number obs: 765
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.047 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.24299709, 10.24294615,  1.05195679])
kernel_variance: 0.0031721956358358775
likelihood_variance: 0.01100000000000001
'predict': 0.049 seconds

2026-05-18 19:15:09.138251: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:15:09.139687: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.60 seconds
--------------------------------------------------
15 / 33
current local expert:
                    x             y       lon        lat        t         z  \
2579790 -1.827843e+06 -820176.78342 -65.83361  71.983328  18262.0  0.096107

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2579790   1245  2020-01-01       cs2        1.0     353383.701665     0.062252
'local_data_select': 0.001 seconds
number obs: 787
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.23141536, 10.23137194,  1.04872905])
kernel_variance: 0.0031222583227827165
likelihood_variance: 0.01100000000000001
'predict': 0.049 seconds

2026-05-18 19:15:09.738499: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:15:09.739922: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.60 seconds
--------------------------------------------------
16 / 33
current local expert:
                    x              y        lon        lat        t         z  \
2579839 -1.810144e+06 -809070.909705 -65.917034  72.171054  18262.0  0.114411

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2579839   1245  2020-01-01       cs2        1.0     374405.048551     0.062252
'local_data_select': 0.001 seconds
number obs: 817
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.051 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.22181756, 10.22178076,  1.04577563])
kernel_variance: 0.0030852591742203607
likelihood_variance: 0.01100000000000001
'predict': 0.052 seconds

2026-05-18 19:15:10.343908: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:15:10.345309: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.62 seconds
--------------------------------------------------
17 / 33
current local expert:
                    x              y        lon       lat        t         z  \
2579885 -1.788638e+06 -795593.940072 -66.020289  72.39898  18262.0 -0.050633

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2579885   1245  2020-01-01       cs2        1.0     399931.694525     0.062252
'local_data_select': 0.001 seconds
number obs: 852
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.051 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.20906229, 10.20903488,  1.04158989])
kernel_variance: 0.0030402658438253975
likelihood_variance: 0.01100000000000001
'predict': 0.053 seconds

2026-05-18 19:15:10.961696: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:15:10.963123: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.61 seconds
--------------------------------------------------
18 / 33
current local expert:
                    x              y        lon        lat        t         z  \
2579932 -1.765848e+06 -781334.800279 -66.132042  72.640278  18262.0 -0.095678

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2579932   1245  2020-01-01       cs2        1.0     426960.602039     0.062252
'local_data_select': 0.001 seconds
number obs: 813
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.050 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.19445201, 10.19443625,  1.03653163])
kernel_variance: 0.002992805326695111
likelihood_variance: 0.01100000000000001
'predict': 0.052 seconds

2026-05-18 19:15:11.571005: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:15:11.572407: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.60 seconds
--------------------------------------------------
19 / 33
current local expert:
                    x              y        lon        lat        t         z  \
2579970 -1.746081e+06 -768985.649491 -66.230993  72.849373  18262.0  0.049758

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2579970   1245  2020-01-01       cs2        1.0      450386.34718     0.062252
'local_data_select': 0.001 seconds
number obs: 785
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.051 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.1811034 , 10.18109916,  1.03171936])
kernel_variance: 0.0029520903532413933
likelihood_variance: 0.01100000000000001
'predict': 0.050 seconds

2026-05-18 19:15:12.177791: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:15:12.179224: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.61 seconds
--------------------------------------------------
20 / 33
current local expert:
                    x              y      lon        lat        t         z  \
2580023 -1.725286e+06 -756012.133513 -66.3372  73.069159  18262.0  0.042439

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2580023   1245  2020-01-01       cs2        1.0     475014.055822     0.062252
'local_data_select': 0.001 seconds
number obs: 757
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.16664879, 10.16665814,  1.02633311])
kernel_variance: 0.0029100087533972018
likelihood_variance: 0.01100000000000001
'predict': 0.048 seconds

2026-05-18 19:15:12.781528: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:15:12.782969: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

SAVING RESULTS TO TABLES:
run_details
preds
total run time : 0.71 seconds
--------------------------------------------------
21 / 33
current local expert:
                    x              y        lon       lat        t         z  \
2580074 -1.703968e+06 -742731.699927 -66.448408  73.29427  18262.0  0.100108

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2580074   1245  2020-01-01       cs2        1.0      500243.10991     0.062252
'local_data_select': 0.001 seconds
number obs: 716
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.049 seconds

2026-05-18 19:15:13.489822: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:15:13.491403: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'_read_params_from_file': 0.050 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.15168541, 10.15171016,  1.02057756])
kernel_variance: 0.002868005238011785
likelihood_variance: 0.01100000000000001
'predict': 0.047 seconds
total run time : 0.62 seconds
--------------------------------------------------
22 / 33
current local expert:
                    x              y        lon        lat        t         z  \
2580121 -1.683143e+06 -729776.796483 -66.559416  73.513985  18262.0  0.066472

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2580121   1245  2020-01-01       cs2        1.0     524872.156201     0.062252
'local_data_select': 0.001 seconds
number obs: 698
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.047 seconds
'_read_params_from_file': 0.045 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.13721097, 10.13725213,  1.01483417])
kernel_variance: 0.0028284194410642047
likelihood_variance: 0.01100000000000001
'predict': 0.045 seconds

2026-05-18 19:15:14.105803: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:15:14.107202: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.59 seconds
--------------------------------------------------
23 / 33
current local expert:
                    x              y       lon       lat        t         z  \
2580168 -1.662048e+06 -716673.440025 -66.67434  73.73634  18262.0  0.067306

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2580168   1245  2020-01-01       cs2        1.0     549802.107473     0.062252
'local_data_select': 0.001 seconds
number obs: 671
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.12295967, 10.12301868,  1.00899715])
kernel_variance: 0.0027901055491912716
likelihood_variance: 0.01100000000000001
'predict': 0.045 seconds

2026-05-18 19:15:14.702415: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:15:14.703951: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.60 seconds
--------------------------------------------------
24 / 33
current local expert:
                    x              y        lon        lat        t         z  \
2580232 -1.640683e+06 -703421.875383 -66.793384  73.961334  18262.0  0.065528

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2580232   1245  2020-01-01       cs2        1.0     575033.255414     0.062252
'local_data_select': 0.001 seconds
number obs: 650
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.10918132, 10.10925949,  1.00315935])
kernel_variance: 0.0027534290422407738
likelihood_variance: 0.01100000000000001
'predict': 0.043 seconds

2026-05-18 19:15:15.299373: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:15:15.301367: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.59 seconds
--------------------------------------------------
25 / 33
current local expert:
                    x              y        lon        lat        t         z  \
2580287 -1.619303e+06 -690180.305368 -66.915293  74.186283  18262.0  0.129783

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2580287   1245  2020-01-01       cs2        1.0     600264.934524     0.062252
'local_data_select': 0.001 seconds
number obs: 633
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.046 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.09624304, 10.09634127,  0.99747319])
kernel_variance: 0.002719120444787177
likelihood_variance: 0.01100000000000001
'predict': 0.044 seconds

2026-05-18 19:15:15.894104: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:15:15.895522: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.60 seconds
--------------------------------------------------
26 / 33
current local expert:
                    x              y        lon       lat        t         z  \
2580333 -1.599945e+06 -678208.323541 -67.028166  74.38977  18262.0  0.082724

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2580333   1245  2020-01-01       cs2        1.0     623094.323442     0.062252
'local_data_select': 0.001 seconds
number obs: 613
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.050 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.08537831, 10.08549527,  0.99251535])
kernel_variance: 0.0026902830227117326
likelihood_variance: 0.01100000000000001
'predict': 0.043 seconds

2026-05-18 19:15:16.494893: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:15:16.496324: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.60 seconds
--------------------------------------------------
27 / 33
current local expert:
                    x              y        lon        lat        t         z  \
2580392 -1.577005e+06 -664041.665012 -67.165129  74.630689  18262.0  0.046723

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2580392   1245  2020-01-01       cs2        1.0     650129.685621     0.062252
'local_data_select': 0.001 seconds
number obs: 603
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.050 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.0736393 , 10.07377892,  0.9869288 ])
kernel_variance: 0.0026589757277303843
likelihood_variance: 0.01100000000000001
'predict': 0.042 seconds

2026-05-18 19:15:17.092987: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:15:17.094396: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.59 seconds
--------------------------------------------------
28 / 33
current local expert:
                    x              y        lon        lat        t         z  \
2580450 -1.556089e+06 -651144.315626 -67.293167  74.850143  18262.0 -0.008433

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2580450   1245  2020-01-01       cs2        1.0     674762.652175     0.062252
'local_data_select': 0.001 seconds
number obs: 583
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.049 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.06404788, 10.06420833,  0.98214512])
kernel_variance: 0.0026331923387045006
likelihood_variance: 0.01100000000000001
'predict': 0.041 seconds

2026-05-18 19:15:17.686969: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:15:17.688372: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.59 seconds
--------------------------------------------------
29 / 33
current local expert:
                    x              y        lon        lat        t         z  \
2580500 -1.535670e+06 -638570.856714 -67.421203  75.064195  18262.0  0.013205

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2580500   1245  2020-01-01       cs2        1.0     698795.381859     0.062252
'local_data_select': 0.001 seconds
number obs: 566
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.05570472, 10.05588547,  0.97778336])
kernel_variance: 0.0026105513773480226
likelihood_variance: 0.01100000000000001
'predict': 0.041 seconds

2026-05-18 19:15:18.279859: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:15:18.281285: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.60 seconds
--------------------------------------------------
30 / 33
current local expert:
                    x              y        lon        lat        t         z  \
2580543 -1.513703e+06 -625064.751365 -67.562432  75.294244  18262.0  0.007827

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2580543   1245  2020-01-01       cs2        1.0     724631.223094     0.062252
'local_data_select': 0.001 seconds
number obs: 538
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.046 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.04781865, 10.04802095,  0.97344554])
kernel_variance: 0.002588915842992128
likelihood_variance: 0.01100000000000001
'predict': 0.040 seconds

2026-05-18 19:15:18.882173: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:15:18.883595: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

SAVING RESULTS TO TABLES:
run_details
preds
total run time : 0.69 seconds
--------------------------------------------------
31 / 33
current local expert:
                    x              y        lon        lat        t         z  \
2580581 -1.492999e+06 -612353.665426 -67.699009  75.510862  18262.0  0.161727

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2580581   1245  2020-01-01       cs2        1.0     748965.684263     0.062252
'local_data_select': 0.001 seconds
number obs: 504
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.049 seconds

2026-05-18 19:15:19.579344: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:15:19.580744: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'_read_params_from_file': 0.050 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.04136085, 10.04158301,  0.96969834])
kernel_variance: 0.002570992091557226
likelihood_variance: 0.01100000000000001
'predict': 0.036 seconds
total run time : 0.59 seconds
--------------------------------------------------
32 / 33
current local expert:
                    x              y        lon        lat        t         z  \
2580629 -1.470702e+06 -598684.726212 -67.850031  75.743922  18262.0  0.075319

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2580629   1245  2020-01-01       cs2        1.0     775155.157913     0.062252
'local_data_select': 0.001 seconds
number obs: 485
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.051 seconds
'_read_params_from_file': 0.045 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.03538094, 10.03562382,  0.96603151])
kernel_variance: 0.002554200662427468
likelihood_variance: 0.01100000000000001
'predict': 0.035 seconds

2026-05-18 19:15:20.174944: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:15:20.176351: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.59 seconds
--------------------------------------------------
33 / 33
current local expert:
                    x              y        lon        lat        t         z  \
2580675 -1.449456e+06 -585679.690957 -67.997909  75.965774  18262.0  0.033903

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2580675   1245  2020-01-01       cs2        1.0     800093.202584     0.062252
'local_data_select': 0.001 seconds
number obs: 460
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.03053395, 10.03079576,  0.96288638])
kernel_variance: 0.00254043660334227
likelihood_variance: 0.01100000000000001
'predict': 0.034 seconds

2026-05-18 19:15:20.759370: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:15:20.761529: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.58 seconds
storing any remaining tables
SAVING RESULTS TO TABLES:
run_details
preds
'run': 20.252 seconds
reading in results
getting all tables
merging on expert location data
table: 'oi_config' does not have all coords_col: ['x', 'y', 't'] in columns, not merging on expert_locations
table: 'oi_config_SMOOTHED' does not have all coords_col: ['x', 'y', 't'] in columns, not merging on expert_locations
lin:
                    x             y        lon        lat        t         z  \
2579069 -2.123680e+06 -1.007852e+06 -64.612012  68.824449  18262.0  0.063925
2579070 -2.123430e+06 -1.007692e+06 -64.612928  68.827134  18262.0  0.065377
2579071 -2.123180e+06 -1.007531e+06 -64.613844  68.829820  18262.0  0.096861
2579072 -2.122930e+06 -1.007371e+06 -64.614760  68.832505  18262.0  0.127399
2579073 -2.122680e+06 -1.007211e+06 -64.615676  68.835190  18262.0  0.137399

         track date_string satellite  lead_mask  dist_along_track  \
2579069   1245  2020-01-01       cs2        1.0          0.000000
2579070   1245  2020-01-01       cs2        1.0        300.143858
2579071   1245  2020-01-01       cs2        1.0        600.397303
2579072   1245  2020-01-01       cs2        1.0        900.540100
2579073   1245  2020-01-01       cs2        1.0       1200.682344

         z_track_avg     f_lin
2579069     0.062252  0.119134
2579070     0.062252  0.119134
2579071     0.062252  0.119134
2579072     0.062252  0.119179
2579073     0.062252  0.119406
gpsat:
                    x             y        lon        lat        t         z  \
2579069 -2.123680e+06 -1.007852e+06 -64.612012  68.824449  18262.0  0.063925
2579070 -2.123430e+06 -1.007692e+06 -64.612928  68.827134  18262.0  0.065377
2579071 -2.123180e+06 -1.007531e+06 -64.613844  68.829820  18262.0  0.096861
2579072 -2.122930e+06 -1.007371e+06 -64.614760  68.832505  18262.0  0.127399
2579073 -2.122680e+06 -1.007211e+06 -64.615676  68.835190  18262.0  0.137399

         track date_string satellite  lead_mask  dist_along_track  \
2579069   1245  2020-01-01       cs2        1.0          0.000000
2579070   1245  2020-01-01       cs2        1.0        300.143858
2579071   1245  2020-01-01       cs2        1.0        600.397303
2579072   1245  2020-01-01       cs2        1.0        900.540100
2579073   1245  2020-01-01       cs2        1.0       1200.682344

         z_track_avg   f_gpsat  f_var_gpsat
2579069     0.062252  0.121168     0.000132
2579070     0.062252  0.121271     0.000129
2579071     0.062252  0.121373     0.000126
2579072     0.062252  0.121473     0.000123
2579073     0.062252  0.121570     0.000120
Test NaNs — Linear: 0, GPSat: 0
Track interpolated!
Interpolating track 1246, 4 of 15...
'data_select': 0.000 seconds
'load': 0.000 seconds
---------
storing expert locations in 'expert_locs' table
exception occurred: 'No object named expert_locs in the file'
will now close object

---------
dropping expert locations that already exists in 'run_details' table
exception occurred: 'No object named run_details in the file'
will now close object

--------------------------------------------------
1 / 14
current local expert:
                    x              y        lon        lat        t         z  \
2580699 -1.312988e+06 -502597.333096 -69.053699  77.385482  18262.0 -0.408308

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2580699   1246  2020-01-01       cs2        1.0               0.0     -0.35395
'data_select': 0.000 seconds
'load': 0.000 seconds
'local_data_select': 0.001 seconds
number obs: 14
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.047 seconds
'get_parameters': 0.003 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

/tmp/ipykernel_1171781/839927469.py:200: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  track_df['f_gpsat'] = ssha
/tmp/ipykernel_1171781/839927469.py:201: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  track_df['f_var_gpsat'] = ssha_var
2026-05-18 19:15:21.872732: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:15:21.874147: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.250 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.00975905, 10.00991038,  1.05438032])
kernel_variance: 2.022353041710255
likelihood_variance: 0.0010001287525752364
'predict': 0.030 seconds
total run time : 0.78 seconds
--------------------------------------------------
2 / 14
current local expert:
                    x              y        lon        lat        t        z  \
2580700 -1.312730e+06 -502441.537112 -69.055883  77.388148  18262.0 -0.41912

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2580700   1246  2020-01-01       cs2        1.0        300.478109     -0.35395
'local_data_select': 0.001 seconds
number obs: 14
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.049 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:15:22.653806: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:15:22.655202: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.249 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.00975905, 10.00991038,  1.05438032])
kernel_variance: 2.022353041710255
likelihood_variance: 0.0010001287525752364
'predict': 0.029 seconds
total run time : 0.78 seconds
--------------------------------------------------
3 / 14
current local expert:
                    x              y        lon        lat        t        z  \
2580701 -1.312473e+06 -502285.675693 -69.058069  77.390815  18262.0 -0.40147

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2580701   1246  2020-01-01       cs2        1.0        601.072011     -0.35395
'local_data_select': 0.001 seconds
number obs: 14
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:15:23.431797: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:15:23.433211: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.244 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.00975905, 10.00991038,  1.05438032])
kernel_variance: 2.022353041710255
likelihood_variance: 0.0010001287525752364
'predict': 0.030 seconds
total run time : 0.78 seconds
--------------------------------------------------
4 / 14
current local expert:
                    x              y        lon        lat        t         z  \
2580702 -1.311959e+06 -501974.069464 -69.062442  77.396147  18262.0 -0.422196

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2580702   1246  2020-01-01       cs2        1.0       1202.039838     -0.35395
'local_data_select': 0.001 seconds
number obs: 14
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.046 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:15:24.213064: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:15:24.214527: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.248 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.00975905, 10.00991038,  1.05438032])
kernel_variance: 2.022353041710255
likelihood_variance: 0.0010001287525752364
'predict': 0.032 seconds
total run time : 0.78 seconds
--------------------------------------------------
5 / 14
current local expert:
                    x              y       lon        lat        t         z  \
2580703 -1.311702e+06 -501818.262105 -69.06463  77.398813  18262.0 -0.460252

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2580703   1246  2020-01-01       cs2        1.0       1502.527248     -0.35395
'local_data_select': 0.001 seconds
number obs: 14
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.051 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:15:24.998255: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:15:24.999651: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.244 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.00975905, 10.00991038,  1.05438032])
kernel_variance: 2.022353041710255
likelihood_variance: 0.0010001287525752364
'predict': 0.030 seconds
total run time : 0.78 seconds
--------------------------------------------------
6 / 14
current local expert:
                    x              y        lon        lat        t         z  \
2580704 -1.311445e+06 -501662.451936 -69.066819  77.401479  18262.0 -0.396371

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2580704   1246  2020-01-01       cs2        1.0       1803.016973     -0.35395
'local_data_select': 0.001 seconds
number obs: 14
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:15:25.780224: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:15:25.781630: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.240 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.00975905, 10.00991038,  1.05438032])
kernel_variance: 2.022353041710255
likelihood_variance: 0.0010001287525752364
'predict': 0.030 seconds
total run time : 0.79 seconds
--------------------------------------------------
7 / 14
current local expert:
                    x              y       lon        lat        t         z  \
2580707 -1.310673e+06 -501195.010824 -69.07339  77.409478  18262.0 -0.340774

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2580707   1246  2020-01-01       cs2        1.0       2704.600759     -0.35395
'local_data_select': 0.001 seconds
number obs: 14
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.046 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:15:26.565148: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:15:26.566541: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.250 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.00975905, 10.00991038,  1.05438032])
kernel_variance: 2.022353041710255
likelihood_variance: 0.0010001287525752364
'predict': 0.030 seconds
total run time : 0.79 seconds
--------------------------------------------------
8 / 14
current local expert:
                    x              y        lon        lat        t         z  \
2580708 -1.310416e+06 -501039.212421 -69.075582  77.412144  18262.0 -0.304098

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2580708   1246  2020-01-01       cs2        1.0         3005.0955     -0.35395
'local_data_select': 0.001 seconds
number obs: 14
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.050 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:15:27.364852: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:15:27.366247: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.243 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.00975905, 10.00991038,  1.05438032])
kernel_variance: 2.022353041710255
likelihood_variance: 0.0010001287525752364
'predict': 0.030 seconds
total run time : 0.79 seconds
--------------------------------------------------
9 / 14
current local expert:
                    x              y        lon        lat        t         z  \
2580709 -1.310159e+06 -500883.371642 -69.077775  77.414811  18262.0 -0.381204

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2580709   1246  2020-01-01       cs2        1.0       3305.701774     -0.35395
'local_data_select': 0.001 seconds
number obs: 14
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.053 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:15:28.162651: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:15:28.164064: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.246 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.00975905, 10.00991038,  1.05438032])
kernel_variance: 2.022353041710255
likelihood_variance: 0.0010001287525752364
'predict': 0.033 seconds
total run time : 0.79 seconds
--------------------------------------------------
10 / 14
current local expert:
                    x              y        lon        lat        t         z  \
2580710 -1.309902e+06 -500727.567759 -69.079969  77.417477  18262.0 -0.342026

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2580710   1246  2020-01-01       cs2        1.0       3606.201143     -0.35395
'local_data_select': 0.001 seconds
number obs: 14
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:15:28.953459: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:15:28.954876: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.246 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.00975905, 10.00991038,  1.05438032])
kernel_variance: 2.022353041710255
likelihood_variance: 0.0010001287525752364
'predict': 0.030 seconds
SAVING RESULTS TO TABLES:
run_details
preds
lengthscales
kernel_variance
likelihood_variance
total run time : 0.91 seconds
--------------------------------------------------
11 / 14
current local expert:
                    x              y        lon        lat        t         z  \
2580711 -1.309644e+06 -500571.784013 -69.082163  77.420143  18262.0 -0.253428

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2580711   1246  2020-01-01       cs2        1.0       3906.698571     -0.35395
'local_data_select': 0.001 seconds
number obs: 14
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.046 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:15:29.862103: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:15:29.863507: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.248 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.00975905, 10.00991038,  1.05438032])
kernel_variance: 2.022353041710255
likelihood_variance: 0.0010001287525752364
'predict': 0.030 seconds
total run time : 0.79 seconds
--------------------------------------------------
12 / 14
current local expert:
                    x              y        lon        lat        t         z  \
2580712 -1.309130e+06 -500260.185542 -69.086555  77.425475  18262.0 -0.252576

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2580712   1246  2020-01-01       cs2        1.0       4507.704618     -0.35395
'local_data_select': 0.001 seconds
number obs: 14
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:15:30.653442: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:15:30.654839: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.248 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.00975905, 10.00991038,  1.05438032])
kernel_variance: 2.022353041710255
likelihood_variance: 0.0010001287525752364
'predict': 0.033 seconds
total run time : 0.79 seconds
--------------------------------------------------
13 / 14
current local expert:
                    x              y        lon        lat        t         z  \
2580713 -1.308873e+06 -500104.393698 -69.088752  77.428141  18262.0 -0.331365

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2580713   1246  2020-01-01       cs2        1.0       4808.208974     -0.35395
'local_data_select': 0.001 seconds
number obs: 14
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.047 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:15:31.448862: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:15:31.450278: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.245 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.00975905, 10.00991038,  1.05438032])
kernel_variance: 2.022353041710255
likelihood_variance: 0.0010001287525752364
'predict': 0.030 seconds
total run time : 0.79 seconds
--------------------------------------------------
14 / 14
current local expert:
                    x              y        lon        lat        t         z  \
2580715 -1.308359e+06 -499792.802005 -69.093149  77.433473  18262.0 -0.239624

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2580715   1246  2020-01-01       cs2        1.0       5409.224612     -0.35395
'local_data_select': 0.001 seconds
number obs: 14
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.049 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:15:32.245296: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:15:32.246709: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.242 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.00975905, 10.00991038,  1.05438032])
kernel_variance: 2.022353041710255
likelihood_variance: 0.0010001287525752364
'predict': 0.030 seconds
total run time : 0.79 seconds
storing any remaining tables
SAVING RESULTS TO TABLES:
run_details
preds
lengthscales
kernel_variance
likelihood_variance
'run': 11.341 seconds
reading in results
getting all tables
merging on expert location data
table: 'oi_config' does not have all coords_col: ['x', 'y', 't'] in columns, not merging on expert_locations
h5 tables: ['expert_locs', 'kernel_variance', 'lengthscales', 'likelihood_variance', 'oi_config', 'preds', 'run_details']
found model_name: GPflowGPRModel
found GPU
setting lengthscales to: [1.]
'__init__': 0.047 seconds
reading in results
selecting only tables: ['lengthscales', 'kernel_variance', 'likelihood_variance']
'data_select': 0.000 seconds
'load': 0.001 seconds
expert_locations data will not be merged on results data
adding smoothed table: lengthscales_SMOOTHED
adding smoothed table: kernel_variance_SMOOTHED
adding smoothed table: likelihood_variance_SMOOTHED
writing (smoothed) hyper parameters to:
/home/mhen/geol0069_data/gpsat/jan20/1246.h5
table_suffix:_SMOOTHED
writing: lengthscales_SMOOTHED to table
writing: kernel_variance_SMOOTHED to table
writing: likelihood_variance_SMOOTHED to table
'data_select': 0.000 seconds
'load': 0.000 seconds

2026-05-18 19:15:33.256852: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:15:33.258275: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

---------
storing expert locations in 'expert_locs' table
exception occurred: 'No object named expert_locs_SMOOTHED in the file'
will now close object

---------
dropping expert locations that already exists in 'run_details' table
exception occurred: 'No object named run_details_SMOOTHED in the file'
will now close object

--------------------------------------------------
1 / 14
current local expert:
                    x              y        lon        lat        t         z  \
2580699 -1.312988e+06 -502597.333096 -69.053699  77.385482  18262.0 -0.408308

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2580699   1246  2020-01-01       cs2        1.0               0.0     -0.35395
'data_select': 0.000 seconds
'load': 0.000 seconds
'local_data_select': 0.001 seconds
number obs: 14
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.050 seconds
'get_parameters': 0.003 seconds
'_read_params_from_file': 0.059 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds

2026-05-18 19:15:33.509815: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:15:33.513667: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  1.05438032])
kernel_variance: 0.10000000000000002
likelihood_variance: 0.01100000000000001
'predict': 0.030 seconds
total run time : 0.63 seconds
--------------------------------------------------
2 / 14
current local expert:
                    x              y        lon        lat        t        z  \
2580700 -1.312730e+06 -502441.537112 -69.055883  77.388148  18262.0 -0.41912

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2580700   1246  2020-01-01       cs2        1.0        300.478109     -0.35395
'local_data_select': 0.001 seconds
number obs: 14
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.049 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  1.05438032])
kernel_variance: 0.10000000000000002
likelihood_variance: 0.01100000000000001
'predict': 0.030 seconds

2026-05-18 19:15:34.144541: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:15:34.145945: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.60 seconds
--------------------------------------------------
3 / 14
current local expert:
                    x              y        lon        lat        t        z  \
2580701 -1.312473e+06 -502285.675693 -69.058069  77.390815  18262.0 -0.40147

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2580701   1246  2020-01-01       cs2        1.0        601.072011     -0.35395
'local_data_select': 0.001 seconds
number obs: 14
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.049 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  1.05438032])
kernel_variance: 0.09999999999999998
likelihood_variance: 0.01100000000000001
'predict': 0.030 seconds

2026-05-18 19:15:34.745884: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:15:34.747286: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.60 seconds
--------------------------------------------------
4 / 14
current local expert:
                    x              y        lon        lat        t         z  \
2580702 -1.311959e+06 -501974.069464 -69.062442  77.396147  18262.0 -0.422196

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2580702   1246  2020-01-01       cs2        1.0       1202.039838     -0.35395
'local_data_select': 0.001 seconds
number obs: 14
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.049 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  1.05438032])
kernel_variance: 0.09999999999999998
likelihood_variance: 0.01100000000000001
'predict': 0.030 seconds

2026-05-18 19:15:35.345128: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:15:35.346539: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.60 seconds
--------------------------------------------------
5 / 14
current local expert:
                    x              y       lon        lat        t         z  \
2580703 -1.311702e+06 -501818.262105 -69.06463  77.398813  18262.0 -0.460252

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2580703   1246  2020-01-01       cs2        1.0       1502.527248     -0.35395
'local_data_select': 0.001 seconds
number obs: 14
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.047 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  1.05438032])
kernel_variance: 0.10000000000000002
likelihood_variance: 0.01100000000000001
'predict': 0.030 seconds

2026-05-18 19:15:35.944619: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:15:35.946044: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.61 seconds
--------------------------------------------------
6 / 14
current local expert:
                    x              y        lon        lat        t         z  \
2580704 -1.311445e+06 -501662.451936 -69.066819  77.401479  18262.0 -0.396371

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2580704   1246  2020-01-01       cs2        1.0       1803.016973     -0.35395
'local_data_select': 0.001 seconds
number obs: 14
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  1.05438032])
kernel_variance: 0.10000000000000002
likelihood_variance: 0.01100000000000001
'predict': 0.030 seconds

2026-05-18 19:15:36.555150: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:15:36.556556: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.60 seconds
--------------------------------------------------
7 / 14
current local expert:
                    x              y       lon        lat        t         z  \
2580707 -1.310673e+06 -501195.010824 -69.07339  77.409478  18262.0 -0.340774

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2580707   1246  2020-01-01       cs2        1.0       2704.600759     -0.35395
'local_data_select': 0.001 seconds
number obs: 14
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.047 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  1.05438032])
kernel_variance: 0.09999999999999998
likelihood_variance: 0.01100000000000001
'predict': 0.030 seconds

2026-05-18 19:15:37.152866: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:15:37.154311: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.61 seconds
--------------------------------------------------
8 / 14
current local expert:
                    x              y        lon        lat        t         z  \
2580708 -1.310416e+06 -501039.212421 -69.075582  77.412144  18262.0 -0.304098

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2580708   1246  2020-01-01       cs2        1.0         3005.0955     -0.35395
'local_data_select': 0.001 seconds
number obs: 14
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.046 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  1.05438032])
kernel_variance: 0.09999999999999998
likelihood_variance: 0.01100000000000001
'predict': 0.030 seconds

2026-05-18 19:15:37.762918: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:15:37.764339: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.59 seconds
--------------------------------------------------
9 / 14
current local expert:
                    x              y        lon        lat        t         z  \
2580709 -1.310159e+06 -500883.371642 -69.077775  77.414811  18262.0 -0.381204

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2580709   1246  2020-01-01       cs2        1.0       3305.701774     -0.35395
'local_data_select': 0.001 seconds
number obs: 14
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.049 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  1.05438032])
kernel_variance: 0.10000000000000002
likelihood_variance: 0.01100000000000001
'predict': 0.030 seconds

2026-05-18 19:15:38.361983: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:15:38.363411: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.60 seconds
--------------------------------------------------
10 / 14
current local expert:
                    x              y        lon        lat        t         z  \
2580710 -1.309902e+06 -500727.567759 -69.079969  77.417477  18262.0 -0.342026

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2580710   1246  2020-01-01       cs2        1.0       3606.201143     -0.35395
'local_data_select': 0.001 seconds
number obs: 14
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.056 seconds
'_read_params_from_file': 0.045 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  1.05438032])
kernel_variance: 0.10000000000000002
likelihood_variance: 0.01100000000000001
'predict': 0.030 seconds

2026-05-18 19:15:38.969435: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:15:38.971418: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

SAVING RESULTS TO TABLES:
run_details
preds
total run time : 0.67 seconds
--------------------------------------------------
11 / 14
current local expert:
                    x              y        lon        lat        t         z  \
2580711 -1.309644e+06 -500571.784013 -69.082163  77.420143  18262.0 -0.253428

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2580711   1246  2020-01-01       cs2        1.0       3906.698571     -0.35395
'local_data_select': 0.001 seconds
number obs: 14
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'_read_params_from_file': 0.050 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  1.05438032])
kernel_variance: 0.09999999999999998
likelihood_variance: 0.01100000000000001

2026-05-18 19:15:39.633143: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:15:39.634541: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'predict': 0.031 seconds
total run time : 0.61 seconds
--------------------------------------------------
12 / 14
current local expert:
                    x              y        lon        lat        t         z  \
2580712 -1.309130e+06 -500260.185542 -69.086555  77.425475  18262.0 -0.252576

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2580712   1246  2020-01-01       cs2        1.0       4507.704618     -0.35395
'local_data_select': 0.001 seconds
number obs: 14
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.047 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  1.05438032])
kernel_variance: 0.09999999999999998
likelihood_variance: 0.01100000000000001
'predict': 0.030 seconds

2026-05-18 19:15:40.243814: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:15:40.245276: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.61 seconds
--------------------------------------------------
13 / 14
current local expert:
                    x              y        lon        lat        t         z  \
2580713 -1.308873e+06 -500104.393698 -69.088752  77.428141  18262.0 -0.331365

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2580713   1246  2020-01-01       cs2        1.0       4808.208974     -0.35395
'local_data_select': 0.001 seconds
number obs: 14
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.047 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  1.05438032])
kernel_variance: 0.10000000000000002
likelihood_variance: 0.01100000000000001
'predict': 0.030 seconds

2026-05-18 19:15:40.854903: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:15:40.856310: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.60 seconds
--------------------------------------------------
14 / 14
current local expert:
                    x              y        lon        lat        t         z  \
2580715 -1.308359e+06 -499792.802005 -69.093149  77.433473  18262.0 -0.239624

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2580715   1246  2020-01-01       cs2        1.0       5409.224612     -0.35395
'local_data_select': 0.001 seconds
number obs: 14
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.046 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  1.05438032])
kernel_variance: 0.10000000000000002
likelihood_variance: 0.01100000000000001
'predict': 0.030 seconds

2026-05-18 19:15:41.454406: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:15:41.455888: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.60 seconds
storing any remaining tables
SAVING RESULTS TO TABLES:
run_details
preds
'run': 8.677 seconds
reading in results
getting all tables
merging on expert location data
table: 'oi_config' does not have all coords_col: ['x', 'y', 't'] in columns, not merging on expert_locations
table: 'oi_config_SMOOTHED' does not have all coords_col: ['x', 'y', 't'] in columns, not merging on expert_locations
lin:
                    x              y        lon        lat        t         z  \
2580699 -1.312988e+06 -502597.333096 -69.053699  77.385482  18262.0 -0.408308
2580700 -1.312730e+06 -502441.537112 -69.055883  77.388148  18262.0 -0.419120
2580701 -1.312473e+06 -502285.675693 -69.058069  77.390815  18262.0 -0.401470
2580702 -1.311959e+06 -501974.069464 -69.062442  77.396147  18262.0 -0.422196
2580703 -1.311702e+06 -501818.262105 -69.064630  77.398813  18262.0 -0.460252

         track date_string satellite  lead_mask  dist_along_track  \
2580699   1246  2020-01-01       cs2        1.0          0.000000
2580700   1246  2020-01-01       cs2        1.0        300.478109
2580701   1246  2020-01-01       cs2        1.0        601.072011
2580702   1246  2020-01-01       cs2        1.0       1202.039838
2580703   1246  2020-01-01       cs2        1.0       1502.527248

         z_track_avg     f_lin
2580699     -0.35395 -0.353772
2580700     -0.35395 -0.353772
2580701     -0.35395 -0.353772
2580702     -0.35395 -0.353772
2580703     -0.35395 -0.353772
gpsat:
                    x              y        lon        lat        t         z  \
2580699 -1.312988e+06 -502597.333096 -69.053699  77.385482  18262.0 -0.408308
2580700 -1.312730e+06 -502441.537112 -69.055883  77.388148  18262.0 -0.419120
2580701 -1.312473e+06 -502285.675693 -69.058069  77.390815  18262.0 -0.401470
2580702 -1.311959e+06 -501974.069464 -69.062442  77.396147  18262.0 -0.422196
2580703 -1.311702e+06 -501818.262105 -69.064630  77.398813  18262.0 -0.460252

         track date_string satellite  lead_mask  dist_along_track  \
2580699   1246  2020-01-01       cs2        1.0          0.000000
2580700   1246  2020-01-01       cs2        1.0        300.478109
2580701   1246  2020-01-01       cs2        1.0        601.072011
2580702   1246  2020-01-01       cs2        1.0       1202.039838
2580703   1246  2020-01-01       cs2        1.0       1502.527248

         z_track_avg   f_gpsat  f_var_gpsat
2580699     -0.35395 -0.435256     0.000267
2580700     -0.35395 -0.426985     0.000215
2580701     -0.35395 -0.418539     0.000175
2580702     -0.35395 -0.401226     0.000126
2580703     -0.35395 -0.392111     0.000112
Test NaNs — Linear: 0, GPSat: 0
Track interpolated!
Interpolating track 1247, 5 of 15...
'data_select': 0.000 seconds
'load': 0.000 seconds
in json_serializable - key: 'df' has value DataFrame/Series, but is too long: 184 >  100
storing as str
---------
storing expert locations in 'expert_locs' table
exception occurred: 'No object named expert_locs in the file'
will now close object

---------
dropping expert locations that already exists in 'run_details' table
exception occurred: 'No object named run_details in the file'
will now close object

--------------------------------------------------
1 / 4
current local expert:
                    x              y        lon        lat        t         z  \
2580719 -1.168276e+06 -415344.178273 -70.428744  78.880192  18262.0 -0.219199

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2580719   1247  2020-01-01       cs2        1.0       1502.718205    -0.185519
'data_select': 0.000 seconds
'load': 0.000 seconds
'local_data_select': 0.001 seconds
number obs: 20
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'get_parameters': 0.003 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

/tmp/ipykernel_1171781/839927469.py:200: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  track_df['f_gpsat'] = ssha
/tmp/ipykernel_1171781/839927469.py:201: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  track_df['f_var_gpsat'] = ssha_var
/home/mhen/miniconda3/envs/geol0069_gpsat/lib/python3.11/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/home/mhen/miniconda3/envs/geol0069_gpsat/lib/python3.11/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
2026-05-18 19:15:42.388535: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:15:42.389948: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.290 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([20.        , 19.99837908,  0.94299441])
kernel_variance: 0.018725229411397825
likelihood_variance: 0.003505421534476339
'predict': 0.030 seconds
total run time : 0.85 seconds
--------------------------------------------------
2 / 4
current local expert:
                    x              y       lon        lat        t        z  \
2580761 -1.146576e+06 -402334.990306 -70.66397  79.103281  18262.0 -0.18058

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2580761   1247  2020-01-01       cs2        1.0      26750.241614    -0.185519
'local_data_select': 0.001 seconds
number obs: 20
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:15:43.236626: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:15:43.238051: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.280 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([20.        , 19.99837908,  0.94299441])
kernel_variance: 0.018725229411397825
likelihood_variance: 0.003505421534476339
'predict': 0.031 seconds
total run time : 0.83 seconds
--------------------------------------------------
3 / 4
current local expert:
                    x              y        lon        lat        t        z  \
2580784 -1.133395e+06 -394442.125281 -70.811173  79.238652  18262.0 -0.09909

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2580784   1247  2020-01-01       cs2        1.0      42079.365387    -0.185519
'local_data_select': 0.001 seconds
number obs: 20
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:15:44.067624: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:15:44.069630: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.289 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([20.        , 19.99837908,  0.94299441])
kernel_variance: 0.018725229411397825
likelihood_variance: 0.003505421534476339
'predict': 0.033 seconds
total run time : 0.84 seconds
--------------------------------------------------
4 / 4
current local expert:
                    x              y        lon        lat        t         z  \
2580849 -1.105724e+06 -377896.257392 -71.131439  79.522468  18262.0 -0.087094

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2580849   1247  2020-01-01       cs2        1.0      74241.205037    -0.185519
'local_data_select': 0.001 seconds
number obs: 20
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.047 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:15:44.910065: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:15:44.911462: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.290 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([20.        , 19.99837908,  0.94299441])
kernel_variance: 0.018725229411397825
likelihood_variance: 0.003505421534476339
'predict': 0.031 seconds
total run time : 0.84 seconds
storing any remaining tables
SAVING RESULTS TO TABLES:
run_details
preds
lengthscales
kernel_variance
likelihood_variance
'run': 3.550 seconds
reading in results
getting all tables
merging on expert location data
table: 'oi_config' does not have all coords_col: ['x', 'y', 't'] in columns, not merging on expert_locations
h5 tables: ['expert_locs', 'kernel_variance', 'lengthscales', 'likelihood_variance', 'oi_config', 'preds', 'run_details']
found model_name: GPflowGPRModel
found GPU
setting lengthscales to: [1.]
'__init__': 0.046 seconds
reading in results
selecting only tables: ['lengthscales', 'kernel_variance', 'likelihood_variance']
'data_select': 0.000 seconds
'load': 0.001 seconds
expert_locations data will not be merged on results data
adding smoothed table: lengthscales_SMOOTHED
adding smoothed table: kernel_variance_SMOOTHED
adding smoothed table: likelihood_variance_SMOOTHED
writing (smoothed) hyper parameters to:
/home/mhen/geol0069_data/gpsat/jan20/1247.h5
table_suffix:_SMOOTHED
writing: lengthscales_SMOOTHED to table
writing: kernel_variance_SMOOTHED to table
writing: likelihood_variance_SMOOTHED to table
'data_select': 0.000 seconds
'load': 0.000 seconds
in json_serializable - key: 'df' has value DataFrame/Series, but is too long: 184 >  100
storing as str
---------
storing expert locations in 'expert_locs' table
exception occurred: 'No object named expert_locs_SMOOTHED in the file'
will now close object

2026-05-18 19:15:45.984216: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:15:45.985687: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

---------
dropping expert locations that already exists in 'run_details' table
exception occurred: 'No object named run_details_SMOOTHED in the file'
will now close object

--------------------------------------------------
1 / 4
current local expert:
                    x              y        lon        lat        t         z  \
2580719 -1.168276e+06 -415344.178273 -70.428744  78.880192  18262.0 -0.219199

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2580719   1247  2020-01-01       cs2        1.0       1502.718205    -0.185519
'data_select': 0.000 seconds
'load': 0.000 seconds
'local_data_select': 0.001 seconds
number obs: 20
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.049 seconds
'get_parameters': 0.003 seconds
'_read_params_from_file': 0.049 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([12.        , 12.        ,  0.94299441])
kernel_variance: 0.018725229411397825
likelihood_variance: 0.01100000000000001
'predict': 0.030 seconds

2026-05-18 19:15:46.226056: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:15:46.227460: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.61 seconds
--------------------------------------------------
2 / 4
current local expert:
                    x              y       lon        lat        t        z  \
2580761 -1.146576e+06 -402334.990306 -70.66397  79.103281  18262.0 -0.18058

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2580761   1247  2020-01-01       cs2        1.0      26750.241614    -0.185519
'local_data_select': 0.001 seconds
number obs: 20
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.047 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([12.        , 12.        ,  0.94299441])
kernel_variance: 0.018725229411397825
likelihood_variance: 0.01100000000000001
'predict': 0.030 seconds

2026-05-18 19:15:46.836049: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:15:46.837492: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.60 seconds
--------------------------------------------------
3 / 4
current local expert:
                    x              y        lon        lat        t        z  \
2580784 -1.133395e+06 -394442.125281 -70.811173  79.238652  18262.0 -0.09909

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2580784   1247  2020-01-01       cs2        1.0      42079.365387    -0.185519
'local_data_select': 0.001 seconds
number obs: 20
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.047 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([12.        , 12.        ,  0.94299441])
kernel_variance: 0.018725229411397825
likelihood_variance: 0.01100000000000001
'predict': 0.030 seconds

2026-05-18 19:15:47.439889: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:15:47.441302: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.60 seconds
--------------------------------------------------
4 / 4
current local expert:
                    x              y        lon        lat        t         z  \
2580849 -1.105724e+06 -377896.257392 -71.131439  79.522468  18262.0 -0.087094

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2580849   1247  2020-01-01       cs2        1.0      74241.205037    -0.185519
'local_data_select': 0.001 seconds
number obs: 20
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.046 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([12.        , 12.        ,  0.94299441])
kernel_variance: 0.018725229411397825
likelihood_variance: 0.01100000000000001
'predict': 0.030 seconds

2026-05-18 19:15:48.040070: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:15:48.041488: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.60 seconds
storing any remaining tables
SAVING RESULTS TO TABLES:
run_details
preds
'run': 2.561 seconds
reading in results
getting all tables
merging on expert location data
table: 'oi_config' does not have all coords_col: ['x', 'y', 't'] in columns, not merging on expert_locations
table: 'oi_config_SMOOTHED' does not have all coords_col: ['x', 'y', 't'] in columns, not merging on expert_locations
lin:
                    x              y        lon        lat        t         z  \
2580716 -1.169567e+06 -416118.855059 -70.415017  78.866909  18262.0       NaN
2580717 -1.169309e+06 -415963.940109 -70.417760  78.869565  18262.0       NaN
2580718 -1.169051e+06 -415808.992947 -70.420504  78.872222  18262.0       NaN
2580719 -1.168276e+06 -415344.178273 -70.428744  78.880192  18262.0 -0.219199
2580720 -1.167243e+06 -414724.416507 -70.439748  78.890819  18262.0       NaN

         track date_string satellite  lead_mask  dist_along_track  \
2580716   1247  2020-01-01       cs2        0.0          0.000000
2580717   1247  2020-01-01       cs2        0.0        300.473720
2580718   1247  2020-01-01       cs2        0.0        601.057741
2580719   1247  2020-01-01       cs2        1.0       1502.718205
2580720   1247  2020-01-01       cs2        0.0       2705.002978

         z_track_avg     f_lin
2580716    -0.185519 -0.153812
2580717    -0.185519 -0.153812
2580718    -0.185519 -0.153812
2580719    -0.185519 -0.153812
2580720    -0.185519 -0.153812
gpsat:
                    x              y        lon        lat        t         z  \
2580716 -1.169567e+06 -416118.855059 -70.415017  78.866909  18262.0       NaN
2580717 -1.169309e+06 -415963.940109 -70.417760  78.869565  18262.0       NaN
2580718 -1.169051e+06 -415808.992947 -70.420504  78.872222  18262.0       NaN
2580719 -1.168276e+06 -415344.178273 -70.428744  78.880192  18262.0 -0.219199
2580720 -1.167243e+06 -414724.416507 -70.439748  78.890819  18262.0       NaN

         track date_string satellite  lead_mask  dist_along_track  \
2580716   1247  2020-01-01       cs2        0.0          0.000000
2580717   1247  2020-01-01       cs2        0.0        300.473720
2580718   1247  2020-01-01       cs2        0.0        601.057741
2580719   1247  2020-01-01       cs2        1.0       1502.718205
2580720   1247  2020-01-01       cs2        0.0       2705.002978

         z_track_avg   f_gpsat  f_var_gpsat
2580716    -0.185519 -0.153341     0.000974
2580717    -0.185519 -0.153376     0.000963
2580718    -0.185519 -0.153411     0.000952
2580719    -0.185519 -0.153510     0.000920
2580720    -0.185519 -0.153630     0.000880
Test NaNs — Linear: 0, GPSat: 0
Track interpolated!
Interpolating track 1248, 6 of 15...
'data_select': 0.000 seconds
'load': 0.000 seconds
---------
storing expert locations in 'expert_locs' table
exception occurred: 'No object named expert_locs in the file'
will now close object

---------
dropping expert locations that already exists in 'run_details' table
exception occurred: 'No object named run_details in the file'
will now close object

--------------------------------------------------
1 / 15
current local expert:
                     x              y        lon        lat        t        z  \
2580904 -752586.974584 -169474.112523 -77.309324  83.088809  18262.0 -0.07177

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2580904   1248  2020-01-01       cs2        1.0       2104.432631    -0.109466
'data_select': 0.000 seconds
'load': 0.000 seconds
'local_data_select': 0.001 seconds
number obs: 29
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'get_parameters': 0.003 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

/tmp/ipykernel_1171781/839927469.py:200: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  track_df['f_gpsat'] = ssha
/tmp/ipykernel_1171781/839927469.py:201: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  track_df['f_var_gpsat'] = ssha_var
2026-05-18 19:15:48.997154: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:15:48.998586: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'optimise_parameters': 0.264 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.00987461, 10.00995722,  0.99966317])
kernel_variance: 0.04591779073220711
likelihood_variance: 0.022013140981606106
'predict': 0.030 seconds
total run time : 0.83 seconds
--------------------------------------------------
2 / 15
current local expert:
                     x              y        lon        lat        t  \
2580939 -732479.467427 -157757.909775 -77.845574  83.287564  18262.0

                z  track date_string satellite  lead_mask  dist_along_track  \
2580939  0.067827   1248  2020-01-01       cs2        1.0      25256.904075

         z_track_avg
2580939    -0.109466
'local_data_select': 0.001 seconds
number obs: 29
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.049 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.011 seconds

2026-05-18 19:15:49.825244: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:15:49.826661: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'optimise_parameters': 0.264 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.00987461, 10.00995722,  0.99966317])
kernel_variance: 0.04591779073220711
likelihood_variance: 0.022013140981606106
'predict': 0.030 seconds
total run time : 0.82 seconds
--------------------------------------------------
3 / 15
current local expert:
                     x              y        lon        lat        t  \
2580905 -752325.979061 -169321.912428 -77.316096  83.091393  18262.0

                z  track date_string satellite  lead_mask  dist_along_track  \
2580905 -0.097971   1248  2020-01-01       cs2        1.0       2405.030203

         z_track_avg
2580905    -0.109466
'local_data_select': 0.001 seconds
number obs: 29
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.046 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:15:50.645245: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:15:50.646664: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'optimise_parameters': 0.260 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.00987461, 10.00995722,  0.99966317])
kernel_variance: 0.04591779073220711
likelihood_variance: 0.022013140981606106
'predict': 0.030 seconds
total run time : 0.81 seconds
--------------------------------------------------
4 / 15
current local expert:
                     x              y        lon       lat        t         z  \
2580911 -749453.971198 -167647.505603 -77.390921  83.11982  18262.0 -0.189269

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2580911   1248  2020-01-01       cs2        1.0       5712.586698    -0.109466
'local_data_select': 0.001 seconds
number obs: 29
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.047 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:15:51.461931: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:15:51.463331: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'optimise_parameters': 0.263 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.00987461, 10.00995722,  0.99966317])
kernel_variance: 0.04591779073220711
likelihood_variance: 0.022013140981606106
'predict': 0.030 seconds
total run time : 0.82 seconds
--------------------------------------------------
5 / 15
current local expert:
                     x              y        lon        lat        t  \
2580914 -748148.420387 -166886.471156 -77.425131  83.132738  18262.0

                z  track date_string satellite  lead_mask  dist_along_track  \
2580914 -0.295851   1248  2020-01-01       cs2        1.0       7216.053894

         z_track_avg
2580914    -0.109466
'local_data_select': 0.001 seconds
number obs: 29
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.047 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:15:52.284804: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:15:52.286221: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'optimise_parameters': 0.262 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.00987461, 10.00995722,  0.99966317])
kernel_variance: 0.04591779073220711
likelihood_variance: 0.022013140981606106
'predict': 0.030 seconds
total run time : 0.83 seconds
--------------------------------------------------
6 / 15
current local expert:
                     x              y        lon        lat        t  \
2580916 -747626.247017 -166582.095446 -77.438849  83.137904  18262.0

                z  track date_string satellite  lead_mask  dist_along_track  \
2580916 -0.277643   1248  2020-01-01       cs2        1.0       7817.378285

         z_track_avg
2580916    -0.109466
'local_data_select': 0.001 seconds
number obs: 29
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:15:53.120661: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:15:53.122057: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'optimise_parameters': 0.262 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.00987461, 10.00995722,  0.99966317])
kernel_variance: 0.04591779073220711
likelihood_variance: 0.022013140981606106
'predict': 0.030 seconds
total run time : 0.83 seconds
--------------------------------------------------
7 / 15
current local expert:
                     x             y        lon        lat        t         z  \
2580921 -745276.225668 -165212.42095 -77.500831  83.161148  18262.0 -0.151735

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2580921   1248  2020-01-01       cs2        1.0       10523.51579    -0.109466
'local_data_select': 0.001 seconds
number obs: 29
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.046 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:15:53.952870: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:15:53.954274: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'optimise_parameters': 0.265 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.00987461, 10.00995722,  0.99966317])
kernel_variance: 0.04591779073220711
likelihood_variance: 0.022013140981606106
'predict': 0.030 seconds
total run time : 0.83 seconds
--------------------------------------------------
8 / 15
current local expert:
                     x              y        lon        lat        t  \
2580931 -737441.911939 -160647.909514 -77.710416  83.238573  18262.0

                z  track date_string satellite  lead_mask  dist_along_track  \
2580931  0.101871   1248  2020-01-01       cs2        1.0      19543.967379

         z_track_avg
2580931    -0.109466
'local_data_select': 0.001 seconds
number obs: 29
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.049 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:15:54.788512: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:15:54.789931: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'optimise_parameters': 0.262 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.00987461, 10.00995722,  0.99966317])
kernel_variance: 0.04591779073220711
likelihood_variance: 0.022013140981606106
'predict': 0.030 seconds
total run time : 0.83 seconds
--------------------------------------------------
9 / 15
current local expert:
                     x              y        lon        lat        t  \
2580938 -733001.825704 -158062.080941 -77.831257  83.282409  18262.0

                z  track date_string satellite  lead_mask  dist_along_track  \
2580938  0.096413   1248  2020-01-01       cs2        1.0      24655.572947

         z_track_avg
2580938    -0.109466
'local_data_select': 0.001 seconds
number obs: 29
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.050 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:15:55.617817: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:15:55.619218: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'optimise_parameters': 0.265 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.00987461, 10.00995722,  0.99966317])
kernel_variance: 0.04591779073220711
likelihood_variance: 0.022013140981606106
'predict': 0.030 seconds
total run time : 0.83 seconds
--------------------------------------------------
10 / 15
current local expert:
                     x              y        lon        lat        t  \
2580941 -731957.061798 -157453.728143 -77.859913  83.292719  18262.0

                z  track date_string satellite  lead_mask  dist_along_track  \
2580941  0.039666   1248  2020-01-01       cs2        1.0      25858.279456

         z_track_avg
2580941    -0.109466
'local_data_select': 0.001 seconds
number obs: 29
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.052 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:15:56.455639: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:15:56.457033: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'optimise_parameters': 0.263 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.00987461, 10.00995722,  0.99966317])
kernel_variance: 0.04591779073220711
likelihood_variance: 0.022013140981606106
'predict': 0.030 seconds
SAVING RESULTS TO TABLES:
run_details
preds
lengthscales
kernel_variance
likelihood_variance
total run time : 0.96 seconds
--------------------------------------------------
11 / 15
current local expert:
                     x              y        lon        lat        t  \
2580943 -727777.555121 -155020.554035 -77.975397  83.333945  18262.0

                z  track date_string satellite  lead_mask  dist_along_track  \
2580943 -0.082038   1248  2020-01-01       cs2        1.0      30669.307114

         z_track_avg
2580943    -0.109466
'local_data_select': 0.001 seconds
number obs: 29
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.046 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:15:57.410154: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:15:57.412142: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'optimise_parameters': 0.266 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.00987461, 10.00995722,  0.99966317])
kernel_variance: 0.04591779073220711
likelihood_variance: 0.022013140981606106
'predict': 0.030 seconds
total run time : 0.83 seconds
--------------------------------------------------
12 / 15
current local expert:
                     x              y        lon        lat        t  \
2580955 -719156.146991 -150003.628059 -78.218011  83.418891  18262.0

                z  track date_string satellite  lead_mask  dist_along_track  \
2580955 -0.421003   1248  2020-01-01       cs2        1.0      40591.974871

         z_track_avg
2580955    -0.109466
'local_data_select': 0.001 seconds
number obs: 29
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.046 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:15:58.246467: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:15:58.247879: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'optimise_parameters': 0.262 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.00987461, 10.00995722,  0.99966317])
kernel_variance: 0.04591779073220711
likelihood_variance: 0.022013140981606106
'predict': 0.030 seconds
total run time : 0.83 seconds
--------------------------------------------------
13 / 15
current local expert:
                     x              y        lon        lat        t  \
2580957 -718633.544282 -149699.618402 -78.232911  83.424036  18262.0

                z  track date_string satellite  lead_mask  dist_along_track  \
2580957 -0.047721   1248  2020-01-01       cs2        1.0      41193.390934

         z_track_avg
2580957    -0.109466
'local_data_select': 0.001 seconds
number obs: 29
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:15:59.080020: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:15:59.081447: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'optimise_parameters': 0.261 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.00987461, 10.00995722,  0.99966317])
kernel_variance: 0.04591779073220711
likelihood_variance: 0.022013140981606106
'predict': 0.030 seconds
total run time : 0.84 seconds
--------------------------------------------------
14 / 15
current local expert:
                     x              y        lon       lat        t        z  \
2580959 -718110.997086 -149395.637356 -78.247833  83.42918  18262.0 -0.00554

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2580959   1248  2020-01-01       cs2        1.0      41794.743272    -0.109466
'local_data_select': 0.001 seconds
number obs: 29
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.049 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:15:59.921468: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:15:59.925257: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'optimise_parameters': 0.263 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.00987461, 10.00995722,  0.99966317])
kernel_variance: 0.04591779073220711
likelihood_variance: 0.022013140981606106
'predict': 0.032 seconds
total run time : 0.85 seconds
--------------------------------------------------
15 / 15
current local expert:
                     x              y        lon        lat        t  \
2580963 -714714.150241 -147419.903594 -78.345382  83.462607  18262.0

                z  track date_string satellite  lead_mask  dist_along_track  \
2580963  0.166448   1248  2020-01-01       cs2        1.0      45703.671154

         z_track_avg
2580963    -0.109466
'local_data_select': 0.001 seconds
number obs: 29
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:16:00.777433: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:16:00.778949: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'optimise_parameters': 0.265 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.00987461, 10.00995722,  0.99966317])
kernel_variance: 0.04591779073220711
likelihood_variance: 0.022013140981606106
'predict': 0.030 seconds
total run time : 0.85 seconds
storing any remaining tables
SAVING RESULTS TO TABLES:
run_details
preds
lengthscales
kernel_variance
likelihood_variance
'run': 12.805 seconds
reading in results
getting all tables
merging on expert location data
table: 'oi_config' does not have all coords_col: ['x', 'y', 't'] in columns, not merging on expert_locations
h5 tables: ['expert_locs', 'kernel_variance', 'lengthscales', 'likelihood_variance', 'oi_config', 'preds', 'run_details']
found model_name: GPflowGPRModel
found GPU
setting lengthscales to: [1.]
'__init__': 0.046 seconds
reading in results
selecting only tables: ['lengthscales', 'kernel_variance', 'likelihood_variance']
'data_select': 0.000 seconds
'load': 0.001 seconds
expert_locations data will not be merged on results data
adding smoothed table: lengthscales_SMOOTHED
adding smoothed table: kernel_variance_SMOOTHED
adding smoothed table: likelihood_variance_SMOOTHED
writing (smoothed) hyper parameters to:
/home/mhen/geol0069_data/gpsat/jan20/1248.h5
table_suffix:_SMOOTHED
writing: lengthscales_SMOOTHED to table
writing: kernel_variance_SMOOTHED to table
writing: likelihood_variance_SMOOTHED to table
'data_select': 0.000 seconds
'load': 0.000 seconds

2026-05-18 19:16:01.844825: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:16:01.846405: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

---------
storing expert locations in 'expert_locs' table
exception occurred: 'No object named expert_locs_SMOOTHED in the file'
will now close object

---------
dropping expert locations that already exists in 'run_details' table
exception occurred: 'No object named run_details_SMOOTHED in the file'
will now close object

--------------------------------------------------
1 / 15
current local expert:
                     x              y        lon        lat        t        z  \
2580904 -752586.974584 -169474.112523 -77.309324  83.088809  18262.0 -0.07177

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2580904   1248  2020-01-01       cs2        1.0       2104.432631    -0.109466
'data_select': 0.000 seconds
'load': 0.000 seconds
'local_data_select': 0.001 seconds
number obs: 29
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.050 seconds
'get_parameters': 0.003 seconds
'_read_params_from_file': 0.056 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds
*** not optimising parameters

2026-05-18 19:16:02.108786: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:16:02.110217: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  0.99966317])
kernel_variance: 0.04591779073220711
likelihood_variance: 0.022013140981606123
'predict': 0.030 seconds
total run time : 0.64 seconds
--------------------------------------------------
2 / 15
current local expert:
                     x              y        lon        lat        t  \
2580939 -732479.467427 -157757.909775 -77.845574  83.287564  18262.0

                z  track date_string satellite  lead_mask  dist_along_track  \
2580939  0.067827   1248  2020-01-01       cs2        1.0      25256.904075

         z_track_avg
2580939    -0.109466
'local_data_select': 0.001 seconds
number obs: 29
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.049 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  0.99966317])
kernel_variance: 0.04591779073220711
likelihood_variance: 0.022013140981606106
'predict': 0.030 seconds

2026-05-18 19:16:02.748464: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:16:02.749869: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.63 seconds
--------------------------------------------------
3 / 15
current local expert:
                     x              y        lon        lat        t  \
2580905 -752325.979061 -169321.912428 -77.316096  83.091393  18262.0

                z  track date_string satellite  lead_mask  dist_along_track  \
2580905 -0.097971   1248  2020-01-01       cs2        1.0       2405.030203

         z_track_avg
2580905    -0.109466
'local_data_select': 0.001 seconds
number obs: 29
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.047 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  0.99966317])
kernel_variance: 0.04591779073220711
likelihood_variance: 0.022013140981606123
'predict': 0.030 seconds

2026-05-18 19:16:03.379653: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:16:03.381066: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.62 seconds
--------------------------------------------------
4 / 15
current local expert:
                     x              y        lon       lat        t         z  \
2580911 -749453.971198 -167647.505603 -77.390921  83.11982  18262.0 -0.189269

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2580911   1248  2020-01-01       cs2        1.0       5712.586698    -0.109466
'local_data_select': 0.001 seconds
number obs: 29
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.046 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  0.99966317])
kernel_variance: 0.04591779073220711
likelihood_variance: 0.022013140981606123
'predict': 0.030 seconds

2026-05-18 19:16:04.001654: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:16:04.003058: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.63 seconds
--------------------------------------------------
5 / 15
current local expert:
                     x              y        lon        lat        t  \
2580914 -748148.420387 -166886.471156 -77.425131  83.132738  18262.0

                z  track date_string satellite  lead_mask  dist_along_track  \
2580914 -0.295851   1248  2020-01-01       cs2        1.0       7216.053894

         z_track_avg
2580914    -0.109466
'local_data_select': 0.001 seconds
number obs: 29
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.046 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  0.99966317])
kernel_variance: 0.04591779073220713
likelihood_variance: 0.022013140981606106
'predict': 0.030 seconds

2026-05-18 19:16:04.634783: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:16:04.636189: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.62 seconds
--------------------------------------------------
6 / 15
current local expert:
                     x              y        lon        lat        t  \
2580916 -747626.247017 -166582.095446 -77.438849  83.137904  18262.0

                z  track date_string satellite  lead_mask  dist_along_track  \
2580916 -0.277643   1248  2020-01-01       cs2        1.0       7817.378285

         z_track_avg
2580916    -0.109466
'local_data_select': 0.001 seconds
number obs: 29
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  0.99966317])
kernel_variance: 0.04591779073220711
likelihood_variance: 0.022013140981606123
'predict': 0.030 seconds

2026-05-18 19:16:05.262062: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:16:05.263476: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.62 seconds
--------------------------------------------------
7 / 15
current local expert:
                     x             y        lon        lat        t         z  \
2580921 -745276.225668 -165212.42095 -77.500831  83.161148  18262.0 -0.151735

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2580921   1248  2020-01-01       cs2        1.0       10523.51579    -0.109466
'local_data_select': 0.001 seconds
number obs: 29
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.049 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  0.99966317])
kernel_variance: 0.04591779073220711
likelihood_variance: 0.022013140981606123
'predict': 0.030 seconds

2026-05-18 19:16:05.881964: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:16:05.885744: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.63 seconds
--------------------------------------------------
8 / 15
current local expert:
                     x              y        lon        lat        t  \
2580931 -737441.911939 -160647.909514 -77.710416  83.238573  18262.0

                z  track date_string satellite  lead_mask  dist_along_track  \
2580931  0.101871   1248  2020-01-01       cs2        1.0      19543.967379

         z_track_avg
2580931    -0.109466
'local_data_select': 0.001 seconds
number obs: 29
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  0.99966317])
kernel_variance: 0.04591779073220713
likelihood_variance: 0.022013140981606123
'predict': 0.030 seconds

2026-05-18 19:16:06.519066: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:16:06.521069: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.63 seconds
--------------------------------------------------
9 / 15
current local expert:
                     x              y        lon        lat        t  \
2580938 -733001.825704 -158062.080941 -77.831257  83.282409  18262.0

                z  track date_string satellite  lead_mask  dist_along_track  \
2580938  0.096413   1248  2020-01-01       cs2        1.0      24655.572947

         z_track_avg
2580938    -0.109466
'local_data_select': 0.001 seconds
number obs: 29
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  0.99966317])
kernel_variance: 0.04591779073220711
likelihood_variance: 0.022013140981606106
'predict': 0.030 seconds

2026-05-18 19:16:07.151585: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:16:07.152996: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.62 seconds
--------------------------------------------------
10 / 15
current local expert:
                     x              y        lon        lat        t  \
2580941 -731957.061798 -157453.728143 -77.859913  83.292719  18262.0

                z  track date_string satellite  lead_mask  dist_along_track  \
2580941  0.039666   1248  2020-01-01       cs2        1.0      25858.279456

         z_track_avg
2580941    -0.109466
'local_data_select': 0.001 seconds
number obs: 29
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  0.99966317])
kernel_variance: 0.04591779073220711
likelihood_variance: 0.022013140981606123
'predict': 0.030 seconds

2026-05-18 19:16:07.774475: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:16:07.776093: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

SAVING RESULTS TO TABLES:
run_details
preds
total run time : 0.69 seconds
--------------------------------------------------
11 / 15
current local expert:
                     x              y        lon        lat        t  \
2580943 -727777.555121 -155020.554035 -77.975397  83.333945  18262.0

                z  track date_string satellite  lead_mask  dist_along_track  \
2580943 -0.082038   1248  2020-01-01       cs2        1.0      30669.307114

         z_track_avg
2580943    -0.109466
'local_data_select': 0.001 seconds
number obs: 29
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'_read_params_from_file': 0.049 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  0.99966317])
kernel_variance: 0.04591779073220709
likelihood_variance: 0.022013140981606123

2026-05-18 19:16:08.464054: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:16:08.465464: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'predict': 0.031 seconds
total run time : 0.64 seconds
--------------------------------------------------
12 / 15
current local expert:
                     x              y        lon        lat        t  \
2580955 -719156.146991 -150003.628059 -78.218011  83.418891  18262.0

                z  track date_string satellite  lead_mask  dist_along_track  \
2580955 -0.421003   1248  2020-01-01       cs2        1.0      40591.974871

         z_track_avg
2580955    -0.109466
'local_data_select': 0.001 seconds
number obs: 29
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.046 seconds
'_read_params_from_file': 0.045 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  0.99966317])
kernel_variance: 0.04591779073220711
likelihood_variance: 0.022013140981606123
'predict': 0.030 seconds

2026-05-18 19:16:09.101866: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:16:09.103283: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.63 seconds
--------------------------------------------------
13 / 15
current local expert:
                     x              y        lon        lat        t  \
2580957 -718633.544282 -149699.618402 -78.232911  83.424036  18262.0

                z  track date_string satellite  lead_mask  dist_along_track  \
2580957 -0.047721   1248  2020-01-01       cs2        1.0      41193.390934

         z_track_avg
2580957    -0.109466
'local_data_select': 0.001 seconds
number obs: 29
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  0.99966317])
kernel_variance: 0.04591779073220711
likelihood_variance: 0.022013140981606123
'predict': 0.030 seconds

2026-05-18 19:16:09.734537: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:16:09.735935: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.62 seconds
--------------------------------------------------
14 / 15
current local expert:
                     x              y        lon       lat        t        z  \
2580959 -718110.997086 -149395.637356 -78.247833  83.42918  18262.0 -0.00554

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2580959   1248  2020-01-01       cs2        1.0      41794.743272    -0.109466
'local_data_select': 0.001 seconds
number obs: 29
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  0.99966317])
kernel_variance: 0.04591779073220711
likelihood_variance: 0.022013140981606123
'predict': 0.030 seconds

2026-05-18 19:16:10.356391: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:16:10.357806: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.62 seconds
--------------------------------------------------
15 / 15
current local expert:
                     x              y        lon        lat        t  \
2580963 -714714.150241 -147419.903594 -78.345382  83.462607  18262.0

                z  track date_string satellite  lead_mask  dist_along_track  \
2580963  0.166448   1248  2020-01-01       cs2        1.0      45703.671154

         z_track_avg
2580963    -0.109466
'local_data_select': 0.001 seconds
number obs: 29
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  0.99966317])
kernel_variance: 0.04591779073220711
likelihood_variance: 0.022013140981606123
'predict': 0.030 seconds

2026-05-18 19:16:10.979456: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:16:10.980964: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.62 seconds
storing any remaining tables
SAVING RESULTS TO TABLES:
run_details
preds
'run': 9.627 seconds
reading in results
getting all tables
merging on expert location data
table: 'oi_config' does not have all coords_col: ['x', 'y', 't'] in columns, not merging on expert_locations
table: 'oi_config_SMOOTHED' does not have all coords_col: ['x', 'y', 't'] in columns, not merging on expert_locations
lin:
                     x              y        lon        lat        t  \
2580900 -754414.178156 -170539.583567 -77.262060  83.070716  18262.0
2580901 -754153.150902 -170387.372478 -77.268797  83.073301  18262.0
2580902 -753631.172346 -170082.968494 -77.282286  83.078470  18262.0
2580903 -752848.067772 -169626.335390 -77.302557  83.086224  18262.0
2580904 -752586.974584 -169474.112523 -77.309324  83.088809  18262.0

                z  track date_string satellite  lead_mask  dist_along_track  \
2580900       NaN   1248  2020-01-01       cs2        0.0          0.000000
2580901       NaN   1248  2020-01-01       cs2        0.0        300.633449
2580902       NaN   1248  2020-01-01       cs2        0.0        901.824587
2580903  0.012273   1248  2020-01-01       cs2        1.0       1803.739199
2580904 -0.071770   1248  2020-01-01       cs2        1.0       2104.432631

         z_track_avg     f_lin
2580900    -0.109466 -0.079419
2580901    -0.109466 -0.079419
2580902    -0.109466 -0.079419
2580903    -0.109466 -0.079419
2580904    -0.109466 -0.079419
gpsat:
                     x              y        lon        lat        t  \
2580900 -754414.178156 -170539.583567 -77.262060  83.070716  18262.0
2580901 -754153.150902 -170387.372478 -77.268797  83.073301  18262.0
2580902 -753631.172346 -170082.968494 -77.282286  83.078470  18262.0
2580903 -752848.067772 -169626.335390 -77.302557  83.086224  18262.0
2580904 -752586.974584 -169474.112523 -77.309324  83.088809  18262.0

                z  track date_string satellite  lead_mask  dist_along_track  \
2580900       NaN   1248  2020-01-01       cs2        0.0          0.000000
2580901       NaN   1248  2020-01-01       cs2        0.0        300.633449
2580902       NaN   1248  2020-01-01       cs2        0.0        901.824587
2580903  0.012273   1248  2020-01-01       cs2        1.0       1803.739199
2580904 -0.071770   1248  2020-01-01       cs2        1.0       2104.432631

         z_track_avg   f_gpsat  f_var_gpsat
2580900    -0.109466 -0.160017     0.002400
2580901    -0.109466 -0.159236     0.002350
2580902    -0.109466 -0.157637     0.002253
2580903    -0.109466 -0.155141     0.002117
2580904    -0.109466 -0.154283     0.002074
Test NaNs — Linear: 0, GPSat: 0
Track interpolated!
Interpolating track 1249, 7 of 15...

/tmp/ipykernel_1171781/839927469.py:200: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  track_df['f_gpsat'] = ssha
/tmp/ipykernel_1171781/839927469.py:201: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  track_df['f_var_gpsat'] = ssha_var

'data_select': 0.000 seconds
'load': 0.000 seconds
in json_serializable - key: 'data_source' has value DataFrame/Series, but is too long: 803 >  100
storing as str
in json_serializable - key: 'df' has value DataFrame/Series, but is too long: 1051 >  100
storing as str
---------
storing expert locations in 'expert_locs' table
exception occurred: 'No object named expert_locs in the file'
will now close object

---------
dropping expert locations that already exists in 'run_details' table
exception occurred: 'No object named run_details in the file'
will now close object

--------------------------------------------------
1 / 19
current local expert:
                    x              y      lon        lat        t         z  \
2580970 -3.305594e+06 -165626.421983 -87.1316  60.000733  18262.0 -0.015819

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2580970   1249  2020-01-01       cs2        1.0               0.0     0.053873
'data_select': 0.000 seconds
'load': 0.000 seconds
'local_data_select': 0.001 seconds
number obs: 728
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.050 seconds
'get_parameters': 0.003 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:16:12.241864: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:16:12.243922: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 1.018 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01010962, 10.01000333,  0.99826041])
kernel_variance: 0.003020926835708144
likelihood_variance: 0.0010000000060793348
'predict': 0.044 seconds
total run time : 1.62 seconds
--------------------------------------------------
2 / 19
current local expert:
                    x              y        lon       lat        t         z  \
2581037 -3.281170e+06 -161629.719516 -87.179902  60.22918  18262.0  0.067989

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2581037   1249  2020-01-01       cs2        1.0      25485.599449     0.053873
'local_data_select': 0.001 seconds
number obs: 768
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.046 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:16:13.858870: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:16:13.860277: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.967 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01015779, 10.01000416,  0.99274878])
kernel_variance: 0.003434290643840671
likelihood_variance: 0.0010000000101702583
'predict': 0.046 seconds
total run time : 1.56 seconds
--------------------------------------------------
3 / 19
current local expert:
                    x              y        lon        lat        t         z  \
2581112 -3.257592e+06 -157787.844406 -87.226934  60.449567  18262.0  0.051744

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2581112   1249  2020-01-01       cs2        1.0      50072.680385     0.053873
'local_data_select': 0.001 seconds
number obs: 802
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:16:15.427158: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:16:15.428589: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 1.103 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01016493, 10.01000427,  0.99920495])
kernel_variance: 0.00805506813131479
likelihood_variance: 0.001000000018606579
'predict': 0.048 seconds
total run time : 1.72 seconds
--------------------------------------------------
4 / 19
current local expert:
                    x              y        lon        lat        t         z  \
2581186 -3.233710e+06 -153912.947591 -87.274984  60.672641  18262.0  0.072541

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2581186   1249  2020-01-01       cs2        1.0      74960.211083     0.053873
'local_data_select': 0.001 seconds
number obs: 803
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.052 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:16:17.151027: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:16:17.152425: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'optimise_parameters': 0.700 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01016696, 10.01000429,  0.99730121])
kernel_variance: 0.00877121688433309
likelihood_variance: 0.0010000000186793708
'predict': 0.048 seconds
total run time : 1.31 seconds
--------------------------------------------------
5 / 19
current local expert:
                    x              y        lon        lat        t       z  \
2581260 -3.209524e+06 -150005.526247 -87.324079  60.898404  18262.0 -0.0024

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2581260   1249  2020-01-01       cs2        1.0     100148.459726     0.053873
'local_data_select': 0.001 seconds
number obs: 803
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.049 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:16:18.459591: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:16:18.461596: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'optimise_parameters': 0.691 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01016696, 10.01000429,  0.99730121])
kernel_variance: 0.00877121688433309
likelihood_variance: 0.0010000000186793708
'predict': 0.048 seconds
total run time : 1.30 seconds
--------------------------------------------------
6 / 19
current local expert:
                    x              y        lon        lat        t         z  \
2581325 -3.185610e+06 -146158.636099 -87.373061  61.121479  18262.0  0.096365

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2581325   1249  2020-01-01       cs2        1.0     125037.542897     0.053873
'local_data_select': 0.001 seconds
number obs: 803
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:16:19.757020: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:16:19.759106: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'optimise_parameters': 0.694 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01016696, 10.01000429,  0.99730121])
kernel_variance: 0.00877121688433309
likelihood_variance: 0.0010000000186793708
'predict': 0.048 seconds
total run time : 1.31 seconds
--------------------------------------------------
7 / 19
current local expert:
                    x              y        lon       lat        t         z  \
2581379 -3.159661e+06 -142003.087497 -87.426716  61.36337  18262.0  0.030089

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2581379   1249  2020-01-01       cs2        1.0     152026.821768     0.053873
'local_data_select': 0.001 seconds
number obs: 803
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.050 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:16:21.072037: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:16:21.073996: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'optimise_parameters': 0.699 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01016696, 10.01000429,  0.99730121])
kernel_variance: 0.00877121688433309
likelihood_variance: 0.0010000000186793708
'predict': 0.048 seconds
total run time : 1.31 seconds
--------------------------------------------------
8 / 19
current local expert:
                    x             y        lon        lat        t         z  \
2581416 -3.137446e+06 -138460.85149 -87.473079  61.570321  18262.0  0.077082

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2581416   1249  2020-01-01       cs2        1.0      175118.34865     0.053873
'local_data_select': 0.001 seconds
number obs: 803
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.049 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:16:22.381720: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:16:22.383124: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'optimise_parameters': 0.699 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01016696, 10.01000429,  0.99730121])
kernel_variance: 0.00877121688433309
likelihood_variance: 0.0010000000186793708
'predict': 0.048 seconds
total run time : 1.31 seconds
--------------------------------------------------
9 / 19
current local expert:
                    x             y        lon       lat        t         z  \
2581471 -3.113773e+06 -134701.82655 -87.522929  61.79071  18262.0  0.090369

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2581471   1249  2020-01-01       cs2        1.0     199710.041094     0.053873
'local_data_select': 0.001 seconds
number obs: 803
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.051 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:16:23.699415: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:16:23.700833: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'optimise_parameters': 0.695 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01016696, 10.01000429,  0.99730121])
kernel_variance: 0.00877121688433309
likelihood_variance: 0.0010000000186793708
'predict': 0.048 seconds
total run time : 1.32 seconds
--------------------------------------------------
10 / 19
current local expert:
                    x              y        lon        lat        t        z  \
2581518 -3.089507e+06 -130865.360173 -87.574515  62.016473  18262.0  0.10927

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2581518   1249  2020-01-01       cs2        1.0     224902.209596     0.053873
'local_data_select': 0.001 seconds
number obs: 803
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.050 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:16:25.020100: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:16:25.021504: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'optimise_parameters': 0.700 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01016696, 10.01000429,  0.99730121])
kernel_variance: 0.00877121688433309
likelihood_variance: 0.0010000000186793708
'predict': 0.048 seconds
SAVING RESULTS TO TABLES:
run_details
preds
lengthscales
kernel_variance
likelihood_variance
total run time : 1.45 seconds
--------------------------------------------------
11 / 19
current local expert:
                    x              y        lon        lat        t         z  \
2581569 -3.065225e+06 -127043.276459 -87.626641  62.242237  18262.0  0.000093

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2581569   1249  2020-01-01       cs2        1.0     250095.355482     0.053873
'local_data_select': 0.001 seconds
number obs: 803
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.051 seconds
'set_lengthscales_constraints': 0.006 seconds

2026-05-18 19:16:26.475813: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:16:26.477245: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'set_likelihood_variance_constraints': 0.011 seconds
'optimise_parameters': 0.700 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01016696, 10.01000429,  0.99730121])
kernel_variance: 0.00877121688433309
likelihood_variance: 0.0010000000186793708
'predict': 0.048 seconds
total run time : 1.32 seconds
--------------------------------------------------
12 / 19
current local expert:
                    x              y       lon        lat        t       z  \
2581623 -3.041506e+06 -123326.076195 -87.67806  62.462624  18262.0  0.0533

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2581623   1249  2020-01-01       cs2        1.0     274689.345451     0.053873
'local_data_select': 0.001 seconds
number obs: 803
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.049 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:16:27.791147: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:16:27.792568: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'optimise_parameters': 0.698 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01016696, 10.01000429,  0.99730121])
kernel_variance: 0.00877121688433309
likelihood_variance: 0.0010000000186793708
'predict': 0.048 seconds
total run time : 1.32 seconds
--------------------------------------------------
13 / 19
current local expert:
                    x              y       lon        lat        t         z  \
2581670 -3.016904e+06 -119487.426024 -87.73193  62.691073  18262.0  0.079524

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2581670   1249  2020-01-01       cs2        1.0     300183.936449     0.053873
'local_data_select': 0.001 seconds
number obs: 803
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.049 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:16:29.109278: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:16:29.110701: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'optimise_parameters': 0.695 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01016696, 10.01000429,  0.99730121])
kernel_variance: 0.00877121688433309
likelihood_variance: 0.0010000000186793708
'predict': 0.048 seconds
total run time : 1.32 seconds
--------------------------------------------------
14 / 19
current local expert:
                    x              y        lon       lat        t         z  \
2581732 -2.992285e+06 -115663.589152 -87.786395  62.91952  18262.0  0.027541

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2581732   1249  2020-01-01       cs2        1.0     325679.279641     0.053873
'local_data_select': 0.001 seconds
number obs: 803
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.047 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:16:30.424287: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:16:30.425694: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'optimise_parameters': 0.692 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01016696, 10.01000429,  0.99730121])
kernel_variance: 0.00877121688433309
likelihood_variance: 0.0010000000186793708
'predict': 0.048 seconds
total run time : 1.31 seconds
--------------------------------------------------
15 / 19
current local expert:
                    x              y        lon        lat        t         z  \
2581771 -2.968521e+06 -111988.811354 -87.839515  63.139903  18262.0  0.017237

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2581771   1249  2020-01-01       cs2        1.0     350275.604718     0.053873
'local_data_select': 0.001 seconds
number obs: 803
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:16:31.737808: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:16:31.739236: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'optimise_parameters': 0.702 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01016696, 10.01000429,  0.99730121])
kernel_variance: 0.00877121688433309
likelihood_variance: 0.0010000000186793708
'predict': 0.048 seconds
total run time : 1.33 seconds
--------------------------------------------------
16 / 19
current local expert:
                    x              y        lon        lat        t         z  \
2581830 -2.944452e+06 -108283.279117 -87.893876  63.362972  18262.0  0.051761

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2581830   1249  2020-01-01       cs2        1.0     375172.691199     0.053873
'local_data_select': 0.001 seconds
number obs: 803
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.050 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:16:33.074141: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:16:33.075559: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'optimise_parameters': 0.697 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01016696, 10.01000429,  0.99730121])
kernel_variance: 0.00877121688433309
likelihood_variance: 0.0010000000186793708
'predict': 0.049 seconds
total run time : 1.32 seconds
--------------------------------------------------
17 / 19
current local expert:
                    x              y        lon        lat        t         z  \
2581892 -2.920099e+06 -104550.924791 -87.949464  63.588521  18262.0  0.104924

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2581892   1249  2020-01-01       cs2        1.0     400347.612758     0.053873
'local_data_select': 0.001 seconds
number obs: 803
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.052 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:16:34.401747: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:16:34.403152: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'optimise_parameters': 0.698 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01016696, 10.01000429,  0.99730121])
kernel_variance: 0.00877121688433309
likelihood_variance: 0.0010000000186793708
'predict': 0.048 seconds
total run time : 1.33 seconds
--------------------------------------------------
18 / 19
current local expert:
                    x              y        lon        lat        t         z  \
2581941 -2.896261e+06 -100913.582598 -88.004467  63.809174  18262.0  0.065372

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2581941   1249  2020-01-01       cs2        1.0     424977.104752     0.053873
'local_data_select': 0.001 seconds
number obs: 768
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.050 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:16:35.726375: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:16:35.727792: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 1.152 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01016382, 10.0100042 ,  0.9986314 ])
kernel_variance: 0.008909390433007343
likelihood_variance: 0.0010000000296636743
'predict': 0.045 seconds
total run time : 1.77 seconds
--------------------------------------------------
19 / 19
current local expert:
                    x             y        lon       lat        t         z  \
2581996 -2.871566e+06 -97162.631585 -88.062073  64.03761  18262.0  0.217621

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2581996   1249  2020-01-01       cs2        1.0     450476.454177     0.053873
'local_data_select': 0.001 seconds
number obs: 711
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.049 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:16:37.501196: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:16:37.502615: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 1.060 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01015587, 10.01000395,  0.99667817])
kernel_variance: 0.00994743065682735
likelihood_variance: 0.0010000000643522276
'predict': 0.045 seconds
total run time : 1.68 seconds
storing any remaining tables
SAVING RESULTS TO TABLES:
run_details
preds
lengthscales
kernel_variance
likelihood_variance
'run': 27.166 seconds
reading in results
getting all tables
merging on expert location data
table: 'oi_config' does not have all coords_col: ['x', 'y', 't'] in columns, not merging on expert_locations
h5 tables: ['expert_locs', 'kernel_variance', 'lengthscales', 'likelihood_variance', 'oi_config', 'preds', 'run_details']
found model_name: GPflowGPRModel
found GPU
setting lengthscales to: [1.]
'__init__': 0.048 seconds
reading in results
selecting only tables: ['lengthscales', 'kernel_variance', 'likelihood_variance']
'data_select': 0.000 seconds
'load': 0.001 seconds
expert_locations data will not be merged on results data
adding smoothed table: lengthscales_SMOOTHED
adding smoothed table: kernel_variance_SMOOTHED
adding smoothed table: likelihood_variance_SMOOTHED
writing (smoothed) hyper parameters to:
/home/mhen/geol0069_data/gpsat/jan20/1249.h5
table_suffix:_SMOOTHED
writing: lengthscales_SMOOTHED to table
writing: kernel_variance_SMOOTHED to table
writing: likelihood_variance_SMOOTHED to table
'data_select': 0.000 seconds
'load': 0.000 seconds
in json_serializable - key: 'data_source' has value DataFrame/Series, but is too long: 803 >  100
storing as str
in json_serializable - key: 'df' has value DataFrame/Series, but is too long: 1051 >  100
storing as str

2026-05-18 19:16:39.463977: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:16:39.465419: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

---------
storing expert locations in 'expert_locs' table
exception occurred: 'No object named expert_locs_SMOOTHED in the file'
will now close object

---------
dropping expert locations that already exists in 'run_details' table
exception occurred: 'No object named run_details_SMOOTHED in the file'
will now close object

--------------------------------------------------
1 / 19
current local expert:
                    x              y      lon        lat        t         z  \
2580970 -3.305594e+06 -165626.421983 -87.1316  60.000733  18262.0 -0.015819

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2580970   1249  2020-01-01       cs2        1.0               0.0     0.053873
'data_select': 0.000 seconds
'load': 0.000 seconds
'local_data_select': 0.001 seconds
number obs: 728
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.052 seconds
'get_parameters': 0.003 seconds
'_read_params_from_file': 0.073 seconds

2026-05-18 19:16:39.725473: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:16:39.726908: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'set_parameters': 0.006 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01016034, 10.01000418,  0.99714839])
kernel_variance: 0.007668578747778525
likelihood_variance: 0.01100000000000001
'predict': 0.044 seconds
total run time : 0.71 seconds
--------------------------------------------------
2 / 19
current local expert:
                    x              y        lon       lat        t         z  \
2581037 -3.281170e+06 -161629.719516 -87.179902  60.22918  18262.0  0.067989

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2581037   1249  2020-01-01       cs2        1.0      25485.599449     0.053873
'local_data_select': 0.001 seconds
number obs: 768
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.051 seconds
'_read_params_from_file': 0.045 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01016086, 10.01000419,  0.99716296])
kernel_variance: 0.007758821580012963
likelihood_variance: 0.01100000000000001
'predict': 0.046 seconds

2026-05-18 19:16:40.432726: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:16:40.434152: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.68 seconds
--------------------------------------------------
3 / 19
current local expert:
                    x              y        lon        lat        t         z  \
2581112 -3.257592e+06 -157787.844406 -87.226934  60.449567  18262.0  0.051744

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2581112   1249  2020-01-01       cs2        1.0      50072.680385     0.053873
'local_data_select': 0.001 seconds
number obs: 802
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.046 seconds
'_read_params_from_file': 0.045 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01016135, 10.0100042 ,  0.99717692])
kernel_variance: 0.007843907120650827
likelihood_variance: 0.01100000000000001
'predict': 0.049 seconds

2026-05-18 19:16:41.108120: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:16:41.109543: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.68 seconds
--------------------------------------------------
4 / 19
current local expert:
                    x              y        lon        lat        t         z  \
2581186 -3.233710e+06 -153912.947591 -87.274984  60.672641  18262.0  0.072541

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2581186   1249  2020-01-01       cs2        1.0      74960.211083     0.053873
'local_data_select': 0.001 seconds
number obs: 803
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'_read_params_from_file': 0.045 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01016181, 10.0100042 ,  0.9971909 ])
kernel_variance: 0.007927715020495479
likelihood_variance: 0.01100000000000001
'predict': 0.049 seconds

2026-05-18 19:16:41.789505: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:16:41.790924: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.69 seconds
--------------------------------------------------
5 / 19
current local expert:
                    x              y        lon        lat        t       z  \
2581260 -3.209524e+06 -150005.526247 -87.324079  60.898404  18262.0 -0.0024

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2581260   1249  2020-01-01       cs2        1.0     100148.459726     0.053873
'local_data_select': 0.001 seconds
number obs: 803
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.046 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01016225, 10.01000421,  0.99720482])
kernel_variance: 0.008009827706827701
likelihood_variance: 0.01100000000000001
'predict': 0.048 seconds

2026-05-18 19:16:42.478190: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:16:42.480198: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.68 seconds
--------------------------------------------------
6 / 19
current local expert:
                    x              y        lon        lat        t         z  \
2581325 -3.185610e+06 -146158.636099 -87.373061  61.121479  18262.0  0.096365

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2581325   1249  2020-01-01       cs2        1.0     125037.542897     0.053873
'local_data_select': 0.001 seconds
number obs: 803
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.049 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01016265, 10.01000422,  0.9972183 ])
kernel_variance: 0.008087981073881905
likelihood_variance: 0.01100000000000001
'predict': 0.048 seconds

2026-05-18 19:16:43.160863: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:16:43.162275: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.68 seconds
--------------------------------------------------
7 / 19
current local expert:
                    x              y        lon       lat        t         z  \
2581379 -3.159661e+06 -142003.087497 -87.426716  61.36337  18262.0  0.030089

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2581379   1249  2020-01-01       cs2        1.0     152026.821768     0.053873
'local_data_select': 0.001 seconds
number obs: 803
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.045 seconds
'_read_params_from_file': 0.045 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01016306, 10.01000422,  0.99723255])
kernel_variance: 0.008169058954478928
likelihood_variance: 0.01100000000000001
'predict': 0.048 seconds

2026-05-18 19:16:43.842178: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:16:43.843737: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.68 seconds
--------------------------------------------------
8 / 19
current local expert:
                    x             y        lon        lat        t         z  \
2581416 -3.137446e+06 -138460.85149 -87.473079  61.570321  18262.0  0.077082

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2581416   1249  2020-01-01       cs2        1.0      175118.34865     0.053873
'local_data_select': 0.001 seconds
number obs: 803
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.045 seconds
'_read_params_from_file': 0.045 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01016337, 10.01000423,  0.99724439])
kernel_variance: 0.008235178532672003
likelihood_variance: 0.01100000000000001
'predict': 0.049 seconds

2026-05-18 19:16:44.519177: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:16:44.520589: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.69 seconds
--------------------------------------------------
9 / 19
current local expert:
                    x             y        lon       lat        t         z  \
2581471 -3.113773e+06 -134701.82655 -87.522929  61.79071  18262.0  0.090369

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2581471   1249  2020-01-01       cs2        1.0     199710.041094     0.053873
'local_data_select': 0.001 seconds
number obs: 803
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.049 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01016368, 10.01000423,  0.9972566 ])
kernel_variance: 0.008302123689346148
likelihood_variance: 0.01100000000000001
'predict': 0.049 seconds

2026-05-18 19:16:45.209333: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:16:45.211303: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.69 seconds
--------------------------------------------------
10 / 19
current local expert:
                    x              y        lon        lat        t        z  \
2581518 -3.089507e+06 -130865.360173 -87.574515  62.016473  18262.0  0.10927

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2581518   1249  2020-01-01       cs2        1.0     224902.209596     0.053873
'local_data_select': 0.001 seconds
number obs: 803
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.047 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01016395, 10.01000423,  0.99726864])
kernel_variance: 0.008366861210692819
likelihood_variance: 0.01100000000000001
'predict': 0.048 seconds

2026-05-18 19:16:45.896314: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:16:45.897740: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

SAVING RESULTS TO TABLES:
run_details
preds
total run time : 0.75 seconds
--------------------------------------------------
11 / 19
current local expert:
                    x              y        lon        lat        t         z  \
2581569 -3.065225e+06 -127043.276459 -87.626641  62.242237  18262.0  0.000093

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2581569   1249  2020-01-01       cs2        1.0     250095.355482     0.053873
'local_data_select': 0.001 seconds
number obs: 803
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.051 seconds
'_read_params_from_file': 0.050 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters

2026-05-18 19:16:46.650101: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:16:46.651523: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01016419, 10.01000424,  0.99728018])
kernel_variance: 0.008427632599251849
likelihood_variance: 0.01100000000000001
'predict': 0.048 seconds
total run time : 0.68 seconds
--------------------------------------------------
12 / 19
current local expert:
                    x              y       lon        lat        t       z  \
2581623 -3.041506e+06 -123326.076195 -87.67806  62.462624  18262.0  0.0533

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2581623   1249  2020-01-01       cs2        1.0     274689.345451     0.053873
'local_data_select': 0.001 seconds
number obs: 803
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.049 seconds
'_read_params_from_file': 0.045 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.0101644 , 10.01000424,  0.99729093])
kernel_variance: 0.008483109990634258
likelihood_variance: 0.01100000000000001
'predict': 0.048 seconds

2026-05-18 19:16:47.332955: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:16:47.335060: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.68 seconds
--------------------------------------------------
13 / 19
current local expert:
                    x              y       lon        lat        t         z  \
2581670 -3.016904e+06 -119487.426024 -87.73193  62.691073  18262.0  0.079524

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2581670   1249  2020-01-01       cs2        1.0     300183.936449     0.053873
'local_data_select': 0.001 seconds
number obs: 803
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.049 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01016457, 10.01000424,  0.99730151])
kernel_variance: 0.008536642069495786
likelihood_variance: 0.01100000000000001
'predict': 0.048 seconds

2026-05-18 19:16:48.014494: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:16:48.015973: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.69 seconds
--------------------------------------------------
14 / 19
current local expert:
                    x              y        lon       lat        t         z  \
2581732 -2.992285e+06 -115663.589152 -87.786395  62.91952  18262.0  0.027541

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2581732   1249  2020-01-01       cs2        1.0     325679.279641     0.053873
'local_data_select': 0.001 seconds
number obs: 803
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.050 seconds
'_read_params_from_file': 0.045 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.004 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01016472, 10.01000424,  0.99731151])
kernel_variance: 0.008586220983163756
likelihood_variance: 0.01100000000000001
'predict': 0.048 seconds

2026-05-18 19:16:48.705918: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:16:48.707354: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.68 seconds
--------------------------------------------------
15 / 19
current local expert:
                    x              y        lon        lat        t         z  \
2581771 -2.968521e+06 -111988.811354 -87.839515  63.139903  18262.0  0.017237

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2581771   1249  2020-01-01       cs2        1.0     350275.604718     0.053873
'local_data_select': 0.001 seconds
number obs: 803
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01016482, 10.01000424,  0.99732061])
kernel_variance: 0.008630439520505597
likelihood_variance: 0.01100000000000001
'predict': 0.049 seconds

2026-05-18 19:16:49.383881: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:16:49.385310: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.68 seconds
--------------------------------------------------
16 / 19
current local expert:
                    x              y        lon        lat        t         z  \
2581830 -2.944452e+06 -108283.279117 -87.893876  63.362972  18262.0  0.051761

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2581830   1249  2020-01-01       cs2        1.0     375172.691199     0.053873
'local_data_select': 0.001 seconds
number obs: 803
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.049 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.0101649 , 10.01000424,  0.99732925])
kernel_variance: 0.008671760749401881
likelihood_variance: 0.01100000000000001
'predict': 0.049 seconds

2026-05-18 19:16:50.068194: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:16:50.069695: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.69 seconds
--------------------------------------------------
17 / 19
current local expert:
                    x              y        lon        lat        t         z  \
2581892 -2.920099e+06 -104550.924791 -87.949464  63.588521  18262.0  0.104924

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2581892   1249  2020-01-01       cs2        1.0     400347.612758     0.053873
'local_data_select': 0.001 seconds
number obs: 803
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.049 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01016496, 10.01000424,  0.99733743])
kernel_variance: 0.008710235918391375
likelihood_variance: 0.01100000000000001
'predict': 0.048 seconds

2026-05-18 19:16:50.758165: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:16:50.759591: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.69 seconds
--------------------------------------------------
18 / 19
current local expert:
                    x              y        lon        lat        t         z  \
2581941 -2.896261e+06 -100913.582598 -88.004467  63.809174  18262.0  0.065372

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2581941   1249  2020-01-01       cs2        1.0     424977.104752     0.053873
'local_data_select': 0.001 seconds
number obs: 768
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.047 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01016499, 10.01000424,  0.99734489])
kernel_variance: 0.008744885962976302
likelihood_variance: 0.01100000000000001
'predict': 0.045 seconds

2026-05-18 19:16:51.448979: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:16:51.450390: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.68 seconds
--------------------------------------------------
19 / 19
current local expert:
                    x             y        lon       lat        t         z  \
2581996 -2.871566e+06 -97162.631585 -88.062073  64.03761  18262.0  0.217621

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2581996   1249  2020-01-01       cs2        1.0     450476.454177     0.053873
'local_data_select': 0.001 seconds
number obs: 711
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.046 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01016499, 10.01000424,  0.99735205])
kernel_variance: 0.008777895424029162
likelihood_variance: 0.01100000000000001
'predict': 0.045 seconds

2026-05-18 19:16:52.125196: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:16:52.126625: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.68 seconds
storing any remaining tables
SAVING RESULTS TO TABLES:
run_details
preds
'run': 13.246 seconds
reading in results
getting all tables
merging on expert location data
table: 'oi_config' does not have all coords_col: ['x', 'y', 't'] in columns, not merging on expert_locations
table: 'oi_config_SMOOTHED' does not have all coords_col: ['x', 'y', 't'] in columns, not merging on expert_locations
lin:
                    x              y        lon        lat        t         z  \
2580970 -3.305594e+06 -165626.421983 -87.131600  60.000733  18262.0 -0.015819
2580971 -3.305307e+06 -165579.299553 -87.132166  60.003420  18262.0  0.005921
2580972 -3.304732e+06 -165485.060709 -87.133298  60.008796  18262.0  0.060658
2580973 -3.304445e+06 -165438.012735 -87.133863  60.011483  18262.0  0.057024
2580974 -3.304158e+06 -165390.907296 -87.134429  60.014171  18262.0  0.061974

         track date_string satellite  lead_mask  dist_along_track  \
2580970   1249  2020-01-01       cs2        1.0          0.000000
2580971   1249  2020-01-01       cs2        1.0        299.761243
2580972   1249  2020-01-01       cs2        1.0        899.503613
2580973   1249  2020-01-01       cs2        1.0       1199.258256
2580974   1249  2020-01-01       cs2        1.0       1499.128776

         z_track_avg     f_lin
2580970     0.053873  0.057389
2580971     0.053873  0.057340
2580972     0.053873  0.057745
2580973     0.053873  0.057736
2580974     0.053873  0.058073
gpsat:
                    x              y        lon        lat        t         z  \
2580970 -3.305594e+06 -165626.421983 -87.131600  60.000733  18262.0 -0.015819
2580971 -3.305307e+06 -165579.299553 -87.132166  60.003420  18262.0  0.005921
2580972 -3.304732e+06 -165485.060709 -87.133298  60.008796  18262.0  0.060658
2580973 -3.304445e+06 -165438.012735 -87.133863  60.011483  18262.0  0.057024
2580974 -3.304158e+06 -165390.907296 -87.134429  60.014171  18262.0  0.061974

         track date_string satellite  lead_mask  dist_along_track  \
2580970   1249  2020-01-01       cs2        1.0          0.000000
2580971   1249  2020-01-01       cs2        1.0        299.761243
2580972   1249  2020-01-01       cs2        1.0        899.503613
2580973   1249  2020-01-01       cs2        1.0       1199.258256
2580974   1249  2020-01-01       cs2        1.0       1499.128776

         z_track_avg   f_gpsat  f_var_gpsat
2580970     0.053873  0.029284     0.000069
2580971     0.053873  0.029638     0.000066
2580972     0.053873  0.030352     0.000060
2580973     0.053873  0.030713     0.000057
2580974     0.053873  0.031076     0.000055
Test NaNs — Linear: 0, GPSat: 0
Track interpolated!
Interpolating track 1250, 8 of 15...

/tmp/ipykernel_1171781/839927469.py:200: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  track_df['f_gpsat'] = ssha
/tmp/ipykernel_1171781/839927469.py:201: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  track_df['f_var_gpsat'] = ssha_var

Expert limit reached.
'data_select': 0.000 seconds
'load': 0.000 seconds
in json_serializable - key: 'data_source' has value DataFrame/Series, but is too long: 1302 >  100
storing as str
in json_serializable - key: 'df' has value DataFrame/Series, but is too long: 6100 >  100
storing as str
---------
storing expert locations in 'expert_locs' table
exception occurred: 'No object named expert_locs in the file'
will now close object

---------
dropping expert locations that already exists in 'run_details' table
exception occurred: 'No object named run_details in the file'
will now close object

--------------------------------------------------
1 / 40
current local expert:
                    x             y        lon        lat        t         z  \
2582040 -2.303590e+06 -15607.065087 -89.611821  69.253436  18262.0  0.245868

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2582040   1250  2020-01-01       cs2        1.0       9006.719373     0.042968
'data_select': 0.000 seconds
'load': 0.000 seconds
'local_data_select': 0.001 seconds
number obs: 247
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.047 seconds
'get_parameters': 0.003 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.011 seconds

2026-05-18 19:16:53.723744: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:16:53.725161: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.518 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([18.76063738, 10.01195239,  0.89651488])
kernel_variance: 0.020087323200199857
likelihood_variance: 0.0026244913095817253
'predict': 0.031 seconds
total run time : 1.13 seconds
--------------------------------------------------
2 / 40
current local expert:
                    x             y        lon        lat        t         z  \
2582066 -2.287690e+06 -13452.684733 -89.663078  69.398439  18262.0  0.223485

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2582066   1250  2020-01-01       cs2        1.0      25219.055087     0.042968
'local_data_select': 0.001 seconds
number obs: 255
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.049 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:16:54.854788: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:16:54.856188: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.533 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([19.99999999, 10.02243826,  1.01679012])
kernel_variance: 0.0238422940115445
likelihood_variance: 0.0027268728314666308
'predict': 0.033 seconds
total run time : 1.15 seconds
--------------------------------------------------
3 / 40
current local expert:
                    x             y        lon        lat        t         z  \
2582117 -2.263536e+06 -10193.211545 -89.741986  69.618617  18262.0  0.312397

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2582117   1250  2020-01-01       cs2        1.0      49838.468592     0.042968
'local_data_select': 0.001 seconds
number obs: 263
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:16:56.010738: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:16:56.012149: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9
2026-05-18 19:16:56.348668: W tensorflow/core/kernels/linalg/cholesky_op_gpu.cu.cc:205] Cholesky decomposition was not successful for batch 0. The input might not be valid. Filling lower-triangular output with NaNs.
2026-05-18 19:16:56.353297: W tensorflow/core/kernels/linalg/cholesky_op_gpu.cu.cc:205] Cholesky decomposition was not successful for batch 0. The input might not be valid. Filling lower-triangular output with NaNs.

'optimise_parameters': 0.327 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([2.e+01, 2.e+01, 1.e-08])
kernel_variance: 453.6666404779808
likelihood_variance: 0.001
'predict': 0.031 seconds
total run time : 0.94 seconds
--------------------------------------------------
4 / 40
current local expert:
                    x            y        lon        lat        t         z  \
2582170 -2.238781e+06 -6869.170485 -89.824202  69.844149  18262.0  0.301739

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2582170   1250  2020-01-01       cs2        1.0      75059.129137     0.042968
'local_data_select': 0.001 seconds
number obs: 263
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.050 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:16:56.951281: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:16:56.952667: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9
2026-05-18 19:16:57.286111: W tensorflow/core/kernels/linalg/cholesky_op_gpu.cu.cc:205] Cholesky decomposition was not successful for batch 0. The input might not be valid. Filling lower-triangular output with NaNs.
2026-05-18 19:16:57.290520: W tensorflow/core/kernels/linalg/cholesky_op_gpu.cu.cc:205] Cholesky decomposition was not successful for batch 0. The input might not be valid. Filling lower-triangular output with NaNs.

'optimise_parameters': 0.324 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([2.e+01, 2.e+01, 1.e-08])
kernel_variance: 453.6666404779808
likelihood_variance: 0.001
'predict': 0.031 seconds
total run time : 0.95 seconds
--------------------------------------------------
5 / 40
current local expert:
                    x            y       lon       lat        t         z  \
2582204 -2.214899e+06 -3678.242835 -89.90485  70.06161  18262.0  0.255932

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2582204   1250  2020-01-01       cs2        1.0      99379.788248     0.042968
'local_data_select': 0.001 seconds
number obs: 263
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.047 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:16:57.897691: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:16:57.899092: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9
2026-05-18 19:16:58.233115: W tensorflow/core/kernels/linalg/cholesky_op_gpu.cu.cc:205] Cholesky decomposition was not successful for batch 0. The input might not be valid. Filling lower-triangular output with NaNs.
2026-05-18 19:16:58.237529: W tensorflow/core/kernels/linalg/cholesky_op_gpu.cu.cc:205] Cholesky decomposition was not successful for batch 0. The input might not be valid. Filling lower-triangular output with NaNs.

'optimise_parameters': 0.324 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([2.e+01, 2.e+01, 1.e-08])
kernel_variance: 453.6666404779808
likelihood_variance: 0.001
'predict': 0.031 seconds
total run time : 0.94 seconds
--------------------------------------------------
6 / 40
current local expert:
                    x           y        lon        lat        t         z  \
2582269 -2.184809e+06  319.852087 -90.008388  70.335423  18262.0  0.197716

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2582269   1250  2020-01-01       cs2        1.0      130006.52959     0.042968
'local_data_select': 0.001 seconds
number obs: 263
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.046 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:16:58.834354: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:16:58.835776: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9
2026-05-18 19:16:59.173109: W tensorflow/core/kernels/linalg/cholesky_op_gpu.cu.cc:205] Cholesky decomposition was not successful for batch 0. The input might not be valid. Filling lower-triangular output with NaNs.
2026-05-18 19:16:59.177592: W tensorflow/core/kernels/linalg/cholesky_op_gpu.cu.cc:205] Cholesky decomposition was not successful for batch 0. The input might not be valid. Filling lower-triangular output with NaNs.

'optimise_parameters': 0.328 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([2.e+01, 2.e+01, 1.e-08])
kernel_variance: 453.6666404779808
likelihood_variance: 0.001
'predict': 0.031 seconds
total run time : 0.95 seconds
--------------------------------------------------
7 / 40
current local expert:
                    x           y        lon        lat        t         z  \
2582315 -2.165034e+06  2933.82019 -90.077641  70.515265  18262.0  0.141018

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2582315   1250  2020-01-01       cs2        1.0     150124.690784     0.042968
'local_data_select': 0.001 seconds
number obs: 264
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.049 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:16:59.788164: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:16:59.790464: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.446 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.00392053, 10.00985815,  1.10025386])
kernel_variance: 0.009097141073233091
likelihood_variance: 0.002726374795186193
'predict': 0.031 seconds
total run time : 1.07 seconds
--------------------------------------------------
8 / 40
current local expert:
                    x            y        lon       lat        t         z  \
2582358 -2.145547e+06  5499.309098 -90.146856  70.69241  18262.0  0.154421

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2582358   1250  2020-01-01       cs2        1.0     169943.028315     0.042968
'local_data_select': 0.001 seconds
number obs: 284
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.049 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:17:00.859360: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:17:00.861317: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.411 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.0101803 , 10.010003  ,  0.99955922])
kernel_variance: 0.009087199887589343
likelihood_variance: 0.0029898286962325086
'predict': 0.031 seconds
total run time : 1.03 seconds
--------------------------------------------------
9 / 40
current local expert:
                    x             y        lon        lat        t         z  \
2582433 -2.110985e+06  10024.088736 -90.272069  71.006406  18262.0  0.007343

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2582433   1250  2020-01-01       cs2        1.0     205076.511757     0.042968
'local_data_select': 0.001 seconds
number obs: 304
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.049 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:17:01.889807: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:17:01.891305: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'optimise_parameters': 0.556 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([16.67699294, 10.01138733,  1.07328704])
kernel_variance: 0.015507055507487417
likelihood_variance: 0.002970351200387917
'predict': 0.034 seconds
total run time : 1.19 seconds
--------------------------------------------------
10 / 40
current local expert:
                    x             y        lon        lat        t         z  \
2582493 -2.083497e+06  13599.593065 -90.373981  71.255962  18262.0 -0.044523

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2582493   1250  2020-01-01       cs2        1.0     233004.224899     0.042968
'local_data_select': 0.001 seconds
number obs: 315
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:17:03.079684: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:17:03.081717: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.597 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([16.65285134, 10.01135992,  0.86089537])
kernel_variance: 0.015161838362810084
likelihood_variance: 0.0029324093634127777
'predict': 0.035 seconds
SAVING RESULTS TO TABLES:
run_details
preds
lengthscales
kernel_variance
likelihood_variance
total run time : 1.36 seconds
--------------------------------------------------
11 / 40
current local expert:
                    x             y        lon       lat        t         z  \
2582527 -2.067825e+06  15628.828287 -90.433039  71.39817  18262.0  0.036883

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2582527   1250  2020-01-01       cs2        1.0     248920.521659     0.042968
'local_data_select': 0.001 seconds
number obs: 315
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.050 seconds
'set_lengthscales_constraints': 0.006 seconds

2026-05-18 19:17:04.448268: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:17:04.449693: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'set_likelihood_variance_constraints': 0.011 seconds
**********
optimization failed!
'optimise_parameters': 0.603 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([16.65285134, 10.01135992,  0.86089537])
kernel_variance: 0.015161838362810084
likelihood_variance: 0.0029324093634127777
'predict': 0.033 seconds
total run time : 1.24 seconds
--------------------------------------------------
12 / 40
current local expert:
                    x             y        lon        lat        t        z  \
2582574 -2.038835e+06  19364.965335 -90.544182  71.661092  18262.0 -0.01815

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2582574   1250  2020-01-01       cs2        1.0     278351.152078     0.042968
'local_data_select': 0.001 seconds
number obs: 315
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.050 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:17:05.692049: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:17:05.693477: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.596 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([16.65285134, 10.01135992,  0.86089537])
kernel_variance: 0.015161838362810084
likelihood_variance: 0.0029324093634127777
'predict': 0.033 seconds
total run time : 1.24 seconds
--------------------------------------------------
13 / 40
current local expert:
                    x             y        lon        lat        t         z  \
2582607 -2.017527e+06  22096.577718 -90.627496  71.854237  18262.0 -0.000557

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2582607   1250  2020-01-01       cs2        1.0     299974.333951     0.042968
'local_data_select': 0.001 seconds
number obs: 315
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.049 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:17:06.928851: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:17:06.930268: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.598 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([16.65285134, 10.01135992,  0.86089537])
kernel_variance: 0.015161838362810084
likelihood_variance: 0.0029324093634127777
'predict': 0.035 seconds
total run time : 1.22 seconds
--------------------------------------------------
14 / 40
current local expert:
                    x             y        lon        lat        t         z  \
2582664 -1.989695e+06  25645.865119 -90.738464  72.106367  18262.0 -0.015638

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2582664   1250  2020-01-01       cs2        1.0     328205.271079     0.042968
'local_data_select': 0.001 seconds
number obs: 318
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.049 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:17:08.154144: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:17:08.155554: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'optimise_parameters': 0.390 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.0101632 , 10.01000274,  1.00046124])
kernel_variance: 0.009099388761673531
likelihood_variance: 0.003043280646528791
'predict': 0.032 seconds
total run time : 1.03 seconds
--------------------------------------------------
15 / 40
current local expert:
                    x             y        lon        lat        t         z  \
2582704 -1.966887e+06  28538.900365 -90.831285  72.312872  18262.0  0.046016

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2582704   1250  2020-01-01       cs2        1.0     351331.267554     0.042968
'local_data_select': 0.001 seconds
number obs: 320
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.049 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:17:09.186002: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:17:09.187429: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.613 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([16.6652362 , 10.01137774,  0.66364718])
kernel_variance: 0.013490111837093572
likelihood_variance: 0.0030918852962014912
'predict': 0.034 seconds
total run time : 1.26 seconds
--------------------------------------------------
16 / 40
current local expert:
                    x             y        lon        lat        t         z  \
2582755 -1.943477e+06  31493.641323 -90.928385  72.524715  18262.0  0.039057

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2582755   1250  2020-01-01       cs2        1.0     375058.638236     0.042968
'local_data_select': 0.001 seconds
number obs: 333
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.047 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:17:10.442765: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:17:10.444175: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'optimise_parameters': 0.332 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01014683, 10.01000245,  0.99913541])
kernel_variance: 0.011036183317272717
likelihood_variance: 0.003065885054919944
'predict': 0.035 seconds
total run time : 0.97 seconds
--------------------------------------------------
17 / 40
current local expert:
                    x             y        lon        lat        t         z  \
2582802 -1.918575e+06  34620.442174 -91.033783  72.749933  18262.0 -0.019392

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2582802   1250  2020-01-01       cs2        1.0     400288.212509     0.042968
'local_data_select': 0.001 seconds
number obs: 339
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.046 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:17:11.409735: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:17:11.411152: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.447 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01006709, 10.0100013 ,  1.00013631])
kernel_variance: 0.08992655481650884
likelihood_variance: 0.002998591779635143
'predict': 0.034 seconds
total run time : 1.08 seconds
--------------------------------------------------
18 / 40
current local expert:
                    x             y        lon        lat        t         z  \
2582853 -1.895442e+06  37510.078111 -91.133714  72.959036  18262.0 -0.022161

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2582853   1250  2020-01-01       cs2        1.0     423716.504956     0.042968
'local_data_select': 0.001 seconds
number obs: 321
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.050 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:17:12.496173: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:17:12.497595: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.684 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.00009561, 10.00968781,  0.99841704])
kernel_variance: 0.0939159626520592
likelihood_variance: 0.0030031117763104705
'predict': 0.035 seconds
total run time : 1.32 seconds
--------------------------------------------------
19 / 40
current local expert:
                    x             y        lon        lat        t         z  \
2582877 -1.884762e+06  38839.284809 -91.180527  73.055534  18262.0 -0.035051

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2582877   1250  2020-01-01       cs2        1.0     434529.658946     0.042968
'local_data_select': 0.001 seconds
number obs: 310
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.051 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:17:13.816430: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:17:13.818544: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.491 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01005084, 10.01000107,  0.99955483])
kernel_variance: 0.09491145380819488
likelihood_variance: 0.003064881827736932
'predict': 0.033 seconds
total run time : 1.14 seconds
--------------------------------------------------
20 / 40
current local expert:
                    x             y        lon        lat        t         z  \
2582907 -1.768387e+06  53123.685107 -91.720691  74.105481  18262.0  0.008416

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2582907   1250  2020-01-01       cs2        1.0     552241.428125     0.042968
'local_data_select': 0.001 seconds
number obs: 224
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.050 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:17:14.959373: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:17:14.960790: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.337 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.0100086 , 10.01000042,  1.00163948])
kernel_variance: 0.14152308151888637
likelihood_variance: 0.0027851210849213527
'predict': 0.031 seconds
SAVING RESULTS TO TABLES:
run_details
preds
lengthscales
kernel_variance
likelihood_variance
total run time : 1.13 seconds
--------------------------------------------------
21 / 40
current local expert:
                    x             y        lon        lat        t        z  \
2582953 -1.741331e+06  56392.502415 -91.854859  74.349169  18262.0 -0.00231

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2582953   1250  2020-01-01       cs2        1.0     579578.775028     0.042968
'local_data_select': 0.001 seconds
number obs: 223
found GPU
setting lengthscales to: [1. 1. 1.]

2026-05-18 19:17:16.092809: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:17:16.094325: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'__init__': 0.050 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds
**********
optimization failed!
'optimise_parameters': 0.396 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.00014624, 10.0095911 ,  0.77972787])
kernel_variance: 0.18913112048444056
likelihood_variance: 0.002899695460756538
'predict': 0.031 seconds
total run time : 1.05 seconds
--------------------------------------------------
22 / 40
current local expert:
                    x             y        lon        lat        t         z  \
2582997 -1.721106e+06  58823.196441 -91.957468  74.531229  18262.0  0.002187

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2582997   1250  2020-01-01       cs2        1.0      600007.17159     0.042968
'local_data_select': 0.001 seconds
number obs: 217
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.046 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:17:17.137230: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:17:17.138665: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'optimise_parameters': 0.327 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01000831, 10.01000037,  1.00068507])
kernel_variance: 0.23587414150258698
likelihood_variance: 0.002812910650688581
'predict': 0.031 seconds
total run time : 0.97 seconds
--------------------------------------------------
23 / 40
current local expert:
                    x             y        lon      lat        t        z  \
2583049 -1.697601e+06  61634.268678 -92.079307  74.7427  18262.0 -0.09409

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2583049   1250  2020-01-01       cs2        1.0     623740.825884     0.042968
'local_data_select': 0.001 seconds
number obs: 212
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.046 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:17:18.104536: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:17:18.105941: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.351 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.00999174, 10.0100002 ,  1.00046232])
kernel_variance: 0.23291993307959036
likelihood_variance: 0.0028931136815441615
'predict': 0.031 seconds
total run time : 0.99 seconds
--------------------------------------------------
24 / 40
current local expert:
                    x             y        lon        lat        t         z  \
2583078 -1.604409e+06  72633.911016 -92.592093  75.579912  18262.0  0.131785

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2583078   1250  2020-01-01       cs2        1.0     717761.240199     0.042968
'local_data_select': 0.001 seconds
number obs: 176
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.045 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:17:19.093102: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:17:19.094507: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.413 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.0001525 , 10.00951844,  1.01377075])
kernel_variance: 0.20064656179977097
likelihood_variance: 0.0033423573441135903
'predict': 0.032 seconds
total run time : 1.05 seconds
--------------------------------------------------
25 / 40
current local expert:
                    x             y        lon        lat        t         z  \
2583086 -1.597554e+06  73433.765812 -92.631826  75.641412  18262.0 -0.157771

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2583086   1250  2020-01-01       cs2        1.0      724671.81688     0.042968
'local_data_select': 0.001 seconds
number obs: 177
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:17:20.148591: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:17:20.150003: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'optimise_parameters': 0.259 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.00999859, 10.0100001 ,  0.99942197])
kernel_variance: 0.2175426646668449
likelihood_variance: 0.0033011313900596657
'predict': 0.031 seconds
total run time : 0.90 seconds
--------------------------------------------------
26 / 40
current local expert:
                    x             y        lon        lat        t         z  \
2583098 -1.569832e+06  76656.010383 -92.795573  75.890034  18262.0  0.051145

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2583098   1250  2020-01-01       cs2        1.0     752614.839582     0.042968
'local_data_select': 0.001 seconds
number obs: 163
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.046 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:17:21.050039: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:17:21.051437: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.382 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.0099758 , 10.00999979,  1.00052116])
kernel_variance: 0.2208900186646119
likelihood_variance: 0.0033602717175496184
'predict': 0.031 seconds
total run time : 1.02 seconds
--------------------------------------------------
27 / 40
current local expert:
                    x             y        lon        lat        t         z  \
2583115 -1.551344e+06  78793.495687 -92.907581  76.055737  18262.0  0.124533

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2583115   1250  2020-01-01       cs2        1.0     771244.068722     0.042968
'local_data_select': 0.001 seconds
number obs: 146
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.046 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.011 seconds

2026-05-18 19:17:22.074292: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:17:22.075693: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.357 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.00998085, 10.00999982,  1.00035441])
kernel_variance: 0.2193542901022262
likelihood_variance: 0.00367245564431691
'predict': 0.031 seconds
total run time : 1.01 seconds
--------------------------------------------------
28 / 40
current local expert:
                    x             y        lon        lat        t         z  \
2583145 -1.529570e+06  81299.212044 -93.042503  76.250785  18262.0 -0.317086

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2583145   1250  2020-01-01       cs2        1.0     793178.435864     0.042968
'local_data_select': 0.001 seconds
number obs: 125
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.050 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:17:23.087273: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:17:23.088702: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.278 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.0099394 , 10.00999924,  1.0004316 ])
kernel_variance: 0.23000410364646964
likelihood_variance: 0.003992677148666944
'predict': 0.030 seconds
total run time : 0.93 seconds
--------------------------------------------------
29 / 40
current local expert:
                    x             y       lon        lat        t         z  \
2583152 -1.454677e+06  89821.501533 -93.53334  76.920785  18262.0 -0.127779

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2583152   1250  2020-01-01       cs2        1.0     868577.668649     0.042968
'local_data_select': 0.001 seconds
number obs: 128
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.049 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:17:24.013715: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:17:24.015121: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'optimise_parameters': 0.312 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.00998435, 10.00999977,  0.99984786])
kernel_variance: 0.26737110712529283
likelihood_variance: 0.0033074450735556464
'predict': 0.030 seconds
total run time : 0.97 seconds
--------------------------------------------------
30 / 40
current local expert:
                    x             y        lon        lat        t         z  \
2583167 -1.448405e+06  90528.356004 -93.576454  76.976826  18262.0 -0.084863

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2583167   1250  2020-01-01       cs2        1.0     874888.340171     0.042968
'local_data_select': 0.001 seconds
number obs: 136
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.047 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:17:24.985026: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:17:24.986424: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.291 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.00997388, 10.00999961,  0.99956931])
kernel_variance: 0.26045886985902
likelihood_variance: 0.003199079407564853
'predict': 0.030 seconds
SAVING RESULTS TO TABLES:
run_details
preds
lengthscales
kernel_variance
likelihood_variance
total run time : 1.10 seconds
--------------------------------------------------
31 / 40
current local expert:
                    x             y        lon        lat        t         z  \
2583198 -1.434367e+06  92106.828882 -93.674162  77.102229  18262.0  0.039143

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2583198   1250  2020-01-01       cs2        1.0     889012.158647     0.042968
'local_data_select': 0.001 seconds
number obs: 142
found GPU
setting lengthscales to: [1. 1. 1.]

2026-05-18 19:17:26.090299: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:17:26.091711: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'__init__': 0.047 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds
**********
optimization failed!
'optimise_parameters': 0.295 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.00997965, 10.00999966,  0.99935265])
kernel_variance: 0.24481596986917267
likelihood_variance: 0.00317696932226261
'predict': 0.031 seconds
total run time : 0.95 seconds
--------------------------------------------------
32 / 40
current local expert:
                    x              y        lon        lat        t         z  \
2583261 -1.356967e+06  100715.814159 -94.244781  77.792689  18262.0 -0.189187

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2583261   1250  2020-01-01       cs2        1.0      966841.04121     0.042968
'local_data_select': 0.001 seconds
number obs: 171
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.047 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:17:27.041264: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:17:27.042689: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.305 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.0099588 , 10.0099992 ,  1.00005654])
kernel_variance: 0.5541191207658178
likelihood_variance: 0.0010003201007451584
'predict': 0.031 seconds
total run time : 0.97 seconds
--------------------------------------------------
33 / 40
current local expert:
                    x              y        lon        lat        t         z  \
2583265 -1.348295e+06  101670.454561 -94.312322  77.869945  18262.0 -0.036608

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2583265   1250  2020-01-01       cs2        1.0      975556.63005     0.042968
'local_data_select': 0.001 seconds
number obs: 174
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.051 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:17:28.013687: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:17:28.015100: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.342 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.00993404, 10.00999889,  1.00049305])
kernel_variance: 0.6160855656124745
likelihood_variance: 0.0010006312996112933
'predict': 0.031 seconds
total run time : 1.00 seconds
--------------------------------------------------
34 / 40
current local expert:
                    x              y        lon        lat        t         z  \
2583304 -1.322274e+06  104523.042612 -94.519714  78.101628  18262.0 -0.177487

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2583304   1250  2020-01-01       cs2        1.0      1.001703e+06     0.042968
'local_data_select': 0.001 seconds
number obs: 166
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:17:29.011668: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:17:29.013092: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.308 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.00998594, 10.00999962,  1.00032709])
kernel_variance: 0.24813137253010997
likelihood_variance: 0.0025450115675698017
'predict': 0.031 seconds
total run time : 0.97 seconds
--------------------------------------------------
35 / 40
current local expert:
                    x              y        lon       lat        t         z  \
2583336 -1.274101e+06  109756.783658 -94.923561  78.53001  18262.0 -0.001464

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2583336   1250  2020-01-01       cs2        1.0      1.050089e+06     0.042968
'local_data_select': 0.001 seconds
number obs: 164
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.047 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:17:29.980147: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:17:29.981719: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.343 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.00997542, 10.00999938,  0.99987918])
kernel_variance: 0.2465994924296568
likelihood_variance: 0.0026752045343984856
'predict': 0.031 seconds
total run time : 1.01 seconds
--------------------------------------------------
36 / 40
current local expert:
                    x              y        lon        lat        t         z  \
2583393 -1.242367e+06  113170.901613 -95.204877  78.811802  18262.0  0.028185

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2583393   1250  2020-01-01       cs2        1.0      1.081948e+06     0.042968
'local_data_select': 0.001 seconds
number obs: 169
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.050 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:17:30.993849: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:17:30.995340: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.313 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.00998025, 10.0099994 ,  1.00016823])
kernel_variance: 0.21337021927934885
likelihood_variance: 0.0026859069164405893
'predict': 0.031 seconds
total run time : 0.97 seconds
--------------------------------------------------
37 / 40
current local expert:
                    x              y        lon       lat        t         z  \
2583416 -1.221704e+06  115379.682913 -95.395103  78.99511  18262.0  0.074314

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2583416   1250  2020-01-01       cs2        1.0      1.102687e+06     0.042968
'local_data_select': 0.001 seconds
number obs: 172
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.047 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:17:31.960635: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:17:31.962033: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.319 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.00997376, 10.00999926,  0.9998891 ])
kernel_variance: 0.20380557743201821
likelihood_variance: 0.002659707225482947
'predict': 0.031 seconds
total run time : 0.97 seconds
--------------------------------------------------
38 / 40
current local expert:
                    x              y        lon        lat        t         z  \
2583463 -1.196242e+06  118085.874167 -95.637631  79.220784  18262.0 -0.036422

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2583463   1250  2020-01-01       cs2        1.0      1.128236e+06     0.042968
'local_data_select': 0.001 seconds
number obs: 182
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.049 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:17:32.938582: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:17:32.939998: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.372 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.00003407, 10.00899252,  1.0036956 ])
kernel_variance: 0.14444679947829453
likelihood_variance: 0.002782373695415118
'predict': 0.031 seconds
total run time : 1.03 seconds
--------------------------------------------------
39 / 40
current local expert:
                    x              y        lon        lat        t         z  \
2583549 -1.082637e+06  129952.006809 -96.844627  80.224732  18262.0  0.034469

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2583549   1250  2020-01-01       cs2        1.0      1.242147e+06     0.042968
'local_data_select': 0.001 seconds
number obs: 191
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:17:33.968524: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:17:33.969936: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'optimise_parameters': 0.389 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.0000612 , 10.00938183,  0.94548977])
kernel_variance: 0.0040241760053691565
likelihood_variance: 0.0036779219478702274
'predict': 0.031 seconds
total run time : 1.06 seconds
--------------------------------------------------
40 / 40
current local expert:
                    x              y        lon        lat        t         z  \
2583566 -1.073338e+06  130908.276408 -96.953663  80.306678  18262.0  0.044315

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2583566   1250  2020-01-01       cs2        1.0      1.251466e+06     0.042968
'local_data_select': 0.001 seconds
number obs: 194
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.049 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:17:35.031655: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:17:35.033053: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.517 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.00000003, 10.0085819 ,  0.99805508])
kernel_variance: 0.004613740685485658
likelihood_variance: 0.0045418866045935915
'predict': 0.032 seconds
SAVING RESULTS TO TABLES:
run_details
preds
lengthscales
kernel_variance
likelihood_variance
total run time : 1.37 seconds
'run': 42.744 seconds
reading in results
getting all tables
merging on expert location data
table: 'oi_config' does not have all coords_col: ['x', 'y', 't'] in columns, not merging on expert_locations
h5 tables: ['expert_locs', 'kernel_variance', 'lengthscales', 'likelihood_variance', 'oi_config', 'preds', 'run_details']
found model_name: GPflowGPRModel
found GPU
setting lengthscales to: [1.]
'__init__': 0.053 seconds
reading in results
selecting only tables: ['lengthscales', 'kernel_variance', 'likelihood_variance']
'data_select': 0.000 seconds
'load': 0.000 seconds
expert_locations data will not be merged on results data
adding smoothed table: lengthscales_SMOOTHED
adding smoothed table: kernel_variance_SMOOTHED
adding smoothed table: likelihood_variance_SMOOTHED
writing (smoothed) hyper parameters to:
/home/mhen/geol0069_data/gpsat/jan20/1250.h5
table_suffix:_SMOOTHED
writing: lengthscales_SMOOTHED to table
writing: kernel_variance_SMOOTHED to table
writing: likelihood_variance_SMOOTHED to table

2026-05-18 19:17:36.568740: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:17:36.570155: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'data_select': 0.000 seconds
'load': 0.000 seconds
in json_serializable - key: 'data_source' has value DataFrame/Series, but is too long: 1302 >  100
storing as str
in json_serializable - key: 'df' has value DataFrame/Series, but is too long: 6100 >  100
storing as str
---------
storing expert locations in 'expert_locs' table
exception occurred: 'No object named expert_locs_SMOOTHED in the file'
will now close object

---------
dropping expert locations that already exists in 'run_details' table
exception occurred: 'No object named run_details_SMOOTHED in the file'
will now close object

--------------------------------------------------
1 / 40
current local expert:
                    x             y        lon        lat        t         z  \
2582040 -2.303590e+06 -15607.065087 -89.611821  69.253436  18262.0  0.245868

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2582040   1250  2020-01-01       cs2        1.0       9006.719373     0.042968
'data_select': 0.000 seconds
'load': 0.000 seconds
'local_data_select': 0.001 seconds
number obs: 247
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'get_parameters': 0.003 seconds
'_read_params_from_file': 0.048 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds

2026-05-18 19:17:36.834822: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:17:36.836230: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([11.54792282, 10.68980326,  0.6316845 ])
kernel_variance: 0.04754279884441281
likelihood_variance: 0.01100000000000001
'predict': 0.032 seconds
total run time : 0.72 seconds
--------------------------------------------------
2 / 40
current local expert:
                    x             y        lon        lat        t         z  \
2582066 -2.287690e+06 -13452.684733 -89.663078  69.398439  18262.0  0.223485

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2582066   1250  2020-01-01       cs2        1.0      25219.055087     0.042968
'local_data_select': 0.001 seconds
number obs: 255
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.050 seconds
'_read_params_from_file': 0.045 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([11.53008896, 10.67155649,  0.63969418])
kernel_variance: 0.04709077138003848
likelihood_variance: 0.01100000000000001
'predict': 0.031 seconds

2026-05-18 19:17:37.554844: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:17:37.556254: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.73 seconds
--------------------------------------------------
3 / 40
current local expert:
                    x             y        lon        lat        t         z  \
2582117 -2.263536e+06 -10193.211545 -89.741986  69.618617  18262.0  0.312397

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2582117   1250  2020-01-01       cs2        1.0      49838.468592     0.042968
'local_data_select': 0.001 seconds
number obs: 263
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.050 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([11.50141955, 10.64215421,  0.65258881])
kernel_variance: 0.046424079235977876
likelihood_variance: 0.01100000000000001
'predict': 0.032 seconds

2026-05-18 19:17:38.282950: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:17:38.284391: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.72 seconds
--------------------------------------------------
4 / 40
current local expert:
                    x            y        lon        lat        t         z  \
2582170 -2.238781e+06 -6869.170485 -89.824202  69.844149  18262.0  0.301739

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2582170   1250  2020-01-01       cs2        1.0      75059.129137     0.042968
'local_data_select': 0.001 seconds
number obs: 263
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([11.46989004, 10.61008019,  0.66664884])
kernel_variance: 0.04578711600819154
likelihood_variance: 0.01100000000000001
'predict': 0.032 seconds

2026-05-18 19:17:38.998809: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:17:39.000232: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.71 seconds
--------------------------------------------------
5 / 40
current local expert:
                    x            y       lon       lat        t         z  \
2582204 -2.214899e+06 -3678.242835 -89.90485  70.06161  18262.0  0.255932

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2582204   1250  2020-01-01       cs2        1.0      99379.788248     0.042968
'local_data_select': 0.001 seconds
number obs: 263
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([11.43721714, 10.57749281,  0.68093934])
kernel_variance: 0.045242586080030324
likelihood_variance: 0.01100000000000001
'predict': 0.032 seconds

2026-05-18 19:17:39.714270: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:17:39.716445: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.72 seconds
--------------------------------------------------
6 / 40
current local expert:
                    x           y        lon        lat        t         z  \
2582269 -2.184809e+06  319.852087 -90.008388  70.335423  18262.0  0.197716

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2582269   1250  2020-01-01       cs2        1.0      130006.52959     0.042968
'local_data_select': 0.001 seconds
number obs: 263
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.049 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([11.39259318, 10.5345287 ,  0.69980954])
kernel_variance: 0.04469712318299057
likelihood_variance: 0.01100000000000001
'predict': 0.032 seconds

2026-05-18 19:17:40.440842: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:17:40.442248: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.71 seconds
--------------------------------------------------
7 / 40
current local expert:
                    x           y        lon        lat        t         z  \
2582315 -2.165034e+06  2933.82019 -90.077641  70.515265  18262.0  0.141018

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2582315   1250  2020-01-01       cs2        1.0     150124.690784     0.042968
'local_data_select': 0.001 seconds
number obs: 264
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.004 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([11.36099139, 10.50538963,  0.71264024])
kernel_variance: 0.04445024373676565
likelihood_variance: 0.01100000000000001
'predict': 0.031 seconds

2026-05-18 19:17:41.151497: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:17:41.152931: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.71 seconds
--------------------------------------------------
8 / 40
current local expert:
                    x            y        lon       lat        t         z  \
2582358 -2.145547e+06  5499.309098 -90.146856  70.69241  18262.0  0.154421

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2582358   1250  2020-01-01       cs2        1.0     169943.028315     0.042968
'local_data_select': 0.001 seconds
number obs: 284
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.046 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([11.32795862, 10.47617691,  0.72554151])
kernel_variance: 0.04431366011361974
likelihood_variance: 0.01100000000000001
'predict': 0.032 seconds

2026-05-18 19:17:41.859248: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:17:41.861225: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.71 seconds
--------------------------------------------------
9 / 40
current local expert:
                    x             y        lon        lat        t         z  \
2582433 -2.110985e+06  10024.088736 -90.272069  71.006406  18262.0  0.007343

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2582433   1250  2020-01-01       cs2        1.0     205076.511757     0.042968
'local_data_select': 0.001 seconds
number obs: 304
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.045 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([11.26445364, 10.42371862,  0.74884225])
kernel_variance: 0.04438573031052833
likelihood_variance: 0.01100000000000001
'predict': 0.032 seconds

2026-05-18 19:17:42.568256: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:17:42.569672: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.72 seconds
--------------------------------------------------
10 / 40
current local expert:
                    x             y        lon        lat        t         z  \
2582493 -2.083497e+06  13599.593065 -90.373981  71.255962  18262.0 -0.044523

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2582493   1250  2020-01-01       cs2        1.0     233004.224899     0.042968
'local_data_select': 0.001 seconds
number obs: 315
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.045 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([11.20919936, 10.38200628,  0.76753898])
kernel_variance: 0.04478397468318661
likelihood_variance: 0.01100000000000001
'predict': 0.034 seconds

2026-05-18 19:17:43.292303: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:17:43.293838: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

SAVING RESULTS TO TABLES:
run_details
preds
total run time : 0.78 seconds
--------------------------------------------------
11 / 40
current local expert:
                    x             y        lon       lat        t         z  \
2582527 -2.067825e+06  15628.828287 -90.433039  71.39817  18262.0  0.036883

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2582527   1250  2020-01-01       cs2        1.0     248920.521659     0.042968
'local_data_select': 0.001 seconds
number obs: 315
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.050 seconds
'_read_params_from_file': 0.050 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters

2026-05-18 19:17:44.078060: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:17:44.079475: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'get_parameters': 0.003 seconds
parameters:
lengthscales: array([11.17574327, 10.35845912,  0.77818142])
kernel_variance: 0.045165780291012314
likelihood_variance: 0.01100000000000001
'predict': 0.034 seconds
total run time : 0.73 seconds
--------------------------------------------------
12 / 40
current local expert:
                    x             y        lon        lat        t        z  \
2582574 -2.038835e+06  19364.965335 -90.544182  71.661092  18262.0 -0.01815

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2582574   1250  2020-01-01       cs2        1.0     278351.152078     0.042968
'local_data_select': 0.001 seconds
number obs: 315
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.052 seconds
'_read_params_from_file': 0.045 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([11.11005724, 10.31575434,  0.79769263])
kernel_variance: 0.04619963391524739
likelihood_variance: 0.01100000000000001
'predict': 0.033 seconds

2026-05-18 19:17:44.808335: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:17:44.809748: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.72 seconds
--------------------------------------------------
13 / 40
current local expert:
                    x             y        lon        lat        t         z  \
2582607 -2.017527e+06  22096.577718 -90.627496  71.854237  18262.0 -0.000557

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2582607   1250  2020-01-01       cs2        1.0     299974.333951     0.042968
'local_data_select': 0.001 seconds
number obs: 315
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.053 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([11.05864973, 10.28536643,  0.81178613])
kernel_variance: 0.0472508088390232
likelihood_variance: 0.01100000000000001
'predict': 0.033 seconds

2026-05-18 19:17:45.536331: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:17:45.537762: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.72 seconds
--------------------------------------------------
14 / 40
current local expert:
                    x             y        lon        lat        t         z  \
2582664 -1.989695e+06  25645.865119 -90.738464  72.106367  18262.0 -0.015638

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2582664   1250  2020-01-01       cs2        1.0     328205.271079     0.042968
'local_data_select': 0.001 seconds
number obs: 318
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.050 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.98766541, 10.24737368,  0.82973297])
kernel_variance: 0.04901791260415183
likelihood_variance: 0.01100000000000001
'predict': 0.033 seconds

2026-05-18 19:17:46.255766: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:17:46.257185: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.73 seconds
--------------------------------------------------
15 / 40
current local expert:
                    x             y        lon        lat        t         z  \
2582704 -1.966887e+06  28538.900365 -90.831285  72.312872  18262.0  0.046016

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2582704   1250  2020-01-01       cs2        1.0     351331.267554     0.042968
'local_data_select': 0.001 seconds
number obs: 320
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.050 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.92648982, 10.21796757,  0.84394968])
kernel_variance: 0.05080779190306912
likelihood_variance: 0.01100000000000001
'predict': 0.033 seconds

2026-05-18 19:17:46.983517: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:17:46.984931: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.72 seconds
--------------------------------------------------
16 / 40
current local expert:
                    x             y        lon        lat        t         z  \
2582755 -1.943477e+06  31493.641323 -90.928385  72.524715  18262.0  0.039057

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2582755   1250  2020-01-01       cs2        1.0     375058.638236     0.042968
'local_data_select': 0.001 seconds
number obs: 333
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.050 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.86125065, 10.18965562,  0.85799481])
kernel_variance: 0.05296364212370872
likelihood_variance: 0.01100000000000001
'predict': 0.033 seconds

2026-05-18 19:17:47.702761: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:17:47.704181: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.72 seconds
--------------------------------------------------
17 / 40
current local expert:
                    x             y        lon        lat        t         z  \
2582802 -1.918575e+06  34620.442174 -91.033783  72.749933  18262.0 -0.019392

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2582802   1250  2020-01-01       cs2        1.0     400288.212509     0.042968
'local_data_select': 0.001 seconds
number obs: 339
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.051 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.78968316, 10.16183976,  0.87224765])
kernel_variance: 0.05559677819581811
likelihood_variance: 0.01100000000000001
'predict': 0.034 seconds

2026-05-18 19:17:48.421269: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:17:48.422672: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.72 seconds
--------------------------------------------------
18 / 40
current local expert:
                    x             y        lon        lat        t         z  \
2582853 -1.895442e+06  37510.078111 -91.133714  72.959036  18262.0 -0.022161

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2582853   1250  2020-01-01       cs2        1.0     423716.504956     0.042968
'local_data_select': 0.001 seconds
number obs: 321
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.052 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.72185825, 10.13828263,  0.88479172])
kernel_variance: 0.0583303698516033
likelihood_variance: 0.01100000000000001
'predict': 0.033 seconds

2026-05-18 19:17:49.144872: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:17:49.146306: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.72 seconds
--------------------------------------------------
19 / 40
current local expert:
                    x             y        lon        lat        t         z  \
2582877 -1.884762e+06  38839.284809 -91.180527  73.055534  18262.0 -0.035051

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2582877   1250  2020-01-01       cs2        1.0     434529.658946     0.042968
'local_data_select': 0.001 seconds
number obs: 310
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.055 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.69032125, 10.12817921,  0.89034308])
kernel_variance: 0.0596755675182528
likelihood_variance: 0.01100000000000001
'predict': 0.033 seconds

2026-05-18 19:17:49.866002: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:17:49.867440: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.73 seconds
--------------------------------------------------
20 / 40
current local expert:
                    x             y        lon        lat        t         z  \
2582907 -1.768387e+06  53123.685107 -91.720691  74.105481  18262.0  0.008416

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2582907   1250  2020-01-01       cs2        1.0     552241.428125     0.042968
'local_data_select': 0.001 seconds
number obs: 224
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.36465607, 10.04995267,  0.94024142])
kernel_variance: 0.07603926895235025
likelihood_variance: 0.01100000000000001
'predict': 0.031 seconds

2026-05-18 19:17:50.594722: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:17:50.596157: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

SAVING RESULTS TO TABLES:
run_details
preds
total run time : 0.81 seconds
--------------------------------------------------
21 / 40
current local expert:
                    x             y        lon        lat        t        z  \
2582953 -1.741331e+06  56392.502415 -91.854859  74.349169  18262.0 -0.00231

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2582953   1250  2020-01-01       cs2        1.0     579578.775028     0.042968
'local_data_select': 0.001 seconds
number obs: 223
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.052 seconds
'_read_params_from_file': 0.050 seconds

2026-05-18 19:17:51.407473: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:17:51.408906: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'set_parameters': 0.006 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.30104035, 10.03942127,  0.94902599])
kernel_variance: 0.07973512915700917
likelihood_variance: 0.01100000000000001
'predict': 0.031 seconds
total run time : 0.73 seconds
--------------------------------------------------
22 / 40
current local expert:
                    x             y        lon        lat        t         z  \
2582997 -1.721106e+06  58823.196441 -91.957468  74.531229  18262.0  0.002187

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2582997   1250  2020-01-01       cs2        1.0      600007.17159     0.042968
'local_data_select': 0.001 seconds
number obs: 217
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.052 seconds
'_read_params_from_file': 0.045 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.25801201, 10.03308436,  0.95493108])
kernel_variance: 0.08232813649637816
likelihood_variance: 0.01100000000000001
'predict': 0.031 seconds

2026-05-18 19:17:52.142001: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:17:52.143417: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.72 seconds
--------------------------------------------------
23 / 40
current local expert:
                    x             y        lon      lat        t        z  \
2583049 -1.697601e+06  61634.268678 -92.079307  74.7427  18262.0 -0.09409

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2583049   1250  2020-01-01       cs2        1.0     623740.825884     0.042968
'local_data_select': 0.001 seconds
number obs: 212
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.21322334, 10.02715604,  0.96111557])
kernel_variance: 0.08510867591222997
likelihood_variance: 0.01100000000000001
'predict': 0.031 seconds

2026-05-18 19:17:52.856675: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:17:52.858085: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.71 seconds
--------------------------------------------------
24 / 40
current local expert:
                    x             y        lon        lat        t         z  \
2583078 -1.604409e+06  72633.911016 -92.592093  75.579912  18262.0  0.131785

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2583078   1250  2020-01-01       cs2        1.0     717761.240199     0.042968
'local_data_select': 0.001 seconds
number obs: 176
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.055 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.004 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.09027521, 10.01452171,  0.97931948])
kernel_variance: 0.09313074509600563
likelihood_variance: 0.01100000000000001
'predict': 0.031 seconds

2026-05-18 19:17:53.575526: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:17:53.576937: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.72 seconds
--------------------------------------------------
25 / 40
current local expert:
                    x             y        lon        lat        t         z  \
2583086 -1.597554e+06  73433.765812 -92.631826  75.641412  18262.0 -0.157771

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2583086   1250  2020-01-01       cs2        1.0      724671.81688     0.042968
'local_data_select': 0.001 seconds
number obs: 177
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.049 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.08432829, 10.01405878,  0.98031322])
kernel_variance: 0.09352426767550709
likelihood_variance: 0.01100000000000001
'predict': 0.031 seconds

2026-05-18 19:17:54.296640: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:17:54.298070: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.72 seconds
--------------------------------------------------
26 / 40
current local expert:
                    x             y        lon        lat        t         z  \
2583098 -1.569832e+06  76656.010383 -92.795573  75.890034  18262.0  0.051145

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2583098   1250  2020-01-01       cs2        1.0     752614.839582     0.042968
'local_data_select': 0.001 seconds
number obs: 163
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.051 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.06379464, 10.01258409,  0.98392615])
kernel_variance: 0.09485765039289229
likelihood_variance: 0.01100000000000001
'predict': 0.031 seconds

2026-05-18 19:17:55.015935: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:17:55.017329: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.73 seconds
--------------------------------------------------
27 / 40
current local expert:
                    x             y        lon        lat        t         z  \
2583115 -1.551344e+06  78793.495687 -92.907581  76.055737  18262.0  0.124533

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2583115   1250  2020-01-01       cs2        1.0     771244.068722     0.042968
'local_data_select': 0.001 seconds
number obs: 146
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.047 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.05289361, 10.01188558,  0.98599987])
kernel_variance: 0.09552839712888565
likelihood_variance: 0.01100000000000001
'predict': 0.031 seconds

2026-05-18 19:17:55.741537: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:17:55.742975: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.71 seconds
--------------------------------------------------
28 / 40
current local expert:
                    x             y        lon        lat        t         z  \
2583145 -1.529570e+06  81299.212044 -93.042503  76.250785  18262.0 -0.317086

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2583145   1250  2020-01-01       cs2        1.0     793178.435864     0.042968
'local_data_select': 0.001 seconds
number obs: 125
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.049 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.04247702, 10.01127945,  0.98813031])
kernel_variance: 0.09611057565359091
likelihood_variance: 0.01100000000000001
'predict': 0.031 seconds

2026-05-18 19:17:56.453293: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:17:56.454702: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.72 seconds
--------------------------------------------------
29 / 40
current local expert:
                    x             y       lon        lat        t         z  \
2583152 -1.454677e+06  89821.501533 -93.53334  76.920785  18262.0 -0.127779

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2583152   1250  2020-01-01       cs2        1.0     868577.668649     0.042968
'local_data_select': 0.001 seconds
number obs: 128
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.051 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.02114626, 10.0102627 ,  0.99328242])
kernel_variance: 0.09661189809613521
likelihood_variance: 0.01100000000000001
'predict': 0.031 seconds

2026-05-18 19:17:57.180980: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:17:57.182584: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.72 seconds
--------------------------------------------------
30 / 40
current local expert:
                    x             y        lon        lat        t         z  \
2583167 -1.448405e+06  90528.356004 -93.576454  76.976826  18262.0 -0.084863

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2583167   1250  2020-01-01       cs2        1.0     874888.340171     0.042968
'local_data_select': 0.001 seconds
number obs: 136
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.051 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.02008618, 10.01022164,  0.99358303])
kernel_variance: 0.09655957042613558
likelihood_variance: 0.01100000000000001
'predict': 0.031 seconds

2026-05-18 19:17:57.903826: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:17:57.905241: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

SAVING RESULTS TO TABLES:
run_details
preds
total run time : 0.82 seconds
--------------------------------------------------
31 / 40
current local expert:
                    x             y        lon        lat        t         z  \
2583198 -1.434367e+06  92106.828882 -93.674162  77.102229  18262.0  0.039143

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2583198   1250  2020-01-01       cs2        1.0     889012.158647     0.042968
'local_data_select': 0.001 seconds
number obs: 142
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.049 seconds

2026-05-18 19:17:58.726108: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:17:58.727532: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'_read_params_from_file': 0.051 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01799654, 10.01014374,  0.99419274])
kernel_variance: 0.09639401055620975
likelihood_variance: 0.01100000000000001
'predict': 0.031 seconds
total run time : 0.72 seconds
--------------------------------------------------
32 / 40
current local expert:
                    x              y        lon        lat        t         z  \
2583261 -1.356967e+06  100715.814159 -94.244781  77.792689  18262.0 -0.189187

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2583261   1250  2020-01-01       cs2        1.0      966841.04121     0.042968
'local_data_select': 0.001 seconds
number obs: 171
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.050 seconds
'_read_params_from_file': 0.045 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01134187, 10.01      ,  0.99619977])
kernel_variance: 0.09433966304012484
likelihood_variance: 0.01100000000000001
'predict': 0.031 seconds

2026-05-18 19:17:59.446341: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:17:59.447770: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.71 seconds
--------------------------------------------------
33 / 40
current local expert:
                    x              y        lon        lat        t         z  \
2583265 -1.348295e+06  101670.454561 -94.312322  77.869945  18262.0 -0.036608

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2583265   1250  2020-01-01       cs2        1.0      975556.63005     0.042968
'local_data_select': 0.001 seconds
number obs: 174
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.050 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01092992, 10.01      ,  0.99630235])
kernel_variance: 0.09399312585057602
likelihood_variance: 0.01100000000000001
'predict': 0.031 seconds

2026-05-18 19:18:00.159087: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:18:00.160531: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.73 seconds
--------------------------------------------------
34 / 40
current local expert:
                    x              y        lon        lat        t         z  \
2583304 -1.322274e+06  104523.042612 -94.519714  78.101628  18262.0 -0.177487

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2583304   1250  2020-01-01       cs2        1.0      1.001703e+06     0.042968
'local_data_select': 0.001 seconds
number obs: 166
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.050 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  0.99648656])
kernel_variance: 0.09281539359634526
likelihood_variance: 0.01100000000000001
'predict': 0.031 seconds

2026-05-18 19:18:00.887482: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:18:00.888885: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.72 seconds
--------------------------------------------------
35 / 40
current local expert:
                    x              y        lon       lat        t         z  \
2583336 -1.274101e+06  109756.783658 -94.923561  78.53001  18262.0 -0.001464

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2583336   1250  2020-01-01       cs2        1.0      1.050089e+06     0.042968
'local_data_select': 0.001 seconds
number obs: 164
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.050 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  0.99639837])
kernel_variance: 0.09009463861580472
likelihood_variance: 0.01100000000000001
'predict': 0.031 seconds

2026-05-18 19:18:01.608913: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:18:01.610317: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.71 seconds
--------------------------------------------------
36 / 40
current local expert:
                    x              y        lon        lat        t         z  \
2583393 -1.242367e+06  113170.901613 -95.204877  78.811802  18262.0  0.028185

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2583393   1250  2020-01-01       cs2        1.0      1.081948e+06     0.042968
'local_data_select': 0.001 seconds
number obs: 169
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.050 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  0.99608422])
kernel_variance: 0.08792687821902224
likelihood_variance: 0.01100000000000001
'predict': 0.031 seconds

2026-05-18 19:18:02.324525: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:18:02.325950: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.71 seconds
--------------------------------------------------
37 / 40
current local expert:
                    x              y        lon       lat        t         z  \
2583416 -1.221704e+06  115379.682913 -95.395103  78.99511  18262.0  0.074314

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2583416   1250  2020-01-01       cs2        1.0      1.102687e+06     0.042968
'local_data_select': 0.001 seconds
number obs: 172
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.049 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  0.99578768])
kernel_variance: 0.08636054598173555
likelihood_variance: 0.01100000000000001
'predict': 0.031 seconds

2026-05-18 19:18:03.038727: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:18:03.040136: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.71 seconds
--------------------------------------------------
38 / 40
current local expert:
                    x              y        lon        lat        t         z  \
2583463 -1.196242e+06  118085.874167 -95.637631  79.220784  18262.0 -0.036422

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2583463   1250  2020-01-01       cs2        1.0      1.128236e+06     0.042968
'local_data_select': 0.001 seconds
number obs: 182
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  0.99533547])
kernel_variance: 0.08426982810473681
likelihood_variance: 0.01100000000000001
'predict': 0.031 seconds

2026-05-18 19:18:03.751486: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:18:03.752926: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.71 seconds
--------------------------------------------------
39 / 40
current local expert:
                    x              y        lon        lat        t         z  \
2583549 -1.082637e+06  129952.006809 -96.844627  80.224732  18262.0  0.034469

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2583549   1250  2020-01-01       cs2        1.0      1.242147e+06     0.042968
'local_data_select': 0.001 seconds
number obs: 191
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.052 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  0.99245969])
kernel_variance: 0.07310631107821977
likelihood_variance: 0.01100000000000001
'predict': 0.031 seconds

2026-05-18 19:18:04.467575: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:18:04.469003: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.72 seconds
--------------------------------------------------
40 / 40
current local expert:
                    x              y        lon        lat        t         z  \
2583566 -1.073338e+06  130908.276408 -96.953663  80.306678  18262.0  0.044315

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2583566   1250  2020-01-01       cs2        1.0      1.251466e+06     0.042968
'local_data_select': 0.001 seconds
number obs: 194
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.052 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.016 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  0.99218089])
kernel_variance: 0.07208848779510052
likelihood_variance: 0.01100000000000001
'predict': 0.031 seconds

2026-05-18 19:18:05.181527: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:18:05.185650: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

SAVING RESULTS TO TABLES:
run_details
preds
total run time : 0.84 seconds
'run': 29.263 seconds
reading in results
getting all tables
merging on expert location data
table: 'oi_config' does not have all coords_col: ['x', 'y', 't'] in columns, not merging on expert_locations
table: 'oi_config_SMOOTHED' does not have all coords_col: ['x', 'y', 't'] in columns, not merging on expert_locations
lin:
                    x             y        lon        lat        t   z  track  \
2582021 -2.312421e+06 -16806.619945 -89.583583  69.172876  18262.0 NaN   1250
2582022 -2.311538e+06 -16686.547310 -89.586400  69.180932  18262.0 NaN   1250
2582023 -2.311244e+06 -16646.542647 -89.587339  69.183617  18262.0 NaN   1250
2582024 -2.310949e+06 -16606.546837 -89.588278  69.186303  18262.0 NaN   1250
2582025 -2.310655e+06 -16566.561458 -89.589217  69.188988  18262.0 NaN   1250

        date_string satellite  lead_mask  dist_along_track  z_track_avg  \
2582021  2020-01-01       cs2        0.0          0.000000     0.042968
2582022  2020-01-01       cs2        0.0        900.661739     0.042968
2582023  2020-01-01       cs2        0.0       1200.844487     0.042968
2582024  2020-01-01       cs2        0.0       1501.136761     0.042968
2582025  2020-01-01       cs2        0.0       1801.318373     0.042968

            f_lin
2582021  0.229557
2582022  0.229557
2582023  0.229557
2582024  0.229557
2582025  0.229557
gpsat:
                    x             y        lon        lat        t   z  track  \
2582021 -2.312421e+06 -16806.619945 -89.583583  69.172876  18262.0 NaN   1250
2582022 -2.311538e+06 -16686.547310 -89.586400  69.180932  18262.0 NaN   1250
2582023 -2.311244e+06 -16646.542647 -89.587339  69.183617  18262.0 NaN   1250
2582024 -2.310949e+06 -16606.546837 -89.588278  69.186303  18262.0 NaN   1250
2582025 -2.310655e+06 -16566.561458 -89.589217  69.188988  18262.0 NaN   1250

        date_string satellite  lead_mask  dist_along_track  z_track_avg  \
2582021  2020-01-01       cs2        0.0          0.000000     0.042968
2582022  2020-01-01       cs2        0.0        900.661739     0.042968
2582023  2020-01-01       cs2        0.0       1200.844487     0.042968
2582024  2020-01-01       cs2        0.0       1501.136761     0.042968
2582025  2020-01-01       cs2        0.0       1801.318373     0.042968

          f_gpsat  f_var_gpsat
2582021  0.165747     0.165747
2582022  0.166225     0.166225
2582023  0.166384     0.166384
2582024  0.166542     0.166542
2582025  0.166701     0.166701
Test NaNs — Linear: 0, GPSat: 184
Track interpolated!
Interpolating track 1251, 9 of 15...

/tmp/ipykernel_1171781/839927469.py:200: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  track_df['f_gpsat'] = ssha
/tmp/ipykernel_1171781/839927469.py:201: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  track_df['f_var_gpsat'] = ssha_var
/tmp/ipykernel_1171781/839927469.py:66: RuntimeWarning: invalid value encountered in sqrt
  gpsat_std = np.sqrt(gpsat_var[both_valid])

Expert limit reached.
'data_select': 0.000 seconds
'load': 0.000 seconds
in json_serializable - key: 'data_source' has value DataFrame/Series, but is too long: 1870 >  100
storing as str
in json_serializable - key: 'df' has value DataFrame/Series, but is too long: 6459 >  100
storing as str
---------
storing expert locations in 'expert_locs' table
exception occurred: 'No object named expert_locs in the file'
will now close object

---------
dropping expert locations that already exists in 'run_details' table
exception occurred: 'No object named run_details in the file'
will now close object

--------------------------------------------------
1 / 40
current local expert:
                    x              y        lon        lat        t         z  \
2588121  1.299330e+06  301319.312827  103.05631  78.034879  18262.0 -0.012229

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2588121   1251  2020-01-01       cs2        1.0               0.0     0.060972
'data_select': 0.000 seconds
'load': 0.000 seconds
'local_data_select': 0.001 seconds
number obs: 57
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'get_parameters': 0.003 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:18:07.114006: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:18:07.116139: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.268 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.00992345, 10.0099999 ,  0.98180609])
kernel_variance: 1.0304314762125673
likelihood_variance: 0.0010000041809218802
'predict': 0.034 seconds
total run time : 0.94 seconds
--------------------------------------------------
2 / 40
current local expert:
                    x              y        lon        lat        t         z  \
2588165  1.327635e+06  302469.951254  102.83441  77.784088  18262.0 -0.006457

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2588165   1251  2020-01-01       cs2        1.0       28298.06846     0.060972
'local_data_select': 0.001 seconds
number obs: 57
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.050 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:18:08.057143: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:18:08.058546: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.261 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.00992345, 10.0099999 ,  0.98180609])
kernel_variance: 1.0304314762125673
likelihood_variance: 0.0010000041809218802
'predict': 0.030 seconds
total run time : 0.94 seconds
--------------------------------------------------
3 / 40
current local expert:
                    x              y        lon        lat        t         z  \
2588209  1.349603e+06  303348.646179  102.66777  77.589308  18262.0  0.131064

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2588209   1251  2020-01-01       cs2        1.0       50264.88395     0.060972
'local_data_select': 0.001 seconds
number obs: 57
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.051 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:18:08.996591: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:18:08.998019: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.260 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.00992345, 10.0099999 ,  0.98180609])
kernel_variance: 1.0304314762125673
likelihood_variance: 0.0010000041809218802
'predict': 0.030 seconds
total run time : 0.94 seconds
--------------------------------------------------
4 / 40
current local expert:
                    x             y        lon        lat        t         z  \
2588223  1.353816e+06  303515.68042  102.63635  77.551944  18262.0  0.287598

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2588223   1251  2020-01-01       cs2        1.0      54477.632817     0.060972
'local_data_select': 0.001 seconds
number obs: 57
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.052 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:18:09.934578: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:18:09.935985: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.263 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.00992345, 10.0099999 ,  0.98180609])
kernel_variance: 1.0304314762125673
likelihood_variance: 0.0010000041809218802
'predict': 0.030 seconds
total run time : 0.93 seconds
--------------------------------------------------
5 / 40
current local expert:
                    x             y       lon       lat        t         z  \
2588226 -1.181670e+06  659260.64246 -119.1574  77.86085  18262.0 -0.157166

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2588226   1251  2020-01-01       cs2        1.0      2.601604e+06     0.060972
'local_data_select': 0.001 seconds
number obs: 119
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.053 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:18:10.866576: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:18:10.867992: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.296 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01012169, 10.01001428,  1.0000671 ])
kernel_variance: 0.0024827660353025196
likelihood_variance: 0.008629643590668212
'predict': 0.030 seconds
total run time : 0.98 seconds
--------------------------------------------------
6 / 40
current local expert:
                    x              y        lon        lat        t         z  \
2588257 -1.159716e+06  651873.429769 -119.34023  78.065882  18262.0 -0.099434

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2588257   1251  2020-01-01       cs2        1.0      2.624741e+06     0.060972
'local_data_select': 0.001 seconds
number obs: 119
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.047 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:18:11.840740: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:18:11.842155: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.302 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01012169, 10.01001428,  1.0000671 ])
kernel_variance: 0.0024827660353025196
likelihood_variance: 0.008629643590668212
'predict': 0.030 seconds
total run time : 0.98 seconds
--------------------------------------------------
7 / 40
current local expert:
                    x              y       lon        lat        t         z  \
2588283 -1.152018e+06  649279.682846 -119.4057  78.137752  18262.0 -0.188626

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2588283   1251  2020-01-01       cs2        1.0      2.632854e+06     0.060972
'local_data_select': 0.001 seconds
number obs: 121
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.049 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:18:12.821815: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:18:12.823335: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'optimise_parameters': 0.243 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01013689, 10.01001605,  1.00118162])
kernel_variance: 0.0021798616905629982
likelihood_variance: 0.008547910757664465
'predict': 0.030 seconds
total run time : 0.93 seconds
--------------------------------------------------
8 / 40
current local expert:
                    x             y        lon        lat        t        z  \
2588346 -1.111244e+06  635511.45617 -119.76488  78.518193  18262.0 -0.02624

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2588346   1251  2020-01-01       cs2        1.0      2.675826e+06     0.060972
'local_data_select': 0.001 seconds
number obs: 131
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.050 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:18:13.750797: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:18:13.752196: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.328 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01015337, 10.01001806,  1.00120039])
kernel_variance: 0.0017322390204969488
likelihood_variance: 0.008367403147329023
'predict': 0.031 seconds
total run time : 1.01 seconds
--------------------------------------------------
9 / 40
current local expert:
                    x             y        lon        lat        t         z  \
2588389 -1.082161e+06  625659.67865 -120.03469  78.789325  18262.0  0.046826

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2588389   1251  2020-01-01       cs2        1.0      2.706478e+06     0.060972
'local_data_select': 0.001 seconds
number obs: 145
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.050 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:18:14.764444: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:18:14.765859: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.323 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01012278, 10.01001475,  0.99941143])
kernel_variance: 0.00268645494905475
likelihood_variance: 0.007804448538673758
'predict': 0.031 seconds
total run time : 1.00 seconds
--------------------------------------------------
10 / 40
current local expert:
                    x              y        lon        lat        t         z  \
2588418 -1.064768e+06  619755.339316 -120.20184  78.951372  18262.0  0.034824

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2588418   1251  2020-01-01       cs2        1.0      2.724809e+06     0.060972
'local_data_select': 0.001 seconds
number obs: 146
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.046 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:18:15.759829: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:18:15.761230: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'optimise_parameters': 0.314 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.        , 10.00009051,  1.16458991])
kernel_variance: 0.0027393709646724934
likelihood_variance: 0.007742376246337706
'predict': 0.031 seconds
SAVING RESULTS TO TABLES:
run_details
preds
lengthscales
kernel_variance
likelihood_variance
total run time : 1.12 seconds
--------------------------------------------------
11 / 40
current local expert:
                    x            y        lon        lat        t         z  \
2588477 -1.040816e+06  611609.9387 -120.43957  79.174389  18262.0 -0.006905

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2588477   1251  2020-01-01       cs2        1.0      2.750053e+06     0.060972
'local_data_select': 0.001 seconds
number obs: 158
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.051 seconds
'set_lengthscales_constraints': 0.006 seconds

2026-05-18 19:18:16.885757: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:18:16.887163: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'set_likelihood_variance_constraints': 0.011 seconds
**********
optimization failed!
'optimise_parameters': 0.351 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01012748, 10.01001515,  0.9999567 ])
kernel_variance: 0.005907889412770216
likelihood_variance: 0.007742311314553152
'predict': 0.031 seconds
total run time : 1.03 seconds
--------------------------------------------------
12 / 40
current local expert:
                    x              y        lon        lat        t        z  \
2588540 -1.006600e+06  599943.128847 -120.79533  79.492705  18262.0 -0.09014

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2588540   1251  2020-01-01       cs2        1.0      2.786116e+06     0.060972
'local_data_select': 0.001 seconds
number obs: 181
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.050 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:18:17.919732: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:18:17.921132: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.407 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.00000671, 10.00378765,  0.87221562])
kernel_variance: 0.0713366487772945
likelihood_variance: 0.007008061833815156
'predict': 0.031 seconds
total run time : 1.09 seconds
--------------------------------------------------
13 / 40
current local expert:
                     x              y        lon        lat        t  \
2588571 -991773.649601  594876.428201 -120.95578  79.630534  18262.0

                z  track date_string satellite  lead_mask  dist_along_track  \
2588571  0.010354   1251  2020-01-01       cs2        1.0      2.801744e+06

         z_track_avg
2588571     0.060972
'local_data_select': 0.001 seconds
number obs: 187
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.046 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:18:19.004000: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:18:19.005389: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.347 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01006135, 10.0100072 ,  1.00016375])
kernel_variance: 0.06459402588944878
likelihood_variance: 0.007283223526831982
'predict': 0.031 seconds
total run time : 1.02 seconds
--------------------------------------------------
14 / 40
current local expert:
                     x             y        lon        lat        t         z  \
2588614 -969533.670144  587263.90289 -121.20404  79.837145  18262.0  0.024825

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2588614   1251  2020-01-01       cs2        1.0      2.825187e+06     0.060972
'local_data_select': 0.001 seconds
number obs: 195
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:18:20.027866: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:18:20.029289: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.401 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.        , 10.00053479,  1.29206626])
kernel_variance: 0.09612751738682165
likelihood_variance: 0.006928204639736354
'predict': 0.031 seconds
total run time : 1.08 seconds
--------------------------------------------------
15 / 40
current local expert:
                     x              y        lon        lat        t  \
2588627 -965542.062182  585895.852954 -121.24959  79.874211  18262.0

                z  track date_string satellite  lead_mask  dist_along_track  \
2588627 -0.129626   1251  2020-01-01       cs2        1.0      2.829394e+06

         z_track_avg
2588627     0.060972
'local_data_select': 0.001 seconds
number obs: 202
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.047 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:18:21.111755: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:18:21.113168: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.373 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.00000013, 10.00236838,  0.90109281])
kernel_variance: 0.09379955330175081
likelihood_variance: 0.006788519059984418
'predict': 0.031 seconds
total run time : 1.07 seconds
--------------------------------------------------
16 / 40
current local expert:
                     x              y        lon        lat        t  \
2588732 -901390.556758  563844.541536 -122.02711  80.469136  18262.0

                z  track date_string satellite  lead_mask  dist_along_track  \
2588732  0.081213   1251  2020-01-01       cs2        1.0      2.897020e+06

         z_track_avg
2588732     0.060972
'local_data_select': 0.001 seconds
number obs: 220
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.053 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:18:22.185860: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:18:22.187289: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.317 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01005019, 10.01000594,  0.99993713])
kernel_variance: 0.1130522516980083
likelihood_variance: 0.006572917160894609
'predict': 0.032 seconds
total run time : 1.02 seconds
--------------------------------------------------
17 / 40
current local expert:
                     x              y        lon        lat        t        z  \
2588738 -896258.608641  562075.056898 -122.09326  80.516661  18262.0 -0.01732

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2588738   1251  2020-01-01       cs2        1.0      2.902430e+06     0.060972
'local_data_select': 0.001 seconds
number obs: 224
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:18:23.200025: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:18:23.201434: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.411 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01003438, 10.01000397,  0.99963894])
kernel_variance: 0.10416817306069519
likelihood_variance: 0.007020257617139624
'predict': 0.031 seconds
total run time : 1.10 seconds
--------------------------------------------------
18 / 40
current local expert:
                     x              y        lon        lat        t  \
2588791 -873735.751503  554299.633673 -122.39112  80.725108  18262.0

                z  track date_string satellite  lead_mask  dist_along_track  \
2588791 -0.217091   1251  2020-01-01       cs2        1.0      2.926176e+06

         z_track_avg
2588791     0.060972
'local_data_select': 0.001 seconds
number obs: 227
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.050 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:18:24.304889: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:18:24.306310: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.509 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.        , 10.00123104,  0.70161128])
kernel_variance: 0.10768189531464264
likelihood_variance: 0.006908212414365946
'predict': 0.033 seconds
total run time : 1.21 seconds
--------------------------------------------------
19 / 40
current local expert:
                     x              y        lon        lat        t  \
2588811 -865468.198014  551441.564708 -122.50365  80.801569  18262.0

                z  track date_string satellite  lead_mask  dist_along_track  \
2588811  0.103901   1251  2020-01-01       cs2        1.0      2.934892e+06

         z_track_avg
2588811     0.060972
'local_data_select': 0.001 seconds
number obs: 228
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.047 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:18:25.510445: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:18:25.511883: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'optimise_parameters': 0.276 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01005446, 10.01000649,  1.00037176])
kernel_variance: 0.10109778226636795
likelihood_variance: 0.006939075753841497
'predict': 0.031 seconds
total run time : 0.96 seconds
--------------------------------------------------
20 / 40
current local expert:
                     x              y        lon        lat        t        z  \
2588884 -825841.706658  537713.717377 -123.06855  81.167611  18262.0  0.10003

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2588884   1251  2020-01-01       cs2        1.0      2.976673e+06     0.060972
'local_data_select': 0.001 seconds
number obs: 247
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.046 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:18:26.474725: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:18:26.476125: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.342 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01004985, 10.01000598,  0.99910704])
kernel_variance: 0.10086327246568043
likelihood_variance: 0.006511030898011881
'predict': 0.032 seconds
SAVING RESULTS TO TABLES:
run_details
preds
lengthscales
kernel_variance
likelihood_variance
total run time : 1.18 seconds
--------------------------------------------------
21 / 40
current local expert:
                     x              y        lon       lat        t         z  \
2588919 -807882.585394  531476.298934 -123.33945  81.33325  18262.0  0.028889

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2588919   1251  2020-01-01       cs2        1.0      2.995610e+06     0.060972
'local_data_select': 0.001 seconds
number obs: 252
found GPU
setting lengthscales to: [1. 1. 1.]

2026-05-18 19:18:27.658093: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:18:27.659497: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'__init__': 0.050 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds
**********
optimization failed!
'optimise_parameters': 0.452 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.00011082, 10.0055463 ,  1.06087335])
kernel_variance: 0.10070998455216658
likelihood_variance: 0.006420443864655697
'predict': 0.032 seconds
total run time : 1.16 seconds
--------------------------------------------------
22 / 40
current local expert:
                     x              y        lon        lat        t  \
2588965 -779662.499145  521655.029563 -123.78561  81.593176  18262.0

                z  track date_string satellite  lead_mask  dist_along_track  \
2588965 -0.023154   1251  2020-01-01       cs2        1.0      3.025369e+06

         z_track_avg
2588965     0.060972
'local_data_select': 0.001 seconds
number obs: 243
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.047 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:18:28.813375: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:18:28.814780: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.476 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.        , 10.00084051,  1.04250644])
kernel_variance: 0.07022061554115168
likelihood_variance: 0.0066399809441526885
'predict': 0.032 seconds
total run time : 1.18 seconds
--------------------------------------------------
23 / 40
current local expert:
                     x              y        lon        lat        t  \
2589008 -757999.936636  514099.500007 -124.14636  81.792388  18262.0

                z  track date_string satellite  lead_mask  dist_along_track  \
2589008  0.050337   1251  2020-01-01       cs2        1.0      3.048215e+06

         z_track_avg
2589008     0.060972
'local_data_select': 0.001 seconds
number obs: 236
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:18:29.995085: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:18:29.996485: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'optimise_parameters': 0.581 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.        , 10.00062854,  1.37575352])
kernel_variance: 0.07190120138780093
likelihood_variance: 0.006884778256649557
'predict': 0.033 seconds
total run time : 1.29 seconds
--------------------------------------------------
24 / 40
current local expert:
                     x             y        lon        lat        t         z  \
2589060 -730353.492745  504435.80944 -124.63181  82.046197  18262.0  0.004148

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2589060   1251  2020-01-01       cs2        1.0      3.077374e+06     0.060972
'local_data_select': 0.001 seconds
number obs: 241
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.046 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:18:31.280161: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:18:31.281554: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.414 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.00998415, 10.00999788,  1.00008278])
kernel_variance: 0.0648762861823138
likelihood_variance: 0.0068935355997950705
'predict': 0.032 seconds
total run time : 1.12 seconds
--------------------------------------------------
25 / 40
current local expert:
                     x              y        lon       lat        t         z  \
2589109 -706983.941063  496248.849214 -125.06593  82.26033  18262.0 -0.021248

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2589109   1251  2020-01-01       cs2        1.0      3.102024e+06     0.060972
'local_data_select': 0.001 seconds
number obs: 256
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.050 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:18:32.401759: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:18:32.403159: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.460 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.        , 10.00006057,  2.23228969])
kernel_variance: 0.056417272129211445
likelihood_variance: 0.0070887904775206595
'predict': 0.033 seconds
total run time : 1.17 seconds
--------------------------------------------------
26 / 40
current local expert:
                     x              y        lon        lat        t  \
2589163 -683900.823065  488145.597132 -125.51798  82.471435  18262.0

                z  track date_string satellite  lead_mask  dist_along_track  \
2589163 -0.115976   1251  2020-01-01       cs2        1.0      3.126375e+06

         z_track_avg
2589163     0.060972
'local_data_select': 0.001 seconds
number obs: 256
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.049 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:18:33.574348: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:18:33.575762: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.358 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01005006, 10.01000627,  1.00110196])
kernel_variance: 0.07478631040180064
likelihood_variance: 0.0063770063057636585
'predict': 0.031 seconds
total run time : 1.07 seconds
--------------------------------------------------
27 / 40
current local expert:
                     x              y       lon        lat        t         z  \
2589211 -660249.417026  479826.058081 -126.0072  82.687282  18262.0  0.010036

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2589211   1251  2020-01-01       cs2        1.0      3.151327e+06     0.060972
'local_data_select': 0.001 seconds
number obs: 236
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.051 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:18:34.643364: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:18:34.644776: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'optimise_parameters': 0.253 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01000779, 10.01000108,  1.00001771])
kernel_variance: 0.058009652129280456
likelihood_variance: 0.006803230601488094
'predict': 0.031 seconds
total run time : 0.95 seconds
--------------------------------------------------
28 / 40
current local expert:
                     x              y        lon        lat        t  \
2589254 -642868.492009  473701.197684 -126.38485  82.845586  18262.0

                z  track date_string satellite  lead_mask  dist_along_track  \
2589254  0.026848   1251  2020-01-01       cs2        1.0      3.169665e+06

         z_track_avg
2589254     0.060972
'local_data_select': 0.001 seconds
number obs: 247
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.051 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:18:35.597273: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:18:35.598683: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.467 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.00000439, 10.00377875,  0.93017725])
kernel_variance: 0.057474188140492245
likelihood_variance: 0.006852291747594221
'predict': 0.033 seconds
total run time : 1.17 seconds
--------------------------------------------------
29 / 40
current local expert:
                     x             y        lon        lat        t         z  \
2589294 -620075.412118  465654.98041 -126.90527  83.052741  18262.0 -0.063366

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2589294   1251  2020-01-01       cs2        1.0      3.193716e+06     0.060972
'local_data_select': 0.001 seconds
number obs: 249
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:18:36.770212: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:18:36.771634: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.573 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.        , 10.00014577,  0.80883364])
kernel_variance: 0.057916771052137175
likelihood_variance: 0.006650442125160169
'predict': 0.033 seconds
total run time : 1.29 seconds
--------------------------------------------------
30 / 40
current local expert:
                     x              y        lon        lat        t  \
2589356 -591016.708346  455373.909963 -127.61398  83.316041  18262.0

                z  track date_string satellite  lead_mask  dist_along_track  \
2589356 -0.002835   1251  2020-01-01       cs2        1.0      3.224382e+06

         z_track_avg
2589356     0.060972
'local_data_select': 0.001 seconds
number obs: 253
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.051 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:18:38.061314: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:18:38.063302: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.453 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.        , 10.00001468,  0.46835311])
kernel_variance: 0.09754606216829134
likelihood_variance: 0.007196260062430193
'predict': 0.032 seconds
SAVING RESULTS TO TABLES:
run_details
preds
lengthscales
kernel_variance
likelihood_variance
total run time : 1.36 seconds
--------------------------------------------------
31 / 40
current local expert:
                     x              y        lon        lat        t  \
2589407 -569082.695926  447596.232645 -128.18584  83.514129  18262.0

                z  track date_string satellite  lead_mask  dist_along_track  \
2589407 -0.092857   1251  2020-01-01       cs2        1.0      3.247532e+06

         z_track_avg
2589407     0.060972
'local_data_select': 0.001 seconds
number obs: 248
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.047 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:18:39.420730: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:18:39.422148: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'optimise_parameters': 0.330 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01000457, 10.01000049,  0.99966559])
kernel_variance: 0.09825097095276342
likelihood_variance: 0.007528021856366631
'predict': 0.032 seconds
total run time : 1.05 seconds
--------------------------------------------------
32 / 40
current local expert:
                    x              y        lon        lat        t         z  \
2589468 -545441.58634  439196.665297 -128.84147  83.726932  18262.0 -0.013711

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2589468   1251  2020-01-01       cs2        1.0      3.272486e+06     0.060972
'local_data_select': 0.001 seconds
number obs: 284
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:18:40.469844: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:18:40.471266: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'optimise_parameters': 0.526 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.        , 10.00000941,  3.99760863])
kernel_variance: 0.09478494536176624
likelihood_variance: 0.008033026165606034
'predict': 0.032 seconds
total run time : 1.24 seconds
--------------------------------------------------
33 / 40
current local expert:
                     x              y       lon        lat        t         z  \
2589512 -518955.191627  429765.794712 -129.6294  83.964386  18262.0 -0.011596

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2589512   1251  2020-01-01       cs2        1.0      3.300447e+06     0.060972
'local_data_select': 0.001 seconds
number obs: 309
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.045 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:18:41.712227: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:18:41.713625: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'optimise_parameters': 0.484 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.        , 10.00066481,  1.03467909])
kernel_variance: 0.11937380091418012
likelihood_variance: 0.007532241397052701
'predict': 0.033 seconds
total run time : 1.19 seconds
--------------------------------------------------
34 / 40
current local expert:
                     x              y        lon        lat        t  \
2589550 -495034.661485  421229.907278 -130.39479  84.177863  18262.0

                z  track date_string satellite  lead_mask  dist_along_track  \
2589550 -0.043501   1251  2020-01-01       cs2        1.0      3.325703e+06

         z_track_avg
2589550     0.060972
'local_data_select': 0.001 seconds
number obs: 312
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.050 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:18:42.912280: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:18:42.913706: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'optimise_parameters': 0.281 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01014881, 10.01001821,  0.99948734])
kernel_variance: 0.0013016354781819972
likelihood_variance: 0.009938200948772735
'predict': 0.033 seconds
total run time : 0.99 seconds
--------------------------------------------------
35 / 40
current local expert:
                     x              y        lon        lat        t  \
2589610 -464853.201865  410434.711283 -131.44238  84.445721  18262.0

                z  track date_string satellite  lead_mask  dist_along_track  \
2589610 -0.119051   1251  2020-01-01       cs2        1.0      3.357575e+06

         z_track_avg
2589610     0.060972
'local_data_select': 0.001 seconds
number obs: 326
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.049 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:18:43.902505: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:18:43.903904: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.411 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.00999789, 10.00999958,  1.00030194])
kernel_variance: 0.0904231338515381
likelihood_variance: 0.007833531237242158
'predict': 0.034 seconds
total run time : 1.13 seconds
--------------------------------------------------
36 / 40
current local expert:
                     x              y        lon        lat        t  \
2589641 -452041.691408  405843.814446 -131.91755  84.558862  18262.0

                z  track date_string satellite  lead_mask  dist_along_track  \
2589641 -0.036274   1251  2020-01-01       cs2        1.0      3.371105e+06

         z_track_avg
2589641     0.060972
'local_data_select': 0.001 seconds
number obs: 332
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.049 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:18:45.034032: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:18:45.035446: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.648 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.        , 10.00102618,  0.62773875])
kernel_variance: 0.0905737959280832
likelihood_variance: 0.007727907164966564
'predict': 0.035 seconds
total run time : 1.37 seconds
--------------------------------------------------
37 / 40
current local expert:
                    x              y       lon       lat        t         z  \
2589681 -429552.48873  397772.751087 -132.8002  84.75657  18262.0  0.050795

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2589681   1251  2020-01-01       cs2        1.0      3.394859e+06     0.060972
'local_data_select': 0.001 seconds
number obs: 330
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.051 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:18:46.412605: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:18:46.414038: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.444 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01004026, 10.01000502,  1.00091003])
kernel_variance: 0.10356015606953592
likelihood_variance: 0.007685667263978082
'predict': 0.033 seconds
total run time : 1.17 seconds
--------------------------------------------------
38 / 40
current local expert:
                     x              y       lon        lat        t         z  \
2589724 -405358.079779  389072.244057 -133.8256  84.967855  18262.0 -0.011415

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2589724   1251  2020-01-01       cs2        1.0      3.420417e+06     0.060972
'local_data_select': 0.001 seconds
number obs: 330
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.046 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:18:47.578896: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:18:47.580306: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.450 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01004026, 10.01000502,  1.00091003])
kernel_variance: 0.10356015606953592
likelihood_variance: 0.007685667263978082
'predict': 0.034 seconds
total run time : 1.16 seconds
--------------------------------------------------
39 / 40
current local expert:
                     x              y        lon        lat        t  \
2589762 -373768.142581  377685.072187 -135.29865  85.241194  18262.0

                z  track date_string satellite  lead_mask  dist_along_track  \
2589762  0.009501   1251  2020-01-01       cs2        1.0      3.453794e+06

         z_track_avg
2589762     0.060972
'local_data_select': 0.001 seconds
number obs: 332
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.049 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:18:48.747264: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:18:48.749390: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.405 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01003235, 10.01000418,  0.99987789])
kernel_variance: 0.09875512031822027
likelihood_variance: 0.007696391492635556
'predict': 0.034 seconds
total run time : 1.12 seconds
--------------------------------------------------
40 / 40
current local expert:
                     x              y        lon        lat        t        z  \
2589781 -352996.033332  370180.583495 -136.36124  85.419138  18262.0 -0.00293

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2589781   1251  2020-01-01       cs2        1.0      3.475745e+06     0.060972
'local_data_select': 0.001 seconds
number obs: 325
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:18:49.872425: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:18:49.873836: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.542 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.0100409 , 10.01000531,  0.99995512])
kernel_variance: 0.10384538356441902
likelihood_variance: 0.007690492109432521
'predict': 0.034 seconds
SAVING RESULTS TO TABLES:
run_details
preds
lengthscales
kernel_variance
likelihood_variance
total run time : 1.50 seconds
'run': 44.328 seconds
reading in results
getting all tables
merging on expert location data
table: 'oi_config' does not have all coords_col: ['x', 'y', 't'] in columns, not merging on expert_locations
h5 tables: ['expert_locs', 'kernel_variance', 'lengthscales', 'likelihood_variance', 'oi_config', 'preds', 'run_details']
found model_name: GPflowGPRModel
found GPU
setting lengthscales to: [1.]
'__init__': 0.049 seconds
reading in results
selecting only tables: ['lengthscales', 'kernel_variance', 'likelihood_variance']
'data_select': 0.000 seconds
'load': 0.000 seconds
expert_locations data will not be merged on results data
adding smoothed table: lengthscales_SMOOTHED
adding smoothed table: kernel_variance_SMOOTHED
adding smoothed table: likelihood_variance_SMOOTHED
writing (smoothed) hyper parameters to:
/home/mhen/geol0069_data/gpsat/jan20/1251.h5
table_suffix:_SMOOTHED
writing: lengthscales_SMOOTHED to table
writing: kernel_variance_SMOOTHED to table
writing: likelihood_variance_SMOOTHED to table
'data_select': 0.000 seconds
'load': 0.000 seconds
in json_serializable - key: 'data_source' has value DataFrame/Series, but is too long: 1870 >  100
storing as str
in json_serializable - key: 'df' has value DataFrame/Series, but is too long: 6459 >  100
storing as str
---------
storing expert locations in 'expert_locs' table
exception occurred: 'No object named expert_locs_SMOOTHED in the file'
will now close object

2026-05-18 19:18:51.552264: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:18:51.556417: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

---------
dropping expert locations that already exists in 'run_details' table
exception occurred: 'No object named run_details_SMOOTHED in the file'
will now close object

--------------------------------------------------
1 / 40
current local expert:
                    x              y        lon        lat        t         z  \
2588121  1.299330e+06  301319.312827  103.05631  78.034879  18262.0 -0.012229

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2588121   1251  2020-01-01       cs2        1.0               0.0     0.060972
'data_select': 0.000 seconds
'load': 0.000 seconds
'local_data_select': 0.001 seconds
number obs: 57
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'get_parameters': 0.003 seconds
'_read_params_from_file': 0.049 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  0.98180609])
kernel_variance: 0.10000000000000002
likelihood_variance: 0.01100000000000001
'predict': 0.030 seconds

2026-05-18 19:18:51.802427: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:18:51.803831: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.77 seconds
--------------------------------------------------
2 / 40
current local expert:
                    x              y        lon        lat        t         z  \
2588165  1.327635e+06  302469.951254  102.83441  77.784088  18262.0 -0.006457

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2588165   1251  2020-01-01       cs2        1.0       28298.06846     0.060972
'local_data_select': 0.001 seconds
number obs: 57
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.045 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  0.98180609])
kernel_variance: 0.09999999999999998
likelihood_variance: 0.01100000000000001
'predict': 0.030 seconds

2026-05-18 19:18:52.573244: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:18:52.574651: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.76 seconds
--------------------------------------------------
3 / 40
current local expert:
                    x              y        lon        lat        t         z  \
2588209  1.349603e+06  303348.646179  102.66777  77.589308  18262.0  0.131064

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2588209   1251  2020-01-01       cs2        1.0       50264.88395     0.060972
'local_data_select': 0.001 seconds
number obs: 57
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.047 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  0.98180609])
kernel_variance: 0.10000000000000002
likelihood_variance: 0.01100000000000001
'predict': 0.030 seconds

2026-05-18 19:18:53.337632: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:18:53.339034: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.78 seconds
--------------------------------------------------
4 / 40
current local expert:
                    x             y        lon        lat        t         z  \
2588223  1.353816e+06  303515.68042  102.63635  77.551944  18262.0  0.287598

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2588223   1251  2020-01-01       cs2        1.0      54477.632817     0.060972
'local_data_select': 0.001 seconds
number obs: 57
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.046 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  0.98180609])
kernel_variance: 0.10000000000000002
likelihood_variance: 0.01100000000000001
'predict': 0.030 seconds

2026-05-18 19:18:54.116346: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:18:54.117775: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.78 seconds
--------------------------------------------------
5 / 40
current local expert:
                    x             y       lon       lat        t         z  \
2588226 -1.181670e+06  659260.64246 -119.1574  77.86085  18262.0 -0.157166

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2588226   1251  2020-01-01       cs2        1.0      2.601604e+06     0.060972
'local_data_select': 0.001 seconds
number obs: 119
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.046 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  1.01692728])
kernel_variance: 0.035861915117445825
likelihood_variance: 0.01100000000000001
'predict': 0.031 seconds

2026-05-18 19:18:54.893133: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:18:54.894545: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.78 seconds
--------------------------------------------------
6 / 40
current local expert:
                    x              y        lon        lat        t         z  \
2588257 -1.159716e+06  651873.429769 -119.34023  78.065882  18262.0 -0.099434

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2588257   1251  2020-01-01       cs2        1.0      2.624741e+06     0.060972
'local_data_select': 0.001 seconds
number obs: 119
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.045 seconds
'_read_params_from_file': 0.045 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  1.01812274])
kernel_variance: 0.03838767945207427
likelihood_variance: 0.01100000000000001
'predict': 0.031 seconds

2026-05-18 19:18:55.669514: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:18:55.670932: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.76 seconds
--------------------------------------------------
7 / 40
current local expert:
                    x              y       lon        lat        t         z  \
2588283 -1.152018e+06  649279.682846 -119.4057  78.137752  18262.0 -0.188626

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2588283   1251  2020-01-01       cs2        1.0      2.632854e+06     0.060972
'local_data_select': 0.001 seconds
number obs: 121
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.049 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  1.01860085])
kernel_variance: 0.03929357667154424
likelihood_variance: 0.01100000000000001
'predict': 0.030 seconds

2026-05-18 19:18:56.437556: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:18:56.438995: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.77 seconds
--------------------------------------------------
8 / 40
current local expert:
                    x             y        lon        lat        t        z  \
2588346 -1.111244e+06  635511.45617 -119.76488  78.518193  18262.0 -0.02624

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2588346   1251  2020-01-01       cs2        1.0      2.675826e+06     0.060972
'local_data_select': 0.001 seconds
number obs: 131
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.049 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01     , 10.01     ,  1.0217576])
kernel_variance: 0.044230546120247606
likelihood_variance: 0.01100000000000001
'predict': 0.031 seconds

2026-05-18 19:18:57.212507: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:18:57.213939: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.78 seconds
--------------------------------------------------
9 / 40
current local expert:
                    x             y        lon        lat        t         z  \
2588389 -1.082161e+06  625659.67865 -120.03469  78.789325  18262.0  0.046826

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2588389   1251  2020-01-01       cs2        1.0      2.706478e+06     0.060972
'local_data_select': 0.001 seconds
number obs: 145
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  1.02479321])
kernel_variance: 0.047844533875698925
likelihood_variance: 0.01100000000000001
'predict': 0.031 seconds

2026-05-18 19:18:57.993902: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:18:57.995357: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.78 seconds
--------------------------------------------------
10 / 40
current local expert:
                    x              y        lon        lat        t         z  \
2588418 -1.064768e+06  619755.339316 -120.20184  78.951372  18262.0  0.034824

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2588418   1251  2020-01-01       cs2        1.0      2.724809e+06     0.060972
'local_data_select': 0.001 seconds
number obs: 146
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.050 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  1.02698758])
kernel_variance: 0.050016380410493534
likelihood_variance: 0.01100000000000001
'predict': 0.031 seconds

2026-05-18 19:18:58.776873: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:18:58.781001: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

SAVING RESULTS TO TABLES:
run_details
preds
total run time : 0.85 seconds
--------------------------------------------------
11 / 40
current local expert:
                    x            y        lon        lat        t         z  \
2588477 -1.040816e+06  611609.9387 -120.43957  79.174389  18262.0 -0.006905

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2588477   1251  2020-01-01       cs2        1.0      2.750053e+06     0.060972
'local_data_select': 0.001 seconds
number obs: 158
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.051 seconds
'_read_params_from_file': 0.050 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters

2026-05-18 19:18:59.631797: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:18:59.633214: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  1.03054087])
kernel_variance: 0.05299041454597076
likelihood_variance: 0.01100000000000001
'predict': 0.031 seconds
total run time : 0.77 seconds
--------------------------------------------------
12 / 40
current local expert:
                    x              y        lon        lat        t        z  \
2588540 -1.006600e+06  599943.128847 -120.79533  79.492705  18262.0 -0.09014

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2588540   1251  2020-01-01       cs2        1.0      2.786116e+06     0.060972
'local_data_select': 0.001 seconds
number obs: 181
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'_read_params_from_file': 0.045 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  1.03682185])
kernel_variance: 0.05713638980211463
likelihood_variance: 0.01100000000000001
'predict': 0.031 seconds

2026-05-18 19:19:00.403519: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:19:00.405566: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.76 seconds
--------------------------------------------------
13 / 40
current local expert:
                     x              y        lon        lat        t  \
2588571 -991773.649601  594876.428201 -120.95578  79.630534  18262.0

                z  track date_string satellite  lead_mask  dist_along_track  \
2588571  0.010354   1251  2020-01-01       cs2        1.0      2.801744e+06

         z_track_avg
2588571     0.060972
'local_data_select': 0.001 seconds
number obs: 187
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.054 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  1.04002607])
kernel_variance: 0.05887043117167508
likelihood_variance: 0.01100000000000001
'predict': 0.031 seconds

2026-05-18 19:19:01.176034: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:19:01.177437: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.79 seconds
--------------------------------------------------
14 / 40
current local expert:
                     x             y        lon        lat        t         z  \
2588614 -969533.670144  587263.90289 -121.20404  79.837145  18262.0  0.024825

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2588614   1251  2020-01-01       cs2        1.0      2.825187e+06     0.060972
'local_data_select': 0.001 seconds
number obs: 195
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.047 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  1.04541491])
kernel_variance: 0.061373168378954256
likelihood_variance: 0.01100000000000001
'predict': 0.031 seconds

2026-05-18 19:19:01.957321: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:19:01.958727: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.77 seconds
--------------------------------------------------
15 / 40
current local expert:
                     x              y        lon        lat        t  \
2588627 -965542.062182  585895.852954 -121.24959  79.874211  18262.0

                z  track date_string satellite  lead_mask  dist_along_track  \
2588627 -0.129626   1251  2020-01-01       cs2        1.0      2.829394e+06

         z_track_avg
2588627     0.060972
'local_data_select': 0.001 seconds
number obs: 202
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.050 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  1.04645782])
kernel_variance: 0.06180796251336747
likelihood_variance: 0.01100000000000001
'predict': 0.031 seconds

2026-05-18 19:19:02.727048: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:19:02.728454: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.78 seconds
--------------------------------------------------
16 / 40
current local expert:
                     x              y        lon        lat        t  \
2588732 -901390.556758  563844.541536 -122.02711  80.469136  18262.0

                z  track date_string satellite  lead_mask  dist_along_track  \
2588732  0.081213   1251  2020-01-01       cs2        1.0      2.897020e+06

         z_track_avg
2588732     0.060972
'local_data_select': 0.001 seconds
number obs: 220
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.049 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  1.06638489])
kernel_variance: 0.06804272588073193
likelihood_variance: 0.01100000000000001
'predict': 0.032 seconds

2026-05-18 19:19:03.509902: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:19:03.511321: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.77 seconds
--------------------------------------------------
17 / 40
current local expert:
                     x              y        lon        lat        t        z  \
2588738 -896258.608641  562075.056898 -122.09326  80.516661  18262.0 -0.01732

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2588738   1251  2020-01-01       cs2        1.0      2.902430e+06     0.060972
'local_data_select': 0.001 seconds
number obs: 224
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.047 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  1.06822583])
kernel_variance: 0.06847228157602951
likelihood_variance: 0.01100000000000001
'predict': 0.031 seconds

2026-05-18 19:19:04.277082: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:19:04.278489: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.78 seconds
--------------------------------------------------
18 / 40
current local expert:
                     x              y        lon        lat        t  \
2588791 -873735.751503  554299.633673 -122.39112  80.725108  18262.0

                z  track date_string satellite  lead_mask  dist_along_track  \
2588791 -0.217091   1251  2020-01-01       cs2        1.0      2.926176e+06

         z_track_avg
2588791     0.060972
'local_data_select': 0.001 seconds
number obs: 227
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  1.07668684])
kernel_variance: 0.07022450738299142
likelihood_variance: 0.01100000000000001
'predict': 0.032 seconds

2026-05-18 19:19:05.058299: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:19:05.059732: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.78 seconds
--------------------------------------------------
19 / 40
current local expert:
                     x              y        lon        lat        t  \
2588811 -865468.198014  551441.564708 -122.50365  80.801569  18262.0

                z  track date_string satellite  lead_mask  dist_along_track  \
2588811  0.103901   1251  2020-01-01       cs2        1.0      2.934892e+06

         z_track_avg
2588811     0.060972
'local_data_select': 0.001 seconds
number obs: 228
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.046 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  1.07993565])
kernel_variance: 0.07081256745743078
likelihood_variance: 0.01100000000000001
'predict': 0.031 seconds

2026-05-18 19:19:05.840271: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:19:05.841669: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.78 seconds
--------------------------------------------------
20 / 40
current local expert:
                     x              y        lon        lat        t        z  \
2588884 -825841.706658  537713.717377 -123.06855  81.167611  18262.0  0.10003

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2588884   1251  2020-01-01       cs2        1.0      2.976673e+06     0.060972
'local_data_select': 0.001 seconds
number obs: 247
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.051 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  1.09633064])
kernel_variance: 0.07322173948109867
likelihood_variance: 0.01100000000000001
'predict': 0.032 seconds

2026-05-18 19:19:06.625867: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:19:06.627294: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

SAVING RESULTS TO TABLES:
run_details
preds
total run time : 0.86 seconds
--------------------------------------------------
21 / 40
current local expert:
                     x              y        lon       lat        t         z  \
2588919 -807882.585394  531476.298934 -123.33945  81.33325  18262.0  0.028889

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2588919   1251  2020-01-01       cs2        1.0      2.995610e+06     0.060972
'local_data_select': 0.001 seconds
number obs: 252
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.045 seconds
'_read_params_from_file': 0.050 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds

2026-05-18 19:19:07.480227: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:19:07.481710: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  1.10405641])
kernel_variance: 0.07409907844062219
likelihood_variance: 0.01100000000000001
'predict': 0.032 seconds
total run time : 0.77 seconds
--------------------------------------------------
22 / 40
current local expert:
                     x              y        lon        lat        t  \
2588965 -779662.499145  521655.029563 -123.78561  81.593176  18262.0

                z  track date_string satellite  lead_mask  dist_along_track  \
2588965 -0.023154   1251  2020-01-01       cs2        1.0      3.025369e+06

         z_track_avg
2588965     0.060972
'local_data_select': 0.001 seconds
number obs: 243
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.047 seconds
'_read_params_from_file': 0.045 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  1.11627363])
kernel_variance: 0.07523380802129669
likelihood_variance: 0.01100000000000001
'predict': 0.032 seconds

2026-05-18 19:19:08.255583: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:19:08.256984: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.77 seconds
--------------------------------------------------
23 / 40
current local expert:
                     x              y        lon        lat        t  \
2589008 -757999.936636  514099.500007 -124.14636  81.792388  18262.0

                z  track date_string satellite  lead_mask  dist_along_track  \
2589008  0.050337   1251  2020-01-01       cs2        1.0      3.048215e+06

         z_track_avg
2589008     0.060972
'local_data_select': 0.001 seconds
number obs: 236
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.045 seconds
'_read_params_from_file': 0.045 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  1.12549936])
kernel_variance: 0.0759276692869317
likelihood_variance: 0.01100000000000001
'predict': 0.032 seconds

2026-05-18 19:19:09.024236: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:19:09.025645: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.78 seconds
--------------------------------------------------
24 / 40
current local expert:
                     x             y        lon        lat        t         z  \
2589060 -730353.492745  504435.80944 -124.63181  82.046197  18262.0  0.004148

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2589060   1251  2020-01-01       cs2        1.0      3.077374e+06     0.060972
'local_data_select': 0.001 seconds
number obs: 241
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.047 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  1.13675599])
kernel_variance: 0.07663243033588375
likelihood_variance: 0.01100000000000001
'predict': 0.032 seconds

2026-05-18 19:19:09.807105: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:19:09.808519: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.78 seconds
--------------------------------------------------
25 / 40
current local expert:
                     x              y        lon       lat        t         z  \
2589109 -706983.941063  496248.849214 -125.06593  82.26033  18262.0 -0.021248

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2589109   1251  2020-01-01       cs2        1.0      3.102024e+06     0.060972
'local_data_select': 0.001 seconds
number obs: 256
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.045 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  1.14555562])
kernel_variance: 0.07710806958920786
likelihood_variance: 0.01100000000000001
'predict': 0.032 seconds

2026-05-18 19:19:10.586294: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:19:10.587731: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.78 seconds
--------------------------------------------------
26 / 40
current local expert:
                     x              y        lon        lat        t  \
2589163 -683900.823065  488145.597132 -125.51798  82.471435  18262.0

                z  track date_string satellite  lead_mask  dist_along_track  \
2589163 -0.115976   1251  2020-01-01       cs2        1.0      3.126375e+06

         z_track_avg
2589163     0.060972
'local_data_select': 0.001 seconds
number obs: 256
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.052 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  1.15337904])
kernel_variance: 0.07750466110005318
likelihood_variance: 0.01100000000000001
'predict': 0.032 seconds

2026-05-18 19:19:11.374868: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:19:11.376269: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.79 seconds
--------------------------------------------------
27 / 40
current local expert:
                     x              y       lon        lat        t         z  \
2589211 -660249.417026  479826.058081 -126.0072  82.687282  18262.0  0.010036

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2589211   1251  2020-01-01       cs2        1.0      3.151327e+06     0.060972
'local_data_select': 0.001 seconds
number obs: 236
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.047 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01     , 10.01     ,  1.1603086])
kernel_variance: 0.07786717574773065
likelihood_variance: 0.01100000000000001
'predict': 0.031 seconds

2026-05-18 19:19:12.157327: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:19:12.158765: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.77 seconds
--------------------------------------------------
28 / 40
current local expert:
                     x              y        lon        lat        t  \
2589254 -642868.492009  473701.197684 -126.38485  82.845586  18262.0

                z  track date_string satellite  lead_mask  dist_along_track  \
2589254  0.026848   1251  2020-01-01       cs2        1.0      3.169665e+06

         z_track_avg
2589254     0.060972
'local_data_select': 0.001 seconds
number obs: 247
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.051 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  1.16460666])
kernel_variance: 0.07812183006602902
likelihood_variance: 0.01100000000000001
'predict': 0.032 seconds

2026-05-18 19:19:12.928078: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:19:12.929507: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.78 seconds
--------------------------------------------------
29 / 40
current local expert:
                     x             y        lon        lat        t         z  \
2589294 -620075.412118  465654.98041 -126.90527  83.052741  18262.0 -0.063366

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2589294   1251  2020-01-01       cs2        1.0      3.193716e+06     0.060972
'local_data_select': 0.001 seconds
number obs: 249
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.049 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  1.16913289])
kernel_variance: 0.07845835010182586
likelihood_variance: 0.01100000000000001
'predict': 0.032 seconds

2026-05-18 19:19:13.710122: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:19:13.711535: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.77 seconds
--------------------------------------------------
30 / 40
current local expert:
                     x              y        lon        lat        t  \
2589356 -591016.708346  455373.909963 -127.61398  83.316041  18262.0

                z  track date_string satellite  lead_mask  dist_along_track  \
2589356 -0.002835   1251  2020-01-01       cs2        1.0      3.224382e+06

         z_track_avg
2589356     0.060972
'local_data_select': 0.001 seconds
number obs: 253
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.050 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  1.17297519])
kernel_variance: 0.07891570213821797
likelihood_variance: 0.01100000000000001
'predict': 0.032 seconds

2026-05-18 19:19:14.483327: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:19:14.484745: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

SAVING RESULTS TO TABLES:
run_details
preds
total run time : 0.89 seconds
--------------------------------------------------
31 / 40
current local expert:
                     x              y        lon        lat        t  \
2589407 -569082.695926  447596.232645 -128.18584  83.514129  18262.0

                z  track date_string satellite  lead_mask  dist_along_track  \
2589407 -0.092857   1251  2020-01-01       cs2        1.0      3.247532e+06

         z_track_avg
2589407     0.060972
'local_data_select': 0.001 seconds
number obs: 248
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.047 seconds

2026-05-18 19:19:15.370398: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:19:15.371814: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'_read_params_from_file': 0.051 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  1.17441085])
kernel_variance: 0.07929519055494828
likelihood_variance: 0.01100000000000001
'predict': 0.032 seconds
total run time : 0.79 seconds
--------------------------------------------------
32 / 40
current local expert:
                    x              y        lon        lat        t         z  \
2589468 -545441.58634  439196.665297 -128.84147  83.726932  18262.0 -0.013711

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2589468   1251  2020-01-01       cs2        1.0      3.272486e+06     0.060972
'local_data_select': 0.001 seconds
number obs: 284
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.047 seconds
'_read_params_from_file': 0.045 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  1.17456147])
kernel_variance: 0.0797444727977047
likelihood_variance: 0.01100000000000001
'predict': 0.033 seconds

2026-05-18 19:19:16.160112: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:19:16.161534: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.78 seconds
--------------------------------------------------
33 / 40
current local expert:
                     x              y       lon        lat        t         z  \
2589512 -518955.191627  429765.794712 -129.6294  83.964386  18262.0 -0.011596

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2589512   1251  2020-01-01       cs2        1.0      3.300447e+06     0.060972
'local_data_select': 0.001 seconds
number obs: 309
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.051 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  1.17307709])
kernel_variance: 0.08030005491584298
likelihood_variance: 0.01100000000000001
'predict': 0.033 seconds

2026-05-18 19:19:16.944746: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:19:16.946168: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.79 seconds
--------------------------------------------------
34 / 40
current local expert:
                     x              y        lon        lat        t  \
2589550 -495034.661485  421229.907278 -130.39479  84.177863  18262.0

                z  track date_string satellite  lead_mask  dist_along_track  \
2589550 -0.043501   1251  2020-01-01       cs2        1.0      3.325703e+06

         z_track_avg
2589550     0.060972
'local_data_select': 0.001 seconds
number obs: 312
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  1.17033669])
kernel_variance: 0.08084749282828109
likelihood_variance: 0.01100000000000001
'predict': 0.034 seconds

2026-05-18 19:19:17.730804: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:19:17.732238: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.78 seconds
--------------------------------------------------
35 / 40
current local expert:
                     x              y        lon        lat        t  \
2589610 -464853.201865  410434.711283 -131.44238  84.445721  18262.0

                z  track date_string satellite  lead_mask  dist_along_track  \
2589610 -0.119051   1251  2020-01-01       cs2        1.0      3.357575e+06

         z_track_avg
2589610     0.060972
'local_data_select': 0.001 seconds
number obs: 326
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.047 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  1.16517959])
kernel_variance: 0.08159268567017179
likelihood_variance: 0.01100000000000001
'predict': 0.034 seconds

2026-05-18 19:19:18.515120: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:19:18.516527: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.78 seconds
--------------------------------------------------
36 / 40
current local expert:
                     x              y        lon        lat        t  \
2589641 -452041.691408  405843.814446 -131.91755  84.558862  18262.0

                z  track date_string satellite  lead_mask  dist_along_track  \
2589641 -0.036274   1251  2020-01-01       cs2        1.0      3.371105e+06

         z_track_avg
2589641     0.060972
'local_data_select': 0.001 seconds
number obs: 332
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  1.16248058])
kernel_variance: 0.08192452784265936
likelihood_variance: 0.01100000000000001
'predict': 0.033 seconds

2026-05-18 19:19:19.296152: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:19:19.297562: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.78 seconds
--------------------------------------------------
37 / 40
current local expert:
                    x              y       lon       lat        t         z  \
2589681 -429552.48873  397772.751087 -132.8002  84.75657  18262.0  0.050795

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2589681   1251  2020-01-01       cs2        1.0      3.394859e+06     0.060972
'local_data_select': 0.001 seconds
number obs: 330
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.047 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  1.15710413])
kernel_variance: 0.0825248186391741
likelihood_variance: 0.01100000000000001
'predict': 0.034 seconds

2026-05-18 19:19:20.080247: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:19:20.081660: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.78 seconds
--------------------------------------------------
38 / 40
current local expert:
                     x              y       lon        lat        t         z  \
2589724 -405358.079779  389072.244057 -133.8256  84.967855  18262.0 -0.011415

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2589724   1251  2020-01-01       cs2        1.0      3.420417e+06     0.060972
'local_data_select': 0.001 seconds
number obs: 330
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.051 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  1.15053996])
kernel_variance: 0.08318975418467116
likelihood_variance: 0.01100000000000001
'predict': 0.034 seconds

2026-05-18 19:19:20.867211: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:19:20.868636: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.79 seconds
--------------------------------------------------
39 / 40
current local expert:
                     x              y        lon        lat        t  \
2589762 -373768.142581  377685.072187 -135.29865  85.241194  18262.0

                z  track date_string satellite  lead_mask  dist_along_track  \
2589762  0.009501   1251  2020-01-01       cs2        1.0      3.453794e+06

         z_track_avg
2589762     0.060972
'local_data_select': 0.001 seconds
number obs: 332
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.047 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  1.14101511])
kernel_variance: 0.08407548417246923
likelihood_variance: 0.01100000000000001
'predict': 0.034 seconds

2026-05-18 19:19:21.650802: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:19:21.652389: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.77 seconds
--------------------------------------------------
40 / 40
current local expert:
                     x              y        lon        lat        t        z  \
2589781 -352996.033332  370180.583495 -136.36124  85.419138  18262.0 -0.00293

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2589781   1251  2020-01-01       cs2        1.0      3.475745e+06     0.060972
'local_data_select': 0.001 seconds
number obs: 325
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.049 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  1.13431637])
kernel_variance: 0.08466187780650229
likelihood_variance: 0.01100000000000001
'predict': 0.034 seconds

2026-05-18 19:19:22.423942: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:19:22.425345: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

SAVING RESULTS TO TABLES:
run_details
preds
total run time : 0.92 seconds
'run': 31.619 seconds
reading in results
getting all tables
merging on expert location data
table: 'oi_config' does not have all coords_col: ['x', 'y', 't'] in columns, not merging on expert_locations
table: 'oi_config_SMOOTHED' does not have all coords_col: ['x', 'y', 't'] in columns, not merging on expert_locations
lin:
                    x              y        lon        lat        t         z  \
2588121  1.299330e+06  301319.312827  103.05631  78.034879  18262.0 -0.012229
2588122  1.299631e+06  301331.522138  103.05390  78.032213  18262.0       NaN
2588123  1.300835e+06  301381.067972  103.04430  78.021547  18262.0       NaN
2588124  1.301437e+06  301405.666626  103.03950  78.016215  18262.0       NaN
2588125  1.301738e+06  301417.928656  103.03710  78.013549  18262.0       NaN

         track date_string satellite  lead_mask  dist_along_track  \
2588121   1251  2020-01-01       cs2        1.0          0.000000
2588122   1251  2020-01-01       cs2        0.0        300.933258
2588123   1251  2020-01-01       cs2        0.0       1504.737483
2588124   1251  2020-01-01       cs2        0.0       2106.543895
2588125   1251  2020-01-01       cs2        0.0       2407.450437

         z_track_avg     f_lin
2588121     0.060972  0.038294
2588122     0.060972  0.040719
2588123     0.060972  0.043145
2588124     0.060972  0.045571
2588125     0.060972  0.047996
gpsat:
                    x              y        lon        lat        t         z  \
2588121  1.299330e+06  301319.312827  103.05631  78.034879  18262.0 -0.012229
2588122  1.299631e+06  301331.522138  103.05390  78.032213  18262.0       NaN
2588123  1.300835e+06  301381.067972  103.04430  78.021547  18262.0       NaN
2588124  1.301437e+06  301405.666626  103.03950  78.016215  18262.0       NaN
2588125  1.301738e+06  301417.928656  103.03710  78.013549  18262.0       NaN

         track date_string satellite  lead_mask  dist_along_track  \
2588121   1251  2020-01-01       cs2        1.0          0.000000
2588122   1251  2020-01-01       cs2        0.0        300.933258
2588123   1251  2020-01-01       cs2        0.0       1504.737483
2588124   1251  2020-01-01       cs2        0.0       2106.543895
2588125   1251  2020-01-01       cs2        0.0       2407.450437

         z_track_avg   f_gpsat  f_var_gpsat
2588121     0.060972 -0.013889    -0.013889
2588122     0.060972 -0.012984    -0.012984
2588123     0.060972 -0.009351    -0.009351
2588124     0.060972 -0.007442    -0.007442
2588125     0.060972 -0.006443    -0.006443
Test NaNs — Linear: 0, GPSat: 330
Track interpolated!
Interpolating track 1253, 10 of 15...

/tmp/ipykernel_1171781/839927469.py:200: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  track_df['f_gpsat'] = ssha
/tmp/ipykernel_1171781/839927469.py:201: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  track_df['f_var_gpsat'] = ssha_var
/tmp/ipykernel_1171781/839927469.py:66: RuntimeWarning: invalid value encountered in sqrt
  gpsat_std = np.sqrt(gpsat_var[both_valid])

Expert limit reached.
'data_select': 0.000 seconds
'load': 0.000 seconds
in json_serializable - key: 'data_source' has value DataFrame/Series, but is too long: 2035 >  100
storing as str
in json_serializable - key: 'df' has value DataFrame/Series, but is too long: 6622 >  100
storing as str
---------
storing expert locations in 'expert_locs' table
exception occurred: 'No object named expert_locs in the file'
will now close object

---------
dropping expert locations that already exists in 'run_details' table
exception occurred: 'No object named run_details in the file'
will now close object

--------------------------------------------------
1 / 40
current local expert:
                    x             y        lon        lat        t         z  \
2594585 -1.469649e+06  1.718644e+06 -139.46554  69.638938  18262.0  0.002592

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2594585   1253  2020-01-01       cs2        1.0       4202.402161     0.097461
'data_select': 0.000 seconds
'load': 0.000 seconds
'local_data_select': 0.001 seconds
number obs: 460
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.047 seconds
'get_parameters': 0.003 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:19:24.519239: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:19:24.520650: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.514 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.0100715 , 10.01005886,  1.00506397])
kernel_variance: 0.018508174507371387
likelihood_variance: 0.004375969326020314
'predict': 0.035 seconds
total run time : 1.25 seconds
--------------------------------------------------
2 / 40
current local expert:
                    x             y        lon        lat        t         z  \
2594606 -1.455083e+06  1.705499e+06 -139.53012  69.816098  18262.0 -0.012831

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2594606   1253  2020-01-01       cs2        1.0      24013.794557     0.097461
'local_data_select': 0.001 seconds
number obs: 481
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:19:25.774857: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:19:25.776267: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'optimise_parameters': 0.533 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01007242, 10.01005983,  0.99602203])
kernel_variance: 0.017115121995698233
likelihood_variance: 0.004403164383521596
'predict': 0.036 seconds
total run time : 1.26 seconds
--------------------------------------------------
3 / 40
current local expert:
                    x             y        lon        lat        t         z  \
2594635 -1.435666e+06  1.687953e+06 -139.61761  70.052296  18262.0 -0.031844

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2594635   1253  2020-01-01       cs2        1.0      50429.846201     0.097461
'local_data_select': 0.001 seconds
number obs: 490
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.049 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:19:27.039942: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:19:27.041332: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.632 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01007977, 10.01006623,  0.99369457])
kernel_variance: 0.01621920671253595
likelihood_variance: 0.004373319468175197
'predict': 0.036 seconds
total run time : 1.37 seconds
--------------------------------------------------
4 / 40
current local expert:
                    x             y        lon       lat        t         z  \
2594681 -1.417588e+06  1.671595e+06 -139.70055  70.27224  18262.0 -0.057792

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2594681   1253  2020-01-01       cs2        1.0      75030.801563     0.097461
'local_data_select': 0.001 seconds
number obs: 499
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.049 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:19:28.411122: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:19:28.412518: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'optimise_parameters': 0.591 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01007764, 10.01006461,  0.99378322])
kernel_variance: 0.01758455055469869
likelihood_variance: 0.004315551815148326
'predict': 0.036 seconds
total run time : 1.33 seconds
--------------------------------------------------
5 / 40
current local expert:
                    x             y        lon        lat        t        z  \
2594744 -1.399283e+06  1.655010e+06 -139.78605  70.494969  18262.0  0.02889

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2594744   1253  2020-01-01       cs2        1.0      99946.109263     0.097461
'local_data_select': 0.001 seconds
number obs: 516
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:19:29.743908: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:19:29.745312: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'optimise_parameters': 0.606 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01007657, 10.01006397,  1.00201571])
kernel_variance: 0.01645645812141488
likelihood_variance: 0.004241278795349486
'predict': 0.040 seconds
total run time : 1.34 seconds
--------------------------------------------------
6 / 40
current local expert:
                    x             y        lon        lat        t         z  \
2594807 -1.382745e+06  1.640008e+06 -139.86465  70.696214  18262.0 -0.109041

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2594807   1253  2020-01-01       cs2        1.0     122460.671155     0.097461
'local_data_select': 0.001 seconds
number obs: 536
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.049 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:19:31.085104: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:19:31.086490: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'optimise_parameters': 0.457 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01007272, 10.01006089,  0.99984666])
kernel_variance: 0.01767505258258601
likelihood_variance: 0.004165744902964289
'predict': 0.040 seconds
total run time : 1.21 seconds
--------------------------------------------------
7 / 40
current local expert:
                    x             y        lon        lat        t         z  \
2594863 -1.362684e+06  1.621785e+06 -139.96178  70.940369  18262.0  0.139116

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2594863   1253  2020-01-01       cs2        1.0     149779.168086     0.097461
'local_data_select': 0.001 seconds
number obs: 566
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.053 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:19:32.297242: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:19:32.299362: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'optimise_parameters': 0.754 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01007453, 10.01006251,  0.99835685])
kernel_variance: 0.016485414763770703
likelihood_variance: 0.004226036109051883
'predict': 0.040 seconds
total run time : 1.51 seconds
--------------------------------------------------
8 / 40
current local expert:
                    x             y        lon        lat        t         z  \
2594907 -1.343949e+06  1.604744e+06 -140.05432  71.168404  18262.0  0.184407

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2594907   1253  2020-01-01       cs2        1.0     175297.442308     0.097461
'local_data_select': 0.001 seconds
number obs: 609
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:19:33.802818: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:19:33.804241: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'optimise_parameters': 0.396 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01007538, 10.01006343,  1.00077841])
kernel_variance: 0.01577616167096377
likelihood_variance: 0.004115740266422231
'predict': 0.048 seconds
total run time : 1.14 seconds
--------------------------------------------------
9 / 40
current local expert:
                    x             y        lon        lat        t        z  \
2594972 -1.325660e+06  1.588085e+06 -140.14643  71.391051  18262.0  0.13367

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2594972   1253  2020-01-01       cs2        1.0     200216.081456     0.097461
'local_data_select': 0.001 seconds
number obs: 627
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.047 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:19:34.947999: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:19:34.949396: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'optimise_parameters': 0.521 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01009483, 10.01008009,  0.99871582])
kernel_variance: 0.014183177169706669
likelihood_variance: 0.004231656023520575
'predict': 0.043 seconds
total run time : 1.28 seconds
--------------------------------------------------
10 / 40
current local expert:
                    x             y        lon        lat        t        z  \
2595024 -1.307154e+06  1.571207e+06 -140.24148  71.616355  18262.0  0.22194

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2595024   1253  2020-01-01       cs2        1.0     225435.589977     0.097461
'local_data_select': 0.001 seconds
number obs: 648
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.049 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:19:36.230630: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:19:36.232040: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 1.100 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01008872, 10.01007495,  0.99627219])
kernel_variance: 0.013536196306115782
likelihood_variance: 0.004247330612976632
'predict': 0.043 seconds
SAVING RESULTS TO TABLES:
run_details
preds
lengthscales
kernel_variance
likelihood_variance
total run time : 1.98 seconds
--------------------------------------------------
11 / 40
current local expert:
                    x             y        lon        lat        t         z  \
2595065 -1.289534e+06  1.555115e+06 -140.33377  71.830908  18262.0  0.194234

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2595065   1253  2020-01-01       cs2        1.0     249455.035394     0.097461
'local_data_select': 0.001 seconds
number obs: 668
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.052 seconds
'set_lengthscales_constraints': 0.006 seconds

2026-05-18 19:19:38.218751: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:19:38.220194: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'set_likelihood_variance_constraints': 0.010 seconds
**********
optimization failed!
'optimise_parameters': 1.160 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01007893, 10.01006591,  0.99969395])
kernel_variance: 0.015081546002911178
likelihood_variance: 0.004874263635261113
'predict': 0.045 seconds
total run time : 1.91 seconds
--------------------------------------------------
12 / 40
current local expert:
                    x             y        lon        lat        t         z  \
2595116 -1.270817e+06  1.538000e+06 -140.43379  72.058843  18262.0  0.195247

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2595116   1253  2020-01-01       cs2        1.0     274976.361972     0.097461
'local_data_select': 0.001 seconds
number obs: 693
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.047 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:19:40.128426: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:19:40.129841: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 1.083 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01007551, 10.01006303,  1.00003842])
kernel_variance: 0.01647633788314799
likelihood_variance: 0.005015561443017816
'predict': 0.045 seconds
total run time : 1.84 seconds
--------------------------------------------------
13 / 40
current local expert:
                    x             y        lon        lat        t         z  \
2595164 -1.251225e+06  1.520059e+06 -140.54076  72.297473  18262.0  0.220563

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2595164   1253  2020-01-01       cs2        1.0     301699.461908     0.097461
'local_data_select': 0.001 seconds
number obs: 711
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.046 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:19:41.967184: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:19:41.968610: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'optimise_parameters': 0.505 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01007956, 10.01006659,  0.99907272])
kernel_variance: 0.015341377685728375
likelihood_variance: 0.0051611503600995385
'predict': 0.045 seconds
total run time : 1.25 seconds
--------------------------------------------------
14 / 40
current local expert:
                    x             y        lon        lat        t         z  \
2595202 -1.233178e+06  1.503511e+06 -140.64144  72.517305  18262.0  0.206252

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2595202   1253  2020-01-01       cs2        1.0     326321.551441     0.097461
'local_data_select': 0.001 seconds
number obs: 715
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.047 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:19:43.222415: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:19:43.223958: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 1.863 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01007893, 10.01006609,  1.0008476 ])
kernel_variance: 0.014590994381552645
likelihood_variance: 0.0051758128683806436
'predict': 0.047 seconds
total run time : 2.62 seconds
--------------------------------------------------
15 / 40
current local expert:
                    x             y        lon        lat        t         z  \
2595273 -1.209195e+06  1.481487e+06 -140.77855  72.809477  18262.0  0.188842

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2595273   1253  2020-01-01       cs2        1.0     359052.321878     0.097461
'local_data_select': 0.001 seconds
number obs: 725
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.050 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:19:45.847355: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:19:45.848800: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 1.098 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01008514, 10.01007152,  0.99678914])
kernel_variance: 0.013749939251390154
likelihood_variance: 0.005191199323091948
'predict': 0.047 seconds
total run time : 1.87 seconds
--------------------------------------------------
16 / 40
current local expert:
                    x             y        lon        lat        t         z  \
2595308 -1.197317e+06  1.470565e+06 -140.84792  72.954202  18262.0  0.229138

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2595308   1253  2020-01-01       cs2        1.0     375268.034221     0.097461
'local_data_select': 0.001 seconds
number obs: 755
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:19:47.715112: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:19:47.716541: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 1.034 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01008277, 10.01006973,  0.99714315])
kernel_variance: 0.013698506002791419
likelihood_variance: 0.005042297640046764
'predict': 0.049 seconds
total run time : 1.79 seconds
--------------------------------------------------
17 / 40
current local expert:
                    x             y        lon        lat        t         z  \
2595356 -1.179283e+06  1.453965e+06 -140.95515  73.173942  18262.0  0.254031

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2595356   1253  2020-01-01       cs2        1.0     399892.439717     0.097461
'local_data_select': 0.001 seconds
number obs: 764
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:19:49.507938: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:19:49.509360: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 1.231 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01009049, 10.01007652,  0.99812559])
kernel_variance: 0.013992025570936003
likelihood_variance: 0.005009893395072484
'predict': 0.049 seconds
total run time : 1.99 seconds
--------------------------------------------------
18 / 40
current local expert:
                    x             y        lon        lat        t         z  \
2595411 -1.160815e+06  1.436943e+06 -141.06744  73.399005  18262.0  0.231516

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2595411   1253  2020-01-01       cs2        1.0     425118.054869     0.097461
'local_data_select': 0.001 seconds
number obs: 779
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:19:51.500372: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:19:51.501789: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'optimise_parameters': 0.931 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01007719, 10.01006503,  0.99985676])
kernel_variance: 0.013316269380933724
likelihood_variance: 0.005104884293739092
'predict': 0.049 seconds
total run time : 1.70 seconds
--------------------------------------------------
19 / 40
current local expert:
                    x             y        lon        lat        t         z  \
2595456 -1.142133e+06  1.419700e+06 -141.18371  73.626708  18262.0  0.151002

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2595456   1253  2020-01-01       cs2        1.0      450644.72188     0.097461
'local_data_select': 0.001 seconds
number obs: 767
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.051 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:19:53.202249: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:19:53.203670: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'optimise_parameters': 0.842 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01007994, 10.01006791,  0.99895591])
kernel_variance: 0.013392361099394436
likelihood_variance: 0.005106387775618623
'predict': 0.049 seconds
total run time : 1.62 seconds
--------------------------------------------------
20 / 40
current local expert:
                    x             y        lon        lat        t         z  \
2595501 -1.122357e+06  1.401422e+06 -141.30982  73.867762  18262.0  0.188292

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2595501   1253  2020-01-01       cs2        1.0     477673.904925     0.097461
'local_data_select': 0.001 seconds
number obs: 751
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.052 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:19:54.828496: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:19:54.829915: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.958 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.0100991 , 10.01008498,  0.99700676])
kernel_variance: 0.013915598879317558
likelihood_variance: 0.004818111849858026
'predict': 0.049 seconds
SAVING RESULTS TO TABLES:
run_details
preds
lengthscales
kernel_variance
likelihood_variance
total run time : 1.86 seconds
--------------------------------------------------
21 / 40
current local expert:
                    x             y        lon        lat        t         z  \
2595540 -1.107199e+06  1.387396e+06 -141.40869  74.052538  18262.0  0.166627

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2595540   1253  2020-01-01       cs2        1.0     498396.942877     0.097461
'local_data_select': 0.001 seconds
number obs: 737
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.053 seconds

2026-05-18 19:19:56.695446: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:19:56.696868: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds
**********
optimization failed!
'optimise_parameters': 1.109 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01008264, 10.01007099,  1.00178317])
kernel_variance: 0.012476439692496944
likelihood_variance: 0.0050295753860398525
'predict': 0.049 seconds
total run time : 1.87 seconds
--------------------------------------------------
22 / 40
current local expert:
                    x             y        lon        lat        t         z  \
2595589 -1.088532e+06  1.370100e+06 -141.53319  74.280118  18262.0  0.163521

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2595589   1253  2020-01-01       cs2        1.0     523925.797263     0.097461
'local_data_select': 0.001 seconds
number obs: 717
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.054 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:19:58.573476: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:19:58.574882: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'optimise_parameters': 0.670 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01007837, 10.01006796,  0.99475185])
kernel_variance: 0.012312672569684699
likelihood_variance: 0.005149706564917078
'predict': 0.047 seconds
total run time : 1.45 seconds
--------------------------------------------------
23 / 40
current local expert:
                    x             y        lon        lat        t         z  \
2595646 -1.069650e+06  1.352583e+06 -141.66233  74.510328  18262.0  0.197352

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2595646   1253  2020-01-01       cs2        1.0     549755.877133     0.097461
'local_data_select': 0.001 seconds
number obs: 696
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.051 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:20:00.024116: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:20:00.025534: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'optimise_parameters': 1.340 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01041573, 10.01036627,  1.00543842])
kernel_variance: 0.012040043215132367
likelihood_variance: 0.004921349276021738
'predict': 0.048 seconds
total run time : 2.12 seconds
--------------------------------------------------
24 / 40
current local expert:
                    x             y        lon        lat        t         z  \
2595699 -1.051214e+06  1.335456e+06 -141.79168  74.735132  18262.0  0.140633

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2595699   1253  2020-01-01       cs2        1.0      574985.67114     0.097461
'local_data_select': 0.001 seconds
number obs: 705
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.047 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:20:02.143566: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:20:02.145075: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.936 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.0101177 , 10.01010215,  1.00007614])
kernel_variance: 0.010308164883821148
likelihood_variance: 0.004792587915362691
'predict': 0.047 seconds
total run time : 1.71 seconds
--------------------------------------------------
25 / 40
current local expert:
                    x             y        lon        lat        t         z  \
2595730 -1.033002e+06  1.318515e+06 -141.92275  74.957211  18262.0  0.169184

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2595730   1253  2020-01-01       cs2        1.0      599916.00983     0.097461
'local_data_select': 0.001 seconds
number obs: 699
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.047 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:20:03.860540: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:20:03.861940: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 1.421 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([19.99990713, 19.99856062,  0.82650372])
kernel_variance: 0.01174265969252754
likelihood_variance: 0.004989523967458226
'predict': 0.048 seconds
total run time : 2.20 seconds
--------------------------------------------------
26 / 40
current local expert:
                    x             y        lon        lat        t         z  \
2595774 -1.015674e+06  1.302375e+06 -142.05065  75.168538  18262.0  0.203622

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2595774   1253  2020-01-01       cs2        1.0      623645.51678     0.097461
'local_data_select': 0.001 seconds
number obs: 688
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:20:06.063134: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:20:06.064542: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'optimise_parameters': 0.906 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01007878, 10.0100694 ,  1.00000911])
kernel_variance: 0.011293530512906984
likelihood_variance: 0.004913339970084568
'predict': 0.045 seconds
total run time : 1.69 seconds
--------------------------------------------------
27 / 40
current local expert:
                     x             y        lon        lat        t         z  \
2595826 -996815.620509  1.284787e+06 -142.19352  75.398533  18262.0  0.009416

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2595826   1253  2020-01-01       cs2        1.0      649478.34294     0.097461
'local_data_select': 0.001 seconds
number obs: 667
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:20:07.751037: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:20:07.752470: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 1.248 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01008422, 10.01007447,  0.99973413])
kernel_variance: 0.009735115014345288
likelihood_variance: 0.0049682335899541834
'predict': 0.046 seconds
total run time : 2.02 seconds
--------------------------------------------------
28 / 40
current local expert:
                     x             y        lon        lat        t         z  \
2595876 -979278.724107  1.268410e+06 -142.32999  75.612424  18262.0  0.199559

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2595876   1253  2020-01-01       cs2        1.0     673509.409548     0.097461
'local_data_select': 0.001 seconds
number obs: 670
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.051 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:20:09.772783: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:20:09.774202: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.799 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01008275, 10.01007283,  0.99674096])
kernel_variance: 0.01226852250449231
likelihood_variance: 0.004387093722957299
'predict': 0.045 seconds
total run time : 1.58 seconds
--------------------------------------------------
29 / 40
current local expert:
                    x             y       lon        lat        t         z  \
2595928 -959337.04267  1.249763e+06 -142.4896  75.855657  18262.0  0.152152

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2595928   1253  2020-01-01       cs2        1.0     700845.711095     0.097461
'local_data_select': 0.001 seconds
number obs: 684
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.047 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:20:11.353272: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:20:11.354677: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'optimise_parameters': 0.422 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01008057, 10.0100707 ,  1.0087538 ])
kernel_variance: 0.012992986755080389
likelihood_variance: 0.004040013375286799
'predict': 0.046 seconds
total run time : 1.21 seconds
--------------------------------------------------
30 / 40
current local expert:
                     x             y        lon        lat        t         z  \
2595978 -943345.060264  1.234789e+06 -142.62116  76.050722  18262.0  0.058406

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2595978   1253  2020-01-01       cs2        1.0     722775.475338     0.097461
'local_data_select': 0.001 seconds
number obs: 690
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.046 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:20:12.565931: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:20:12.567344: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 1.085 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01007926, 10.0100698 ,  1.00094194])
kernel_variance: 0.014105511740064684
likelihood_variance: 0.004041960322767536
'predict': 0.046 seconds
SAVING RESULTS TO TABLES:
run_details
preds
lengthscales
kernel_variance
likelihood_variance
total run time : 2.03 seconds
--------------------------------------------------
31 / 40
current local expert:
                     x             y       lon        lat        t         z  \
2596022 -923635.149058  1.216311e+06 -142.7879  76.291139  18262.0  0.092729

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2596022   1253  2020-01-01       cs2        1.0     749812.841859     0.097461
'local_data_select': 0.001 seconds
number obs: 703
found GPU

2026-05-18 19:20:14.596204: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:20:14.597668: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

setting lengthscales to: [1. 1. 1.]
'__init__': 0.050 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds
**********
optimization failed!
'optimise_parameters': 1.151 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01007438, 10.0100657 ,  1.00664019])
kernel_variance: 0.015610811048871352
likelihood_variance: 0.003993063758995134
'predict': 0.047 seconds
total run time : 1.93 seconds
--------------------------------------------------
32 / 40
current local expert:
                    x             y        lon        lat        t         z  \
2596085 -905026.96619  1.198842e+06 -142.95019  76.518121  18262.0  0.009816

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2596085   1253  2020-01-01       cs2        1.0     775348.812795     0.097461
'local_data_select': 0.001 seconds
number obs: 694
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.050 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:20:16.526816: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:20:16.528238: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 1.078 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.0100734 , 10.01006447,  0.99859576])
kernel_variance: 0.013292039644633052
likelihood_variance: 0.0043337887754271295
'predict': 0.047 seconds
total run time : 1.87 seconds
--------------------------------------------------
33 / 40
current local expert:
                     x             y       lon        lat        t         z  \
2596138 -886425.354483  1.181355e+06 -143.1174  76.745023  18262.0  0.067219

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2596138   1253  2020-01-01       cs2        1.0     800885.517636     0.097461
'local_data_select': 0.001 seconds
number obs: 725
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.049 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:20:18.397010: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:20:18.398405: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 1.114 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01007298, 10.01006448,  1.00356108])
kernel_variance: 0.014463326368898955
likelihood_variance: 0.004097947367624659
'predict': 0.046 seconds
total run time : 1.89 seconds
--------------------------------------------------
34 / 40
current local expert:
                     x             y        lon        lat        t         z  \
2596198 -869580.193386  1.165499e+06 -143.27334  76.950495  18262.0  0.024675

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2596198   1253  2020-01-01       cs2        1.0     824019.255019     0.097461
'local_data_select': 0.001 seconds
number obs: 709
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.047 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:20:20.286634: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:20:20.288032: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 1.077 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01007509, 10.01006671,  1.00155302])
kernel_variance: 0.01109956978990555
likelihood_variance: 0.004100374799423866
'predict': 0.046 seconds
total run time : 1.85 seconds
--------------------------------------------------
35 / 40
current local expert:
                     x             y       lon        lat        t         z  \
2596245 -851865.660583  1.148805e+06 -143.4422  77.166562  18262.0  0.098078

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2596245   1253  2020-01-01       cs2        1.0     848355.458943     0.097461
'local_data_select': 0.001 seconds
number obs: 704
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.049 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:20:22.143632: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:20:22.145028: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.986 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01007504, 10.01006718,  0.99313981])
kernel_variance: 0.011331104303797392
likelihood_variance: 0.004098375906086143
'predict': 0.045 seconds
total run time : 1.76 seconds
--------------------------------------------------
36 / 40
current local expert:
                     x             y        lon        lat        t         z  \
2596314 -832627.438925  1.130650e+06 -143.63152  77.401204  18262.0 -0.004782

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2596314   1253  2020-01-01       cs2        1.0     874795.462903     0.097461
'local_data_select': 0.001 seconds
number obs: 715
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.051 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:20:23.909670: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:20:23.911055: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.930 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01007734, 10.01006967,  1.0008056 ])
kernel_variance: 0.010278887974699008
likelihood_variance: 0.004071697727796225
'predict': 0.048 seconds
total run time : 1.72 seconds
--------------------------------------------------
37 / 40
current local expert:
                     x             y        lon        lat        t         z  \
2596370 -814270.505989  1.113304e+06 -143.81826  77.625079  18262.0  0.036487

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2596370   1253  2020-01-01       cs2        1.0     900034.240442     0.097461
'local_data_select': 0.001 seconds
number obs: 713
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.051 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:20:25.629549: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:20:25.630975: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.898 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01007605, 10.01006891,  0.99227654])
kernel_variance: 0.01201528427189024
likelihood_variance: 0.004011267136926294
'predict': 0.047 seconds
total run time : 1.68 seconds
--------------------------------------------------
38 / 40
current local expert:
                     x             y        lon        lat        t         z  \
2596416 -795046.840181  1.095114e+06 -144.02055  77.859503  18262.0  0.059112

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2596416   1253  2020-01-01       cs2        1.0     926475.546543     0.097461
'local_data_select': 0.001 seconds
number obs: 703
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.049 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:20:27.310466: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:20:27.311865: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'optimise_parameters': 0.954 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01008342, 10.0100761 ,  1.00732997])
kernel_variance: 0.008753314475690551
likelihood_variance: 0.004076173237277216
'predict': 0.047 seconds
total run time : 1.75 seconds
--------------------------------------------------
39 / 40
current local expert:
                     x             y        lon        lat        t         z  \
2596462 -778013.938703  1.078976e+06 -144.20587  78.067187  18262.0  0.097879

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2596462   1253  2020-01-01       cs2        1.0     949912.810667     0.097461
'local_data_select': 0.001 seconds
number obs: 690
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.047 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:20:29.062766: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:20:29.064178: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'optimise_parameters': 1.274 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01007653, 10.01007031,  0.99534185])
kernel_variance: 0.010021754595118715
likelihood_variance: 0.00395588177258059
'predict': 0.046 seconds
total run time : 2.07 seconds
--------------------------------------------------
40 / 40
current local expert:
                     x             y        lon        lat        t         z  \
2596520 -758150.011707  1.060131e+06 -144.42963  78.309356  18262.0  0.044546

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2596520   1253  2020-01-01       cs2        1.0     977256.844554     0.097461
'local_data_select': 0.001 seconds
number obs: 657
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:20:31.140296: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:20:31.141714: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.819 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01007541, 10.01006959,  1.00488666])
kernel_variance: 0.009617965738149365
likelihood_variance: 0.003997909889892284
'predict': 0.046 seconds
SAVING RESULTS TO TABLES:
run_details
preds
lengthscales
kernel_variance
likelihood_variance
total run time : 1.84 seconds
'run': 68.529 seconds
reading in results
getting all tables
merging on expert location data
table: 'oi_config' does not have all coords_col: ['x', 'y', 't'] in columns, not merging on expert_locations
h5 tables: ['expert_locs', 'kernel_variance', 'lengthscales', 'likelihood_variance', 'oi_config', 'preds', 'run_details']
found model_name: GPflowGPRModel
found GPU
setting lengthscales to: [1.]
'__init__': 0.049 seconds
reading in results
selecting only tables: ['lengthscales', 'kernel_variance', 'likelihood_variance']
'data_select': 0.000 seconds
'load': 0.000 seconds
expert_locations data will not be merged on results data
adding smoothed table: lengthscales_SMOOTHED
adding smoothed table: kernel_variance_SMOOTHED
adding smoothed table: likelihood_variance_SMOOTHED
writing (smoothed) hyper parameters to:
/home/mhen/geol0069_data/gpsat/jan20/1253.h5
table_suffix:_SMOOTHED
writing: lengthscales_SMOOTHED to table
writing: kernel_variance_SMOOTHED to table
writing: likelihood_variance_SMOOTHED to table
'data_select': 0.000 seconds
'load': 0.000 seconds
in json_serializable - key: 'data_source' has value DataFrame/Series, but is too long: 2035 >  100
storing as str
in json_serializable - key: 'df' has value DataFrame/Series, but is too long: 6622 >  100
storing as str
---------
storing expert locations in 'expert_locs' table
exception occurred: 'No object named expert_locs_SMOOTHED in the file'
will now close object

2026-05-18 19:20:33.169919: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:20:33.171332: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

---------
dropping expert locations that already exists in 'run_details' table
exception occurred: 'No object named run_details_SMOOTHED in the file'
will now close object

--------------------------------------------------
1 / 40
current local expert:
                    x             y        lon        lat        t         z  \
2594585 -1.469649e+06  1.718644e+06 -139.46554  69.638938  18262.0  0.002592

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2594585   1253  2020-01-01       cs2        1.0       4202.402161     0.097461
'data_select': 0.000 seconds
'load': 0.000 seconds
'local_data_select': 0.001 seconds
number obs: 460
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.049 seconds
'get_parameters': 0.003 seconds
'_read_params_from_file': 0.048 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01238681, 10.01237391,  0.99843159])
kernel_variance: 0.01613958642340714
likelihood_variance: 0.01100000000000001
'predict': 0.035 seconds

2026-05-18 19:20:33.427154: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:20:33.428573: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.83 seconds
--------------------------------------------------
2 / 40
current local expert:
                    x             y        lon        lat        t         z  \
2594606 -1.455083e+06  1.705499e+06 -139.53012  69.816098  18262.0 -0.012831

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2594606   1253  2020-01-01       cs2        1.0      24013.794557     0.097461
'local_data_select': 0.001 seconds
number obs: 481
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.049 seconds
'_read_params_from_file': 0.045 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01294222, 10.0129293 ,  0.99839288])
kernel_variance: 0.016059513300069782
likelihood_variance: 0.01100000000000001
'predict': 0.036 seconds

2026-05-18 19:20:34.259587: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:20:34.261012: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.83 seconds
--------------------------------------------------
3 / 40
current local expert:
                    x             y        lon        lat        t         z  \
2594635 -1.435666e+06  1.687953e+06 -139.61761  70.052296  18262.0 -0.031844

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2594635   1253  2020-01-01       cs2        1.0      50429.846201     0.097461
'local_data_select': 0.001 seconds
number obs: 490
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.050 seconds
'_read_params_from_file': 0.045 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.0138731 , 10.01386016,  0.9983273 ])
kernel_variance: 0.015946123625162928
likelihood_variance: 0.01100000000000001
'predict': 0.035 seconds

2026-05-18 19:20:35.093066: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:20:35.094497: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.82 seconds
--------------------------------------------------
4 / 40
current local expert:
                    x             y        lon       lat        t         z  \
2594681 -1.417588e+06  1.671595e+06 -139.70055  70.27224  18262.0 -0.057792

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2594681   1253  2020-01-01       cs2        1.0      75030.801563     0.097461
'local_data_select': 0.001 seconds
number obs: 499
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.049 seconds
'_read_params_from_file': 0.045 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01497764, 10.01496467,  0.99824828])
kernel_variance: 0.015833470820314145
likelihood_variance: 0.01100000000000001
'predict': 0.036 seconds

2026-05-18 19:20:35.917158: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:20:35.918580: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.83 seconds
--------------------------------------------------
5 / 40
current local expert:
                    x             y        lon        lat        t        z  \
2594744 -1.399283e+06  1.655010e+06 -139.78605  70.494969  18262.0  0.02889

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2594744   1253  2020-01-01       cs2        1.0      99946.109263     0.097461
'local_data_select': 0.001 seconds
number obs: 516
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.049 seconds
'_read_params_from_file': 0.045 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01637993, 10.01636692,  0.99814637])
kernel_variance: 0.015712241860118662
likelihood_variance: 0.01100000000000001
'predict': 0.040 seconds

2026-05-18 19:20:36.746195: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:20:36.747603: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.84 seconds
--------------------------------------------------
6 / 40
current local expert:
                    x             y        lon        lat        t         z  \
2594807 -1.382745e+06  1.640008e+06 -139.86465  70.696214  18262.0 -0.109041

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2594807   1253  2020-01-01       cs2        1.0     122460.671155     0.097461
'local_data_select': 0.001 seconds
number obs: 536
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.047 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01793801, 10.01792497,  0.99803154])
kernel_variance: 0.01559641791931155
likelihood_variance: 0.01100000000000001
'predict': 0.041 seconds

2026-05-18 19:20:37.590161: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:20:37.591598: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.83 seconds
--------------------------------------------------
7 / 40
current local expert:
                    x             y        lon        lat        t         z  \
2594863 -1.362684e+06  1.621785e+06 -139.96178  70.940369  18262.0  0.139116

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2594863   1253  2020-01-01       cs2        1.0     149779.168086     0.097461
'local_data_select': 0.001 seconds
number obs: 566
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.047 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.02026349, 10.0202504 ,  0.99785792])
kernel_variance: 0.015447865838846818
likelihood_variance: 0.01100000000000001
'predict': 0.040 seconds

2026-05-18 19:20:38.417760: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:20:38.419178: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.83 seconds
--------------------------------------------------
8 / 40
current local expert:
                    x             y        lon        lat        t         z  \
2594907 -1.343949e+06  1.604744e+06 -140.05432  71.168404  18262.0  0.184407

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2594907   1253  2020-01-01       cs2        1.0     175297.442308     0.097461
'local_data_select': 0.001 seconds
number obs: 609
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.045 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.02293178, 10.02291865,  0.99765646])
kernel_variance: 0.015301299155478822
likelihood_variance: 0.01100000000000001
'predict': 0.043 seconds

2026-05-18 19:20:39.245263: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:20:39.246681: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.83 seconds
--------------------------------------------------
9 / 40
current local expert:
                    x             y        lon        lat        t        z  \
2594972 -1.325660e+06  1.588085e+06 -140.14643  71.391051  18262.0  0.13367

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2594972   1253  2020-01-01       cs2        1.0     200216.081456     0.097461
'local_data_select': 0.001 seconds
number obs: 627
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.02606   , 10.02604682,  0.99741833])
kernel_variance: 0.015151202255058829
likelihood_variance: 0.01100000000000001
'predict': 0.044 seconds

2026-05-18 19:20:40.081502: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:20:40.082907: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.84 seconds
--------------------------------------------------
10 / 40
current local expert:
                    x             y        lon        lat        t        z  \
2595024 -1.307154e+06  1.571207e+06 -140.24148  71.616355  18262.0  0.22194

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2595024   1253  2020-01-01       cs2        1.0     225435.589977     0.097461
'local_data_select': 0.001 seconds
number obs: 648
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.02980313, 10.0297899 ,  0.99713173])
kernel_variance: 0.01499276956480642
likelihood_variance: 0.01100000000000001
'predict': 0.043 seconds

2026-05-18 19:20:40.922005: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:20:40.923480: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

SAVING RESULTS TO TABLES:
run_details
preds
total run time : 0.92 seconds
--------------------------------------------------
11 / 40
current local expert:
                    x             y        lon        lat        t         z  \
2595065 -1.289534e+06  1.555115e+06 -140.33377  71.830908  18262.0  0.194234

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2595065   1253  2020-01-01       cs2        1.0     249455.035394     0.097461
'local_data_select': 0.001 seconds
number obs: 668
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'_read_params_from_file': 0.050 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds

2026-05-18 19:20:41.844954: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:20:41.846358: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'set_likelihood_variance_constraints': 0.016 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.03394276, 10.03392949,  0.9968136 ])
kernel_variance: 0.014836423730416484
likelihood_variance: 0.01100000000000001
'predict': 0.045 seconds
total run time : 0.84 seconds
--------------------------------------------------
12 / 40
current local expert:
                    x             y        lon        lat        t         z  \
2595116 -1.270817e+06  1.538000e+06 -140.43379  72.058843  18262.0  0.195247

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2595116   1253  2020-01-01       cs2        1.0     274976.361972     0.097461
'local_data_select': 0.001 seconds
number obs: 693
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'_read_params_from_file': 0.045 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.03897327, 10.03895995,  0.99642637])
kernel_variance: 0.014665399709129667
likelihood_variance: 0.01100000000000001
'predict': 0.046 seconds

2026-05-18 19:20:42.686681: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:20:42.688089: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.85 seconds
--------------------------------------------------
13 / 40
current local expert:
                    x             y        lon        lat        t         z  \
2595164 -1.251225e+06  1.520059e+06 -140.54076  72.297473  18262.0  0.220563

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2595164   1253  2020-01-01       cs2        1.0     301699.461908     0.097461
'local_data_select': 0.001 seconds
number obs: 711
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.054 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.04492798, 10.04491463,  0.99596812])
kernel_variance: 0.014482214036714012
likelihood_variance: 0.01100000000000001
'predict': 0.046 seconds

2026-05-18 19:20:43.546326: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:20:43.548309: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.84 seconds
--------------------------------------------------
14 / 40
current local expert:
                    x             y        lon        lat        t         z  \
2595202 -1.233178e+06  1.503511e+06 -140.64144  72.517305  18262.0  0.206252

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2595202   1253  2020-01-01       cs2        1.0     326321.551441     0.097461
'local_data_select': 0.001 seconds
number obs: 715
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.046 seconds
'_read_params_from_file': 0.045 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.05099307, 10.05097969,  0.99550242])
kernel_variance: 0.014311124667542556
likelihood_variance: 0.01100000000000001
'predict': 0.046 seconds

2026-05-18 19:20:44.383187: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:20:44.384599: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.83 seconds
--------------------------------------------------
15 / 40
current local expert:
                    x             y        lon        lat        t         z  \
2595273 -1.209195e+06  1.481487e+06 -140.77855  72.809477  18262.0  0.188842

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2595273   1253  2020-01-01       cs2        1.0     359052.321878     0.097461
'local_data_select': 0.001 seconds
number obs: 725
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.047 seconds
'_read_params_from_file': 0.045 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.05977385, 10.05976045,  0.99483158])
kernel_variance: 0.01408289479562398
likelihood_variance: 0.01100000000000001
'predict': 0.046 seconds

2026-05-18 19:20:45.219846: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:20:45.221432: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.85 seconds
--------------------------------------------------
16 / 40
current local expert:
                    x             y        lon        lat        t         z  \
2595308 -1.197317e+06  1.470565e+06 -140.84792  72.954202  18262.0  0.229138

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2595308   1253  2020-01-01       cs2        1.0     375268.034221     0.097461
'local_data_select': 0.001 seconds
number obs: 755
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.050 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.06435076, 10.06433736,  0.99448409])
kernel_variance: 0.013970539335460186
likelihood_variance: 0.01100000000000001
'predict': 0.049 seconds

2026-05-18 19:20:46.078213: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:20:46.079603: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.86 seconds
--------------------------------------------------
17 / 40
current local expert:
                    x             y        lon        lat        t         z  \
2595356 -1.179283e+06  1.453965e+06 -140.95515  73.173942  18262.0  0.254031

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2595356   1253  2020-01-01       cs2        1.0     399892.439717     0.097461
'local_data_select': 0.001 seconds
number obs: 764
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.07146038, 10.071447  ,  0.99394819])
kernel_variance: 0.013802209479808078
likelihood_variance: 0.01100000000000001
'predict': 0.049 seconds

2026-05-18 19:20:46.933211: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:20:46.934649: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.85 seconds
--------------------------------------------------
18 / 40
current local expert:
                    x             y        lon        lat        t         z  \
2595411 -1.160815e+06  1.436943e+06 -141.06744  73.399005  18262.0  0.231516

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2595411   1253  2020-01-01       cs2        1.0     425118.054869     0.097461
'local_data_select': 0.001 seconds
number obs: 779
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.052 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.07876904, 10.0787557 ,  0.99340355])
kernel_variance: 0.013634162931296556
likelihood_variance: 0.01100000000000001
'predict': 0.049 seconds

2026-05-18 19:20:47.784435: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:20:47.785857: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.85 seconds
--------------------------------------------------
19 / 40
current local expert:
                    x             y        lon        lat        t         z  \
2595456 -1.142133e+06  1.419700e+06 -141.18371  73.626708  18262.0  0.151002

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2595456   1253  2020-01-01       cs2        1.0      450644.72188     0.097461
'local_data_select': 0.001 seconds
number obs: 767
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.047 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.085962  , 10.08594873,  0.9928759 ])
kernel_variance: 0.013470332082197342
likelihood_variance: 0.01100000000000001
'predict': 0.049 seconds

2026-05-18 19:20:48.628238: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:20:48.630218: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.84 seconds
--------------------------------------------------
20 / 40
current local expert:
                    x             y        lon        lat        t         z  \
2595501 -1.122357e+06  1.401422e+06 -141.30982  73.867762  18262.0  0.188292

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2595501   1253  2020-01-01       cs2        1.0     477673.904925     0.097461
'local_data_select': 0.001 seconds
number obs: 751
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.047 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.0930788 , 10.09306564,  0.99236551])
kernel_variance: 0.013305357655152221
likelihood_variance: 0.01100000000000001
'predict': 0.049 seconds

2026-05-18 19:20:49.469176: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:20:49.470596: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

SAVING RESULTS TO TABLES:
run_details
preds
total run time : 0.94 seconds
--------------------------------------------------
21 / 40
current local expert:
                    x             y        lon        lat        t         z  \
2595540 -1.107199e+06  1.387396e+06 -141.40869  74.052538  18262.0  0.166627

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2595540   1253  2020-01-01       cs2        1.0     498396.942877     0.097461
'local_data_select': 0.001 seconds
number obs: 737
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'_read_params_from_file': 0.050 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds

2026-05-18 19:20:50.410070: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:20:50.411492: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'set_likelihood_variance_constraints': 0.016 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.09800494, 10.09799189,  0.99202245])
kernel_variance: 0.013185679547522339
likelihood_variance: 0.01100000000000001
'predict': 0.050 seconds
total run time : 0.86 seconds
--------------------------------------------------
22 / 40
current local expert:
                    x             y        lon        lat        t         z  \
2595589 -1.088532e+06  1.370100e+06 -141.53319  74.280118  18262.0  0.163521

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2595589   1253  2020-01-01       cs2        1.0     523925.797263     0.097461
'local_data_select': 0.001 seconds
number obs: 717
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.052 seconds
'_read_params_from_file': 0.045 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.10323705, 10.10322417,  0.99167335])
kernel_variance: 0.013047103022293305
likelihood_variance: 0.01100000000000001
'predict': 0.047 seconds

2026-05-18 19:20:51.275997: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:20:51.277397: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.84 seconds
--------------------------------------------------
23 / 40
current local expert:
                    x             y        lon        lat        t         z  \
2595646 -1.069650e+06  1.352583e+06 -141.66233  74.510328  18262.0  0.197352

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2595646   1253  2020-01-01       cs2        1.0     549755.877133     0.097461
'local_data_select': 0.001 seconds
number obs: 696
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.047 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.10739683, 10.10738415,  0.99141749])
kernel_variance: 0.012917248338369236
likelihood_variance: 0.01100000000000001
'predict': 0.047 seconds

2026-05-18 19:20:52.118261: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:20:52.119652: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.84 seconds
--------------------------------------------------
24 / 40
current local expert:
                    x             y        lon        lat        t         z  \
2595699 -1.051214e+06  1.335456e+06 -141.79168  74.735132  18262.0  0.140633

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2595699   1253  2020-01-01       cs2        1.0      574985.67114     0.097461
'local_data_select': 0.001 seconds
number obs: 705
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.11020323, 10.11019077,  0.99127333])
kernel_variance: 0.012800461522077962
likelihood_variance: 0.01100000000000001
'predict': 0.047 seconds

2026-05-18 19:20:52.960794: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:20:52.962846: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.84 seconds
--------------------------------------------------
25 / 40
current local expert:
                    x             y        lon        lat        t         z  \
2595730 -1.033002e+06  1.318515e+06 -141.92275  74.957211  18262.0  0.169184

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2595730   1253  2020-01-01       cs2        1.0      599916.00983     0.097461
'local_data_select': 0.001 seconds
number obs: 699
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'_read_params_from_file': 0.045 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.11166219, 10.11164997,  0.9912396 ])
kernel_variance: 0.01269439413712669
likelihood_variance: 0.01100000000000001
'predict': 0.047 seconds

2026-05-18 19:20:53.800310: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:20:53.801728: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.84 seconds
--------------------------------------------------
26 / 40
current local expert:
                    x             y        lon        lat        t         z  \
2595774 -1.015674e+06  1.302375e+06 -142.05065  75.168538  18262.0  0.203622

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2595774   1253  2020-01-01       cs2        1.0      623645.51678     0.097461
'local_data_select': 0.001 seconds
number obs: 688
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.11180697, 10.11179501,  0.99130874])
kernel_variance: 0.01260134805256425
likelihood_variance: 0.01100000000000001
'predict': 0.045 seconds

2026-05-18 19:20:54.645798: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:20:54.647201: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.84 seconds
--------------------------------------------------
27 / 40
current local expert:
                     x             y        lon        lat        t         z  \
2595826 -996815.620509  1.284787e+06 -142.19352  75.398533  18262.0  0.009416

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2595826   1253  2020-01-01       cs2        1.0      649478.34294     0.097461
'local_data_select': 0.001 seconds
number obs: 667
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.046 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.11061248, 10.11060081,  0.99149228])
kernel_variance: 0.012507746184916355
likelihood_variance: 0.01100000000000001
'predict': 0.045 seconds

2026-05-18 19:20:55.485597: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:20:55.486998: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.85 seconds
--------------------------------------------------
28 / 40
current local expert:
                     x             y        lon        lat        t         z  \
2595876 -979278.724107  1.268410e+06 -142.32999  75.612424  18262.0  0.199559

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2595876   1253  2020-01-01       cs2        1.0     673509.409548     0.097461
'local_data_select': 0.001 seconds
number obs: 670
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.050 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.10831293, 10.10830155,  0.99175647])
kernel_variance: 0.012426685319549997
likelihood_variance: 0.01100000000000001
'predict': 0.045 seconds

2026-05-18 19:20:56.338159: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:20:56.339600: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.84 seconds
--------------------------------------------------
29 / 40
current local expert:
                    x             y       lon        lat        t         z  \
2595928 -959337.04267  1.249763e+06 -142.4896  75.855657  18262.0  0.152152

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2595928   1253  2020-01-01       cs2        1.0     700845.711095     0.097461
'local_data_select': 0.001 seconds
number obs: 684
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.047 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.10445479, 10.10444374,  0.99215254])
kernel_variance: 0.012339944476330342
likelihood_variance: 0.01100000000000001
'predict': 0.046 seconds

2026-05-18 19:20:57.179867: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:20:57.181285: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.84 seconds
--------------------------------------------------
30 / 40
current local expert:
                     x             y        lon        lat        t         z  \
2595978 -943345.060264  1.234789e+06 -142.62116  76.050722  18262.0  0.058406

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2595978   1253  2020-01-01       cs2        1.0     722775.475338     0.097461
'local_data_select': 0.001 seconds
number obs: 690
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.10054399, 10.10053321,  0.99253135])
kernel_variance: 0.012273410290439863
likelihood_variance: 0.01100000000000001
'predict': 0.046 seconds

2026-05-18 19:20:58.021289: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:20:58.023300: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

SAVING RESULTS TO TABLES:
run_details
preds
total run time : 0.95 seconds
--------------------------------------------------
31 / 40
current local expert:
                     x             y       lon        lat        t         z  \
2596022 -923635.149058  1.216311e+06 -142.7879  76.291139  18262.0  0.092729

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2596022   1253  2020-01-01       cs2        1.0     749812.841859     0.097461
'local_data_select': 0.001 seconds
number obs: 703
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.049 seconds

2026-05-18 19:20:58.976027: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:20:58.977433: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'_read_params_from_file': 0.050 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.09492644, 10.09491598,  0.9930557 ])
kernel_variance: 0.012193731682758432
likelihood_variance: 0.01100000000000001
'predict': 0.048 seconds
total run time : 0.86 seconds
--------------------------------------------------
32 / 40
current local expert:
                    x             y        lon        lat        t         z  \
2596085 -905026.96619  1.198842e+06 -142.95019  76.518121  18262.0  0.009816

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2596085   1253  2020-01-01       cs2        1.0     775348.812795     0.097461
'local_data_select': 0.001 seconds
number obs: 694
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.049 seconds
'_read_params_from_file': 0.045 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.08902602, 10.08901586,  0.99359123])
kernel_variance: 0.012119654972019256
likelihood_variance: 0.01100000000000001
'predict': 0.047 seconds

2026-05-18 19:20:59.837684: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:20:59.839125: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.84 seconds
--------------------------------------------------
33 / 40
current local expert:
                     x             y       lon        lat        t         z  \
2596138 -886425.354483  1.181355e+06 -143.1174  76.745023  18262.0  0.067219

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2596138   1253  2020-01-01       cs2        1.0     800885.517636     0.097461
'local_data_select': 0.001 seconds
number obs: 725
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.051 seconds
'_read_params_from_file': 0.045 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.08276096, 10.08275108,  0.99414842])
kernel_variance: 0.012045709967082747
likelihood_variance: 0.01100000000000001
'predict': 0.046 seconds

2026-05-18 19:21:00.680634: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:21:00.682035: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.84 seconds
--------------------------------------------------
34 / 40
current local expert:
                     x             y        lon        lat        t         z  \
2596198 -869580.193386  1.165499e+06 -143.27334  76.950495  18262.0  0.024675

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2596198   1253  2020-01-01       cs2        1.0     824019.255019     0.097461
'local_data_select': 0.001 seconds
number obs: 709
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.047 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.07693447, 10.07692484,  0.99465871])
kernel_variance: 0.011978216607365678
likelihood_variance: 0.01100000000000001
'predict': 0.046 seconds

2026-05-18 19:21:01.521208: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:21:01.523960: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.84 seconds
--------------------------------------------------
35 / 40
current local expert:
                     x             y       lon        lat        t         z  \
2596245 -851865.660583  1.148805e+06 -143.4422  77.166562  18262.0  0.098078

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2596245   1253  2020-01-01       cs2        1.0     848355.458943     0.097461
'local_data_select': 0.001 seconds
number obs: 704
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.047 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.07079768, 10.0707883 ,  0.99518966])
kernel_variance: 0.011906275603846824
likelihood_variance: 0.01100000000000001
'predict': 0.046 seconds

2026-05-18 19:21:02.360338: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:21:02.361760: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.84 seconds
--------------------------------------------------
36 / 40
current local expert:
                     x             y        lon        lat        t         z  \
2596314 -832627.438925  1.130650e+06 -143.63152  77.401204  18262.0 -0.004782

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2596314   1253  2020-01-01       cs2        1.0     874795.462903     0.097461
'local_data_select': 0.001 seconds
number obs: 715
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.046 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.06426898, 10.06425985,  0.99574847])
kernel_variance: 0.011826764904935312
likelihood_variance: 0.01100000000000001
'predict': 0.048 seconds

2026-05-18 19:21:03.200359: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:21:03.201794: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.84 seconds
--------------------------------------------------
37 / 40
current local expert:
                     x             y        lon        lat        t         z  \
2596370 -814270.505989  1.113304e+06 -143.81826  77.625079  18262.0  0.036487

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2596370   1253  2020-01-01       cs2        1.0     900034.240442     0.097461
'local_data_select': 0.001 seconds
number obs: 713
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.049 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.05829025, 10.05828134,  0.99625565])
kernel_variance: 0.011749504036186595
likelihood_variance: 0.01100000000000001
'predict': 0.047 seconds

2026-05-18 19:21:04.041857: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:21:04.043992: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.84 seconds
--------------------------------------------------
38 / 40
current local expert:
                     x             y        lon        lat        t         z  \
2596416 -795046.840181  1.095114e+06 -144.02055  77.859503  18262.0  0.059112

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2596416   1253  2020-01-01       cs2        1.0     926475.546543     0.097461
'local_data_select': 0.001 seconds
number obs: 703
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.05238816, 10.05237947,  0.99675281])
kernel_variance: 0.011667273488793808
likelihood_variance: 0.01100000000000001
'predict': 0.047 seconds

2026-05-18 19:21:04.885939: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:21:04.887332: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.84 seconds
--------------------------------------------------
39 / 40
current local expert:
                     x             y        lon        lat        t         z  \
2596462 -778013.938703  1.078976e+06 -144.20587  78.067187  18262.0  0.097879

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2596462   1253  2020-01-01       cs2        1.0     949912.810667     0.097461
'local_data_select': 0.001 seconds
number obs: 690
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.047 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.04752053, 10.04751201,  0.99716077])
kernel_variance: 0.011593519537882653
likelihood_variance: 0.01100000000000001
'predict': 0.047 seconds

2026-05-18 19:21:05.723150: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:21:05.724566: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.83 seconds
--------------------------------------------------
40 / 40
current local expert:
                     x             y        lon        lat        t         z  \
2596520 -758150.011707  1.060131e+06 -144.42963  78.309356  18262.0  0.044546

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2596520   1253  2020-01-01       cs2        1.0     977256.844554     0.097461
'local_data_select': 0.001 seconds
number obs: 657
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.050 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.04231377, 10.04230543,  0.99759578])
kernel_variance: 0.011506837800007623
likelihood_variance: 0.01100000000000001
'predict': 0.046 seconds

2026-05-18 19:21:06.562806: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:21:06.564241: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

SAVING RESULTS TO TABLES:
run_details
preds
total run time : 1.03 seconds
'run': 34.242 seconds
reading in results
getting all tables
merging on expert location data
table: 'oi_config' does not have all coords_col: ['x', 'y', 't'] in columns, not merging on expert_locations
table: 'oi_config_SMOOTHED' does not have all coords_col: ['x', 'y', 't'] in columns, not merging on expert_locations
lin:
                    x             y        lon        lat        t   z  track  \
2594580 -1.472739e+06  1.721431e+06 -139.45195  69.601357  18262.0 NaN   1253
2594581 -1.472518e+06  1.721232e+06 -139.45292  69.604041  18262.0 NaN   1253
2594582 -1.470753e+06  1.719639e+06 -139.46068  69.625516  18262.0 NaN   1253
2594583 -1.470311e+06  1.719241e+06 -139.46263  69.630885  18262.0 NaN   1253
2594584 -1.470090e+06  1.719042e+06 -139.46360  69.633569  18262.0 NaN   1253

        date_string satellite  lead_mask  dist_along_track  z_track_avg  \
2594580  2020-01-01       cs2        0.0          0.000000     0.097461
2594581  2020-01-01       cs2        0.0        300.132663     0.097461
2594582  2020-01-01       cs2        0.0       2701.502880     0.097461
2594583  2020-01-01       cs2        0.0       3301.915369     0.097461
2594584  2020-01-01       cs2        0.0       3602.041530     0.097461

            f_lin
2594580 -0.005776
2594581 -0.005776
2594582 -0.005776
2594583 -0.005776
2594584 -0.005776
gpsat:
                    x             y        lon        lat        t   z  track  \
2594580 -1.472739e+06  1.721431e+06 -139.45195  69.601357  18262.0 NaN   1253
2594581 -1.472518e+06  1.721232e+06 -139.45292  69.604041  18262.0 NaN   1253
2594582 -1.470753e+06  1.719639e+06 -139.46068  69.625516  18262.0 NaN   1253
2594583 -1.470311e+06  1.719241e+06 -139.46263  69.630885  18262.0 NaN   1253
2594584 -1.470090e+06  1.719042e+06 -139.46360  69.633569  18262.0 NaN   1253

        date_string satellite  lead_mask  dist_along_track  z_track_avg  \
2594580  2020-01-01       cs2        0.0          0.000000     0.097461
2594581  2020-01-01       cs2        0.0        300.132663     0.097461
2594582  2020-01-01       cs2        0.0       2701.502880     0.097461
2594583  2020-01-01       cs2        0.0       3301.915369     0.097461
2594584  2020-01-01       cs2        0.0       3602.041530     0.097461

          f_gpsat  f_var_gpsat
2594580 -0.001872    -0.001872
2594581 -0.001782    -0.001782
2594582 -0.001027    -0.001027
2594583 -0.000828    -0.000828
2594584 -0.000727    -0.000727
Test NaNs — Linear: 0, GPSat: 205
Track interpolated!
Interpolating track 1254, 11 of 15...
'data_select': 0.000 seconds
'load': 0.000 seconds
in json_serializable - key: 'data_source' has value DataFrame/Series, but is too long: 196 >  100
storing as str
in json_serializable - key: 'df' has value DataFrame/Series, but is too long: 487 >  100
storing as str
---------
storing expert locations in 'expert_locs' table
exception occurred: 'No object named expert_locs in the file'
will now close object

/tmp/ipykernel_1171781/839927469.py:200: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  track_df['f_gpsat'] = ssha
/tmp/ipykernel_1171781/839927469.py:201: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  track_df['f_var_gpsat'] = ssha_var
/tmp/ipykernel_1171781/839927469.py:66: RuntimeWarning: invalid value encountered in sqrt
  gpsat_std = np.sqrt(gpsat_var[both_valid])
2026-05-18 19:21:08.117883: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:21:08.119287: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

---------
dropping expert locations that already exists in 'run_details' table
exception occurred: 'No object named run_details in the file'
will now close object

--------------------------------------------------
1 / 10
current local expert:
                     x              y        lon        lat        t  \
2601234  938975.227065 -654633.154057  55.116628  79.737114  18262.0

                z  track date_string satellite  lead_mask  dist_along_track  \
2601234  0.036749   1254  2020-01-01       cs2        1.0      89664.980989

         z_track_avg
2601234     0.115167
'data_select': 0.000 seconds
'load': 0.000 seconds
'local_data_select': 0.001 seconds
number obs: 196
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.050 seconds
'get_parameters': 0.003 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds
**********
optimization failed!
'optimise_parameters': 0.529 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([19.53110226, 19.90504648,  0.97152678])
kernel_variance: 0.018301399749480203
likelihood_variance: 0.0030608285078985264
'predict': 0.031 seconds
total run time : 1.31 seconds
--------------------------------------------------
2 / 10
current local expert:
                     x              y        lon        lat        t  \
2601253  945138.611269 -661262.218343  55.021604  79.657544  18262.0

                z  track date_string satellite  lead_mask  dist_along_track  \
2601253  0.139173   1254  2020-01-01       cs2        1.0      98692.083691

         z_track_avg
2601253     0.115167
'local_data_select': 0.001 seconds
number obs: 196
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:21:09.422309: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:21:09.423703: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.525 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([19.53110226, 19.90504648,  0.97152678])
kernel_variance: 0.018301399749480203
likelihood_variance: 0.0030608285078985264
'predict': 0.032 seconds
total run time : 1.29 seconds
--------------------------------------------------
3 / 10
current local expert:
                     x              y        lon        lat        t  \
2601299  963001.279981 -680492.199677  54.753564  79.426656  18262.0

                z  track date_string satellite  lead_mask  dist_along_track  \
2601299  0.137043   1254  2020-01-01       cs2        1.0     124870.714141

         z_track_avg
2601299     0.115167
'local_data_select': 0.001 seconds
number obs: 196
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:21:10.718679: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:21:10.720073: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.534 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([19.53110226, 19.90504648,  0.97152678])
kernel_variance: 0.018301399749480203
likelihood_variance: 0.0030608285078985264
'predict': 0.032 seconds
total run time : 1.31 seconds
--------------------------------------------------
4 / 10
current local expert:
                     x              y        lon        lat        t  \
2601344  979412.106035 -698182.373418  54.516501  79.214176  18262.0

                z  track date_string satellite  lead_mask  dist_along_track  \
2601344  0.134079   1254  2020-01-01       cs2        1.0     148943.124219

         z_track_avg
2601344     0.115167
'local_data_select': 0.001 seconds
number obs: 196
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:21:12.026876: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:21:12.028285: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.529 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([19.53110226, 19.90504648,  0.97152678])
kernel_variance: 0.018301399749480203
likelihood_variance: 0.0030608285078985264
'predict': 0.032 seconds
total run time : 1.32 seconds
--------------------------------------------------
5 / 10
current local expert:
                     x              y       lon        lat        t         z  \
2601396  997242.929942 -717428.443765  54.26831  78.982931  18262.0  0.095279

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2601396   1254  2020-01-01       cs2        1.0     175122.014105     0.115167
'local_data_select': 0.001 seconds
number obs: 196
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.047 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:21:13.343905: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:21:13.345300: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.528 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([19.53110226, 19.90504648,  0.97152678])
kernel_variance: 0.018301399749480203
likelihood_variance: 0.0030608285078985264
'predict': 0.032 seconds
total run time : 1.30 seconds
--------------------------------------------------
6 / 10
current local expert:
                    x              y       lon        lat        t        z  \
2601443  1.014238e+06 -735797.288063  54.04032  78.762161  18262.0  0.10018

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2601443   1254  2020-01-01       cs2        1.0     200097.301366     0.115167
'local_data_select': 0.001 seconds
number obs: 196
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:21:14.647710: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:21:14.649104: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.530 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([19.53110226, 19.90504648,  0.97152678])
kernel_variance: 0.018301399749480203
likelihood_variance: 0.0030608285078985264
'predict': 0.032 seconds
total run time : 1.32 seconds
--------------------------------------------------
7 / 10
current local expert:
                    x              y       lon        lat        t         z  \
2601492  1.030605e+06 -753509.211053  53.82823  78.549233  18262.0  0.125779

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2601492   1254  2020-01-01       cs2        1.0     224169.994096     0.115167
'local_data_select': 0.001 seconds
number obs: 196
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.053 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:21:15.973175: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:21:15.974573: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.524 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([19.53110226, 19.90504648,  0.97152678])
kernel_variance: 0.018301399749480203
likelihood_variance: 0.0030608285078985264
'predict': 0.032 seconds
total run time : 1.31 seconds
--------------------------------------------------
8 / 10
current local expert:
                    x              y        lon        lat        t         z  \
2601548  1.048591e+06 -773000.069097  53.603123  78.314867  18262.0  0.184784

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2601548   1254  2020-01-01       cs2        1.0     250649.891259     0.115167
'local_data_select': 0.001 seconds
number obs: 196
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:21:17.275923: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:21:17.277346: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.526 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([19.53110226, 19.90504648,  0.97152678])
kernel_variance: 0.018301399749480203
likelihood_variance: 0.0030608285078985264
'predict': 0.032 seconds
total run time : 1.32 seconds
--------------------------------------------------
9 / 10
current local expert:
                    x              y        lon        lat        t         z  \
2601619  1.065948e+06 -791834.200391  53.393381  78.088353  18262.0  0.159461

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2601619   1254  2020-01-01       cs2        1.0     276227.178341     0.115167
'local_data_select': 0.001 seconds
number obs: 196
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.047 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:21:18.598404: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:21:18.599805: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.531 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([19.53110226, 19.90504648,  0.97152678])
kernel_variance: 0.018301399749480203
likelihood_variance: 0.0030608285078985264
'predict': 0.032 seconds
total run time : 1.32 seconds
--------------------------------------------------
10 / 10
current local expert:
                    x              y        lon        lat        t         z  \
2601681  1.082066e+06 -809345.698805  53.204849  77.877712  18262.0  0.216476

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2601681   1254  2020-01-01       cs2        1.0      299999.28195     0.115167
'local_data_select': 0.001 seconds
number obs: 196
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.050 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:21:19.921226: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:21:19.922630: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.529 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([19.53110226, 19.90504648,  0.97152678])
kernel_variance: 0.018301399749480203
likelihood_variance: 0.0030608285078985264
'predict': 0.033 seconds
SAVING RESULTS TO TABLES:
run_details
preds
lengthscales
kernel_variance
likelihood_variance
total run time : 1.45 seconds
'run': 13.324 seconds
reading in results
getting all tables
merging on expert location data
table: 'oi_config' does not have all coords_col: ['x', 'y', 't'] in columns, not merging on expert_locations
h5 tables: ['expert_locs', 'kernel_variance', 'lengthscales', 'likelihood_variance', 'oi_config', 'preds', 'run_details']
found model_name: GPflowGPRModel
found GPU
setting lengthscales to: [1.]
'__init__': 0.047 seconds
reading in results
selecting only tables: ['lengthscales', 'kernel_variance', 'likelihood_variance']
'data_select': 0.000 seconds
'load': 0.001 seconds
expert_locations data will not be merged on results data
adding smoothed table: lengthscales_SMOOTHED
adding smoothed table: kernel_variance_SMOOTHED
adding smoothed table: likelihood_variance_SMOOTHED
writing (smoothed) hyper parameters to:
/home/mhen/geol0069_data/gpsat/jan20/1254.h5
table_suffix:_SMOOTHED
writing: lengthscales_SMOOTHED to table
writing: kernel_variance_SMOOTHED to table
writing: likelihood_variance_SMOOTHED to table
'data_select': 0.000 seconds
'load': 0.000 seconds
in json_serializable - key: 'data_source' has value DataFrame/Series, but is too long: 196 >  100
storing as str
in json_serializable - key: 'df' has value DataFrame/Series, but is too long: 487 >  100
storing as str

2026-05-18 19:21:21.489312: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:21:21.490825: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

---------
storing expert locations in 'expert_locs' table
exception occurred: 'No object named expert_locs_SMOOTHED in the file'
will now close object

---------
dropping expert locations that already exists in 'run_details' table
exception occurred: 'No object named run_details_SMOOTHED in the file'
will now close object

--------------------------------------------------
1 / 10
current local expert:
                     x              y        lon        lat        t  \
2601234  938975.227065 -654633.154057  55.116628  79.737114  18262.0

                z  track date_string satellite  lead_mask  dist_along_track  \
2601234  0.036749   1254  2020-01-01       cs2        1.0      89664.980989

         z_track_avg
2601234     0.115167
'data_select': 0.000 seconds
'load': 0.000 seconds
'local_data_select': 0.001 seconds
number obs: 196
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.049 seconds
'get_parameters': 0.003 seconds
'_read_params_from_file': 0.051 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters

2026-05-18 19:21:21.756761: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:21:21.758196: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'get_parameters': 0.003 seconds
parameters:
lengthscales: array([12.        , 12.        ,  0.97152678])
kernel_variance: 0.018301399749480196
likelihood_variance: 0.01100000000000001
'predict': 0.031 seconds
total run time : 0.86 seconds
--------------------------------------------------
2 / 10
current local expert:
                     x              y        lon        lat        t  \
2601253  945138.611269 -661262.218343  55.021604  79.657544  18262.0

                z  track date_string satellite  lead_mask  dist_along_track  \
2601253  0.139173   1254  2020-01-01       cs2        1.0      98692.083691

         z_track_avg
2601253     0.115167
'local_data_select': 0.001 seconds
number obs: 196
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.047 seconds
'_read_params_from_file': 0.045 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([12.        , 12.        ,  0.97152678])
kernel_variance: 0.018301399749480196
likelihood_variance: 0.01100000000000001
'predict': 0.032 seconds

2026-05-18 19:21:22.615278: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:21:22.616769: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.84 seconds
--------------------------------------------------
3 / 10
current local expert:
                     x              y        lon        lat        t  \
2601299  963001.279981 -680492.199677  54.753564  79.426656  18262.0

                z  track date_string satellite  lead_mask  dist_along_track  \
2601299  0.137043   1254  2020-01-01       cs2        1.0     124870.714141

         z_track_avg
2601299     0.115167
'local_data_select': 0.001 seconds
number obs: 196
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.047 seconds
'_read_params_from_file': 0.045 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([12.        , 12.        ,  0.97152678])
kernel_variance: 0.01830139974948021
likelihood_variance: 0.01100000000000001
'predict': 0.031 seconds

2026-05-18 19:21:23.462754: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:21:23.464155: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.84 seconds
--------------------------------------------------
4 / 10
current local expert:
                     x              y        lon        lat        t  \
2601344  979412.106035 -698182.373418  54.516501  79.214176  18262.0

                z  track date_string satellite  lead_mask  dist_along_track  \
2601344  0.134079   1254  2020-01-01       cs2        1.0     148943.124219

         z_track_avg
2601344     0.115167
'local_data_select': 0.001 seconds
number obs: 196
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.047 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([12.        , 12.        ,  0.97152678])
kernel_variance: 0.01830139974948021
likelihood_variance: 0.01100000000000001
'predict': 0.031 seconds

2026-05-18 19:21:24.308983: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:21:24.310417: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.83 seconds
--------------------------------------------------
5 / 10
current local expert:
                     x              y       lon        lat        t         z  \
2601396  997242.929942 -717428.443765  54.26831  78.982931  18262.0  0.095279

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2601396   1254  2020-01-01       cs2        1.0     175122.014105     0.115167
'local_data_select': 0.001 seconds
number obs: 196
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'_read_params_from_file': 0.045 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([12.        , 12.        ,  0.97152678])
kernel_variance: 0.01830139974948021
likelihood_variance: 0.01100000000000001
'predict': 0.031 seconds

2026-05-18 19:21:25.144087: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:21:25.145505: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.85 seconds
--------------------------------------------------
6 / 10
current local expert:
                    x              y       lon        lat        t        z  \
2601443  1.014238e+06 -735797.288063  54.04032  78.762161  18262.0  0.10018

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2601443   1254  2020-01-01       cs2        1.0     200097.301366     0.115167
'local_data_select': 0.001 seconds
number obs: 196
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([12.        , 12.        ,  0.97152678])
kernel_variance: 0.018301399749480196
likelihood_variance: 0.01100000000000001
'predict': 0.031 seconds

2026-05-18 19:21:25.991283: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:21:25.993263: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.83 seconds
--------------------------------------------------
7 / 10
current local expert:
                    x              y       lon        lat        t         z  \
2601492  1.030605e+06 -753509.211053  53.82823  78.549233  18262.0  0.125779

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2601492   1254  2020-01-01       cs2        1.0     224169.994096     0.115167
'local_data_select': 0.001 seconds
number obs: 196
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.046 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([12.        , 12.        ,  0.97152678])
kernel_variance: 0.01830139974948021
likelihood_variance: 0.01100000000000001
'predict': 0.031 seconds

2026-05-18 19:21:26.823303: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:21:26.824712: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.83 seconds
--------------------------------------------------
8 / 10
current local expert:
                    x              y        lon        lat        t         z  \
2601548  1.048591e+06 -773000.069097  53.603123  78.314867  18262.0  0.184784

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2601548   1254  2020-01-01       cs2        1.0     250649.891259     0.115167
'local_data_select': 0.001 seconds
number obs: 196
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([12.        , 12.        ,  0.97152678])
kernel_variance: 0.01830139974948021
likelihood_variance: 0.01100000000000001
'predict': 0.031 seconds

2026-05-18 19:21:27.651422: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:21:27.652870: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.83 seconds
--------------------------------------------------
9 / 10
current local expert:
                    x              y        lon        lat        t         z  \
2601619  1.065948e+06 -791834.200391  53.393381  78.088353  18262.0  0.159461

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2601619   1254  2020-01-01       cs2        1.0     276227.178341     0.115167
'local_data_select': 0.001 seconds
number obs: 196
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.050 seconds
'_read_params_from_file': 0.045 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([12.        , 12.        ,  0.97152678])
kernel_variance: 0.01830139974948021
likelihood_variance: 0.01100000000000001
'predict': 0.031 seconds

2026-05-18 19:21:28.490087: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:21:28.491513: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.85 seconds
--------------------------------------------------
10 / 10
current local expert:
                    x              y        lon        lat        t         z  \
2601681  1.082066e+06 -809345.698805  53.204849  77.877712  18262.0  0.216476

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2601681   1254  2020-01-01       cs2        1.0      299999.28195     0.115167
'local_data_select': 0.001 seconds
number obs: 196
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.050 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([12.        , 12.        ,  0.97152678])
kernel_variance: 0.01830139974948021
likelihood_variance: 0.01100000000000001
'predict': 0.031 seconds

2026-05-18 19:21:29.338222: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:21:29.339653: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

SAVING RESULTS TO TABLES:
run_details
preds
total run time : 0.91 seconds
'run': 8.567 seconds
reading in results
getting all tables
merging on expert location data
table: 'oi_config' does not have all coords_col: ['x', 'y', 't'] in columns, not merging on expert_locations
table: 'oi_config_SMOOTHED' does not have all coords_col: ['x', 'y', 't'] in columns, not merging on expert_locations
lin:
                     x              y        lon        lat        t   z  \
2601202  877649.021868 -588842.821293  56.141075  80.526027  18262.0 NaN
2601203  878061.613678 -589284.444954  56.133660  80.520737  18262.0 NaN
2601204  878473.960479 -589725.798517  56.126258  80.515450  18262.0 NaN
2601205  878680.090845 -589946.426073  56.122561  80.512807  18262.0 NaN
2601206  878886.206192 -590167.067006  56.118865  80.510164  18262.0 NaN

         track date_string satellite  lead_mask  dist_along_track  \
2601202   1254  2020-01-01       cs2        0.0          0.000000
2601203   1254  2020-01-01       cs2        0.0        602.332491
2601204   1254  2020-01-01       cs2        0.0       1204.304082
2601205   1254  2020-01-01       cs2        0.0       1505.225681
2601206   1254  2020-01-01       cs2        0.0       1806.147370

         z_track_avg     f_lin
2601202     0.115167  0.106148
2601203     0.115167  0.106148
2601204     0.115167  0.106148
2601205     0.115167  0.106148
2601206     0.115167  0.106148
gpsat:
                     x              y        lon        lat        t   z  \
2601202  877649.021868 -588842.821293  56.141075  80.526027  18262.0 NaN
2601203  878061.613678 -589284.444954  56.133660  80.520737  18262.0 NaN
2601204  878473.960479 -589725.798517  56.126258  80.515450  18262.0 NaN
2601205  878680.090845 -589946.426073  56.122561  80.512807  18262.0 NaN
2601206  878886.206192 -590167.067006  56.118865  80.510164  18262.0 NaN

         track date_string satellite  lead_mask  dist_along_track  \
2601202   1254  2020-01-01       cs2        0.0          0.000000
2601203   1254  2020-01-01       cs2        0.0        602.332491
2601204   1254  2020-01-01       cs2        0.0       1204.304082
2601205   1254  2020-01-01       cs2        0.0       1505.225681
2601206   1254  2020-01-01       cs2        0.0       1806.147370

         z_track_avg   f_gpsat  f_var_gpsat
2601202     0.115167  0.067109     0.005586
2601203     0.115167  0.067317     0.005534
2601204     0.115167  0.067526     0.005482
2601205     0.115167  0.067631     0.005456
2601206     0.115167  0.067736     0.005430
Test NaNs — Linear: 0, GPSat: 0
Track interpolated!
Interpolating track 1257, 12 of 15...

/tmp/ipykernel_1171781/839927469.py:200: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  track_df['f_gpsat'] = ssha
/tmp/ipykernel_1171781/839927469.py:201: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  track_df['f_var_gpsat'] = ssha_var

Expert limit reached.
'data_select': 0.000 seconds
'load': 0.000 seconds
in json_serializable - key: 'data_source' has value DataFrame/Series, but is too long: 2750 >  100
storing as str
in json_serializable - key: 'df' has value DataFrame/Series, but is too long: 7988 >  100
storing as str
---------
storing expert locations in 'expert_locs' table
exception occurred: 'No object named expert_locs in the file'
will now close object

---------
dropping expert locations that already exists in 'run_details' table
exception occurred: 'No object named run_details in the file'
will now close object

--------------------------------------------------
1 / 40
current local expert:
                     x             y        lon        lat        t         z  \
2602051 -563834.651129  2.066474e+06 -164.73841  70.724595  18262.0 -0.498303

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2602051   1257  2020-01-01       cs2        1.0     192698.973917    -0.026275
'data_select': 0.000 seconds
'load': 0.000 seconds
'local_data_select': 0.001 seconds
number obs: 566
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'get_parameters': 0.003 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:21:31.572842: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:21:31.574413: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'optimise_parameters': 0.413 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01002546, 10.01014815,  0.99723019])
kernel_variance: 0.04711798524731409
likelihood_variance: 0.001000000003689623
'predict': 0.041 seconds
total run time : 1.21 seconds
--------------------------------------------------
2 / 40
current local expert:
                     x             y        lon        lat        t         z  \
2602131 -551788.930876  2.037935e+06 -164.84991  71.003626  18262.0 -0.494699

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2602131   1257  2020-01-01       cs2        1.0     223920.874415    -0.026275
'local_data_select': 0.001 seconds
number obs: 610
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.045 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:21:32.784275: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:21:32.785691: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'optimise_parameters': 0.494 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01002279, 10.01013234,  1.00006979])
kernel_variance: 0.05733740325014075
likelihood_variance: 0.0010000000047275125
'predict': 0.043 seconds
total run time : 1.31 seconds
--------------------------------------------------
3 / 40
current local expert:
                     x             y        lon        lat        t         z  \
2602180 -541841.445861  2.014318e+06 -164.94411  71.234337  18262.0 -0.403015

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2602180   1257  2020-01-01       cs2        1.0     249739.853467    -0.026275
'local_data_select': 0.001 seconds
number obs: 641
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.050 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:21:34.097152: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:21:34.098561: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 1.115 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01002298, 10.01013365,  1.0026317 ])
kernel_variance: 0.056412180419481796
likelihood_variance: 0.0010000000044933155
'predict': 0.045 seconds
total run time : 1.93 seconds
--------------------------------------------------
4 / 40
current local expert:
                     x             y        lon       lat        t         z  \
2602239 -532137.177154  1.991235e+06 -165.03793  71.45966  18262.0 -0.416162

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2602239   1257  2020-01-01       cs2        1.0     274959.293715    -0.026275
'local_data_select': 0.001 seconds
number obs: 679
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.050 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:21:36.034354: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:21:36.035742: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 1.502 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01002132, 10.01012387,  1.0032038 ])
kernel_variance: 0.06057903188258816
likelihood_variance: 0.0010000000061280922
'predict': 0.047 seconds
total run time : 2.31 seconds
--------------------------------------------------
5 / 40
current local expert:
                     x             y        lon        lat        t         z  \
2602271 -522675.256325  1.968687e+06 -165.13131  71.679593  18262.0 -0.355759

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2602271   1257  2020-01-01       cs2        1.0     299578.880353    -0.026275
'local_data_select': 0.001 seconds
number obs: 709
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.050 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:21:38.341183: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:21:38.342585: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 1.177 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01002285, 10.01013335,  0.99972141])
kernel_variance: 0.05296495663842674
likelihood_variance: 0.0010000000039508195
'predict': 0.047 seconds
total run time : 1.99 seconds
--------------------------------------------------
6 / 40
current local expert:
                     x             y        lon        lat        t         z  \
2602318 -512879.150262  1.945299e+06 -165.23004  71.907547  18262.0 -0.234395

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2602318   1257  2020-01-01       cs2        1.0     325100.028603    -0.026275
'local_data_select': 0.001 seconds
number obs: 733
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.050 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:21:40.335284: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:21:40.336704: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'optimise_parameters': 0.522 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.0100245 , 10.01014371,  0.99996513])
kernel_variance: 0.04610533211696836
likelihood_variance: 0.001000000003192087
'predict': 0.048 seconds
total run time : 1.34 seconds
--------------------------------------------------
7 / 40
current local expert:
                     x             y        lon        lat        t         z  \
2602371 -503209.835084  1.922171e+06 -165.32963  72.132792  18262.0 -0.220557

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2602371   1257  2020-01-01       cs2        1.0     350321.781892    -0.026275
'local_data_select': 0.001 seconds
number obs: 773
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.051 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:21:41.673727: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:21:41.675134: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 1.467 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01002372, 10.01013914,  1.00001313])
kernel_variance: 0.048482828771678976
likelihood_variance: 0.0010000000028693107
'predict': 0.051 seconds
total run time : 2.29 seconds
--------------------------------------------------
8 / 40
current local expert:
                     x             y        lon       lat        t         z  \
2602436 -493323.032544  1.898477e+06 -165.43373  72.36337  18262.0 -0.266936

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2602436   1257  2020-01-01       cs2        1.0     376144.767111    -0.026275
'local_data_select': 0.001 seconds
number obs: 807
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.051 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:21:43.961409: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:21:43.962926: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.945 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01002158, 10.01012631,  0.99983142])
kernel_variance: 0.050028173428246274
likelihood_variance: 0.0010000000050085073
'predict': 0.050 seconds
total run time : 1.78 seconds
--------------------------------------------------
9 / 40
current local expert:
                    x             y        lon        lat        t         z  \
2602493 -484251.92654  1.876699e+06 -165.53135  72.575152  18262.0 -0.108551

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2602493   1257  2020-01-01       cs2        1.0     399866.580177    -0.026275
'local_data_select': 0.001 seconds
number obs: 836
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.046 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:21:45.740931: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:21:45.742332: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'optimise_parameters': 0.881 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01002383, 10.01014054,  1.00128772])
kernel_variance: 0.043898537988615594
likelihood_variance: 0.0010000000038043184
'predict': 0.051 seconds
total run time : 1.72 seconds
--------------------------------------------------
10 / 40
current local expert:
                     x             y        lon        lat        t         z  \
2602534 -474618.009133  1.853528e+06 -165.63733  72.800308  18262.0 -0.077163

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2602534   1257  2020-01-01       cs2        1.0     425090.644212    -0.026275
'local_data_select': 0.001 seconds
number obs: 874
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.052 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:21:47.463672: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:21:47.465677: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 1.633 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.010025  , 10.01014809,  0.99989613])
kernel_variance: 0.03899050036972714
likelihood_variance: 0.0010000000030251418
'predict': 0.053 seconds
SAVING RESULTS TO TABLES:
run_details
preds
lengthscales
kernel_variance
likelihood_variance
total run time : 2.60 seconds
--------------------------------------------------
11 / 40
current local expert:
                     x             y        lon        lat        t        z  \
2602584 -465110.689028  1.830618e+06 -165.74433  73.022751  18262.0 -0.06368

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2602584   1257  2020-01-01       cs2        1.0     450015.167515    -0.026275
'local_data_select': 0.001 seconds
number obs: 902
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.047 seconds
'set_lengthscales_constraints': 0.006 seconds

2026-05-18 19:21:50.064529: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:21:50.065955: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'set_likelihood_variance_constraints': 0.010 seconds
**********
optimization failed!
'optimise_parameters': 1.100 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.0100242 , 10.01014369,  1.00069742])
kernel_variance: 0.037879501862949284
likelihood_variance: 0.00100000000609764
'predict': 0.056 seconds
total run time : 1.93 seconds
--------------------------------------------------
12 / 40
current local expert:
                     x             y        lon        lat        t        z  \
2602627 -455615.544169  1.807695e+06 -165.85368  73.245159  18262.0 -0.01025

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2602627   1257  2020-01-01       cs2        1.0     474940.283698    -0.026275
'local_data_select': 0.001 seconds
number obs: 941
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.047 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:21:51.993474: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:21:51.994872: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 1.189 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01002289, 10.01013566,  0.99940656])
kernel_variance: 0.0414989926734111
likelihood_variance: 0.0010000000064663592
'predict': 0.056 seconds
total run time : 2.03 seconds
--------------------------------------------------
13 / 40
current local expert:
                     x             y       lon        lat        t         z  \
2602690 -446131.808151  1.784758e+06 -165.9655  73.467531  18262.0  0.009621

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2602690   1257  2020-01-01       cs2        1.0     499866.185044    -0.026275
'local_data_select': 0.001 seconds
number obs: 982
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:21:54.027825: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:21:54.029221: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'optimise_parameters': 0.860 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01001124, 10.01006149,  1.00021315])
kernel_variance: 0.09486088360932986
likelihood_variance: 0.0010000000108386837
'predict': 0.059 seconds
total run time : 1.69 seconds
--------------------------------------------------
14 / 40
current local expert:
                     x             y        lon        lat        t         z  \
2602751 -436203.944832  1.760701e+06 -166.08545  73.700579  18262.0  0.082605

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2602751   1257  2020-01-01       cs2        1.0      525994.07555    -0.026275
'local_data_select': 0.001 seconds
number obs: 1011
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.047 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:21:55.720611: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:21:55.722017: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'optimise_parameters': 1.457 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.00923017, 10.00602461,  0.97831829])
kernel_variance: 0.06556847456688981
likelihood_variance: 0.001000000016763245
'predict': 0.061 seconds
total run time : 2.30 seconds
--------------------------------------------------
15 / 40
current local expert:
                     x             y        lon        lat        t         z  \
2602803 -426972.845914  1.738289e+06 -166.19975  73.917515  18262.0  0.005116

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2602803   1257  2020-01-01       cs2        1.0     550320.662635    -0.026275
'local_data_select': 0.001 seconds
number obs: 1052
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.050 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:21:58.029480: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:21:58.030935: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 2.282 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01001302, 10.01007372,  0.99464924])
kernel_variance: 0.06427137484312449
likelihood_variance: 0.0010000000138732934
'predict': 0.061 seconds
total run time : 3.12 seconds
--------------------------------------------------
16 / 40
current local expert:
                     x             y        lon       lat        t         z  \
2602868 -417638.908079  1.715588e+06 -166.31817  74.13709  18262.0 -0.068499

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2602868   1257  2020-01-01       cs2        1.0     574948.490217    -0.026275
'local_data_select': 0.001 seconds
number obs: 1081
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:22:01.152529: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:22:01.153917: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'optimise_parameters': 1.254 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01000751, 10.01003876,  0.99874302])
kernel_variance: 0.10143728845099784
likelihood_variance: 0.001000000024365722
'predict': 0.065 seconds
total run time : 2.11 seconds
--------------------------------------------------
17 / 40
current local expert:
                     x             y        lon        lat        t        z  \
2602928 -408430.576178  1.693151e+06 -166.43791  74.353944  18262.0 -0.03857

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2602928   1257  2020-01-01       cs2        1.0     599276.501054    -0.026275
'local_data_select': 0.001 seconds
number obs: 1102
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.049 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:22:03.268074: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:22:03.269504: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 1.828 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.00999536, 10.00996329,  1.00818097])
kernel_variance: 0.11280675776967874
likelihood_variance: 0.0010000000254866406
'predict': 0.067 seconds
total run time : 2.69 seconds
--------------------------------------------------
18 / 40
current local expert:
                     x             y        lon        lat        t         z  \
2602977 -398666.557487  1.669314e+06 -166.56818  74.584137  18262.0  0.095247

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2602977   1257  2020-01-01       cs2        1.0     625107.075755    -0.026275
'local_data_select': 0.001 seconds
number obs: 1113
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.049 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:22:05.960119: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:22:05.961526: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 2.546 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.00999118, 10.00993959,  0.99818365])
kernel_variance: 0.11169919230036615
likelihood_variance: 0.0010000000253326347
'predict': 0.065 seconds
total run time : 3.39 seconds
--------------------------------------------------
19 / 40
current local expert:
                     x             y        lon        lat        t         z  \
2603013 -389368.779751  1.646573e+06 -166.69554  74.803574  18262.0  0.098354

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2603013   1257  2020-01-01       cs2        1.0     649736.856583    -0.026275
'local_data_select': 0.001 seconds
number obs: 1110
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.052 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:22:09.356943: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:22:09.358352: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 1.619 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01000051, 10.0099997 ,  0.99070175])
kernel_variance: 0.13276590487323892
likelihood_variance: 0.001000000029071845
'predict': 0.068 seconds
total run time : 2.47 seconds
--------------------------------------------------
20 / 40
current local expert:
                     x             y        lon        lat        t         z  \
2603064 -379856.417788  1.623265e+06 -166.82934  75.028311  18262.0  0.175455

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2603064   1257  2020-01-01       cs2        1.0     674968.058938    -0.026275
'local_data_select': 0.001 seconds
number obs: 1100
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:22:11.826954: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:22:11.828386: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 1.788 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01000459, 10.01002559,  0.98896997])
kernel_variance: 0.14452091390187802
likelihood_variance: 0.0010000000342517842
'predict': 0.066 seconds
SAVING RESULTS TO TABLES:
run_details
preds
lengthscales
kernel_variance
likelihood_variance
total run time : 2.83 seconds
--------------------------------------------------
21 / 40
current local expert:
                    x             y        lon        lat        t        z  \
2603115 -370469.43549  1.600220e+06 -166.96501  75.250319  18262.0  0.11189

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2603115   1257  2020-01-01       cs2        1.0     699899.683625    -0.026275
'local_data_select': 0.001 seconds
number obs: 1103

2026-05-18 19:22:14.658612: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:22:14.660029: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds
**********
optimization failed!
'optimise_parameters': 2.744 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.00999298, 10.00995276,  1.00118704])
kernel_variance: 0.3912266325424397
likelihood_variance: 0.0010000000791522562
'predict': 0.065 seconds
total run time : 3.59 seconds
--------------------------------------------------
22 / 40
current local expert:
                     x             y        lon        lat        t         z  \
2603158 -361207.988293  1.577441e+06 -167.10256  75.469597  18262.0  0.060663

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2603158   1257  2020-01-01       cs2        1.0     724531.599396    -0.026275
'local_data_select': 0.001 seconds
number obs: 1080
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.046 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:22:18.252202: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:22:18.253582: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 2.826 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.00998454, 10.00989429,  1.00150239])
kernel_variance: 0.4000378619011872
likelihood_variance: 0.0010000001085213256
'predict': 0.064 seconds
total run time : 3.67 seconds
--------------------------------------------------
23 / 40
current local expert:
                    x             y        lon        lat        t         z  \
2603206 -351394.48486  1.553259e+06 -167.25253  75.702181  18262.0  0.030505

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2603206   1257  2020-01-01       cs2        1.0     750666.188551    -0.026275
'local_data_select': 0.001 seconds
number obs: 1046
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:22:21.929292: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:22:21.930681: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'optimise_parameters': 1.671 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.00997454, 10.00981647,  1.01341872])
kernel_variance: 0.2800302270983624
likelihood_variance: 0.0010000001098115462
'predict': 0.064 seconds
total run time : 2.54 seconds
--------------------------------------------------
24 / 40
current local expert:
                     x             y        lon        lat        t         z  \
2603252 -342157.794143  1.530454e+06 -167.39783  75.921335  18262.0  0.076249

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2603252   1257  2020-01-01       cs2        1.0      775299.44978    -0.026275
'local_data_select': 0.001 seconds
number obs: 1000
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:22:24.468841: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:22:24.471536: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 1.381 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.00999603, 10.00996121,  0.996213  ])
kernel_variance: 0.2702313313195708
likelihood_variance: 0.0010000001514567525
'predict': 0.060 seconds
total run time : 2.23 seconds
--------------------------------------------------
25 / 40
current local expert:
                     x             y        lon        lat        t         z  \
2603303 -332708.247229  1.507080e+06 -167.55086  76.145767  18262.0 -0.020136

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2603303   1257  2020-01-01       cs2        1.0     800534.244025    -0.026275
'local_data_select': 0.001 seconds
number obs: 987
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:22:26.699458: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:22:26.700951: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'optimise_parameters': 1.625 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.00999132, 10.00993294,  1.0001224 ])
kernel_variance: 0.29781184083654616
likelihood_variance: 0.001000000214048657
'predict': 0.058 seconds
total run time : 2.47 seconds
--------------------------------------------------
26 / 40
current local expert:
                     x             y        lon        lat        t         z  \
2603349 -323608.152772  1.484528e+06 -167.70263  76.362115  18262.0 -0.019481

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2603349   1257  2020-01-01       cs2        1.0     824868.415293    -0.026275
'local_data_select': 0.001 seconds
number obs: 984
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:22:29.171485: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:22:29.172881: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'optimise_parameters': 1.045 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.0099943 , 10.00995261,  0.99698325])
kernel_variance: 0.284922762967748
likelihood_variance: 0.0010000002277082735
'predict': 0.059 seconds
total run time : 1.89 seconds
--------------------------------------------------
27 / 40
current local expert:
                     x             y        lon        lat        t         z  \
2603387 -314183.883806  1.461129e+06 -167.86458  76.586402  18262.0  0.035954

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2603387   1257  2020-01-01       cs2        1.0     850104.541663    -0.026275
'local_data_select': 0.001 seconds
number obs: 961
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.047 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:22:31.059801: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:22:31.061225: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'optimise_parameters': 0.943 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01000019, 10.00999252,  0.99844148])
kernel_variance: 0.23380336497674808
likelihood_variance: 0.001000000106388529
'predict': 0.058 seconds
total run time : 1.81 seconds
--------------------------------------------------
28 / 40
current local expert:
                     x             y       lon        lat        t         z  \
2603437 -304996.050093  1.438275e+06 -168.0274  76.805271  18262.0 -0.063678

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2603437   1257  2020-01-01       cs2        1.0     874740.459917    -0.026275
'local_data_select': 0.001 seconds
number obs: 954
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:22:32.872599: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:22:32.874001: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 3.286 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.0100018 , 10.01000447,  1.00317097])
kernel_variance: 0.24738672471188672
likelihood_variance: 0.0010000001177293578
'predict': 0.059 seconds
total run time : 4.14 seconds
--------------------------------------------------
29 / 40
current local expert:
                     x             y        lon        lat        t         z  \
2603494 -295597.222712  1.414852e+06 -168.19925  77.029395  18262.0 -0.053436

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2603494   1257  2020-01-01       cs2        1.0     899977.897389    -0.026275
'local_data_select': 0.001 seconds
number obs: 911
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:22:37.010368: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:22:37.011834: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 1.528 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.00999859, 10.00998455,  0.9995561 ])
kernel_variance: 0.2576618309999152
likelihood_variance: 0.001000000196632388
'predict': 0.054 seconds
total run time : 2.39 seconds
--------------------------------------------------
30 / 40
current local expert:
                     x             y        lon        lat        t         z  \
2603547 -286322.727665  1.391695e+06 -168.37437  77.250762  18262.0 -0.046795

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2603547   1257  2020-01-01       cs2        1.0     924915.490724    -0.026275
'local_data_select': 0.001 seconds
number obs: 871
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:22:39.402745: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:22:39.404147: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 1.365 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.00999675, 10.00997296,  1.00936976])
kernel_variance: 0.3590178906736126
likelihood_variance: 0.0010000003703149471
'predict': 0.055 seconds
SAVING RESULTS TO TABLES:
run_details
preds
lengthscales
kernel_variance
likelihood_variance
total run time : 2.44 seconds
--------------------------------------------------
31 / 40
current local expert:
                    x             y        lon        lat        t         z  \
2603600 -276838.24457  1.367967e+06 -168.55945  77.477368  18262.0  0.063904

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2603600   1257  2020-01-01       cs2        1.0     950454.674156    -0.026275
'local_data_select': 0.001 seconds
number obs: 868
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.046 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:22:41.841220: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:22:41.842727: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 1.352 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.00991285, 10.0094285 ,  0.99789025])
kernel_variance: 0.37350513634854
likelihood_variance: 0.0010000005784982222
'predict': 0.054 seconds
total run time : 2.20 seconds
--------------------------------------------------
32 / 40
current local expert:
                     x             y        lon        lat        t         z  \
2603653 -267700.994226  1.345066e+06 -168.74382  77.695879  18262.0 -0.057667

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2603653   1257  2020-01-01       cs2        1.0     975093.161073    -0.026275
'local_data_select': 0.001 seconds
number obs: 840
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.047 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:22:44.044727: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:22:44.046180: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'optimise_parameters': 0.573 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.00999785, 10.00998216,  0.99818315])
kernel_variance: 0.40855535145319355
likelihood_variance: 0.001000001338382296
'predict': 0.051 seconds
total run time : 1.44 seconds
--------------------------------------------------
33 / 40
current local expert:
                     x             y        lon        lat        t         z  \
2603696 -258909.726526  1.322991e+06 -168.92714  77.906301  18262.0  0.037628

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2603696   1257  2020-01-01       cs2        1.0     998830.950582    -0.026275
'local_data_select': 0.001 seconds
number obs: 808
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.047 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:22:45.481493: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:22:45.483400: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 1.375 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.00998912, 10.00992637,  1.00661913])
kernel_variance: 0.4817135843017161
likelihood_variance: 0.0010000014300710826
'predict': 0.050 seconds
total run time : 2.24 seconds
--------------------------------------------------
34 / 40
current local expert:
                     x             y        lon        lat        t         z  \
2603739 -249686.019535  1.299787e+06 -169.12608  78.127268  18262.0  0.021209

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2603739   1257  2020-01-01       cs2        1.0      1.023771e+06    -0.026275
'local_data_select': 0.001 seconds
number obs: 798
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.049 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:22:47.724880: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:22:47.726303: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 1.410 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.00999418, 10.00995451,  0.9989074 ])
kernel_variance: 0.490389777789396
likelihood_variance: 0.0010000024199411431
'predict': 0.051 seconds
total run time : 2.28 seconds
--------------------------------------------------
35 / 40
current local expert:
                     x             y        lon        lat        t         z  \
2603793 -239920.587317  1.275173e+06 -169.34451  78.361421  18262.0 -0.012822

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2603793   1257  2020-01-01       cs2        1.0      1.050214e+06    -0.026275
'local_data_select': 0.001 seconds
number obs: 780
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.049 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:22:50.002862: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:22:50.004258: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'optimise_parameters': 0.855 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.00999206, 10.00994317,  1.01299279])
kernel_variance: 0.5391017017160578
likelihood_variance: 0.0010000048724709291
'predict': 0.050 seconds
total run time : 1.70 seconds
--------------------------------------------------
36 / 40
current local expert:
                     x             y       lon        lat        t         z  \
2603841 -230834.085448  1.252225e+06 -169.5554  78.579484  18262.0  0.026182

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2603841   1257  2020-01-01       cs2        1.0      1.074855e+06    -0.026275
'local_data_select': 0.001 seconds
number obs: 756
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.047 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:22:51.706733: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:22:51.708153: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.867 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.00999117, 10.00993681,  0.99197947])
kernel_variance: 0.59855714734143
likelihood_variance: 0.0010000066257649135
'predict': 0.049 seconds
total run time : 1.72 seconds
--------------------------------------------------
37 / 40
current local expert:
                    x             y        lon        lat        t         z  \
2603886 -220986.25609  1.227306e+06 -169.79281  78.816017  18262.0 -0.017355

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2603886   1257  2020-01-01       cs2        1.0      1.101601e+06    -0.026275
'local_data_select': 0.001 seconds
number obs: 732
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.050 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:22:53.432411: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:22:53.433814: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'optimise_parameters': 0.912 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.0099926 , 10.00994897,  0.99257046])
kernel_variance: 0.6446256829386969
likelihood_variance: 0.0010000130925512858
'predict': 0.047 seconds
total run time : 1.76 seconds
--------------------------------------------------
38 / 40
current local expert:
                     x             y       lon        lat        t         z  \
2603928 -212367.948033  1.205457e+06 -170.0086  79.023183  18262.0  0.044398

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2603928   1257  2020-01-01       cs2        1.0      1.125041e+06    -0.026275
'local_data_select': 0.001 seconds
number obs: 724
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.049 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:22:55.195378: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:22:55.196901: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 1.052 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.00998882, 10.00992663,  0.99114875])
kernel_variance: 0.6510354052641433
likelihood_variance: 0.0010000182889548224
'predict': 0.047 seconds
total run time : 1.91 seconds
--------------------------------------------------
39 / 40
current local expert:
                     x             y        lon        lat        t        z  \
2603971 -202989.295181  1.181635e+06 -170.25248  79.248792  18262.0  0.07161

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2603971   1257  2020-01-01       cs2        1.0      1.150586e+06    -0.026275
'local_data_select': 0.001 seconds
number obs: 696
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.049 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:22:57.101939: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:22:57.103335: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'optimise_parameters': 0.982 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.00997349, 10.00982655,  0.94866148])
kernel_variance: 0.6627671283647303
likelihood_variance: 0.001000030258120334
'predict': 0.046 seconds
total run time : 1.85 seconds
--------------------------------------------------
40 / 40
current local expert:
                     x             y        lon        lat        t         z  \
2604030 -192083.057191  1.153875e+06 -170.54876  79.511348  18262.0  0.099178

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2604030   1257  2020-01-01       cs2        1.0      1.180338e+06    -0.026275
'local_data_select': 0.001 seconds
number obs: 670
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.046 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:22:58.950209: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:22:58.951710: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'optimise_parameters': 0.548 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.00999538, 10.00996787,  1.0038586 ])
kernel_variance: 0.8031727552243947
likelihood_variance: 0.0010000415253276944
'predict': 0.045 seconds
SAVING RESULTS TO TABLES:
run_details
preds
lengthscales
kernel_variance
likelihood_variance
total run time : 1.64 seconds
'run': 89.084 seconds
reading in results
getting all tables
merging on expert location data
table: 'oi_config' does not have all coords_col: ['x', 'y', 't'] in columns, not merging on expert_locations
h5 tables: ['expert_locs', 'kernel_variance', 'lengthscales', 'likelihood_variance', 'oi_config', 'preds', 'run_details']
found model_name: GPflowGPRModel
found GPU
setting lengthscales to: [1.]
'__init__': 0.049 seconds
reading in results
selecting only tables: ['lengthscales', 'kernel_variance', 'likelihood_variance']
'data_select': 0.000 seconds
'load': 0.000 seconds
expert_locations data will not be merged on results data
adding smoothed table: lengthscales_SMOOTHED
adding smoothed table: kernel_variance_SMOOTHED
adding smoothed table: likelihood_variance_SMOOTHED
writing (smoothed) hyper parameters to:
/home/mhen/geol0069_data/gpsat/jan20/1257.h5
table_suffix:_SMOOTHED
writing: lengthscales_SMOOTHED to table
writing: kernel_variance_SMOOTHED to table
writing: likelihood_variance_SMOOTHED to table
'data_select': 0.000 seconds
'load': 0.000 seconds
in json_serializable - key: 'data_source' has value DataFrame/Series, but is too long: 2750 >  100
storing as str
in json_serializable - key: 'df' has value DataFrame/Series, but is too long: 7988 >  100
storing as str
---------
storing expert locations in 'expert_locs' table
exception occurred: 'No object named expert_locs_SMOOTHED in the file'
will now close object

2026-05-18 19:23:00.787252: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:23:00.788674: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

---------
dropping expert locations that already exists in 'run_details' table
exception occurred: 'No object named run_details_SMOOTHED in the file'
will now close object

--------------------------------------------------
1 / 40
current local expert:
                     x             y        lon        lat        t         z  \
2602051 -563834.651129  2.066474e+06 -164.73841  70.724595  18262.0 -0.498303

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2602051   1257  2020-01-01       cs2        1.0     192698.973917    -0.026275
'data_select': 0.000 seconds
'load': 0.000 seconds
'local_data_select': 0.001 seconds
number obs: 566
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'get_parameters': 0.003 seconds
'_read_params_from_file': 0.049 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01000161, 10.01002178,  0.99964332])
kernel_variance: 0.05532638923555426
likelihood_variance: 0.01100000000000001
'predict': 0.041 seconds

2026-05-18 19:23:01.040467: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:23:01.041890: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.92 seconds
--------------------------------------------------
2 / 40
current local expert:
                     x             y        lon        lat        t         z  \
2602131 -551788.930876  2.037935e+06 -164.84991  71.003626  18262.0 -0.494699

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2602131   1257  2020-01-01       cs2        1.0     223920.874415    -0.026275
'local_data_select': 0.001 seconds
number obs: 610
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.047 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01000445,  0.99953942])
kernel_variance: 0.05613489693936877
likelihood_variance: 0.01100000000000001
'predict': 0.043 seconds

2026-05-18 19:23:01.965790: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:23:01.967218: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.90 seconds
--------------------------------------------------
3 / 40
current local expert:
                     x             y        lon        lat        t         z  \
2602180 -541841.445861  2.014318e+06 -164.94411  71.234337  18262.0 -0.403015

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2602180   1257  2020-01-01       cs2        1.0     249739.853467    -0.026275
'local_data_select': 0.001 seconds
number obs: 641
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.047 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  0.99944471])
kernel_variance: 0.05693967706323284
likelihood_variance: 0.01100000000000001
'predict': 0.045 seconds

2026-05-18 19:23:02.868708: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:23:02.870136: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.91 seconds
--------------------------------------------------
4 / 40
current local expert:
                     x             y        lon       lat        t         z  \
2602239 -532137.177154  1.991235e+06 -165.03793  71.45966  18262.0 -0.416162

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2602239   1257  2020-01-01       cs2        1.0     274959.293715    -0.026275
'local_data_select': 0.001 seconds
number obs: 679
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.050 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.016 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  0.99934575])
kernel_variance: 0.05785754522750727
likelihood_variance: 0.01100000000000001
'predict': 0.046 seconds

2026-05-18 19:23:03.779960: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:23:03.781355: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.91 seconds
--------------------------------------------------
5 / 40
current local expert:
                     x             y        lon        lat        t         z  \
2602271 -522675.256325  1.968687e+06 -165.13131  71.679593  18262.0 -0.355759

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2602271   1257  2020-01-01       cs2        1.0     299578.880353    -0.026275
'local_data_select': 0.001 seconds
number obs: 709
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.046 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  0.99924449])
kernel_variance: 0.058889208112528325
likelihood_variance: 0.01100000000000001
'predict': 0.046 seconds

2026-05-18 19:23:04.689809: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:23:04.691221: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.90 seconds
--------------------------------------------------
6 / 40
current local expert:
                     x             y        lon        lat        t         z  \
2602318 -512879.150262  1.945299e+06 -165.23004  71.907547  18262.0 -0.234395

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2602318   1257  2020-01-01       cs2        1.0     325100.028603    -0.026275
'local_data_select': 0.001 seconds
number obs: 733
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.047 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  0.99913669])
kernel_variance: 0.06010859203468879
likelihood_variance: 0.01100000000000001
'predict': 0.048 seconds

2026-05-18 19:23:05.596279: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:23:05.598292: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.90 seconds
--------------------------------------------------
7 / 40
current local expert:
                     x             y        lon        lat        t         z  \
2602371 -503209.835084  1.922171e+06 -165.32963  72.132792  18262.0 -0.220557

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2602371   1257  2020-01-01       cs2        1.0     350321.781892    -0.026275
'local_data_select': 0.001 seconds
number obs: 773
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  0.99902977])
kernel_variance: 0.06146946040674813
likelihood_variance: 0.01100000000000001
'predict': 0.051 seconds

2026-05-18 19:23:06.500408: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:23:06.502039: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.91 seconds
--------------------------------------------------
8 / 40
current local expert:
                     x             y        lon       lat        t         z  \
2602436 -493323.032544  1.898477e+06 -165.43373  72.36337  18262.0 -0.266936

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2602436   1257  2020-01-01       cs2        1.0     376144.767111    -0.026275
'local_data_select': 0.001 seconds
number obs: 807
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.050 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  0.99892288])
kernel_variance: 0.06302564896601617
likelihood_variance: 0.01100000000000001
'predict': 0.050 seconds

2026-05-18 19:23:07.413927: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:23:07.415345: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.91 seconds
--------------------------------------------------
9 / 40
current local expert:
                    x             y        lon        lat        t         z  \
2602493 -484251.92654  1.876699e+06 -165.53135  72.575152  18262.0 -0.108551

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2602493   1257  2020-01-01       cs2        1.0     399866.580177    -0.026275
'local_data_select': 0.001 seconds
number obs: 836
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.049 seconds
'_read_params_from_file': 0.045 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  0.99882989])
kernel_variance: 0.06459869193950368
likelihood_variance: 0.01100000000000001
'predict': 0.051 seconds

2026-05-18 19:23:08.322215: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:23:08.323657: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.93 seconds
--------------------------------------------------
10 / 40
current local expert:
                     x             y        lon        lat        t         z  \
2602534 -474618.009133  1.853528e+06 -165.63733  72.800308  18262.0 -0.077163

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2602534   1257  2020-01-01       cs2        1.0     425090.644212    -0.026275
'local_data_select': 0.001 seconds
number obs: 874
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.046 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  0.99873974])
kernel_variance: 0.06641555188343956
likelihood_variance: 0.01100000000000001
'predict': 0.053 seconds

2026-05-18 19:23:09.249173: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:23:09.250580: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

SAVING RESULTS TO TABLES:
run_details
preds
total run time : 1.00 seconds
--------------------------------------------------
11 / 40
current local expert:
                     x             y        lon        lat        t        z  \
2602584 -465110.689028  1.830618e+06 -165.74433  73.022751  18262.0 -0.06368

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2602584   1257  2020-01-01       cs2        1.0     450015.167515    -0.026275
'local_data_select': 0.001 seconds
number obs: 902
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.050 seconds
'_read_params_from_file': 0.051 seconds
'set_parameters': 0.005 seconds

2026-05-18 19:23:10.254427: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:23:10.255826: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  0.99866277])
kernel_variance: 0.06834518861891148
likelihood_variance: 0.01100000000000001
'predict': 0.056 seconds
total run time : 0.94 seconds
--------------------------------------------------
12 / 40
current local expert:
                     x             y        lon        lat        t        z  \
2602627 -455615.544169  1.807695e+06 -165.85368  73.245159  18262.0 -0.01025

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2602627   1257  2020-01-01       cs2        1.0     474940.283698    -0.026275
'local_data_select': 0.001 seconds
number obs: 941
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'_read_params_from_file': 0.045 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  0.99860102])
kernel_variance: 0.07039137160900102
likelihood_variance: 0.01100000000000001
'predict': 0.056 seconds

2026-05-18 19:23:11.195081: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:23:11.196524: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.93 seconds
--------------------------------------------------
13 / 40
current local expert:
                     x             y       lon        lat        t         z  \
2602690 -446131.808151  1.784758e+06 -165.9655  73.467531  18262.0  0.009621

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2602690   1257  2020-01-01       cs2        1.0     499866.185044    -0.026275
'local_data_select': 0.001 seconds
number obs: 982
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  0.99855724])
kernel_variance: 0.07253194815834055
likelihood_variance: 0.01100000000000001
'predict': 0.059 seconds

2026-05-18 19:23:12.128487: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:23:12.129892: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.94 seconds
--------------------------------------------------
14 / 40
current local expert:
                     x             y        lon        lat        t         z  \
2602751 -436203.944832  1.760701e+06 -166.08545  73.700579  18262.0  0.082605

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2602751   1257  2020-01-01       cs2        1.0      525994.07555    -0.026275
'local_data_select': 0.001 seconds
number obs: 1011
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.049 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  0.99853296])
kernel_variance: 0.07484770027728146
likelihood_variance: 0.01100000000000001
'predict': 0.061 seconds

2026-05-18 19:23:13.066128: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:23:13.067534: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.92 seconds
--------------------------------------------------
15 / 40
current local expert:
                     x             y        lon        lat        t         z  \
2602803 -426972.845914  1.738289e+06 -166.19975  73.917515  18262.0  0.005116

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2602803   1257  2020-01-01       cs2        1.0     550320.662635    -0.026275
'local_data_select': 0.001 seconds
number obs: 1052
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.047 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  0.99853144])
kernel_variance: 0.07703952629449919
likelihood_variance: 0.01100000000000001
'predict': 0.063 seconds

2026-05-18 19:23:13.988319: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:23:13.989737: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.93 seconds
--------------------------------------------------
16 / 40
current local expert:
                     x             y        lon       lat        t         z  \
2602868 -417638.908079  1.715588e+06 -166.31817  74.13709  18262.0 -0.068499

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2602868   1257  2020-01-01       cs2        1.0     574948.490217    -0.026275
'local_data_select': 0.001 seconds
number obs: 1081
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  0.99855068])
kernel_variance: 0.07926138069319506
likelihood_variance: 0.01100000000000001

2026-05-18 19:23:14.923292: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:23:14.924700: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'predict': 0.065 seconds
total run time : 0.93 seconds
--------------------------------------------------
17 / 40
current local expert:
                     x             y        lon        lat        t        z  \
2602928 -408430.576178  1.693151e+06 -166.43791  74.353944  18262.0 -0.03857

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2602928   1257  2020-01-01       cs2        1.0     599276.501054    -0.026275
'local_data_select': 0.001 seconds
number obs: 1102
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.050 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  0.99858911])
kernel_variance: 0.08142713165837426
likelihood_variance: 0.01100000000000001

2026-05-18 19:23:15.858757: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:23:15.860190: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'predict': 0.067 seconds
total run time : 0.93 seconds
--------------------------------------------------
18 / 40
current local expert:
                     x             y        lon        lat        t         z  \
2602977 -398666.557487  1.669314e+06 -166.56818  74.584137  18262.0  0.095247

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2602977   1257  2020-01-01       cs2        1.0     625107.075755    -0.026275
'local_data_select': 0.001 seconds
number obs: 1113
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.047 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  0.99864837])
kernel_variance: 0.08366041960459861
likelihood_variance: 0.01100000000000001

2026-05-18 19:23:16.787071: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:23:16.788481: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'predict': 0.066 seconds
total run time : 0.94 seconds
--------------------------------------------------
19 / 40
current local expert:
                     x             y        lon        lat        t         z  \
2603013 -389368.779751  1.646573e+06 -166.69554  74.803574  18262.0  0.098354

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2603013   1257  2020-01-01       cs2        1.0     649736.856583    -0.026275
'local_data_select': 0.001 seconds
number obs: 1110
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.047 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  0.99871865])
kernel_variance: 0.08569557949847356
likelihood_variance: 0.01100000000000001

2026-05-18 19:23:17.731653: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:23:17.733052: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'predict': 0.068 seconds
total run time : 0.95 seconds
--------------------------------------------------
20 / 40
current local expert:
                     x             y        lon        lat        t         z  \
2603064 -379856.417788  1.623265e+06 -166.82934  75.028311  18262.0  0.175455

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2603064   1257  2020-01-01       cs2        1.0     674968.058938    -0.026275
'local_data_select': 0.001 seconds
number obs: 1100
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.047 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  0.99879928])
kernel_variance: 0.08765748813918967
likelihood_variance: 0.01100000000000001

2026-05-18 19:23:18.677542: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:23:18.678968: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'predict': 0.067 seconds
SAVING RESULTS TO TABLES:
run_details
preds
total run time : 1.06 seconds
--------------------------------------------------
21 / 40
current local expert:
                    x             y        lon        lat        t        z  \
2603115 -370469.43549  1.600220e+06 -166.96501  75.250319  18262.0  0.11189

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2603115   1257  2020-01-01       cs2        1.0     699899.683625    -0.026275
'local_data_select': 0.001 seconds
number obs: 1103
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.050 seconds

2026-05-18 19:23:19.744287: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:23:19.745711: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'_read_params_from_file': 0.051 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  0.99888125])
kernel_variance: 0.08945211716170469
likelihood_variance: 0.01100000000000001
'predict': 0.065 seconds
total run time : 0.95 seconds
--------------------------------------------------
22 / 40
current local expert:
                     x             y        lon        lat        t         z  \
2603158 -361207.988293  1.577441e+06 -167.10256  75.469597  18262.0  0.060663

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2603158   1257  2020-01-01       cs2        1.0     724531.599396    -0.026275
'local_data_select': 0.001 seconds
number obs: 1080
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.051 seconds
'_read_params_from_file': 0.045 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  0.99895762])
kernel_variance: 0.09106921012830625
likelihood_variance: 0.01100000000000001

2026-05-18 19:23:20.699519: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:23:20.700933: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'predict': 0.065 seconds
total run time : 0.93 seconds
--------------------------------------------------
23 / 40
current local expert:
                    x             y        lon        lat        t         z  \
2603206 -351394.48486  1.553259e+06 -167.25253  75.702181  18262.0  0.030505

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2603206   1257  2020-01-01       cs2        1.0     750666.188551    -0.026275
'local_data_select': 0.001 seconds
number obs: 1046
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.050 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  0.99902568])
kernel_variance: 0.09260540449275237
likelihood_variance: 0.01100000000000001

2026-05-18 19:23:21.631280: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:23:21.632688: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'predict': 0.065 seconds
total run time : 0.94 seconds
--------------------------------------------------
24 / 40
current local expert:
                     x             y        lon        lat        t         z  \
2603252 -342157.794143  1.530454e+06 -167.39783  75.921335  18262.0  0.076249

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2603252   1257  2020-01-01       cs2        1.0      775299.44978    -0.026275
'local_data_select': 0.001 seconds
number obs: 1000
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.051 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  0.99907017])
kernel_variance: 0.09388097148329817
likelihood_variance: 0.01100000000000001
'predict': 0.060 seconds

2026-05-18 19:23:22.577143: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:23:22.579131: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.92 seconds
--------------------------------------------------
25 / 40
current local expert:
                     x             y        lon        lat        t         z  \
2603303 -332708.247229  1.507080e+06 -167.55086  76.145767  18262.0 -0.020136

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2603303   1257  2020-01-01       cs2        1.0     800534.244025    -0.026275
'local_data_select': 0.001 seconds
number obs: 987
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.050 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  0.99908887])
kernel_variance: 0.09501689982223657
likelihood_variance: 0.01100000000000001
'predict': 0.058 seconds

2026-05-18 19:23:23.497696: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:23:23.499126: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.92 seconds
--------------------------------------------------
26 / 40
current local expert:
                     x             y        lon        lat        t         z  \
2603349 -323608.152772  1.484528e+06 -167.70263  76.362115  18262.0 -0.019481

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2603349   1257  2020-01-01       cs2        1.0     824868.415293    -0.026275
'local_data_select': 0.001 seconds
number obs: 984
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.049 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  0.99907529])
kernel_variance: 0.09595572240813703
likelihood_variance: 0.01100000000000001
'predict': 0.058 seconds

2026-05-18 19:23:24.420328: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:23:24.421732: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.92 seconds
--------------------------------------------------
27 / 40
current local expert:
                     x             y        lon        lat        t         z  \
2603387 -314183.883806  1.461129e+06 -167.86458  76.586402  18262.0  0.035954

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2603387   1257  2020-01-01       cs2        1.0     850104.541663    -0.026275
'local_data_select': 0.001 seconds
number obs: 961
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  0.99902336])
kernel_variance: 0.09677818304974581
likelihood_variance: 0.01100000000000001
'predict': 0.058 seconds

2026-05-18 19:23:25.342287: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:23:25.343691: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.92 seconds
--------------------------------------------------
28 / 40
current local expert:
                     x             y       lon        lat        t         z  \
2603437 -304996.050093  1.438275e+06 -168.0274  76.805271  18262.0 -0.063678

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2603437   1257  2020-01-01       cs2        1.0     874740.459917    -0.026275
'local_data_select': 0.001 seconds
number obs: 954
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.047 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01     , 10.01     ,  0.9989319])
kernel_variance: 0.09744609847229663
likelihood_variance: 0.01100000000000001
'predict': 0.058 seconds

2026-05-18 19:23:26.258371: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:23:26.259790: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.92 seconds
--------------------------------------------------
29 / 40
current local expert:
                     x             y        lon        lat        t         z  \
2603494 -295597.222712  1.414852e+06 -168.19925  77.029395  18262.0 -0.053436

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2603494   1257  2020-01-01       cs2        1.0     899977.897389    -0.026275
'local_data_select': 0.001 seconds
number obs: 911
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.047 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  0.99879412])
kernel_variance: 0.0980075486095577
likelihood_variance: 0.01100000000000001
'predict': 0.054 seconds

2026-05-18 19:23:27.181405: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:23:27.182818: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.91 seconds
--------------------------------------------------
30 / 40
current local expert:
                     x             y        lon        lat        t         z  \
2603547 -286322.727665  1.391695e+06 -168.37437  77.250762  18262.0 -0.046795

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2603547   1257  2020-01-01       cs2        1.0     924915.490724    -0.026275
'local_data_select': 0.001 seconds
number obs: 871
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  0.99861334])
kernel_variance: 0.09845617387451615
likelihood_variance: 0.01100000000000001
'predict': 0.055 seconds

2026-05-18 19:23:28.096826: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:23:28.098237: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

SAVING RESULTS TO TABLES:
run_details
preds
total run time : 1.08 seconds
--------------------------------------------------
31 / 40
current local expert:
                    x             y        lon        lat        t         z  \
2603600 -276838.24457  1.367967e+06 -168.55945  77.477368  18262.0  0.063904

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2603600   1257  2020-01-01       cs2        1.0     950454.674156    -0.026275
'local_data_select': 0.001 seconds
number obs: 868
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.046 seconds

2026-05-18 19:23:29.173967: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:23:29.175380: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'_read_params_from_file': 0.051 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  0.99838281])
kernel_variance: 0.09882252202691164
likelihood_variance: 0.01100000000000001
'predict': 0.054 seconds
total run time : 0.93 seconds
--------------------------------------------------
32 / 40
current local expert:
                     x             y        lon        lat        t         z  \
2603653 -267700.994226  1.345066e+06 -168.74382  77.695879  18262.0 -0.057667

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2603653   1257  2020-01-01       cs2        1.0     975093.161073    -0.026275
'local_data_select': 0.001 seconds
number obs: 840
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.049 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  0.99811872])
kernel_variance: 0.09910123828768533
likelihood_variance: 0.01100000000000001
'predict': 0.051 seconds

2026-05-18 19:23:30.111999: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:23:30.113426: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.91 seconds
--------------------------------------------------
33 / 40
current local expert:
                     x             y        lon        lat        t         z  \
2603696 -258909.726526  1.322991e+06 -168.92714  77.906301  18262.0  0.037628

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2603696   1257  2020-01-01       cs2        1.0     998830.950582    -0.026275
'local_data_select': 0.001 seconds
number obs: 808
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.049 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  0.99782818])
kernel_variance: 0.0993124977995389
likelihood_variance: 0.01100000000000001
'predict': 0.050 seconds

2026-05-18 19:23:31.027525: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:23:31.028959: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.93 seconds
--------------------------------------------------
34 / 40
current local expert:
                     x             y        lon        lat        t         z  \
2603739 -249686.019535  1.299787e+06 -169.12608  78.127268  18262.0  0.021209

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2603739   1257  2020-01-01       cs2        1.0      1.023771e+06    -0.026275
'local_data_select': 0.001 seconds
number obs: 798
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.050 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  0.99748835])
kernel_variance: 0.09948516250463929
likelihood_variance: 0.01100000000000001
'predict': 0.051 seconds

2026-05-18 19:23:31.956856: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:23:31.958282: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.91 seconds
--------------------------------------------------
35 / 40
current local expert:
                     x             y        lon        lat        t         z  \
2603793 -239920.587317  1.275173e+06 -169.34451  78.361421  18262.0 -0.012822

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2603793   1257  2020-01-01       cs2        1.0      1.050214e+06    -0.026275
'local_data_select': 0.001 seconds
number obs: 780
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  0.99709408])
kernel_variance: 0.09962417070435116
likelihood_variance: 0.01100000000000001
'predict': 0.050 seconds

2026-05-18 19:23:32.868497: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:23:32.869933: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.92 seconds
--------------------------------------------------
36 / 40
current local expert:
                     x             y       lon        lat        t         z  \
2603841 -230834.085448  1.252225e+06 -169.5554  78.579484  18262.0  0.026182

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2603841   1257  2020-01-01       cs2        1.0      1.074855e+06    -0.026275
'local_data_select': 0.001 seconds
number obs: 756
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.049 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  0.99670012])
kernel_variance: 0.09972164666914009
likelihood_variance: 0.01100000000000001
'predict': 0.050 seconds

2026-05-18 19:23:33.793722: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:23:33.795148: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.92 seconds
--------------------------------------------------
37 / 40
current local expert:
                    x             y        lon        lat        t         z  \
2603886 -220986.25609  1.227306e+06 -169.79281  78.816017  18262.0 -0.017355

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2603886   1257  2020-01-01       cs2        1.0      1.101601e+06    -0.026275
'local_data_select': 0.001 seconds
number obs: 732
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.049 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  0.99624919])
kernel_variance: 0.09980047623371746
likelihood_variance: 0.01100000000000001
'predict': 0.047 seconds

2026-05-18 19:23:34.710215: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:23:34.711612: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.91 seconds
--------------------------------------------------
38 / 40
current local expert:
                     x             y       lon        lat        t         z  \
2603928 -212367.948033  1.205457e+06 -170.0086  79.023183  18262.0  0.044398

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2603928   1257  2020-01-01       cs2        1.0      1.125041e+06    -0.026275
'local_data_select': 0.001 seconds
number obs: 724
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.049 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  0.99583871])
kernel_variance: 0.0998518096715442
likelihood_variance: 0.01100000000000001
'predict': 0.047 seconds

2026-05-18 19:23:35.621324: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:23:35.623235: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.91 seconds
--------------------------------------------------
39 / 40
current local expert:
                     x             y        lon        lat        t        z  \
2603971 -202989.295181  1.181635e+06 -170.25248  79.248792  18262.0  0.07161

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2603971   1257  2020-01-01       cs2        1.0      1.150586e+06    -0.026275
'local_data_select': 0.001 seconds
number obs: 696
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.046 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  0.99538004])
kernel_variance: 0.09989342770641875
likelihood_variance: 0.01100000000000001
'predict': 0.046 seconds

2026-05-18 19:23:36.526515: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:23:36.527946: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.92 seconds
--------------------------------------------------
40 / 40
current local expert:
                     x             y        lon        lat        t         z  \
2604030 -192083.057191  1.153875e+06 -170.54876  79.511348  18262.0  0.099178

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2604030   1257  2020-01-01       cs2        1.0      1.180338e+06    -0.026275
'local_data_select': 0.001 seconds
number obs: 670
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  0.99483727])
kernel_variance: 0.09992789376382677
likelihood_variance: 0.01100000000000001
'predict': 0.045 seconds

2026-05-18 19:23:37.451644: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:23:37.453061: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

SAVING RESULTS TO TABLES:
run_details
preds
total run time : 1.07 seconds
'run': 37.562 seconds
reading in results
getting all tables
merging on expert location data
table: 'oi_config' does not have all coords_col: ['x', 'y', 't'] in columns, not merging on expert_locations
table: 'oi_config_SMOOTHED' does not have all coords_col: ['x', 'y', 't'] in columns, not merging on expert_locations
lin:
                     x             y        lon        lat        t         z  \
2601689 -638579.271484  2.242111e+06 -164.10243  69.001559  18262.0 -0.746479
2601690 -638462.214874  2.241838e+06 -164.10336  69.004244  18262.0 -0.798415
2601691 -638111.488080  2.241019e+06 -164.10614  69.012299  18262.0 -0.665761
2601692 -637409.906412  2.239382e+06 -164.11171  69.028408  18262.0 -0.714593
2601693 -637292.936222  2.239109e+06 -164.11264  69.031093  18262.0 -0.669882

         track date_string satellite  lead_mask  dist_along_track  \
2601689   1257  2020-01-01       cs2        1.0          0.000000
2601690   1257  2020-01-01       cs2        1.0        300.176217
2601691   1257  2020-01-01       cs2        1.0       1200.652652
2601692   1257  2020-01-01       cs2        1.0       3001.529271
2601693   1257  2020-01-01       cs2        1.0       3301.699913

         z_track_avg     f_lin
2601689    -0.026275 -0.469714
2601690    -0.026275 -0.469714
2601691    -0.026275 -0.469714
2601692    -0.026275 -0.469714
2601693    -0.026275 -0.469714
gpsat:
                     x             y        lon        lat        t         z  \
2601689 -638579.271484  2.242111e+06 -164.10243  69.001559  18262.0 -0.746479
2601690 -638462.214874  2.241838e+06 -164.10336  69.004244  18262.0 -0.798415
2601691 -638111.488080  2.241019e+06 -164.10614  69.012299  18262.0 -0.665761
2601692 -637409.906412  2.239382e+06 -164.11171  69.028408  18262.0 -0.714593
2601693 -637292.936222  2.239109e+06 -164.11264  69.031093  18262.0 -0.669882

         track date_string satellite  lead_mask  dist_along_track  \
2601689   1257  2020-01-01       cs2        1.0          0.000000
2601690   1257  2020-01-01       cs2        1.0        300.176217
2601691   1257  2020-01-01       cs2        1.0       1200.652652
2601692   1257  2020-01-01       cs2        1.0       3001.529271
2601693   1257  2020-01-01       cs2        1.0       3301.699913

         z_track_avg   f_gpsat  f_var_gpsat
2601689    -0.026275 -0.070027    -0.070027
2601690    -0.026275 -0.070306    -0.070306
2601691    -0.026275 -0.071150    -0.071150
2601692    -0.026275 -0.072866    -0.072866
2601693    -0.026275 -0.073156    -0.073156
Test NaNs — Linear: 0, GPSat: 330
Track interpolated!
Interpolating track 1258, 13 of 15...

/tmp/ipykernel_1171781/839927469.py:200: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  track_df['f_gpsat'] = ssha
/tmp/ipykernel_1171781/839927469.py:201: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  track_df['f_var_gpsat'] = ssha_var
/tmp/ipykernel_1171781/839927469.py:66: RuntimeWarning: invalid value encountered in sqrt
  gpsat_std = np.sqrt(gpsat_var[both_valid])

Expert limit reached.
'data_select': 0.000 seconds
'load': 0.000 seconds
in json_serializable - key: 'data_source' has value DataFrame/Series, but is too long: 1814 >  100
storing as str
in json_serializable - key: 'df' has value DataFrame/Series, but is too long: 6881 >  100
storing as str
---------
storing expert locations in 'expert_locs' table
exception occurred: 'No object named expert_locs in the file'
will now close object

---------
dropping expert locations that already exists in 'run_details' table
exception occurred: 'No object named run_details in the file'
will now close object

--------------------------------------------------
1 / 40
current local expert:
                    x             y        lon        lat        t         z  \
2609679  359196.91784  2.171377e+06  170.60699  70.189152  18262.0  0.151773

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2609679   1258  2020-01-01       cs2        1.0        900.563443      0.08407
'data_select': 0.000 seconds
'load': 0.000 seconds
'local_data_select': 0.001 seconds
number obs: 301
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.047 seconds
'get_parameters': 0.003 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.011 seconds

2026-05-18 19:23:39.690641: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:23:39.692071: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.559 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.00995595, 10.00002838,  1.65184798])
kernel_variance: 0.037119323396145314
likelihood_variance: 0.003312348634115409
'predict': 0.032 seconds
total run time : 1.40 seconds
--------------------------------------------------
2 / 40
current local expert:
                     x             y        lon        lat        t         z  \
2609726  358416.503277  2.147582e+06  170.52506  70.403855  18262.0  0.125492

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2609726   1258  2020-01-01       cs2        1.0      24917.387423      0.08407
'local_data_select': 0.001 seconds
number obs: 316
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.051 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:23:41.098998: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:23:41.100401: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.386 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01000014, 10.01010284,  0.99900923])
kernel_variance: 0.032543000289501786
likelihood_variance: 0.004023324941356214
'predict': 0.032 seconds
total run time : 1.24 seconds
--------------------------------------------------
3 / 40
current local expert:
                     x             y       lon        lat        t         z  \
2609779  357620.773668  2.123780e+06  170.4417  70.618539  18262.0  0.099033

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2609779   1258  2020-01-01       cs2        1.0      48934.789732      0.08407
'local_data_select': 0.001 seconds
number obs: 319
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.049 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:23:42.342016: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:23:42.343443: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'optimise_parameters': 0.432 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01000011, 10.01007161,  0.99987252])
kernel_variance: 0.03562863169583816
likelihood_variance: 0.004001566159242078
'predict': 0.032 seconds
total run time : 1.29 seconds
--------------------------------------------------
4 / 40
current local expert:
                     x             y        lon       lat        t         z  \
2609830  356604.344251  2.094015e+06  170.33542  70.88687  18262.0  0.002512

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2609830   1258  2020-01-01       cs2        1.0      78957.779062      0.08407
'local_data_select': 0.001 seconds
number obs: 328
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.047 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:23:43.631008: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:23:43.632411: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'optimise_parameters': 0.343 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01000013, 10.0100782 ,  0.99874078])
kernel_variance: 0.030383891353216865
likelihood_variance: 0.004054444031644072
'predict': 0.033 seconds
total run time : 1.19 seconds
--------------------------------------------------
5 / 40
current local expert:
                     x             y       lon        lat        t         z  \
2609869  355878.514203  2.073172e+06  170.2596  71.074682  18262.0  0.080421

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2609869   1258  2020-01-01       cs2        1.0      99974.365488      0.08407
'local_data_select': 0.001 seconds
number obs: 328
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.046 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:23:44.821261: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:23:44.822651: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'optimise_parameters': 0.345 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01000013, 10.0100782 ,  0.99874078])
kernel_variance: 0.030383891353216865
likelihood_variance: 0.004054444031644072
'predict': 0.033 seconds
total run time : 1.19 seconds
--------------------------------------------------
6 / 40
current local expert:
                     x             y        lon        lat        t         z  \
2609896  354991.945131  2.048152e+06  170.16701  71.300037  18262.0  0.118978

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2609896   1258  2020-01-01       cs2        1.0     125195.146076      0.08407
'local_data_select': 0.001 seconds
number obs: 329
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.050 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:23:46.013173: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:23:46.014584: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.415 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01000015, 10.01009498,  1.00016127])
kernel_variance: 0.027359519188812326
likelihood_variance: 0.004070375336093208
'predict': 0.033 seconds
total run time : 1.26 seconds
--------------------------------------------------
7 / 40
current local expert:
                     x             y        lon        lat        t        z  \
2609930  354121.013859  2.024018e+06  170.07601  71.517321  18262.0 -0.08639

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2609930   1258  2020-01-01       cs2        1.0     149515.926806      0.08407
'local_data_select': 0.001 seconds
number obs: 334
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.046 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:23:47.274181: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:23:47.275604: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.599 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.00995808, 10.00011576,  0.99449732])
kernel_variance: 0.02479115392769751
likelihood_variance: 0.004072015565069212
'predict': 0.034 seconds
total run time : 1.44 seconds
--------------------------------------------------
8 / 40
current local expert:
                     x             y        lon        lat        t         z  \
2609981  353190.425799  1.998683e+06  169.97863  71.745309  18262.0  0.076463

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2609981   1258  2020-01-01       cs2        1.0     175038.440334      0.08407
'local_data_select': 0.001 seconds
number obs: 342
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.047 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:23:48.715299: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:23:48.717294: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'optimise_parameters': 0.357 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.00994488, 10.00002426,  0.99592666])
kernel_variance: 0.02266908313610352
likelihood_variance: 0.004005807148158765
'predict': 0.034 seconds
total run time : 1.22 seconds
--------------------------------------------------
9 / 40
current local expert:
                     x             y        lon        lat        t         z  \
2610030  352287.015651  1.974532e+06  169.88399  71.962544  18262.0  0.080553

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2610030   1258  2020-01-01       cs2        1.0     199360.678082      0.08407
'local_data_select': 0.001 seconds
number obs: 350
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.047 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:23:49.940807: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:23:49.942327: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.620 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01000019, 10.01010589,  1.00010689])
kernel_variance: 0.025185613720286038
likelihood_variance: 0.003922068024135401
'predict': 0.035 seconds
total run time : 1.49 seconds
--------------------------------------------------
10 / 40
current local expert:
                     x             y        lon        lat        t         z  \
2610075  351528.232249  1.954549e+06  169.80428  72.142213  18262.0  0.087219

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2610075   1258  2020-01-01       cs2        1.0     219479.688778      0.08407
'local_data_select': 0.001 seconds
number obs: 364
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.047 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:23:51.428015: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:23:51.429416: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'optimise_parameters': 0.489 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.0100002 , 10.01011137,  1.00079495])
kernel_variance: 0.023905375554072593
likelihood_variance: 0.0038463376454230228
'predict': 0.035 seconds
SAVING RESULTS TO TABLES:
run_details
preds
lengthscales
kernel_variance
likelihood_variance
total run time : 1.49 seconds
--------------------------------------------------
11 / 40
current local expert:
                     x             y        lon        lat        t         z  \
2610147  350270.260797  1.922029e+06  169.67177  72.434471  18262.0  0.089665

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2610147   1258  2020-01-01       cs2        1.0     252211.613832      0.08407
'local_data_select': 0.001 seconds
number obs: 382
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.047 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:23:52.918471: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:23:52.919913: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.476 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01000021, 10.01011153,  0.99944358])
kernel_variance: 0.02428294650558854
likelihood_variance: 0.0037353405274409665
'predict': 0.035 seconds
total run time : 1.35 seconds
--------------------------------------------------
12 / 40
current local expert:
                     x             y      lon        lat        t         z  \
2610187  349459.052271  1.901436e+06  169.586  72.619452  18262.0  0.086406

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2610187   1258  2020-01-01       cs2        1.0     272932.493471      0.08407
'local_data_select': 0.001 seconds
number obs: 406
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:23:54.267813: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:23:54.269223: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.662 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.00994388, 10.0000475 ,  0.90987011])
kernel_variance: 0.02947936628364423
likelihood_variance: 0.0035491097673114027
'predict': 0.036 seconds
total run time : 1.52 seconds
--------------------------------------------------
13 / 40
current local expert:
                     x             y        lon        lat        t        z  \
2610240  348360.115448  1.873970e+06  169.46925  72.866058  18262.0  0.10557

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2610240   1258  2020-01-01       cs2        1.0      300561.02212      0.08407
'local_data_select': 0.001 seconds
number obs: 418
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.047 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:23:55.786335: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:23:55.787752: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.532 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01000021, 10.01010957,  1.00018557])
kernel_variance: 0.028144303242200415
likelihood_variance: 0.003485800526477277
'predict': 0.036 seconds
total run time : 1.41 seconds
--------------------------------------------------
14 / 40
current local expert:
                     x             y        lon        lat        t        z  \
2610280  347387.842887  1.850078e+06  169.36544  73.080466  18262.0  0.13663

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2610280   1258  2020-01-01       cs2        1.0       324586.6534      0.08407
'local_data_select': 0.001 seconds
number obs: 436
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:23:57.195125: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:23:57.196560: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.496 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.0100002 , 10.01009944,  0.99867162])
kernel_variance: 0.03283992098794649
likelihood_variance: 0.003382532013106381
'predict': 0.036 seconds
total run time : 1.36 seconds
--------------------------------------------------
15 / 40
current local expert:
                     x             y        lon       lat        t         z  \
2610349  346125.688314  1.819606e+06  169.22986  73.35379  18262.0  0.149285

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2610349   1258  2020-01-01       cs2        1.0     355220.377437      0.08407
'local_data_select': 0.001 seconds
number obs: 457
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.047 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:23:58.554475: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:23:58.555893: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'optimise_parameters': 0.813 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.00995243, 10.00009493,  0.72228313])
kernel_variance: 0.02851910554623173
likelihood_variance: 0.003311774412271606
'predict': 0.039 seconds
total run time : 1.68 seconds
--------------------------------------------------
16 / 40
current local expert:
                     x             y       lon        lat        t        z  \
2610396  345308.270507  1.800182e+06  169.1415  73.527938  18262.0  0.25622

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2610396   1258  2020-01-01       cs2        1.0     374742.409198      0.08407
'local_data_select': 0.001 seconds
number obs: 468
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.046 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:24:00.231813: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:24:00.233209: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.719 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01000024, 10.01010422,  1.0011644 ])
kernel_variance: 0.027254744522834797
likelihood_variance: 0.0032855133730178305
'predict': 0.039 seconds
total run time : 1.60 seconds
--------------------------------------------------
17 / 40
current local expert:
                    x             y        lon        lat        t         z  \
2610460  344249.97765  1.775371e+06  169.02635  73.750278  18262.0  0.213794

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2610460   1258  2020-01-01       cs2        1.0     399671.304385      0.08407
'local_data_select': 0.001 seconds
number obs: 487
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.049 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:24:01.834723: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:24:01.836128: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.617 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01000017, 10.0100946 ,  1.00073757])
kernel_variance: 0.03288781279784167
likelihood_variance: 0.0034230684250386
'predict': 0.039 seconds
total run time : 1.49 seconds
--------------------------------------------------
18 / 40
current local expert:
                     x             y       lon        lat        t         z  \
2610529  342913.507215  1.744573e+06  168.8797  74.026137  18262.0  0.088776

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2610529   1258  2020-01-01       cs2        1.0     430608.073349      0.08407
'local_data_select': 0.001 seconds
number obs: 468
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.050 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:24:03.325749: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:24:03.327146: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.603 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01000018, 10.01008898,  1.00116609])
kernel_variance: 0.024775128208678332
likelihood_variance: 0.003232753652691375
'predict': 0.037 seconds
total run time : 1.49 seconds
--------------------------------------------------
19 / 40
current local expert:
                     x             y        lon        lat        t         z  \
2610589  341804.679987  1.719447e+06  168.75688  74.251061  18262.0  0.184701

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2610589   1258  2020-01-01       cs2        1.0     455838.913061      0.08407
'local_data_select': 0.001 seconds
number obs: 453
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.047 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:24:04.812093: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:24:04.813501: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.625 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.00996621, 10.00197581,  1.42653082])
kernel_variance: 0.02881657078823655
likelihood_variance: 0.002862984989019992
'predict': 0.037 seconds
total run time : 1.49 seconds
--------------------------------------------------
20 / 40
current local expert:
                     x             y        lon        lat        t         z  \
2610637  340934.987447  1.700000e+06  168.65977  74.425077  18262.0 -0.006906

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2610637   1258  2020-01-01       cs2        1.0     475363.191317      0.08407
'local_data_select': 0.001 seconds
number obs: 432
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.049 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:24:06.308157: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:24:06.309566: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.629 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01000014, 10.01007939,  0.99774535])
kernel_variance: 0.02901019770571791
likelihood_variance: 0.0028787451261234123
'predict': 0.037 seconds
SAVING RESULTS TO TABLES:
run_details
preds
lengthscales
kernel_variance
likelihood_variance
total run time : 1.67 seconds
--------------------------------------------------
21 / 40
current local expert:
                     x             y      lon        lat        t         z  \
2610754  339192.499774  1.661691e+06  168.463  74.767672  18262.0  0.130161

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2610754   1258  2020-01-01       cs2        1.0     513812.543715      0.08407
'local_data_select': 0.001 seconds
number obs: 421

2026-05-18 19:24:07.984132: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:24:07.985566: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.049 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds
'optimise_parameters': 0.702 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.00966401, 10.00000446,  3.37531126])
kernel_variance: 0.016949107250751626
likelihood_variance: 0.002832278833770465
'predict': 0.037 seconds
total run time : 1.59 seconds
--------------------------------------------------
22 / 40
current local expert:
                     x             y        lon       lat        t         z  \
2610856  337452.980234  1.624264e+06  168.26334  75.10212  18262.0  0.083539

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2610856   1258  2020-01-01       cs2        1.0     551362.276047      0.08407
'local_data_select': 0.001 seconds
number obs: 421
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:24:09.574817: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:24:09.576230: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.581 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.00991522, 10.00029115,  0.10639872])
kernel_variance: 0.0146763415733643
likelihood_variance: 0.0027162904170632924
'predict': 0.038 seconds
total run time : 1.46 seconds
--------------------------------------------------
23 / 40
current local expert:
                     x             y        lon        lat        t         z  \
2610910  336505.268316  1.604197e+06  168.15309  75.281335  18262.0  0.069717

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2610910   1258  2020-01-01       cs2        1.0     571489.775231      0.08407
'local_data_select': 0.001 seconds
number obs: 402
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:24:11.032952: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:24:11.034353: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.598 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.00991135, 10.00018974,  3.81665978])
kernel_variance: 0.014989378481566116
likelihood_variance: 0.002717102269997832
'predict': 0.038 seconds
total run time : 1.47 seconds
--------------------------------------------------
24 / 40
current local expert:
                     x             y        lon        lat        t         z  \
2610983  335142.825923  1.575737e+06  167.99271  75.535379  18262.0  0.203011

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2610983   1258  2020-01-01       cs2        1.0     600029.228347      0.08407
'local_data_select': 0.001 seconds
number obs: 381
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.051 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:24:12.508022: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:24:12.509433: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'optimise_parameters': 0.394 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.00979278, 10.00001256,  0.93543331])
kernel_variance: 0.010128283658526341
likelihood_variance: 0.0032810883645757885
'predict': 0.037 seconds
total run time : 1.29 seconds
--------------------------------------------------
25 / 40
current local expert:
                    x             y        lon        lat        t         z  \
2611047  333964.04117  1.551464e+06  167.85203  75.751922  18262.0  0.006052

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2611047   1258  2020-01-01       cs2        1.0     624363.551446      0.08407
'local_data_select': 0.001 seconds
number obs: 399
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.047 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:24:13.795165: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:24:13.796593: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'optimise_parameters': 0.349 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01000013, 10.01007385,  1.00324342])
kernel_variance: 0.008854542362675341
likelihood_variance: 0.0032197023175983444
'predict': 0.038 seconds
total run time : 1.22 seconds
--------------------------------------------------
26 / 40
current local expert:
                    x             y        lon        lat        t         z  \
2611112  332724.79562  1.526286e+06  167.70213  75.976422  18262.0  0.139253

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2611112   1258  2020-01-01       cs2        1.0     649599.953117      0.08407
'local_data_select': 0.001 seconds
number obs: 409
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.046 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:24:15.019238: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:24:15.020660: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'optimise_parameters': 0.302 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01000009, 10.0100553 ,  1.0004885 ])
kernel_variance: 0.007952145215971774
likelihood_variance: 0.0033301555262321763
'predict': 0.038 seconds
total run time : 1.18 seconds
--------------------------------------------------
27 / 40
current local expert:
                     x             y        lon        lat        t         z  \
2611169  331438.837733  1.500502e+06  167.54421  76.206194  18262.0  0.059319

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2611169   1258  2020-01-01       cs2        1.0     675437.819576      0.08407
'local_data_select': 0.001 seconds
number obs: 417
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:24:16.204706: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:24:16.206097: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.619 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.00982382, 10.00003274,  1.01855029])
kernel_variance: 0.008241155976368167
likelihood_variance: 0.0035003680839158645
'predict': 0.038 seconds
total run time : 1.51 seconds
--------------------------------------------------
28 / 40
current local expert:
                     x             y        lon        lat        t         z  \
2611235  330089.077644  1.473812e+06  167.37582  76.443902  18262.0  0.059448

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2611235   1258  2020-01-01       cs2        1.0     702177.889551      0.08407
'local_data_select': 0.001 seconds
number obs: 408
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.046 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:24:17.717718: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:24:17.719120: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'optimise_parameters': 0.461 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.00989146, 10.00019905,  0.99834262])
kernel_variance: 0.006682114019145407
likelihood_variance: 0.003588066714681034
'predict': 0.037 seconds
total run time : 1.34 seconds
--------------------------------------------------
29 / 40
current local expert:
                     x             y        lon       lat        t         z  \
2611289  328921.318023  1.451015e+06  167.22783  76.64682  18262.0  0.097988

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2611289   1258  2020-01-01       cs2        1.0     725012.700294      0.08407
'local_data_select': 0.001 seconds
number obs: 402
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.047 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:24:19.058402: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:24:19.059938: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.588 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01000024, 10.01009521,  0.99714552])
kernel_variance: 0.0063118093163045995
likelihood_variance: 0.0036458442165246494
'predict': 0.039 seconds
total run time : 1.48 seconds
--------------------------------------------------
30 / 40
current local expert:
                     x             y        lon        lat        t         z  \
2611351  327567.479867  1.424912e+06  167.05343  76.879026  18262.0 -0.003509

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2611351   1258  2020-01-01       cs2        1.0      751153.26076      0.08407
'local_data_select': 0.001 seconds
number obs: 410
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:24:20.537372: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:24:20.538823: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.634 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.00984017, 10.00000334,  0.97747189])
kernel_variance: 0.006561834784451452
likelihood_variance: 0.0035927497854593366
'predict': 0.038 seconds
SAVING RESULTS TO TABLES:
run_details
preds
lengthscales
kernel_variance
likelihood_variance
total run time : 1.70 seconds
--------------------------------------------------
31 / 40
current local expert:
                     x             y        lon        lat        t         z  \
2611415  326290.884185  1.400603e+06  166.88602  77.095134  18262.0  0.059887

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2611415   1258  2020-01-01       cs2        1.0       775491.6297      0.08407
'local_data_select': 0.001 seconds
number obs: 415

2026-05-18 19:24:22.238821: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:24:22.240242: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.047 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds
**********
optimization failed!
'optimise_parameters': 0.559 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01000039, 10.01013324,  0.99659833])
kernel_variance: 0.005416832539890411
likelihood_variance: 0.003592792554395601
'predict': 0.038 seconds
total run time : 1.46 seconds
--------------------------------------------------
32 / 40
current local expert:
                     x             y        lon        lat        t         z  \
2611471  324934.108018  1.375089e+06  166.70486  77.321823  18262.0  0.042512

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2611471   1258  2020-01-01       cs2        1.0     801032.546069      0.08407
'local_data_select': 0.001 seconds
number obs: 425
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:24:23.701311: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:24:23.702706: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.488 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01000037, 10.01012211,  0.99984233])
kernel_variance: 0.004442287099597339
likelihood_variance: 0.003524288297423006
'predict': 0.039 seconds
total run time : 1.39 seconds
--------------------------------------------------
33 / 40
current local expert:
                     x             y        lon        lat        t         z  \
2611529  323657.645529  1.351370e+06  166.53118  77.532422  18262.0  0.041446

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2611529   1258  2020-01-01       cs2        1.0     824771.208149      0.08407
'local_data_select': 0.001 seconds
number obs: 420
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.053 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:24:25.093969: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:24:25.095372: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.767 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.00990802, 10.00095398,  0.94430365])
kernel_variance: 0.006498514891665471
likelihood_variance: 0.0029673413758205644
'predict': 0.040 seconds
total run time : 1.67 seconds
--------------------------------------------------
34 / 40
current local expert:
                    x             y        lon       lat        t         z  \
2611588  322283.80997  1.326146e+06  166.34061  77.75625  18262.0 -0.049508

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2611588   1258  2020-01-01       cs2        1.0     850012.807937      0.08407
'local_data_select': 0.001 seconds
number obs: 434
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:24:26.756339: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:24:26.757744: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9
2026-05-18 19:24:27.120353: W tensorflow/core/kernels/linalg/cholesky_op_gpu.cu.cc:205] Cholesky decomposition was not successful for batch 0. The input might not be valid. Filling lower-triangular output with NaNs.

'optimise_parameters': 0.358 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([1.00092829e+01, 1.00000000e+01, 1.00000000e-08])
kernel_variance: 5.661882941889318
likelihood_variance: 10.0
'predict': 0.039 seconds
total run time : 1.26 seconds
--------------------------------------------------
35 / 40
current local expert:
                     x             y        lon        lat        t         z  \
2611647  320976.393795  1.302417e+06  166.15553  77.966657  18262.0  0.091921

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2611647   1258  2020-01-01       cs2        1.0     873752.610646      0.08407
'local_data_select': 0.001 seconds
number obs: 434
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.046 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:24:28.014107: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:24:28.015504: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.504 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.00999967, 10.00990079,  1.0008789 ])
kernel_variance: 0.888885712570878
likelihood_variance: 0.0010005774476144105
'predict': 0.037 seconds
total run time : 1.39 seconds
--------------------------------------------------
36 / 40
current local expert:
                     x             y        lon        lat        t         z  \
2611692  319485.484187  1.275680e+06  165.93985  78.203577  18262.0  0.091828

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2611692   1258  2020-01-01       cs2        1.0     900498.188186      0.08407
'local_data_select': 0.001 seconds
number obs: 446
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.049 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:24:29.411512: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:24:29.413518: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.458 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.00999979, 10.00993109,  1.00489211])
kernel_variance: 0.8230959054994734
likelihood_variance: 0.001000490308930899
'predict': 0.037 seconds
total run time : 1.35 seconds
--------------------------------------------------
37 / 40
current local expert:
                     x             y        lon        lat        t         z  \
2611751  318163.368532  1.252242e+06  165.74422  78.411103  18262.0  0.085536

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2611751   1258  2020-01-01       cs2        1.0     923938.793163      0.08407
'local_data_select': 0.001 seconds
number obs: 451
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.049 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:24:30.761707: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:24:30.763129: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.473 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.00999981, 10.00993294,  1.0019242 ])
kernel_variance: 0.8287399975287203
likelihood_variance: 0.0010004663300265603
'predict': 0.038 seconds
total run time : 1.38 seconds
--------------------------------------------------
38 / 40
current local expert:
                     x             y        lon        lat        t         z  \
2611805  316671.169201  1.226095e+06  165.51833  78.642443  18262.0  0.024269

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2611805   1258  2020-01-01       cs2        1.0     950084.675176      0.08407
'local_data_select': 0.001 seconds
number obs: 449
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.047 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:24:32.139684: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:24:32.141116: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'optimise_parameters': 0.538 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.00999984, 10.00993099,  1.00050307])
kernel_variance: 0.8063036398564544
likelihood_variance: 0.001000440410791847
'predict': 0.037 seconds
total run time : 1.45 seconds
--------------------------------------------------
39 / 40
current local expert:
                     x             y        lon       lat        t         z  \
2611866  315283.269529  1.202046e+06  165.30302  78.85504  18262.0 -0.000003

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2611866   1258  2020-01-01       cs2        1.0     974127.557713      0.08407
'local_data_select': 0.001 seconds
number obs: 453
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.046 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:24:33.587097: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:24:33.588505: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'optimise_parameters': 1.016 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.00997137, 10.00539449,  0.78922425])
kernel_variance: 0.005080228746654528
likelihood_variance: 0.0031293105379717454
'predict': 0.038 seconds
total run time : 1.91 seconds
--------------------------------------------------
40 / 40
current local expert:
                     x             y        lon        lat        t         z  \
2611915  313897.428428  1.178295e+06  165.08286  79.064851  18262.0  0.089658

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2611915   1258  2020-01-01       cs2        1.0     997870.555467      0.08407
'local_data_select': 0.001 seconds
number obs: 470
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.052 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:24:35.505288: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:24:35.506691: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'optimise_parameters': 0.418 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01000023, 10.01007604,  1.00123572])
kernel_variance: 0.007229027711922693
likelihood_variance: 0.0031957025159416344
'predict': 0.038 seconds
SAVING RESULTS TO TABLES:
run_details
preds
lengthscales
kernel_variance
likelihood_variance
total run time : 1.63 seconds
'run': 57.509 seconds
reading in results
getting all tables
merging on expert location data
table: 'oi_config' does not have all coords_col: ['x', 'y', 't'] in columns, not merging on expert_locations
h5 tables: ['expert_locs', 'kernel_variance', 'lengthscales', 'likelihood_variance', 'oi_config', 'preds', 'run_details']
found model_name: GPflowGPRModel
found GPU
setting lengthscales to: [1.]
'__init__': 0.048 seconds
reading in results
selecting only tables: ['lengthscales', 'kernel_variance', 'likelihood_variance']
'data_select': 0.000 seconds
'load': 0.000 seconds
expert_locations data will not be merged on results data
adding smoothed table: lengthscales_SMOOTHED
adding smoothed table: kernel_variance_SMOOTHED
adding smoothed table: likelihood_variance_SMOOTHED
writing (smoothed) hyper parameters to:
/home/mhen/geol0069_data/gpsat/jan20/1258.h5
table_suffix:_SMOOTHED
writing: lengthscales_SMOOTHED to table
writing: kernel_variance_SMOOTHED to table
writing: likelihood_variance_SMOOTHED to table

2026-05-18 19:24:37.330480: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:24:37.331901: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'data_select': 0.000 seconds
'load': 0.000 seconds
in json_serializable - key: 'data_source' has value DataFrame/Series, but is too long: 1814 >  100
storing as str
in json_serializable - key: 'df' has value DataFrame/Series, but is too long: 6881 >  100
storing as str
---------
storing expert locations in 'expert_locs' table
exception occurred: 'No object named expert_locs_SMOOTHED in the file'
will now close object

---------
dropping expert locations that already exists in 'run_details' table
exception occurred: 'No object named run_details_SMOOTHED in the file'
will now close object

--------------------------------------------------
1 / 40
current local expert:
                    x             y        lon        lat        t         z  \
2609679  359196.91784  2.171377e+06  170.60699  70.189152  18262.0  0.151773

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2609679   1258  2020-01-01       cs2        1.0        900.563443      0.08407
'data_select': 0.000 seconds
'load': 0.000 seconds
'local_data_select': 0.001 seconds
number obs: 301
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.049 seconds
'get_parameters': 0.003 seconds
'_read_params_from_file': 0.049 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds

2026-05-18 19:24:37.592764: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:24:37.594215: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  1.06613913])
kernel_variance: 0.02930575567509592
likelihood_variance: 0.01100000000000001
'predict': 0.032 seconds
total run time : 0.95 seconds
--------------------------------------------------
2 / 40
current local expert:
                     x             y        lon        lat        t         z  \
2609726  358416.503277  2.147582e+06  170.52506  70.403855  18262.0  0.125492

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2609726   1258  2020-01-01       cs2        1.0      24917.387423      0.08407
'local_data_select': 0.001 seconds
number obs: 316
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.047 seconds
'_read_params_from_file': 0.045 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01     , 10.01     ,  1.0632427])
kernel_variance: 0.029095773915197104
likelihood_variance: 0.01100000000000001
'predict': 0.032 seconds

2026-05-18 19:24:38.543607: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:24:38.545038: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.94 seconds
--------------------------------------------------
3 / 40
current local expert:
                     x             y       lon        lat        t         z  \
2609779  357620.773668  2.123780e+06  170.4417  70.618539  18262.0  0.099033

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2609779   1258  2020-01-01       cs2        1.0      48934.789732      0.08407
'local_data_select': 0.001 seconds
number obs: 319
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.046 seconds
'_read_params_from_file': 0.045 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  1.06119673])
kernel_variance: 0.02888187950346933
likelihood_variance: 0.01100000000000001
'predict': 0.032 seconds

2026-05-18 19:24:39.487982: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:24:39.489394: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.95 seconds
--------------------------------------------------
4 / 40
current local expert:
                     x             y        lon       lat        t         z  \
2609830  356604.344251  2.094015e+06  170.33542  70.88687  18262.0  0.002512

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2609830   1258  2020-01-01       cs2        1.0      78957.779062      0.08407
'local_data_select': 0.001 seconds
number obs: 328
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.047 seconds
'_read_params_from_file': 0.045 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.016 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  1.06004202])
kernel_variance: 0.028607131337449073
likelihood_variance: 0.01100000000000001
'predict': 0.034 seconds

2026-05-18 19:24:40.443011: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:24:40.444406: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.94 seconds
--------------------------------------------------
5 / 40
current local expert:
                     x             y       lon        lat        t         z  \
2609869  355878.514203  2.073172e+06  170.2596  71.074682  18262.0  0.080421

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2609869   1258  2020-01-01       cs2        1.0      99974.365488      0.08407
'local_data_select': 0.001 seconds
number obs: 328
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.047 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  1.06029733])
kernel_variance: 0.028408291673079684
likelihood_variance: 0.01100000000000001
'predict': 0.033 seconds

2026-05-18 19:24:41.383103: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:24:41.384513: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.94 seconds
--------------------------------------------------
6 / 40
current local expert:
                     x             y        lon        lat        t         z  \
2609896  354991.945131  2.048152e+06  170.16701  71.300037  18262.0  0.118978

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2609896   1258  2020-01-01       cs2        1.0     125195.146076      0.08407
'local_data_select': 0.001 seconds
number obs: 329
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.051 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  1.06190911])
kernel_variance: 0.02816025534867667
likelihood_variance: 0.01100000000000001
'predict': 0.034 seconds

2026-05-18 19:24:42.333082: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:24:42.334484: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.94 seconds
--------------------------------------------------
7 / 40
current local expert:
                     x             y        lon        lat        t        z  \
2609930  354121.013859  2.024018e+06  170.07601  71.517321  18262.0 -0.08639

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2609930   1258  2020-01-01       cs2        1.0     149515.926806      0.08407
'local_data_select': 0.001 seconds
number obs: 334
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.049 seconds
'_read_params_from_file': 0.045 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  1.06494483])
kernel_variance: 0.027908604791560408
likelihood_variance: 0.01100000000000001
'predict': 0.034 seconds

2026-05-18 19:24:43.275655: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:24:43.277059: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.96 seconds
--------------------------------------------------
8 / 40
current local expert:
                     x             y        lon        lat        t         z  \
2609981  353190.425799  1.998683e+06  169.97863  71.745309  18262.0  0.076463

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2609981   1258  2020-01-01       cs2        1.0     175038.440334      0.08407
'local_data_select': 0.001 seconds
number obs: 342
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'_read_params_from_file': 0.045 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  1.06982104])
kernel_variance: 0.027627848539614773
likelihood_variance: 0.01100000000000001
'predict': 0.034 seconds

2026-05-18 19:24:44.235868: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:24:44.237288: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.96 seconds
--------------------------------------------------
9 / 40
current local expert:
                     x             y        lon        lat        t         z  \
2610030  352287.015651  1.974532e+06  169.88399  71.962544  18262.0  0.080553

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2610030   1258  2020-01-01       cs2        1.0     199360.678082      0.08407
'local_data_select': 0.001 seconds
number obs: 350
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  1.07616221])
kernel_variance: 0.027340842960010433
likelihood_variance: 0.01100000000000001
'predict': 0.034 seconds

2026-05-18 19:24:45.198886: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:24:45.200283: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.96 seconds
--------------------------------------------------
10 / 40
current local expert:
                     x             y        lon        lat        t         z  \
2610075  351528.232249  1.954549e+06  169.80428  72.142213  18262.0  0.087219

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2610075   1258  2020-01-01       cs2        1.0     219479.688778      0.08407
'local_data_select': 0.001 seconds
number obs: 364
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.051 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  1.08268133])
kernel_variance: 0.027086615687508316
likelihood_variance: 0.01100000000000001
'predict': 0.035 seconds

2026-05-18 19:24:46.163306: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:24:46.164721: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

SAVING RESULTS TO TABLES:
run_details
preds
total run time : 1.01 seconds
--------------------------------------------------
11 / 40
current local expert:
                     x             y        lon        lat        t         z  \
2610147  350270.260797  1.922029e+06  169.67177  72.434471  18262.0  0.089665

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2610147   1258  2020-01-01       cs2        1.0     252211.613832      0.08407
'local_data_select': 0.001 seconds
number obs: 382
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.047 seconds
'_read_params_from_file': 0.050 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters

2026-05-18 19:24:47.175731: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:24:47.177171: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  1.09569875])
kernel_variance: 0.026635847367980543
likelihood_variance: 0.01100000000000001
'predict': 0.036 seconds
total run time : 0.97 seconds
--------------------------------------------------
12 / 40
current local expert:
                     x             y      lon        lat        t         z  \
2610187  349459.052271  1.901436e+06  169.586  72.619452  18262.0  0.086406

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2610187   1258  2020-01-01       cs2        1.0     272932.493471      0.08407
'local_data_select': 0.001 seconds
number obs: 406
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.051 seconds
'_read_params_from_file': 0.045 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  1.10537541])
kernel_variance: 0.026324741834051892
likelihood_variance: 0.012317052277909517
'predict': 0.037 seconds

2026-05-18 19:24:48.147502: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:24:48.148943: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.96 seconds
--------------------------------------------------
13 / 40
current local expert:
                     x             y        lon        lat        t        z  \
2610240  348360.115448  1.873970e+06  169.46925  72.866058  18262.0  0.10557

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2610240   1258  2020-01-01       cs2        1.0      300561.02212      0.08407
'local_data_select': 0.001 seconds
number obs: 418
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.047 seconds
'_read_params_from_file': 0.045 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  1.11974588])
kernel_variance: 0.025878281357715242
likelihood_variance: 0.01621406369946171
'predict': 0.037 seconds

2026-05-18 19:24:49.102134: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:24:49.103539: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.96 seconds
--------------------------------------------------
14 / 40
current local expert:
                     x             y        lon        lat        t        z  \
2610280  347387.842887  1.850078e+06  169.36544  73.080466  18262.0  0.13663

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2610280   1258  2020-01-01       cs2        1.0       324586.6534      0.08407
'local_data_select': 0.001 seconds
number obs: 436
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  1.13327429])
kernel_variance: 0.025462674296775213
likelihood_variance: 0.02080636722080209
'predict': 0.037 seconds

2026-05-18 19:24:50.061724: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:24:50.063308: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.95 seconds
--------------------------------------------------
15 / 40
current local expert:
                     x             y        lon       lat        t         z  \
2610349  346125.688314  1.819606e+06  169.22986  73.35379  18262.0  0.149285

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2610349   1258  2020-01-01       cs2        1.0     355220.377437      0.08407
'local_data_select': 0.001 seconds
number obs: 457
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.047 seconds
'_read_params_from_file': 0.045 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  1.15123647])
kernel_variance: 0.02490403650966838
likelihood_variance: 0.02875062626610694
'predict': 0.038 seconds

2026-05-18 19:24:51.011774: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:24:51.013170: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.96 seconds
--------------------------------------------------
16 / 40
current local expert:
                     x             y       lon        lat        t        z  \
2610396  345308.270507  1.800182e+06  169.1415  73.527938  18262.0  0.25622

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2610396   1258  2020-01-01       cs2        1.0     374742.409198      0.08407
'local_data_select': 0.001 seconds
number obs: 468
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.049 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  1.16266146])
kernel_variance: 0.02453875273573107
likelihood_variance: 0.03531042117343459
'predict': 0.038 seconds

2026-05-18 19:24:51.975521: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:24:51.976924: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.95 seconds
--------------------------------------------------
17 / 40
current local expert:
                    x             y        lon        lat        t         z  \
2610460  344249.97765  1.775371e+06  169.02635  73.750278  18262.0  0.213794

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2610460   1258  2020-01-01       cs2        1.0     399671.304385      0.08407
'local_data_select': 0.001 seconds
number obs: 487
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.047 seconds
'_read_params_from_file': 0.045 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  1.17665392])
kernel_variance: 0.02407439342316104
likelihood_variance: 0.045720330486203796
'predict': 0.039 seconds

2026-05-18 19:24:52.927697: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:24:52.929089: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.95 seconds
--------------------------------------------------
18 / 40
current local expert:
                     x             y       lon        lat        t         z  \
2610529  342913.507215  1.744573e+06  168.8797  74.026137  18262.0  0.088776

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2610529   1258  2020-01-01       cs2        1.0     430608.073349      0.08407
'local_data_select': 0.001 seconds
number obs: 468
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.045 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  1.19212905])
kernel_variance: 0.02352796020249731
likelihood_variance: 0.062350670854341865
'predict': 0.038 seconds

2026-05-18 19:24:53.876115: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:24:53.877525: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.96 seconds
--------------------------------------------------
19 / 40
current local expert:
                     x             y        lon        lat        t         z  \
2610589  341804.679987  1.719447e+06  168.75688  74.251061  18262.0  0.184701

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2610589   1258  2020-01-01       cs2        1.0     455838.913061      0.08407
'local_data_select': 0.001 seconds
number obs: 453
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.049 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  1.20236123])
kernel_variance: 0.023135458158680424
likelihood_variance: 0.07940817869481757
'predict': 0.037 seconds

2026-05-18 19:24:54.837075: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:24:54.838494: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.95 seconds
--------------------------------------------------
20 / 40
current local expert:
                     x             y        lon        lat        t         z  \
2610637  340934.987447  1.700000e+06  168.65977  74.425077  18262.0 -0.006906

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2610637   1258  2020-01-01       cs2        1.0     475363.191317      0.08407
'local_data_select': 0.001 seconds
number obs: 432
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.047 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  1.20836158])
kernel_variance: 0.022883408113239693
likelihood_variance: 0.09498597444413856
'predict': 0.037 seconds

2026-05-18 19:24:55.787656: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:24:55.789044: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

SAVING RESULTS TO TABLES:
run_details
preds
total run time : 1.05 seconds
--------------------------------------------------
21 / 40
current local expert:
                     x             y      lon        lat        t         z  \
2610754  339192.499774  1.661691e+06  168.463  74.767672  18262.0  0.130161

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2610754   1258  2020-01-01       cs2        1.0     513812.543715      0.08407
'local_data_select': 0.001 seconds
number obs: 421
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.049 seconds
'_read_params_from_file': 0.051 seconds

2026-05-18 19:24:56.843081: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:24:56.844539: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'set_parameters': 0.006 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01     , 10.01     ,  1.2142883])
kernel_variance: 0.022575888135329937
likelihood_variance: 0.132158634744709
'predict': 0.037 seconds
total run time : 0.97 seconds
--------------------------------------------------
22 / 40
current local expert:
                     x             y        lon       lat        t         z  \
2610856  337452.980234  1.624264e+06  168.26334  75.10212  18262.0  0.083539

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2610856   1258  2020-01-01       cs2        1.0     551362.276047      0.08407
'local_data_select': 0.001 seconds
number obs: 421
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.047 seconds
'_read_params_from_file': 0.045 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  1.21163176])
kernel_variance: 0.022599220598953338
likelihood_variance: 0.17696394319097114
'predict': 0.039 seconds

2026-05-18 19:24:57.809401: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:24:57.810824: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.96 seconds
--------------------------------------------------
23 / 40
current local expert:
                     x             y        lon        lat        t         z  \
2610910  336505.268316  1.604197e+06  168.15309  75.281335  18262.0  0.069717

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2610910   1258  2020-01-01       cs2        1.0     571489.775231      0.08407
'local_data_select': 0.001 seconds
number obs: 402
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.050 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  1.20666266])
kernel_variance: 0.02277288759553202
likelihood_variance: 0.2043049689430585
'predict': 0.038 seconds

2026-05-18 19:24:58.771886: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:24:58.773298: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.96 seconds
--------------------------------------------------
24 / 40
current local expert:
                     x             y        lon        lat        t         z  \
2610983  335142.825923  1.575737e+06  167.99271  75.535379  18262.0  0.203011

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2610983   1258  2020-01-01       cs2        1.0     600029.228347      0.08407
'local_data_select': 0.001 seconds
number obs: 381
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.047 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  1.19556831])
kernel_variance: 0.023235267504655623
likelihood_variance: 0.24663931017277974
'predict': 0.038 seconds

2026-05-18 19:24:59.734667: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:24:59.736072: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.96 seconds
--------------------------------------------------
25 / 40
current local expert:
                    x             y        lon        lat        t         z  \
2611047  333964.04117  1.551464e+06  167.85203  75.751922  18262.0  0.006052

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2611047   1258  2020-01-01       cs2        1.0     624363.551446      0.08407
'local_data_select': 0.001 seconds
number obs: 399
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.052 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  1.18270605])
kernel_variance: 0.023840102605307157
likelihood_variance: 0.28553515883989045
'predict': 0.037 seconds

2026-05-18 19:25:00.698539: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:25:00.700517: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.96 seconds
--------------------------------------------------
26 / 40
current local expert:
                    x             y        lon        lat        t         z  \
2611112  332724.79562  1.526286e+06  167.70213  75.976422  18262.0  0.139253

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2611112   1258  2020-01-01       cs2        1.0     649599.953117      0.08407
'local_data_select': 0.001 seconds
number obs: 409
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.047 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  1.16656565])
kernel_variance: 0.024674505392301604
likelihood_variance: 0.3279204471169357
'predict': 0.038 seconds

2026-05-18 19:25:01.651507: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:25:01.652939: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.95 seconds
--------------------------------------------------
27 / 40
current local expert:
                     x             y        lon        lat        t         z  \
2611169  331438.837733  1.500502e+06  167.54421  76.206194  18262.0  0.059319

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2611169   1258  2020-01-01       cs2        1.0     675437.819576      0.08407
'local_data_select': 0.001 seconds
number obs: 417
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  1.14771067])
kernel_variance: 0.025740448659109096
likelihood_variance: 0.3726618863443387
'predict': 0.038 seconds

2026-05-18 19:25:02.599765: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:25:02.601906: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.94 seconds
--------------------------------------------------
28 / 40
current local expert:
                     x             y        lon        lat        t         z  \
2611235  330089.077644  1.473812e+06  167.37582  76.443902  18262.0  0.059448

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2611235   1258  2020-01-01       cs2        1.0     702177.889551      0.08407
'local_data_select': 0.001 seconds
number obs: 408
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.049 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  1.12646148])
kernel_variance: 0.027052029670014712
likelihood_variance: 0.41941501010222443
'predict': 0.038 seconds

2026-05-18 19:25:03.546676: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:25:03.548096: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.95 seconds
--------------------------------------------------
29 / 40
current local expert:
                     x             y        lon       lat        t         z  \
2611289  328921.318023  1.451015e+06  167.22783  76.64682  18262.0  0.097988

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2611289   1258  2020-01-01       cs2        1.0     725012.700294      0.08407
'local_data_select': 0.001 seconds
number obs: 402
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'_read_params_from_file': 0.045 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  1.10750454])
kernel_variance: 0.028320132918905387
likelihood_variance: 0.4589040500780784
'predict': 0.039 seconds

2026-05-18 19:25:04.500430: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:25:04.501892: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.96 seconds
--------------------------------------------------
30 / 40
current local expert:
                     x             y        lon        lat        t         z  \
2611351  327567.479867  1.424912e+06  167.05343  76.879026  18262.0 -0.003509

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2611351   1258  2020-01-01       cs2        1.0      751153.26076      0.08407
'local_data_select': 0.001 seconds
number obs: 410
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.050 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  1.08551543])
kernel_variance: 0.02991101474996718
likelihood_variance: 0.5027228213235723
'predict': 0.038 seconds

2026-05-18 19:25:05.465598: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:25:05.467001: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

SAVING RESULTS TO TABLES:
run_details
preds
total run time : 1.09 seconds
--------------------------------------------------
31 / 40
current local expert:
                     x             y        lon        lat        t         z  \
2611415  326290.884185  1.400603e+06  166.88602  77.095134  18262.0  0.059887

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2611415   1258  2020-01-01       cs2        1.0       775491.6297      0.08407
'local_data_select': 0.001 seconds
number obs: 415
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds

2026-05-18 19:25:06.560745: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:25:06.562180: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'_read_params_from_file': 0.052 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  1.06528878])
kernel_variance: 0.031495789210484695
likelihood_variance: 0.5414083004316105
'predict': 0.038 seconds
total run time : 0.95 seconds
--------------------------------------------------
32 / 40
current local expert:
                     x             y        lon        lat        t         z  \
2611471  324934.108018  1.375089e+06  166.70486  77.321823  18262.0  0.042512

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2611471   1258  2020-01-01       cs2        1.0     801032.546069      0.08407
'local_data_select': 0.001 seconds
number obs: 425
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'_read_params_from_file': 0.045 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  1.04479422])
kernel_variance: 0.03323178771789899
likelihood_variance: 0.5790612889745488
'predict': 0.039 seconds

2026-05-18 19:25:07.513487: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:25:07.514885: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.94 seconds
--------------------------------------------------
33 / 40
current local expert:
                     x             y        lon        lat        t         z  \
2611529  323657.645529  1.351370e+06  166.53118  77.532422  18262.0  0.041446

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2611529   1258  2020-01-01       cs2        1.0     824771.208149      0.08407
'local_data_select': 0.001 seconds
number obs: 420
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'_read_params_from_file': 0.045 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  1.02675459])
kernel_variance: 0.03488108716624341
likelihood_variance: 0.6107841967894435
'predict': 0.039 seconds

2026-05-18 19:25:08.456806: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:25:08.458208: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.96 seconds
--------------------------------------------------
34 / 40
current local expert:
                    x             y        lon       lat        t         z  \
2611588  322283.80997  1.326146e+06  166.34061  77.75625  18262.0 -0.049508

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2611588   1258  2020-01-01       cs2        1.0     850012.807937      0.08407
'local_data_select': 0.001 seconds
number obs: 434
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.047 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  1.00890679])
kernel_variance: 0.036640190535051846
likelihood_variance: 0.6405689073844699
'predict': 0.039 seconds

2026-05-18 19:25:09.419427: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:25:09.420861: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.94 seconds
--------------------------------------------------
35 / 40
current local expert:
                     x             y        lon        lat        t         z  \
2611647  320976.393795  1.302417e+06  166.15553  77.966657  18262.0  0.091921

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2611647   1258  2020-01-01       cs2        1.0     873752.610646      0.08407
'local_data_select': 0.001 seconds
number obs: 434
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  0.99354102])
kernel_variance: 0.038271771069598975
likelihood_variance: 0.6645407145387057
'predict': 0.037 seconds

2026-05-18 19:25:10.365492: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:25:10.366890: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.95 seconds
--------------------------------------------------
36 / 40
current local expert:
                     x             y        lon        lat        t         z  \
2611692  319485.484187  1.275680e+06  165.93985  78.203577  18262.0  0.091828

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2611692   1258  2020-01-01       cs2        1.0     900498.188186      0.08407
'local_data_select': 0.001 seconds
number obs: 446
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.049 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  0.97799105])
kernel_variance: 0.04005288184976806
likelihood_variance: 0.6866028508731362
'predict': 0.037 seconds

2026-05-18 19:25:11.319725: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:25:11.321313: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.96 seconds
--------------------------------------------------
37 / 40
current local expert:
                     x             y        lon        lat        t         z  \
2611751  318163.368532  1.252242e+06  165.74422  78.411103  18262.0  0.085536

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2611751   1258  2020-01-01       cs2        1.0     923938.793163      0.08407
'local_data_select': 0.001 seconds
number obs: 451
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  0.96592899])
kernel_variance: 0.04154158449230451
likelihood_variance: 0.7015331532150948
'predict': 0.038 seconds

2026-05-18 19:25:12.281867: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:25:12.283877: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.95 seconds
--------------------------------------------------
38 / 40
current local expert:
                     x             y        lon        lat        t         z  \
2611805  316671.169201  1.226095e+06  165.51833  78.642443  18262.0  0.024269

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2611805   1258  2020-01-01       cs2        1.0     950084.675176      0.08407
'local_data_select': 0.001 seconds
number obs: 449
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  0.95417845])
kernel_variance: 0.043100865663540815
likelihood_variance: 0.7133431364033644
'predict': 0.038 seconds

2026-05-18 19:25:13.237397: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:25:13.238807: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.96 seconds
--------------------------------------------------
39 / 40
current local expert:
                     x             y        lon       lat        t         z  \
2611866  315283.269529  1.202046e+06  165.30302  78.85504  18262.0 -0.000003

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2611866   1258  2020-01-01       cs2        1.0     974127.557713      0.08407
'local_data_select': 0.001 seconds
number obs: 453
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.049 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  0.94489751])
kernel_variance: 0.044425057258303494
likelihood_variance: 0.7198027440063799
'predict': 0.037 seconds

2026-05-18 19:25:14.198428: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:25:14.199852: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.94 seconds
--------------------------------------------------
40 / 40
current local expert:
                     x             y        lon        lat        t         z  \
2611915  313897.428428  1.178295e+06  165.08286  79.064851  18262.0  0.089658

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2611915   1258  2020-01-01       cs2        1.0     997870.555467      0.08407
'local_data_select': 0.001 seconds
number obs: 470
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  0.93708112])
kernel_variance: 0.04561851287595746
likelihood_variance: 0.7222200261199829
'predict': 0.038 seconds

2026-05-18 19:25:15.137439: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:25:15.139065: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

SAVING RESULTS TO TABLES:
run_details
preds
total run time : 1.14 seconds
'run': 38.765 seconds
reading in results
getting all tables
merging on expert location data
table: 'oi_config' does not have all coords_col: ['x', 'y', 't'] in columns, not merging on expert_locations
table: 'oi_config_SMOOTHED' does not have all coords_col: ['x', 'y', 't'] in columns, not merging on expert_locations
lin:
                     x             y        lon        lat        t         z  \
2609677  359225.689430  2.172269e+06  170.61004  70.181101  18262.0       NaN
2609678  359216.229933  2.171971e+06  170.60902  70.183785  18262.0       NaN
2609679  359196.917840  2.171377e+06  170.60699  70.189152  18262.0  0.151773
2609680  359148.596020  2.169890e+06  170.60191  70.202572  18262.0  0.174938
2609681  359129.117052  2.169295e+06  170.59988  70.207940  18262.0  0.155294

         track date_string satellite  lead_mask  dist_along_track  \
2609677   1258  2020-01-01       cs2        0.0          0.000000
2609678   1258  2020-01-01       cs2        0.0        300.241117
2609679   1258  2020-01-01       cs2        1.0        900.563443
2609680   1258  2020-01-01       cs2        1.0       2401.657219
2609681   1258  2020-01-01       cs2        1.0       3002.080758

         z_track_avg    f_lin
2609677      0.08407  0.05218
2609678      0.08407  0.05218
2609679      0.08407  0.05218
2609680      0.08407  0.05218
2609681      0.08407  0.05218
gpsat:
                     x             y        lon        lat        t         z  \
2609677  359225.689430  2.172269e+06  170.61004  70.181101  18262.0       NaN
2609678  359216.229933  2.171971e+06  170.60902  70.183785  18262.0       NaN
2609679  359196.917840  2.171377e+06  170.60699  70.189152  18262.0  0.151773
2609680  359148.596020  2.169890e+06  170.60191  70.202572  18262.0  0.174938
2609681  359129.117052  2.169295e+06  170.59988  70.207940  18262.0  0.155294

         track date_string satellite  lead_mask  dist_along_track  \
2609677   1258  2020-01-01       cs2        0.0          0.000000
2609678   1258  2020-01-01       cs2        0.0        300.241117
2609679   1258  2020-01-01       cs2        1.0        900.563443
2609680   1258  2020-01-01       cs2        1.0       2401.657219
2609681   1258  2020-01-01       cs2        1.0       3002.080758

         z_track_avg   f_gpsat  f_var_gpsat
2609677      0.08407  0.119788     0.119788
2609678      0.08407  0.119080     0.119080
2609679      0.08407  0.117634     0.117634
2609680      0.08407  0.113832     0.113832
2609681      0.08407  0.112239     0.112239
Test NaNs — Linear: 0, GPSat: 248
Track interpolated!
Interpolating track 1259, 14 of 15...
'data_select': 0.000 seconds
'load': 0.000 seconds
in json_serializable - key: 'df' has value DataFrame/Series, but is too long: 509 >  100
storing as str
---------
storing expert locations in 'expert_locs' table
exception occurred: 'No object named expert_locs in the file'
will now close object

---------
dropping expert locations that already exists in 'run_details' table
exception occurred: 'No object named run_details in the file'
will now close object

--------------------------------------------------
1 / 10
current local expert:
                    x             y        lon        lat        t         z  \
2616558  1.114191e+06  1.574012e+06  144.70658  72.663214  18262.0 -0.105337

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2616558   1259  2020-01-01       cs2        1.0               0.0     -0.05953
'data_select': 0.000 seconds
'load': 0.000 seconds
'local_data_select': 0.001 seconds
number obs: 82

/tmp/ipykernel_1171781/839927469.py:200: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  track_df['f_gpsat'] = ssha
/tmp/ipykernel_1171781/839927469.py:201: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  track_df['f_var_gpsat'] = ssha_var
/tmp/ipykernel_1171781/839927469.py:66: RuntimeWarning: invalid value encountered in sqrt
  gpsat_std = np.sqrt(gpsat_var[both_valid])
2026-05-18 19:25:16.777482: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:25:16.779539: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'get_parameters': 0.003 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds
**********
optimization failed!
'optimise_parameters': 0.389 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.00036247, 10.00000004,  1.02067501])
kernel_variance: 0.00484857579457984
likelihood_variance: 0.0030206540011178265
'predict': 0.030 seconds
total run time : 1.28 seconds
--------------------------------------------------
2 / 10
current local expert:
                    x             y       lon        lat        t         z  \
2616613  1.101916e+06  1.550082e+06  144.5919  72.904476  18262.0 -0.101058

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2616613   1259  2020-01-01       cs2        1.0      27030.708098     -0.05953
'local_data_select': 0.001 seconds
number obs: 82
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:25:18.060756: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:25:18.062174: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.385 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.00036247, 10.00000004,  1.02067501])
kernel_variance: 0.00484857579457984
likelihood_variance: 0.0030206540011178265
'predict': 0.032 seconds
total run time : 1.28 seconds
--------------------------------------------------
3 / 10
current local expert:
                    x             y        lon        lat        t         z  \
2616655  1.091260e+06  1.529342e+06  144.49031  73.113538  18262.0 -0.022869

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2616655   1259  2020-01-01       cs2        1.0      50458.026626     -0.05953
'local_data_select': 0.001 seconds
number obs: 82
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.046 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:25:19.340571: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:25:19.342159: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.378 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.00036247, 10.00000004,  1.02067501])
kernel_variance: 0.00484857579457984
likelihood_variance: 0.0030206540011178265
'predict': 0.032 seconds
total run time : 1.29 seconds
--------------------------------------------------
4 / 10
current local expert:
                    x             y        lon        lat        t         z  \
2616662  1.090166e+06  1.527215e+06  144.47977  73.134978  18262.0 -0.039072

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2616662   1259  2020-01-01       cs2        1.0      52860.815208     -0.05953
'local_data_select': 0.001 seconds
number obs: 82
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.046 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:25:20.629043: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:25:20.630446: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.382 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.00036247, 10.00000004,  1.02067501])
kernel_variance: 0.00484857579457984
likelihood_variance: 0.0030206540011178265
'predict': 0.032 seconds
total run time : 1.27 seconds
--------------------------------------------------
5 / 10
current local expert:
                    x             y        lon        lat        t         z  \
2616804  1.063704e+06  1.475858e+06  144.21834  73.652538  18262.0 -0.059531

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2616804   1259  2020-01-01       cs2        1.0     110877.260893     -0.05953
'local_data_select': 0.001 seconds
number obs: 82
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.046 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:25:21.904334: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:25:21.905736: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.377 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.00036247, 10.00000004,  1.02067501])
kernel_variance: 0.00484857579457984
likelihood_variance: 0.0030206540011178265
'predict': 0.032 seconds
total run time : 1.27 seconds
--------------------------------------------------
6 / 10
current local expert:
                    x             y        lon        lat        t         z  \
2616825  1.056895e+06  1.462674e+06  144.14897  73.785369  18262.0 -0.154075

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2616825   1259  2020-01-01       cs2        1.0     125771.474737     -0.05953
'local_data_select': 0.001 seconds
number obs: 82
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.047 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:25:23.180959: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:25:23.182351: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.383 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.00036247, 10.00000004,  1.02067501])
kernel_variance: 0.00484857579457984
likelihood_variance: 0.0030206540011178265
'predict': 0.031 seconds
total run time : 1.28 seconds
--------------------------------------------------
7 / 10
current local expert:
                    x             y        lon        lat        t        z  \
2616875  1.044658e+06  1.439011e+06  144.02201  74.023749  18262.0  0.01717

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2616875   1259  2020-01-01       cs2        1.0     152505.579191     -0.05953
'local_data_select': 0.001 seconds
number obs: 82
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:25:24.464371: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:25:24.465872: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.382 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.00036247, 10.00000004,  1.02067501])
kernel_variance: 0.00484857579457984
likelihood_variance: 0.0030206540011178265
'predict': 0.032 seconds
total run time : 1.28 seconds
--------------------------------------------------
8 / 10
current local expert:
                    x             y        lon        lat        t         z  \
2616900  1.039562e+06  1.429168e+06  143.96825  74.122887  18262.0 -0.151514

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2616900   1259  2020-01-01       cs2        1.0     163625.674623     -0.05953
'local_data_select': 0.001 seconds
number obs: 82
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.046 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:25:25.741005: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:25:25.742441: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.381 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.00036247, 10.00000004,  1.02067501])
kernel_variance: 0.00484857579457984
likelihood_variance: 0.0030206540011178265
'predict': 0.032 seconds
total run time : 1.28 seconds
--------------------------------------------------
9 / 10
current local expert:
                    x             y        lon        lat        t         z  \
2616979  1.022327e+06  1.395933e+06  143.78241  74.457594  18262.0  0.054877

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2616979   1259  2020-01-01       cs2        1.0     201177.415699     -0.05953
'local_data_select': 0.001 seconds
number obs: 82
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.046 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:25:27.023760: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:25:27.025155: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.382 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.00036247, 10.00000004,  1.02067501])
kernel_variance: 0.00484857579457984
likelihood_variance: 0.0030206540011178265
'predict': 0.032 seconds
total run time : 1.30 seconds
--------------------------------------------------
10 / 10
current local expert:
                    x             y        lon        lat        t       z  \
2617024  1.010583e+06  1.373334e+06  143.65208  74.685133  18262.0 -0.0788

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2617024   1259  2020-01-01       cs2        1.0     226713.409764     -0.05953
'local_data_select': 0.001 seconds
number obs: 82
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:25:28.323447: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:25:28.324846: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.378 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.00036247, 10.00000004,  1.02067501])
kernel_variance: 0.00484857579457984
likelihood_variance: 0.0030206540011178265
'predict': 0.032 seconds
SAVING RESULTS TO TABLES:
run_details
preds
lengthscales
kernel_variance
likelihood_variance
total run time : 1.43 seconds
'run': 13.042 seconds
reading in results
getting all tables
merging on expert location data
table: 'oi_config' does not have all coords_col: ['x', 'y', 't'] in columns, not merging on expert_locations
h5 tables: ['expert_locs', 'kernel_variance', 'lengthscales', 'likelihood_variance', 'oi_config', 'preds', 'run_details']
found model_name: GPflowGPRModel
found GPU
setting lengthscales to: [1.]
'__init__': 0.048 seconds
reading in results
selecting only tables: ['lengthscales', 'kernel_variance', 'likelihood_variance']
'data_select': 0.000 seconds
'load': 0.001 seconds
expert_locations data will not be merged on results data
adding smoothed table: lengthscales_SMOOTHED
adding smoothed table: kernel_variance_SMOOTHED
adding smoothed table: likelihood_variance_SMOOTHED
writing (smoothed) hyper parameters to:
/home/mhen/geol0069_data/gpsat/jan20/1259.h5
table_suffix:_SMOOTHED
writing: lengthscales_SMOOTHED to table
writing: kernel_variance_SMOOTHED to table
writing: likelihood_variance_SMOOTHED to table
'data_select': 0.000 seconds
'load': 0.000 seconds
in json_serializable - key: 'df' has value DataFrame/Series, but is too long: 509 >  100
storing as str
---------
storing expert locations in 'expert_locs' table

2026-05-18 19:25:29.867988: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:25:29.869390: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

exception occurred: 'No object named expert_locs_SMOOTHED in the file'
will now close object

---------
dropping expert locations that already exists in 'run_details' table
exception occurred: 'No object named run_details_SMOOTHED in the file'
will now close object

--------------------------------------------------
1 / 10
current local expert:
                    x             y        lon        lat        t         z  \
2616558  1.114191e+06  1.574012e+06  144.70658  72.663214  18262.0 -0.105337

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2616558   1259  2020-01-01       cs2        1.0               0.0     -0.05953
'data_select': 0.000 seconds
'load': 0.000 seconds
'local_data_select': 0.001 seconds
number obs: 82
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.050 seconds
'get_parameters': 0.003 seconds
'_read_params_from_file': 0.050 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters

2026-05-18 19:25:30.120524: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:25:30.121923: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  1.02067501])
kernel_variance: 0.00484857579457984
likelihood_variance: 0.01100000000000001
'predict': 0.031 seconds
total run time : 0.97 seconds
--------------------------------------------------
2 / 10
current local expert:
                    x             y       lon        lat        t         z  \
2616613  1.101916e+06  1.550082e+06  144.5919  72.904476  18262.0 -0.101058

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2616613   1259  2020-01-01       cs2        1.0      27030.708098     -0.05953
'local_data_select': 0.001 seconds
number obs: 82
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.049 seconds
'_read_params_from_file': 0.045 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  1.02067501])
kernel_variance: 0.00484857579457984
likelihood_variance: 0.01100000000000001
'predict': 0.031 seconds

2026-05-18 19:25:31.090481: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:25:31.092583: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.96 seconds
--------------------------------------------------
3 / 10
current local expert:
                    x             y        lon        lat        t         z  \
2616655  1.091260e+06  1.529342e+06  144.49031  73.113538  18262.0 -0.022869

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2616655   1259  2020-01-01       cs2        1.0      50458.026626     -0.05953
'local_data_select': 0.001 seconds
number obs: 82
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.050 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  1.02067501])
kernel_variance: 0.00484857579457984
likelihood_variance: 0.01100000000000001
'predict': 0.030 seconds

2026-05-18 19:25:32.051607: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:25:32.053045: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.95 seconds
--------------------------------------------------
4 / 10
current local expert:
                    x             y        lon        lat        t         z  \
2616662  1.090166e+06  1.527215e+06  144.47977  73.134978  18262.0 -0.039072

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2616662   1259  2020-01-01       cs2        1.0      52860.815208     -0.05953
'local_data_select': 0.001 seconds
number obs: 82
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.047 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  1.02067501])
kernel_variance: 0.00484857579457984
likelihood_variance: 0.01100000000000001
'predict': 0.031 seconds

2026-05-18 19:25:33.000736: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:25:33.002157: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.96 seconds
--------------------------------------------------
5 / 10
current local expert:
                    x             y        lon        lat        t         z  \
2616804  1.063704e+06  1.475858e+06  144.21834  73.652538  18262.0 -0.059531

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2616804   1259  2020-01-01       cs2        1.0     110877.260893     -0.05953
'local_data_select': 0.001 seconds
number obs: 82
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.046 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  1.02067501])
kernel_variance: 0.00484857579457984
likelihood_variance: 0.01100000000000001
'predict': 0.031 seconds

2026-05-18 19:25:33.966133: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:25:33.967543: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.96 seconds
--------------------------------------------------
6 / 10
current local expert:
                    x             y        lon        lat        t         z  \
2616825  1.056895e+06  1.462674e+06  144.14897  73.785369  18262.0 -0.154075

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2616825   1259  2020-01-01       cs2        1.0     125771.474737     -0.05953
'local_data_select': 0.001 seconds
number obs: 82
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.051 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  1.02067501])
kernel_variance: 0.00484857579457984
likelihood_variance: 0.01100000000000001
'predict': 0.030 seconds

2026-05-18 19:25:34.929147: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:25:34.930560: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.96 seconds
--------------------------------------------------
7 / 10
current local expert:
                    x             y        lon        lat        t        z  \
2616875  1.044658e+06  1.439011e+06  144.02201  74.023749  18262.0  0.01717

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2616875   1259  2020-01-01       cs2        1.0     152505.579191     -0.05953
'local_data_select': 0.001 seconds
number obs: 82
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.047 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  1.02067501])
kernel_variance: 0.00484857579457984
likelihood_variance: 0.01100000000000001
'predict': 0.031 seconds

2026-05-18 19:25:35.887837: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:25:35.889241: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.96 seconds
--------------------------------------------------
8 / 10
current local expert:
                    x             y        lon        lat        t         z  \
2616900  1.039562e+06  1.429168e+06  143.96825  74.122887  18262.0 -0.151514

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2616900   1259  2020-01-01       cs2        1.0     163625.674623     -0.05953
'local_data_select': 0.001 seconds
number obs: 82
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.050 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  1.02067501])
kernel_variance: 0.00484857579457984
likelihood_variance: 0.01100000000000001
'predict': 0.031 seconds

2026-05-18 19:25:36.855412: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:25:36.857395: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.96 seconds
--------------------------------------------------
9 / 10
current local expert:
                    x             y        lon        lat        t         z  \
2616979  1.022327e+06  1.395933e+06  143.78241  74.457594  18262.0  0.054877

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2616979   1259  2020-01-01       cs2        1.0     201177.415699     -0.05953
'local_data_select': 0.001 seconds
number obs: 82
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  1.02067501])
kernel_variance: 0.00484857579457984
likelihood_variance: 0.01100000000000001
'predict': 0.031 seconds

2026-05-18 19:25:37.813785: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:25:37.815761: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 0.96 seconds
--------------------------------------------------
10 / 10
current local expert:
                    x             y        lon        lat        t       z  \
2617024  1.010583e+06  1.373334e+06  143.65208  74.685133  18262.0 -0.0788

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2617024   1259  2020-01-01       cs2        1.0     226713.409764     -0.05953
'local_data_select': 0.001 seconds
number obs: 82
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01      , 10.01      ,  1.02067501])
kernel_variance: 0.00484857579457984
likelihood_variance: 0.01100000000000001
'predict': 0.031 seconds

2026-05-18 19:25:38.771721: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:25:38.773118: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

SAVING RESULTS TO TABLES:
run_details
preds
total run time : 1.03 seconds
'run': 9.771 seconds
reading in results
getting all tables
merging on expert location data
table: 'oi_config' does not have all coords_col: ['x', 'y', 't'] in columns, not merging on expert_locations
table: 'oi_config_SMOOTHED' does not have all coords_col: ['x', 'y', 't'] in columns, not merging on expert_locations
lin:
                    x             y        lon        lat        t         z  \
2616558  1.114191e+06  1.574012e+06  144.70658  72.663214  18262.0 -0.105337
2616559  1.114055e+06  1.573746e+06  144.70532  72.665895  18262.0 -0.125954
2616560  1.113919e+06  1.573480e+06  144.70406  72.668575  18262.0 -0.091535
2616561  1.113783e+06  1.573215e+06  144.70280  72.671256  18262.0       NaN
2616562  1.113646e+06  1.572949e+06  144.70154  72.673937  18262.0       NaN

         track date_string satellite  lead_mask  dist_along_track  \
2616558   1259  2020-01-01       cs2        1.0          0.000000
2616559   1259  2020-01-01       cs2        1.0        300.349218
2616560   1259  2020-01-01       cs2        1.0        600.587691
2616561   1259  2020-01-01       cs2        0.0        900.935192
2616562   1259  2020-01-01       cs2        0.0       1201.281811

         z_track_avg     f_lin
2616558     -0.05953 -0.078024
2616559     -0.05953 -0.078024
2616560     -0.05953 -0.075121
2616561     -0.05953 -0.074858
2616562     -0.05953 -0.074596
gpsat:
                    x             y        lon        lat        t         z  \
2616558  1.114191e+06  1.574012e+06  144.70658  72.663214  18262.0 -0.105337
2616559  1.114055e+06  1.573746e+06  144.70532  72.665895  18262.0 -0.125954
2616560  1.113919e+06  1.573480e+06  144.70406  72.668575  18262.0 -0.091535
2616561  1.113783e+06  1.573215e+06  144.70280  72.671256  18262.0       NaN
2616562  1.113646e+06  1.572949e+06  144.70154  72.673937  18262.0       NaN

         track date_string satellite  lead_mask  dist_along_track  \
2616558   1259  2020-01-01       cs2        1.0          0.000000
2616559   1259  2020-01-01       cs2        1.0        300.349218
2616560   1259  2020-01-01       cs2        1.0        600.587691
2616561   1259  2020-01-01       cs2        0.0        900.935192
2616562   1259  2020-01-01       cs2        0.0       1201.281811

         z_track_avg   f_gpsat  f_var_gpsat
2616558     -0.05953 -0.085000     0.000260
2616559     -0.05953 -0.084911     0.000256
2616560     -0.05953 -0.084819     0.000252
2616561     -0.05953 -0.084724     0.000248
2616562     -0.05953 -0.084626     0.000244
Test NaNs — Linear: 0, GPSat: 0
Track interpolated!
Interpolating track 1260, 15 of 15...

/tmp/ipykernel_1171781/839927469.py:200: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  track_df['f_gpsat'] = ssha
/tmp/ipykernel_1171781/839927469.py:201: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  track_df['f_var_gpsat'] = ssha_var

Expert limit reached.
'data_select': 0.000 seconds
'load': 0.000 seconds
in json_serializable - key: 'data_source' has value DataFrame/Series, but is too long: 1331 >  100
storing as str
in json_serializable - key: 'df' has value DataFrame/Series, but is too long: 4620 >  100
storing as str
---------
storing expert locations in 'expert_locs' table
exception occurred: 'No object named expert_locs in the file'
will now close object

---------
dropping expert locations that already exists in 'run_details' table
exception occurred: 'No object named run_details in the file'
will now close object

--------------------------------------------------
1 / 40
current local expert:
                     x             y        lon        lat        t         z  \
2617067  950053.565564  1.257429e+06  142.92703  75.851377  18262.0  0.071572

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2617067   1260  2020-01-01       cs2        1.0               0.0      0.09918
'data_select': 0.000 seconds
'load': 0.000 seconds
'local_data_select': 0.001 seconds
number obs: 312
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.046 seconds
'get_parameters': 0.003 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.011 seconds

2026-05-18 19:25:40.608203: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:25:40.609602: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.498 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.00995924, 10.00985216,  0.99689665])
kernel_variance: 1.3201458619176059
likelihood_variance: 0.0010000281689153052
'predict': 0.032 seconds
total run time : 1.42 seconds
--------------------------------------------------
2 / 40
current local expert:
                     x             y        lon        lat        t         z  \
2617096  938474.992357  1.235367e+06  142.77705  76.073205  18262.0  0.161424

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2617096   1260  2020-01-01       cs2        1.0      24939.727824      0.09918
'local_data_select': 0.001 seconds
number obs: 323
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:25:42.035082: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:25:42.036502: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'optimise_parameters': 0.439 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.00997072, 10.0098926 ,  1.0136712 ])
kernel_variance: 1.2383367189107672
likelihood_variance: 0.0010000236647847527
'predict': 0.033 seconds
total run time : 1.35 seconds
--------------------------------------------------
3 / 40
current local expert:
                     x             y        lon        lat        t         z  \
2617160  926805.635693  1.213168e+06  142.62181  76.296363  18262.0  0.176901

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2617160   1260  2020-01-01       cs2        1.0      50037.524555      0.09918
'local_data_select': 0.001 seconds
number obs: 340
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.049 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:25:43.390194: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:25:43.392030: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'optimise_parameters': 0.413 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.00996365, 10.00987114,  0.99368801])
kernel_variance: 1.5806258719903354
likelihood_variance: 0.001000066939755302
'predict': 0.033 seconds
total run time : 1.33 seconds
--------------------------------------------------
4 / 40
current local expert:
                    x             y        lon        lat        t         z  \
2617206  915192.72796  1.191111e+06  142.46305  76.518035  18262.0  0.260992

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2617206   1260  2020-01-01       cs2        1.0      74977.135381      0.09918
'local_data_select': 0.001 seconds
number obs: 367
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:25:44.717677: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:25:44.719078: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'optimise_parameters': 0.494 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.00996192, 10.00986451,  0.9688747 ])
kernel_variance: 1.5053940109590738
likelihood_variance: 0.0010000718511018547
'predict': 0.032 seconds
total run time : 1.40 seconds
--------------------------------------------------
5 / 40
current local expert:
                     x             y       lon        lat        t         z  \
2617240  903562.100101  1.169056e+06  142.2996  76.739629  18262.0  0.180446

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2617240   1260  2020-01-01       cs2        1.0      99917.247001      0.09918
'local_data_select': 0.001 seconds
number obs: 391
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.049 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:25:46.121502: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:25:46.122890: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'optimise_parameters': 0.284 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.00997584, 10.00991223,  0.9970202 ])
kernel_variance: 1.3270815911512057
likelihood_variance: 0.001000103321199731
'predict': 0.033 seconds
total run time : 1.20 seconds
--------------------------------------------------
6 / 40
current local expert:
                     x             y        lon        lat        t         z  \
2617278  891773.675333  1.146736e+06  142.12914  76.963811  18262.0  0.216118

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2617278   1260  2020-01-01       cs2        1.0     125158.666433      0.09918
'local_data_select': 0.001 seconds
number obs: 408
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:25:47.317583: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:25:47.318988: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.642 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.00997745, 10.00991729,  1.01921426])
kernel_variance: 1.2497174874795753
likelihood_variance: 0.0010000879004803712
'predict': 0.035 seconds
total run time : 1.55 seconds
--------------------------------------------------
7 / 40
current local expert:
                     x             y        lon        lat        t         z  \
2617305  880108.050496  1.124685e+06  141.95548  77.185238  18262.0  0.080431

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2617305   1260  2020-01-01       cs2        1.0     150100.295224      0.09918
'local_data_select': 0.001 seconds
number obs: 436
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:25:48.870538: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:25:48.871946: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.553 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.00999137, 10.00996706,  0.9918249 ])
kernel_variance: 1.205554770381782
likelihood_variance: 0.0010000669238979098
'predict': 0.034 seconds
total run time : 1.47 seconds
--------------------------------------------------
8 / 40
current local expert:
                     x             y        lon        lat        t         z  \
2617332  868425.046549  1.102635e+06  141.77635  77.406574  18262.0  0.160561

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2617332   1260  2020-01-01       cs2        1.0     175042.572282      0.09918
'local_data_select': 0.001 seconds
number obs: 472
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.049 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:25:50.346648: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:25:50.348064: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'optimise_parameters': 0.404 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.00998356, 10.00993959,  1.00283266])
kernel_variance: 1.2516977875070017
likelihood_variance: 0.0010000452154910718
'predict': 0.035 seconds
total run time : 1.32 seconds
--------------------------------------------------
9 / 40
current local expert:
                     x             y        lon        lat        t         z  \
2617371  856724.739534  1.080587e+06  141.59146  77.627813  18262.0  0.098312

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2617371   1260  2020-01-01       cs2        1.0     199985.412641      0.09918
'local_data_select': 0.001 seconds
number obs: 477
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.050 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:25:51.670570: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:25:51.671983: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.510 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.00997008, 10.00989147,  1.02314668])
kernel_variance: 1.2142829883976134
likelihood_variance: 0.0010000514204840105
'predict': 0.037 seconds
total run time : 1.43 seconds
--------------------------------------------------
10 / 40
current local expert:
                     x             y        lon        lat        t         z  \
2617395  844583.353516  1.057744e+06  141.39347  77.856942  18262.0  0.012142

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2617395   1260  2020-01-01       cs2        1.0       225830.6203      0.09918
'local_data_select': 0.001 seconds
number obs: 488
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.050 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:25:53.105163: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:25:53.106565: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.515 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.00997833, 10.0099208 ,  0.99232219])
kernel_variance: 1.2138703263163384
likelihood_variance: 0.0010000486229821072
'predict': 0.036 seconds
SAVING RESULTS TO TABLES:
run_details
preds
lengthscales
kernel_variance
likelihood_variance
total run time : 1.58 seconds
--------------------------------------------------
11 / 40
current local expert:
                     x             y        lon        lat        t         z  \
2617436  832989.447212  1.035966e+06  141.19827  78.075307  18262.0  0.079263

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2617436   1260  2020-01-01       cs2        1.0     250474.529163      0.09918
'local_data_select': 0.001 seconds
number obs: 504
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:25:54.685941: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:25:54.687365: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'optimise_parameters': 0.874 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.00994372, 10.00979743,  0.97198195])
kernel_variance: 1.1709088682886695
likelihood_variance: 0.0010000678129708659
'predict': 0.036 seconds
total run time : 1.81 seconds
--------------------------------------------------
12 / 40
current local expert:
                     x             y        lon        lat        t         z  \
2617493  819678.269678  1.011004e+06  140.96635  78.325488  18262.0  0.105693

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2617493   1260  2020-01-01       cs2        1.0     278725.425277      0.09918
'local_data_select': 0.001 seconds
number obs: 535
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:25:56.502425: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:25:56.503851: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'optimise_parameters': 0.555 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.00997883, 10.00992222,  0.98985931])
kernel_variance: 1.1134033909995742
likelihood_variance: 0.001000076943692734
'predict': 0.041 seconds
total run time : 1.50 seconds
--------------------------------------------------
13 / 40
current local expert:
                     x              y        lon        lat        t  \
2617526  810744.709404  994275.643603  140.80577  78.493074  18262.0

                z  track date_string satellite  lead_mask  dist_along_track  \
2617526  0.145379   1260  2020-01-01       cs2        1.0     297659.876603

         z_track_avg
2617526      0.09918
'local_data_select': 0.001 seconds
number obs: 546
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.049 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:25:58.007765: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:25:58.009179: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'optimise_parameters': 1.015 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.00789097, 10.00449715,  2.73100776])
kernel_variance: 0.037606530594910995
likelihood_variance: 0.002619750999020635
'predict': 0.042 seconds
total run time : 1.95 seconds
--------------------------------------------------
14 / 40
current local expert:
                     x             y        lon        lat        t         z  \
2617569  797254.911533  969053.35875  140.55535  78.745643  18262.0  0.115728

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2617569   1260  2020-01-01       cs2        1.0     326212.662772      0.09918
'local_data_select': 0.001 seconds
number obs: 557
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.046 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:25:59.961348: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:25:59.962758: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.584 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.00995665, 10.00985296,  1.01558856])
kernel_variance: 2.335819789883675
likelihood_variance: 0.0010006060260967038
'predict': 0.040 seconds
total run time : 1.51 seconds
--------------------------------------------------
15 / 40
current local expert:
                    x              y        lon        lat        t         z  \
2617622  785735.43704  947550.981096  140.33354  78.960848  18262.0  0.069829

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2617622   1260  2020-01-01       cs2        1.0     350558.172724      0.09918
'local_data_select': 0.001 seconds
number obs: 566
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.049 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:26:01.474676: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:26:01.476084: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 1.154 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.00898413, 10.00713364,  0.51664998])
kernel_variance: 0.02311572497013794
likelihood_variance: 0.002822849759976532
'predict': 0.044 seconds
total run time : 2.10 seconds
--------------------------------------------------
16 / 40
current local expert:
                     x              y        lon        lat        t  \
2617664  773914.902741  925520.276646  140.09782  79.181222  18262.0

                z  track date_string satellite  lead_mask  dist_along_track  \
2617664  0.089341   1260  2020-01-01       cs2        1.0     375505.479923

         z_track_avg
2617664      0.09918
'local_data_select': 0.001 seconds
number obs: 578
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:26:03.572359: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:26:03.573767: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'optimise_parameters': 0.495 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.00993575, 10.00978693,  1.00929131])
kernel_variance: 2.658715215788576
likelihood_variance: 0.001000713410645444
'predict': 0.042 seconds
total run time : 1.45 seconds
--------------------------------------------------
17 / 40
current local expert:
                     x              y        lon        lat        t  \
2617689  761649.199181  902696.294165  139.84403  79.409397  18262.0

                z  track date_string satellite  lead_mask  dist_along_track  \
2617689  0.134439   1260  2020-01-01       cs2        1.0      401355.20188

         z_track_avg
2617689      0.09918
'local_data_select': 0.001 seconds
number obs: 591
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.047 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:26:05.021984: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:26:05.023381: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'optimise_parameters': 1.046 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.00974916, 10.00921378,  1.29045988])
kernel_variance: 0.02333565674887348
likelihood_variance: 0.0028601419207496996
'predict': 0.042 seconds
total run time : 2.00 seconds
--------------------------------------------------
18 / 40
current local expert:
                     x              y        lon        lat        t        z  \
2617720  750223.139844  881467.438649  139.59866  79.621492  18262.0 -0.19209

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2617720   1260  2020-01-01       cs2        1.0     425402.073809      0.09918
'local_data_select': 0.001 seconds
number obs: 584
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.049 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:26:07.028394: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:26:07.029792: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'optimise_parameters': 0.777 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01003762, 10.01013378,  1.0004917 ])
kernel_variance: 0.0077286655196445895
likelihood_variance: 0.0033343639174670766
'predict': 0.042 seconds
total run time : 1.72 seconds
--------------------------------------------------
19 / 40
current local expert:
                     x              y        lon        lat        t  \
2617758  738495.093711  859710.903981  139.33729  79.838718  18262.0

                z  track date_string satellite  lead_mask  dist_along_track  \
2617758  0.071523   1260  2020-01-01       cs2        1.0     450050.702106

         z_track_avg
2617758      0.09918
'local_data_select': 0.001 seconds
number obs: 549
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.047 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:26:08.751412: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:26:08.752930: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 1.317 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([19.99503551, 20.        ,  1.14159416])
kernel_variance: 0.010777327746724305
likelihood_variance: 0.0035788622950835075
'predict': 0.042 seconds
total run time : 2.26 seconds
--------------------------------------------------
20 / 40
current local expert:
                     x              y        lon        lat        t  \
2617800  726750.863971  837957.547545  139.06528  80.055757  18262.0

                z  track date_string satellite  lead_mask  dist_along_track  \
2617800  0.125194   1260  2020-01-01       cs2        1.0     474699.774282

         z_track_avg
2617800      0.09918
'local_data_select': 0.001 seconds
number obs: 531
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:26:11.014668: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:26:11.016076: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.767 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01003937, 10.01013867,  1.0011311 ])
kernel_variance: 0.007581413273061131
likelihood_variance: 0.004301175167224013
'predict': 0.041 seconds
SAVING RESULTS TO TABLES:
run_details
preds
lengthscales
kernel_variance
likelihood_variance
total run time : 1.87 seconds
--------------------------------------------------
21 / 40
current local expert:
                     x              y        lon        lat        t        z  \
2617832  714559.622201  815411.821701  138.77135  80.280527  18262.0  0.14086

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2617832   1260  2020-01-01       cs2        1.0     500251.236165      0.09918
'local_data_select': 0.001 seconds
number obs: 522
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'set_lengthscales_constraints': 0.006 seconds

2026-05-18 19:26:12.882072: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:26:12.883485: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'set_likelihood_variance_constraints': 0.011 seconds
**********
optimization failed!
'optimise_parameters': 0.704 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01003465, 10.01012296,  0.99941645])
kernel_variance: 0.009074864003691962
likelihood_variance: 0.004371365496477882
'predict': 0.040 seconds
total run time : 1.65 seconds
--------------------------------------------------
22 / 40
current local expert:
                     x              y        lon        lat        t  \
2617884  702926.048599  793930.177492  138.47912  80.494507  18262.0

                z  track date_string satellite  lead_mask  dist_along_track  \
2617884  0.121789   1260  2020-01-01       cs2        1.0      524600.93149

         z_track_avg
2617884      0.09918
'local_data_select': 0.001 seconds
number obs: 514
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.049 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:26:14.530977: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:26:14.532406: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'optimise_parameters': 0.481 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01003991, 10.01013883,  1.00001272])
kernel_variance: 0.005286127228571319
likelihood_variance: 0.004633655713688107
'predict': 0.039 seconds
total run time : 1.43 seconds
--------------------------------------------------
23 / 40
current local expert:
                     x             y        lon        lat        t         z  \
2617929  690412.954486  770861.15305  138.15115  80.724089  18262.0  0.103773

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2617929   1260  2020-01-01       cs2        1.0     550754.886515      0.09918
'local_data_select': 0.001 seconds
number obs: 518
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.047 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:26:15.956893: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:26:15.958322: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.644 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01004137, 10.01014347,  0.99243306])
kernel_variance: 0.004539930625152512
likelihood_variance: 0.004698993330725841
'predict': 0.042 seconds
total run time : 1.60 seconds
--------------------------------------------------
24 / 40
current local expert:
                     x              y        lon        lat        t       z  \
2617989  678170.124578  748326.266704  137.81558  80.948125  18262.0  0.1253

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2617989   1260  2020-01-01       cs2        1.0     576308.149342      0.09918
'local_data_select': 0.001 seconds
number obs: 507
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.049 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:26:17.564831: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:26:17.566416: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'optimise_parameters': 0.645 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.0100419 , 10.01014415,  0.99899877])
kernel_variance: 0.00406233672828936
likelihood_variance: 0.004781220005505008
'predict': 0.038 seconds
total run time : 1.59 seconds
--------------------------------------------------
25 / 40
current local expert:
                     x              y        lon        lat        t  \
2618028  667209.019321  728180.628239  137.50195  81.148199  18262.0

                z  track date_string satellite  lead_mask  dist_along_track  \
2618028  0.133613   1260  2020-01-01       cs2        1.0     599156.332008

         z_track_avg
2618028      0.09918
'local_data_select': 0.001 seconds
number obs: 494
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.047 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:26:19.158879: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:26:19.160287: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'optimise_parameters': 0.361 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01004187, 10.01014324,  1.00365107])
kernel_variance: 0.0039297535428675515
likelihood_variance: 0.004950121041398281
'predict': 0.039 seconds
total run time : 1.30 seconds
--------------------------------------------------
26 / 40
current local expert:
                     x              y        lon        lat        t  \
2618065  655945.114857  707508.199869  137.16578  81.353284  18262.0

                z  track date_string satellite  lead_mask  dist_along_track  \
2618065  0.135854   1260  2020-01-01       cs2        1.0      622606.25631

         z_track_avg
2618065      0.09918
'local_data_select': 0.001 seconds
number obs: 496
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.049 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:26:20.465382: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:26:20.466779: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.629 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01003878, 10.01013439,  1.00170398])
kernel_variance: 0.0045431560485708
likelihood_variance: 0.005271510643800644
'predict': 0.038 seconds
total run time : 1.59 seconds
--------------------------------------------------
27 / 40
current local expert:
                     x              y        lon        lat        t        z  \
2618106  643798.595498  685249.607271  136.78639  81.573834  18262.0  0.14897

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2618106   1260  2020-01-01       cs2        1.0     647860.427285      0.09918
'local_data_select': 0.001 seconds
number obs: 504
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.046 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:26:22.055295: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:26:22.056690: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.575 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01004053, 10.0101387 ,  0.99712936])
kernel_variance: 0.004314477501774408
likelihood_variance: 0.005266661692348616
'predict': 0.038 seconds
total run time : 1.53 seconds
--------------------------------------------------
28 / 40
current local expert:
                     x              y        lon        lat        t  \
2618152  630331.123071  660610.932034  136.34366  81.817609  18262.0

                z  track date_string satellite  lead_mask  dist_along_track  \
2618152  0.107653   1260  2020-01-01       cs2        1.0     675821.113534

         z_track_avg
2618152      0.09918
'local_data_select': 0.001 seconds
number obs: 508
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.049 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:26:23.585723: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:26:23.587147: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.832 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.00247496, 10.00025523,  0.74891413])
kernel_variance: 0.005113437999912162
likelihood_variance: 0.005266901131763085
'predict': 0.040 seconds
total run time : 1.80 seconds
--------------------------------------------------
29 / 40
current local expert:
                     x              y        lon        lat        t  \
2618201  619020.165825  639950.227921  135.95244  82.021708  18262.0

                z  track date_string satellite  lead_mask  dist_along_track  \
2618201  0.098432   1260  2020-01-01       cs2        1.0     699272.502429

         z_track_avg
2618201      0.09918
'local_data_select': 0.001 seconds
number obs: 497
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.049 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:26:25.386647: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:26:25.388053: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'optimise_parameters': 0.506 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01003944, 10.01013369,  0.99676203])
kernel_variance: 0.004716133590557467
likelihood_variance: 0.005428781763771227
'predict': 0.038 seconds
total run time : 1.46 seconds
--------------------------------------------------
30 / 40
current local expert:
                     x              y        lon        lat        t  \
2618256  605515.344894  615321.107431  135.46019  82.264593  18262.0

                z  track date_string satellite  lead_mask  dist_along_track  \
2618256  0.060942   1260  2020-01-01       cs2        1.0     727234.468576

         z_track_avg
2618256      0.09918
'local_data_select': 0.001 seconds
number obs: 490
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.049 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:26:26.844782: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:26:26.846200: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.728 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01003878, 10.01013096,  0.99870773])
kernel_variance: 0.00497364730768389
likelihood_variance: 0.005383369649600278
'predict': 0.038 seconds
SAVING RESULTS TO TABLES:
run_details
preds
lengthscales
kernel_variance
likelihood_variance
total run time : 1.87 seconds
--------------------------------------------------
31 / 40
current local expert:
                     x              y        lon        lat        t  \
2618303  594464.020004  595198.218272  135.03536  82.462672  18262.0

                z  track date_string satellite  lead_mask  dist_along_track  \
2618303  0.082743   1260  2020-01-01       cs2        1.0     750085.564521

         z_track_avg
2618303      0.09918
'local_data_select': 0.001 seconds
number obs: 482
found GPU
setting lengthscales to: [1. 1. 1.]

2026-05-18 19:26:28.709992: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:26:28.711421: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'__init__': 0.047 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds
'optimise_parameters': 0.443 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01003749, 10.01012623,  0.99940061])
kernel_variance: 0.00516407255530277
likelihood_variance: 0.0054683352045343005
'predict': 0.039 seconds
total run time : 1.41 seconds
--------------------------------------------------
32 / 40
current local expert:
                     x              y        lon        lat        t  \
2618371  579902.327724  568726.377782  134.44254  82.722689  18262.0

                z  track date_string satellite  lead_mask  dist_along_track  \
2618371  0.106076   1260  2020-01-01       cs2        1.0     780153.472268

         z_track_avg
2618371      0.09918
'local_data_select': 0.001 seconds
number obs: 474
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.046 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:26:30.125225: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:26:30.126827: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'optimise_parameters': 0.657 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01003576, 10.0101201 ,  1.00396754])
kernel_variance: 0.00814245100550068
likelihood_variance: 0.005326295130223638
'predict': 0.038 seconds
total run time : 1.63 seconds
--------------------------------------------------
33 / 40
current local expert:
                     x              y        lon        lat        t  \
2618410  569841.292191  550464.656563  134.00912  82.901657  18262.0

                z  track date_string satellite  lead_mask  dist_along_track  \
2618410  0.122077   1260  2020-01-01       cs2        1.0     800900.728081

         z_track_avg
2618410      0.09918
'local_data_select': 0.001 seconds
number obs: 472
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.050 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:26:31.759843: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:26:31.761465: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.730 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01003802, 10.01012705,  1.0029234 ])
kernel_variance: 0.005395288180134549
likelihood_variance: 0.005415235765138478
'predict': 0.038 seconds
total run time : 1.68 seconds
--------------------------------------------------
34 / 40
current local expert:
                     x              y       lon        lat        t         z  \
2618469  557870.181922  528766.527025  133.4658  83.113829  18262.0  0.105858

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2618469   1260  2020-01-01       cs2        1.0     825557.413738      0.09918
'local_data_select': 0.001 seconds
number obs: 461
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.049 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:26:33.444393: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:26:33.445793: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'optimise_parameters': 0.467 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01003851, 10.01012838,  1.00179766])
kernel_variance: 0.005619638746712098
likelihood_variance: 0.005282262172991858
'predict': 0.038 seconds
total run time : 1.44 seconds
--------------------------------------------------
35 / 40
current local expert:
                     x              y        lon        lat        t  \
2618519  545737.368159  506808.392438  132.88185  83.327966  18262.0

                z  track date_string satellite  lead_mask  dist_along_track  \
2618519  0.033718   1260  2020-01-01       cs2        1.0     850515.352298

         z_track_avg
2618519      0.09918
'local_data_select': 0.001 seconds
number obs: 458
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.046 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:26:34.885838: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:26:34.887415: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.876 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.00009136, 10.        ,  1.10264939])
kernel_variance: 0.006893843887767216
likelihood_variance: 0.005232179443764226
'predict': 0.039 seconds
total run time : 1.84 seconds
--------------------------------------------------
36 / 40
current local expert:
                     x              y        lon        lat        t  \
2618569  533735.070917  485119.807911  132.26817  83.538846  18262.0

                z  track date_string satellite  lead_mask  dist_along_track  \
2618569  0.046366   1260  2020-01-01       cs2        1.0     875172.937487

         z_track_avg
2618569      0.09918
'local_data_select': 0.001 seconds
number obs: 451
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.051 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:26:36.732129: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:26:36.733538: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'optimise_parameters': 0.461 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01003584, 10.01011806,  1.00166288])
kernel_variance: 0.0067466544798423424
likelihood_variance: 0.0052589404028917765
'predict': 0.037 seconds
total run time : 1.44 seconds
--------------------------------------------------
37 / 40
current local expert:
                     x              y        lon        lat        t  \
2618621  521864.097269  463700.374219  131.62257  83.746427  18262.0

                z  track date_string satellite  lead_mask  dist_along_track  \
2618621 -0.253447   1260  2020-01-01       cs2        1.0     899530.337525

         z_track_avg
2618621      0.09918
'local_data_select': 0.001 seconds
number obs: 438
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.049 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:26:38.172092: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:26:38.173501: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'optimise_parameters': 0.371 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01003599, 10.01011751,  0.99984327])
kernel_variance: 0.006606807683346029
likelihood_variance: 0.005292716250529053
'predict': 0.038 seconds
total run time : 1.35 seconds
--------------------------------------------------
38 / 40
current local expert:
                     x              y        lon        lat        t  \
2618671  509684.393832  441757.112703  130.91635  83.958305  18262.0

                z  track date_string satellite  lead_mask  dist_along_track  \
2618671  0.097826   1260  2020-01-01       cs2        1.0     924489.634608

         z_track_avg
2618671      0.09918
'local_data_select': 0.001 seconds
number obs: 451
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:26:39.521738: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:26:39.523138: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'optimise_parameters': 0.436 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01003684, 10.01011946,  0.99742227])
kernel_variance: 0.006814790264571564
likelihood_variance: 0.00522893154949926
'predict': 0.039 seconds
total run time : 1.42 seconds
--------------------------------------------------
39 / 40
current local expert:
                     x              y        lon        lat        t  \
2618723  497194.980003  419290.535926  130.14134  84.174323  18262.0

                z  track date_string satellite  lead_mask  dist_along_track  \
2618723  0.115032   1260  2020-01-01       cs2        1.0     950050.777554

         z_track_avg
2618723      0.09918
'local_data_select': 0.001 seconds
number obs: 430
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:26:40.942952: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:26:40.944539: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

**********
optimization failed!
'optimise_parameters': 0.509 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01003762, 10.01012105,  1.00041688])
kernel_variance: 0.006353063738161751
likelihood_variance: 0.00546759439460483
'predict': 0.037 seconds
total run time : 1.47 seconds
--------------------------------------------------
40 / 40
current local expert:
                     x              y        lon        lat        t  \
2618775  484983.566989  397357.891614  129.32853  84.384209  18262.0

                z  track date_string satellite  lead_mask  dist_along_track  \
2618775  0.058939   1260  2020-01-01       cs2        1.0     975011.018558

         z_track_avg
2618775      0.09918
'local_data_select': 0.001 seconds
number obs: 405
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.049 seconds
'set_lengthscales_constraints': 0.006 seconds
'set_likelihood_variance_constraints': 0.010 seconds

2026-05-18 19:26:42.410582: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:26:42.411980: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'optimise_parameters': 0.380 seconds
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01003841, 10.01012248,  1.00002484])
kernel_variance: 0.006094823125068192
likelihood_variance: 0.00578996523859762
'predict': 0.037 seconds
SAVING RESULTS TO TABLES:
run_details
preds
lengthscales
kernel_variance
likelihood_variance
total run time : 1.59 seconds
'run': 63.456 seconds
reading in results
getting all tables
merging on expert location data
table: 'oi_config' does not have all coords_col: ['x', 'y', 't'] in columns, not merging on expert_locations
h5 tables: ['expert_locs', 'kernel_variance', 'lengthscales', 'likelihood_variance', 'oi_config', 'preds', 'run_details']
found model_name: GPflowGPRModel
found GPU
setting lengthscales to: [1.]
'__init__': 0.049 seconds
reading in results
selecting only tables: ['lengthscales', 'kernel_variance', 'likelihood_variance']
'data_select': 0.000 seconds
'load': 0.000 seconds
expert_locations data will not be merged on results data
adding smoothed table: lengthscales_SMOOTHED
adding smoothed table: kernel_variance_SMOOTHED
adding smoothed table: likelihood_variance_SMOOTHED
writing (smoothed) hyper parameters to:
/home/mhen/geol0069_data/gpsat/jan20/1260.h5
table_suffix:_SMOOTHED
writing: lengthscales_SMOOTHED to table
writing: kernel_variance_SMOOTHED to table
writing: likelihood_variance_SMOOTHED to table
'data_select': 0.000 seconds
'load': 0.000 seconds
in json_serializable - key: 'data_source' has value DataFrame/Series, but is too long: 1331 >  100
storing as str
in json_serializable - key: 'df' has value DataFrame/Series, but is too long: 4620 >  100
storing as str
---------
storing expert locations in 'expert_locs' table
exception occurred: 'No object named expert_locs_SMOOTHED in the file'
will now close object

2026-05-18 19:26:44.182854: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:26:44.184439: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

---------
dropping expert locations that already exists in 'run_details' table
exception occurred: 'No object named run_details_SMOOTHED in the file'
will now close object

--------------------------------------------------
1 / 40
current local expert:
                     x             y        lon        lat        t         z  \
2617067  950053.565564  1.257429e+06  142.92703  75.851377  18262.0  0.071572

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2617067   1260  2020-01-01       cs2        1.0               0.0      0.09918
'data_select': 0.000 seconds
'load': 0.000 seconds
'local_data_select': 0.001 seconds
number obs: 312
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.046 seconds
'get_parameters': 0.003 seconds
'_read_params_from_file': 0.048 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.02486724, 10.02464786,  1.04758278])
kernel_variance: 0.09208474538947847
likelihood_variance: 0.01100000000000001
'predict': 0.032 seconds

2026-05-18 19:26:44.445169: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:26:44.446595: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 1.03 seconds
--------------------------------------------------
2 / 40
current local expert:
                     x             y        lon        lat        t         z  \
2617096  938474.992357  1.235367e+06  142.77705  76.073205  18262.0  0.161424

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2617096   1260  2020-01-01       cs2        1.0      24939.727824      0.09918
'local_data_select': 0.001 seconds
number obs: 323
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'_read_params_from_file': 0.045 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.02786913, 10.02763567,  1.05217095])
kernel_variance: 0.09075657030822815
likelihood_variance: 0.01100000000000001
'predict': 0.033 seconds

2026-05-18 19:26:45.478873: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:26:45.480307: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 1.01 seconds
--------------------------------------------------
3 / 40
current local expert:
                     x             y        lon        lat        t         z  \
2617160  926805.635693  1.213168e+06  142.62181  76.296363  18262.0  0.176901

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2617160   1260  2020-01-01       cs2        1.0      50037.524555      0.09918
'local_data_select': 0.001 seconds
number obs: 340
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'_read_params_from_file': 0.045 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.03136428, 10.03111623,  1.05685656])
kernel_variance: 0.08922644656272696
likelihood_variance: 0.01100000000000001
'predict': 0.033 seconds

2026-05-18 19:26:46.493143: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:26:46.494551: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 1.03 seconds
--------------------------------------------------
4 / 40
current local expert:
                    x             y        lon        lat        t         z  \
2617206  915192.72796  1.191111e+06  142.46305  76.518035  18262.0  0.260992

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2617206   1260  2020-01-01       cs2        1.0      74977.135381      0.09918
'local_data_select': 0.001 seconds
number obs: 367
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.03533981, 10.0350771 ,  1.06149738])
kernel_variance: 0.0874955336601822
likelihood_variance: 0.01100000000000001
'predict': 0.033 seconds

2026-05-18 19:26:47.519276: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:26:47.520690: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 1.01 seconds
--------------------------------------------------
5 / 40
current local expert:
                     x             y       lon        lat        t         z  \
2617240  903562.100101  1.169056e+06  142.2996  76.739629  18262.0  0.180446

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2617240   1260  2020-01-01       cs2        1.0      99917.247001      0.09918
'local_data_select': 0.001 seconds
number obs: 391
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.046 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.03983547, 10.03955825,  1.06602495])
kernel_variance: 0.08553791848947949
likelihood_variance: 0.01100000000000001
'predict': 0.033 seconds

2026-05-18 19:26:48.527300: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:26:48.528704: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 1.00 seconds
--------------------------------------------------
6 / 40
current local expert:
                     x             y        lon        lat        t         z  \
2617278  891773.675333  1.146736e+06  142.12914  76.963811  18262.0  0.216118

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2617278   1260  2020-01-01       cs2        1.0     125158.666433      0.09918
'local_data_select': 0.001 seconds
number obs: 408
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.051 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.04491749, 10.04462608,  1.07037748])
kernel_variance: 0.08331083004401535
likelihood_variance: 0.01100000000000001
'predict': 0.034 seconds

2026-05-18 19:26:49.533029: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:26:49.534444: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 1.02 seconds
--------------------------------------------------
7 / 40
current local expert:
                     x             y        lon        lat        t         z  \
2617305  880108.050496  1.124685e+06  141.95548  77.185238  18262.0  0.080431

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2617305   1260  2020-01-01       cs2        1.0     150100.295224      0.09918
'local_data_select': 0.001 seconds
number obs: 436
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'_read_params_from_file': 0.045 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.05044537, 10.05014084,  1.07432694])
kernel_variance: 0.08085575117906177
likelihood_variance: 0.01100000000000001
'predict': 0.034 seconds

2026-05-18 19:26:50.548435: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:26:50.549973: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 1.03 seconds
--------------------------------------------------
8 / 40
current local expert:
                     x             y        lon        lat        t         z  \
2617332  868425.046549  1.102635e+06  141.77635  77.406574  18262.0  0.160561

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2617332   1260  2020-01-01       cs2        1.0     175042.572282      0.09918
'local_data_select': 0.001 seconds
number obs: 472
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.049 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.0564303 , 10.05611398,  1.07779625])
kernel_variance: 0.07814075787118667
likelihood_variance: 0.01100000000000001
'predict': 0.035 seconds

2026-05-18 19:26:51.579383: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:26:51.580797: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 1.03 seconds
--------------------------------------------------
9 / 40
current local expert:
                     x             y        lon        lat        t         z  \
2617371  856724.739534  1.080587e+06  141.59146  77.627813  18262.0  0.098312

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2617371   1260  2020-01-01       cs2        1.0     199985.412641      0.09918
'local_data_select': 0.001 seconds
number obs: 477
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.050 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.06279511, 10.06246875,  1.08065307])
kernel_variance: 0.07516474265768901
likelihood_variance: 0.01100000000000001
'predict': 0.037 seconds

2026-05-18 19:26:52.611440: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:26:52.612848: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 1.02 seconds
--------------------------------------------------
10 / 40
current local expert:
                     x             y        lon        lat        t         z  \
2617395  844583.353516  1.057744e+06  141.39347  77.856942  18262.0  0.012142

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2617395   1260  2020-01-01       cs2        1.0       225830.6203      0.09918
'local_data_select': 0.001 seconds
number obs: 488
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.050 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.06967194, 10.06933747,  1.08283115])
kernel_variance: 0.07181211380978943
likelihood_variance: 0.01100000000000001
'predict': 0.036 seconds

2026-05-18 19:26:53.631285: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:26:53.632699: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

SAVING RESULTS TO TABLES:
run_details
preds
total run time : 1.10 seconds
--------------------------------------------------
11 / 40
current local expert:
                     x             y        lon        lat        t         z  \
2617436  832989.447212  1.035966e+06  141.19827  78.075307  18262.0  0.079263

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2617436   1260  2020-01-01       cs2        1.0     250474.529163      0.09918
'local_data_select': 0.001 seconds
number obs: 504
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.049 seconds
'_read_params_from_file': 0.050 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters

2026-05-18 19:26:54.733646: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:26:54.735058: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.07634895, 10.07600931,  1.08405127])
kernel_variance: 0.0683744625272616
likelihood_variance: 0.01100000000000001
'predict': 0.037 seconds
total run time : 1.04 seconds
--------------------------------------------------
12 / 40
current local expert:
                     x             y        lon        lat        t         z  \
2617493  819678.269678  1.011004e+06  140.96635  78.325488  18262.0  0.105693

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2617493   1260  2020-01-01       cs2        1.0     278725.425277      0.09918
'local_data_select': 0.001 seconds
number obs: 535
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.050 seconds
'_read_params_from_file': 0.045 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.08392024, 10.08357813,  1.0843042 ])
kernel_variance: 0.0641734191431322
likelihood_variance: 0.01100000000000001
'predict': 0.041 seconds

2026-05-18 19:26:55.773194: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:26:55.774605: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 1.02 seconds
--------------------------------------------------
13 / 40
current local expert:
                     x              y        lon        lat        t  \
2617526  810744.709404  994275.643603  140.80577  78.493074  18262.0

                z  track date_string satellite  lead_mask  dist_along_track  \
2617526  0.145379   1260  2020-01-01       cs2        1.0     297659.876603

         z_track_avg
2617526      0.09918
'local_data_select': 0.001 seconds
number obs: 546
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.049 seconds
'_read_params_from_file': 0.045 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.08880323, 10.08846168,  1.08374451])
kernel_variance: 0.06122397840149225
likelihood_variance: 0.01100000000000001
'predict': 0.041 seconds

2026-05-18 19:26:56.789810: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:26:56.791227: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 1.04 seconds
--------------------------------------------------
14 / 40
current local expert:
                     x             y        lon        lat        t         z  \
2617569  797254.911533  969053.35875  140.55535  78.745643  18262.0  0.115728

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2617569   1260  2020-01-01       cs2        1.0     326212.662772      0.09918
'local_data_select': 0.001 seconds
number obs: 557
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.049 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.09562953, 10.09529229,  1.08176296])
kernel_variance: 0.05661749895873401
likelihood_variance: 0.01100000000000001
'predict': 0.041 seconds

2026-05-18 19:26:57.827922: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:26:57.829348: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 1.02 seconds
--------------------------------------------------
15 / 40
current local expert:
                    x              y        lon        lat        t         z  \
2617622  785735.43704  947550.981096  140.33354  78.960848  18262.0  0.069829

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2617622   1260  2020-01-01       cs2        1.0     350558.172724      0.09918
'local_data_select': 0.001 seconds
number obs: 566
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.052 seconds
'_read_params_from_file': 0.045 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.10071234, 10.10038201,  1.07900577])
kernel_variance: 0.0525862979785489
likelihood_variance: 0.01100000000000001
'predict': 0.042 seconds

2026-05-18 19:26:58.848676: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:26:58.850088: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 1.04 seconds
--------------------------------------------------
16 / 40
current local expert:
                     x              y        lon        lat        t  \
2617664  773914.902741  925520.276646  140.09782  79.181222  18262.0

                z  track date_string satellite  lead_mask  dist_along_track  \
2617664  0.089341   1260  2020-01-01       cs2        1.0     375505.479923

         z_track_avg
2617664      0.09918
'local_data_select': 0.001 seconds
number obs: 578
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.10499048, 10.10467014,  1.07521718])
kernel_variance: 0.04841141169285172
likelihood_variance: 0.01100000000000001
'predict': 0.042 seconds

2026-05-18 19:26:59.889833: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:26:59.891251: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 1.02 seconds
--------------------------------------------------
17 / 40
current local expert:
                     x              y        lon        lat        t  \
2617689  761649.199181  902696.294165  139.84403  79.409397  18262.0

                z  track date_string satellite  lead_mask  dist_along_track  \
2617689  0.134439   1260  2020-01-01       cs2        1.0      401355.20188

         z_track_avg
2617689      0.09918
'local_data_select': 0.001 seconds
number obs: 591
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.050 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.1082246 , 10.10791742,  1.0703674 ])
kernel_variance: 0.0440990212203425
likelihood_variance: 0.01100000000000001
'predict': 0.042 seconds

2026-05-18 19:27:00.909600: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:27:00.911094: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 1.02 seconds
--------------------------------------------------
18 / 40
current local expert:
                     x              y        lon        lat        t        z  \
2617720  750223.139844  881467.438649  139.59866  79.621492  18262.0 -0.19209

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2617720   1260  2020-01-01       cs2        1.0     425402.073809      0.09918
'local_data_select': 0.001 seconds
number obs: 584
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.049 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.10998994, 10.10969714,  1.06514278])
kernel_variance: 0.04015587256925958
likelihood_variance: 0.01100000000000001
'predict': 0.042 seconds

2026-05-18 19:27:01.932923: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:27:01.934347: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 1.04 seconds
--------------------------------------------------
19 / 40
current local expert:
                     x              y        lon        lat        t  \
2617758  738495.093711  859710.903981  139.33729  79.838718  18262.0

                z  track date_string satellite  lead_mask  dist_along_track  \
2617758  0.071523   1260  2020-01-01       cs2        1.0     450050.702106

         z_track_avg
2617758      0.09918
'local_data_select': 0.001 seconds
number obs: 549
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.047 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.11046003, 10.11018366,  1.05923452])
kernel_variance: 0.036236903801484234
likelihood_variance: 0.01100000000000001
'predict': 0.041 seconds

2026-05-18 19:27:02.971767: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:27:02.973166: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 1.04 seconds
--------------------------------------------------
20 / 40
current local expert:
                     x              y        lon        lat        t  \
2617800  726750.863971  837957.547545  139.06528  80.055757  18262.0

                z  track date_string satellite  lead_mask  dist_along_track  \
2617800  0.125194   1260  2020-01-01       cs2        1.0     474699.774282

         z_track_avg
2617800      0.09918
'local_data_select': 0.001 seconds
number obs: 531
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.049 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.10953867, 10.10927992,  1.05294629])
kernel_variance: 0.03249225175585339
likelihood_variance: 0.01100000000000001
'predict': 0.041 seconds

2026-05-18 19:27:04.010108: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:27:04.011518: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

SAVING RESULTS TO TABLES:
run_details
preds
total run time : 1.09 seconds
--------------------------------------------------
21 / 40
current local expert:
                     x              y        lon        lat        t        z  \
2617832  714559.622201  815411.821701  138.77135  80.280527  18262.0  0.14086

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2617832   1260  2020-01-01       cs2        1.0     500251.236165      0.09918
'local_data_select': 0.001 seconds
number obs: 522
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.046 seconds
'_read_params_from_file': 0.051 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds

2026-05-18 19:27:05.102093: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:27:05.103550: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'set_likelihood_variance_constraints': 0.016 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.10714519, 10.10690541,  1.04623087])
kernel_variance: 0.028841567153275034
likelihood_variance: 0.01100000000000001
'predict': 0.040 seconds
total run time : 1.04 seconds
--------------------------------------------------
22 / 40
current local expert:
                     x              y        lon        lat        t  \
2617884  702926.048599  793930.177492  138.47912  80.494507  18262.0

                z  track date_string satellite  lead_mask  dist_along_track  \
2617884  0.121789   1260  2020-01-01       cs2        1.0      524600.93149

         z_track_avg
2617884      0.09918
'local_data_select': 0.001 seconds
number obs: 514
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.10359379, 10.10337228,  1.03983557])
kernel_variance: 0.025617409914482876
likelihood_variance: 0.01100000000000001
'predict': 0.039 seconds

2026-05-18 19:27:06.146840: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:27:06.148812: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 1.01 seconds
--------------------------------------------------
23 / 40
current local expert:
                     x             y        lon        lat        t         z  \
2617929  690412.954486  770861.15305  138.15115  80.724089  18262.0  0.103773

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2617929   1260  2020-01-01       cs2        1.0     550754.886515      0.09918
'local_data_select': 0.001 seconds
number obs: 518
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.047 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.0985637 , 10.09836158,  1.03316883])
kernel_variance: 0.02246038789574521
likelihood_variance: 0.01100000000000001
'predict': 0.042 seconds

2026-05-18 19:27:07.161778: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:27:07.163193: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 1.01 seconds
--------------------------------------------------
24 / 40
current local expert:
                     x              y        lon        lat        t       z  \
2617989  678170.124578  748326.266704  137.81558  80.948125  18262.0  0.1253

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2617989   1260  2020-01-01       cs2        1.0     576308.149342      0.09918
'local_data_select': 0.001 seconds
number obs: 507
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.045 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.09264947, 10.09246567,  1.02703098])
kernel_variance: 0.01969947576017627
likelihood_variance: 0.01100000000000001
'predict': 0.038 seconds

2026-05-18 19:27:08.175224: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:27:08.176696: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 1.01 seconds
--------------------------------------------------
25 / 40
current local expert:
                     x              y        lon        lat        t  \
2618028  667209.019321  728180.628239  137.50195  81.148199  18262.0

                z  track date_string satellite  lead_mask  dist_along_track  \
2618028  0.133613   1260  2020-01-01       cs2        1.0     599156.332008

         z_track_avg
2618028      0.09918
'local_data_select': 0.001 seconds
number obs: 494
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.050 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.086729  , 10.08656086,  1.02197363])
kernel_variance: 0.017506897256862677
likelihood_variance: 0.01100000000000001
'predict': 0.039 seconds

2026-05-18 19:27:09.190376: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:27:09.192092: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 1.04 seconds
--------------------------------------------------
26 / 40
current local expert:
                     x              y        lon        lat        t  \
2618065  655945.114857  707508.199869  137.16578  81.353284  18262.0

                z  track date_string satellite  lead_mask  dist_along_track  \
2618065  0.135854   1260  2020-01-01       cs2        1.0      622606.25631

         z_track_avg
2618065      0.09918
'local_data_select': 0.001 seconds
number obs: 496
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.047 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.08023673, 10.08008385,  1.01728808])
kernel_variance: 0.015524617153172526
likelihood_variance: 0.01100000000000001
'predict': 0.038 seconds

2026-05-18 19:27:10.226304: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:27:10.227747: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 1.01 seconds
--------------------------------------------------
27 / 40
current local expert:
                     x              y        lon        lat        t        z  \
2618106  643798.595498  685249.607271  136.78639  81.573834  18262.0  0.14897

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2618106   1260  2020-01-01       cs2        1.0     647860.427285      0.09918
'local_data_select': 0.001 seconds
number obs: 504
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.049 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.07300278, 10.07286532,  1.01287415])
kernel_variance: 0.013682458327929598
likelihood_variance: 0.01100000000000001
'predict': 0.038 seconds

2026-05-18 19:27:11.243429: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:27:11.244851: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 1.02 seconds
--------------------------------------------------
28 / 40
current local expert:
                     x              y        lon        lat        t  \
2618152  630331.123071  660610.932034  136.34366  81.817609  18262.0

                z  track date_string satellite  lead_mask  dist_along_track  \
2618152  0.107653   1260  2020-01-01       cs2        1.0     675821.113534

         z_track_avg
2618152      0.09918
'local_data_select': 0.001 seconds
number obs: 508
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.050 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.06497639, 10.06485482,  1.00878775])
kernel_variance: 0.011974412383397925
likelihood_variance: 0.01100000000000001
'predict': 0.039 seconds

2026-05-18 19:27:12.265356: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:27:12.266780: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 1.02 seconds
--------------------------------------------------
29 / 40
current local expert:
                     x              y        lon        lat        t  \
2618201  619020.165825  639950.227921  135.95244  82.021708  18262.0

                z  track date_string satellite  lead_mask  dist_along_track  \
2618201  0.098432   1260  2020-01-01       cs2        1.0     699272.502429

         z_track_avg
2618201      0.09918
'local_data_select': 0.001 seconds
number obs: 497
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.047 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.05842561, 10.05831648,  1.00600718])
kernel_variance: 0.010787386224904468
likelihood_variance: 0.01100000000000001
'predict': 0.039 seconds

2026-05-18 19:27:13.278769: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:27:13.280179: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 1.03 seconds
--------------------------------------------------
30 / 40
current local expert:
                     x              y        lon        lat        t  \
2618256  605515.344894  615321.107431  135.46019  82.264593  18262.0

                z  track date_string satellite  lead_mask  dist_along_track  \
2618256  0.060942   1260  2020-01-01       cs2        1.0     727234.468576

         z_track_avg
2618256      0.09918
'local_data_select': 0.001 seconds
number obs: 490
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.047 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.05102517, 10.0509299 ,  1.00342721])
kernel_variance: 0.009632429902861478
likelihood_variance: 0.01100000000000001
'predict': 0.038 seconds

2026-05-18 19:27:14.311931: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:27:14.313333: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

SAVING RESULTS TO TABLES:
run_details
preds
total run time : 1.14 seconds
--------------------------------------------------
31 / 40
current local expert:
                     x              y        lon        lat        t  \
2618303  594464.020004  595198.218272  135.03536  82.462672  18262.0

                z  track date_string satellite  lead_mask  dist_along_track  \
2618303  0.082743   1260  2020-01-01       cs2        1.0     750085.564521

         z_track_avg
2618303      0.09918
'local_data_select': 0.001 seconds
number obs: 482
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds

2026-05-18 19:27:15.455762: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:27:15.457165: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

'_read_params_from_file': 0.050 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.04541777, 10.04533315,  1.00186665])
kernel_variance: 0.008873114255715976
likelihood_variance: 0.01100000000000001
'predict': 0.039 seconds
total run time : 1.02 seconds
--------------------------------------------------
32 / 40
current local expert:
                     x              y        lon        lat        t  \
2618371  579902.327724  568726.377782  134.44254  82.722689  18262.0

                z  track date_string satellite  lead_mask  dist_along_track  \
2618371  0.106076   1260  2020-01-01       cs2        1.0     780153.472268

         z_track_avg
2618371      0.09918
'local_data_select': 0.001 seconds
number obs: 474
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'_read_params_from_file': 0.045 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.0387486 , 10.03867718,  1.00047544])
kernel_variance: 0.008088657206263441
likelihood_variance: 0.01100000000000001
'predict': 0.038 seconds

2026-05-18 19:27:16.478455: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:27:16.479868: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 1.02 seconds
--------------------------------------------------
33 / 40
current local expert:
                     x              y        lon        lat        t  \
2618410  569841.292191  550464.656563  134.00912  82.901657  18262.0

                z  track date_string satellite  lead_mask  dist_along_track  \
2618410  0.122077   1260  2020-01-01       cs2        1.0     800900.728081

         z_track_avg
2618410      0.09918
'local_data_select': 0.001 seconds
number obs: 472
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.03464964, 10.03458688,  0.9998942 ])
kernel_variance: 0.007667618240032801
likelihood_variance: 0.01100000000000001
'predict': 0.037 seconds

2026-05-18 19:27:17.500727: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:27:17.502139: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 1.02 seconds
--------------------------------------------------
34 / 40
current local expert:
                     x              y       lon        lat        t         z  \
2618469  557870.181922  528766.527025  133.4658  83.113829  18262.0  0.105858

         track date_string satellite  lead_mask  dist_along_track  z_track_avg
2618469   1260  2020-01-01       cs2        1.0     825557.413738      0.09918
'local_data_select': 0.001 seconds
number obs: 461
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.046 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.03032055, 10.03026765,  0.99953786])
kernel_variance: 0.007272856340244425
likelihood_variance: 0.01100000000000001
'predict': 0.038 seconds

2026-05-18 19:27:18.517796: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:27:18.519178: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 1.01 seconds
--------------------------------------------------
35 / 40
current local expert:
                     x              y        lon        lat        t  \
2618519  545737.368159  506808.392438  132.88185  83.327966  18262.0

                z  track date_string satellite  lead_mask  dist_along_track  \
2618519  0.033718   1260  2020-01-01       cs2        1.0     850515.352298

         z_track_avg
2618519      0.09918
'local_data_select': 0.001 seconds
number obs: 458
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.02652354, 10.02648017,  0.99947857])
kernel_variance: 0.006969721128653404
likelihood_variance: 0.01100000000000001
'predict': 0.038 seconds

2026-05-18 19:27:19.532544: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:27:19.533989: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 1.02 seconds
--------------------------------------------------
36 / 40
current local expert:
                     x              y        lon        lat        t  \
2618569  533735.070917  485119.807911  132.26817  83.538846  18262.0

                z  track date_string satellite  lead_mask  dist_along_track  \
2618569  0.046366   1260  2020-01-01       cs2        1.0     875172.937487

         z_track_avg
2618569      0.09918
'local_data_select': 0.001 seconds
number obs: 451
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.049 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.02331777, 10.02328343,  0.99965061])
kernel_variance: 0.00674685700135391
likelihood_variance: 0.01100000000000001
'predict': 0.037 seconds

2026-05-18 19:27:20.554684: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:27:20.556115: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 1.01 seconds
--------------------------------------------------
37 / 40
current local expert:
                     x              y        lon        lat        t  \
2618621  521864.097269  463700.374219  131.62257  83.746427  18262.0

                z  track date_string satellite  lead_mask  dist_along_track  \
2618621 -0.253447   1260  2020-01-01       cs2        1.0     899530.337525

         z_track_avg
2618621      0.09918
'local_data_select': 0.001 seconds
number obs: 438
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.049 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.02064031, 10.02061449,  0.99998646])
kernel_variance: 0.006585953078498595
likelihood_variance: 0.01100000000000001
'predict': 0.037 seconds

2026-05-18 19:27:21.564593: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:27:21.566058: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 1.03 seconds
--------------------------------------------------
38 / 40
current local expert:
                     x              y        lon        lat        t  \
2618671  509684.393832  441757.112703  130.91635  83.958305  18262.0

                z  track date_string satellite  lead_mask  dist_along_track  \
2618671  0.097826   1260  2020-01-01       cs2        1.0     924489.634608

         z_track_avg
2618671      0.09918
'local_data_select': 0.001 seconds
number obs: 451
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.048 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01834978, 10.01833228,  1.00044831])
kernel_variance: 0.0064687370807561045
likelihood_variance: 0.01100000000000001
'predict': 0.038 seconds

2026-05-18 19:27:22.595717: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:27:22.597141: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 1.01 seconds
--------------------------------------------------
39 / 40
current local expert:
                     x              y        lon        lat        t  \
2618723  497194.980003  419290.535926  130.14134  84.174323  18262.0

                z  track date_string satellite  lead_mask  dist_along_track  \
2618723  0.115032   1260  2020-01-01       cs2        1.0     950050.777554

         z_track_avg
2618723      0.09918
'local_data_select': 0.001 seconds
number obs: 430
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.052 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01642192, 10.01641253,  1.00099673])
kernel_variance: 0.006386982337391692
likelihood_variance: 0.01100000000000001
'predict': 0.036 seconds

2026-05-18 19:27:23.610422: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:27:23.612577: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

total run time : 1.03 seconds
--------------------------------------------------
40 / 40
current local expert:
                     x              y        lon        lat        t  \
2618775  484983.566989  397357.891614  129.32853  84.384209  18262.0

                z  track date_string satellite  lead_mask  dist_along_track  \
2618775  0.058939   1260  2020-01-01       cs2        1.0     975011.018558

         z_track_avg
2618775      0.09918
'local_data_select': 0.001 seconds
number obs: 405
found GPU
setting lengthscales to: [1. 1. 1.]
'__init__': 0.051 seconds
'_read_params_from_file': 0.044 seconds
'set_parameters': 0.005 seconds
'set_lengthscales_constraints': 0.005 seconds
'set_likelihood_variance_constraints': 0.015 seconds
*** not optimising parameters
'get_parameters': 0.003 seconds
parameters:
lengthscales: array([10.01489149, 10.01488959,  1.00156709])
kernel_variance: 0.006335221919568361
likelihood_variance: 0.01100000000000001
'predict': 0.036 seconds

2026-05-18 19:27:24.645993: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:0 with 20872 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:42:00.0, compute capability: 8.9
2026-05-18 19:27:24.647406: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /device:GPU:1 with 20872 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:c4:00.0, compute capability: 8.9

SAVING RESULTS TO TABLES:
run_details
preds
total run time : 1.17 seconds
'run': 41.451 seconds
reading in results
getting all tables
merging on expert location data
table: 'oi_config' does not have all coords_col: ['x', 'y', 't'] in columns, not merging on expert_locations
table: 'oi_config_SMOOTHED' does not have all coords_col: ['x', 'y', 't'] in columns, not merging on expert_locations
lin:
                     x             y        lon        lat        t         z  \
2617067  950053.565564  1.257429e+06  142.92703  75.851377  18262.0  0.071572
2617068  948798.845002  1.255036e+06  142.91097  75.875434  18262.0 -0.027448
2617069  948380.678230  1.254239e+06  142.90560  75.883453  18262.0  0.082242
2617070  947962.365305  1.253441e+06  142.90023  75.891472  18262.0  0.012394
2617071  947683.408832  1.252910e+06  142.89665  75.896818  18262.0  0.022885

         track date_string satellite  lead_mask  dist_along_track  \
2617067   1260  2020-01-01       cs2        1.0          0.000000
2617068   1260  2020-01-01       cs2        1.0       2704.278190
2617069   1260  2020-01-01       cs2        1.0       3605.750959
2617070   1260  2020-01-01       cs2        1.0       4507.210693
2617071   1260  2020-01-01       cs2        1.0       5108.176609

         z_track_avg     f_lin
2617067      0.09918  0.185981
2617068      0.09918  0.186824
2617069      0.09918  0.187667
2617070      0.09918  0.187580
2617071      0.09918  0.187494
gpsat:
                     x             y        lon        lat        t         z  \
2617067  950053.565564  1.257429e+06  142.92703  75.851377  18262.0  0.071572
2617068  948798.845002  1.255036e+06  142.91097  75.875434  18262.0 -0.027448
2617069  948380.678230  1.254239e+06  142.90560  75.883453  18262.0  0.082242
2617070  947962.365305  1.253441e+06  142.90023  75.891472  18262.0  0.012394
2617071  947683.408832  1.252910e+06  142.89665  75.896818  18262.0  0.022885

         track date_string satellite  lead_mask  dist_along_track  \
2617067   1260  2020-01-01       cs2        1.0          0.000000
2617068   1260  2020-01-01       cs2        1.0       2704.278190
2617069   1260  2020-01-01       cs2        1.0       3605.750959
2617070   1260  2020-01-01       cs2        1.0       4507.210693
2617071   1260  2020-01-01       cs2        1.0       5108.176609

         z_track_avg   f_gpsat  f_var_gpsat
2617067      0.09918  0.051888     0.051888
2617068      0.09918  0.026513     0.026513
2617069      0.09918  0.019280     0.019280
2617070      0.09918  0.013415     0.013415
2617071      0.09918  0.011032     0.011032
Test NaNs — Linear: 0, GPSat: 115
Track interpolated!
All tracks interpolated

/tmp/ipykernel_1171781/839927469.py:200: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  track_df['f_gpsat'] = ssha
/tmp/ipykernel_1171781/839927469.py:201: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  track_df['f_var_gpsat'] = ssha_var
/tmp/ipykernel_1171781/839927469.py:66: RuntimeWarning: invalid value encountered in sqrt
  gpsat_std = np.sqrt(gpsat_var[both_valid])

In [12]:
dfs, _ = get_results_from_h5file('/home/mhen/geol0069_data/gpsat/jan20/1243.h5')

run_details = dfs['run_details']

reading in results
getting all tables
merging on expert location data
table: 'oi_config' does not have all coords_col: ['x', 'y', 't'] in columns, not merging on expert_locations
table: 'oi_config_SMOOTHED' does not have all coords_col: ['x', 'y', 't'] in columns, not merging on expert_locations
               x              y        t  _dim_0  num_obs  run_time  \
0 -584280.987782 -430861.767792  18262.0       0      116  0.408209
1 -570418.599441 -411052.893457  18262.0       0      124  0.390630
2 -555327.315351 -389517.775035  18262.0       0      133  0.403390
3 -542825.464630 -371701.254797  18262.0       0      136  0.367528
4 -525095.068321 -346469.863559  18262.0       0      139  0.368807

   objective_value  parameters_optimised  optimise_success  \
0      -148.145213                  True             False
1      -162.322020                  True              True
2      -176.598838                  True              True
3      -177.445625                  True              True
4      -182.751731                  True              True

                                       model  ... config_id        lon  \
0  GPSat.models.gpflow_models.GPflowGPRModel  ...         1 -53.594113
1  GPSat.models.gpflow_models.GPflowGPRModel  ...         1 -54.222867
2  GPSat.models.gpflow_models.GPflowGPRModel  ...         1 -54.953406
3  GPSat.models.gpflow_models.GPflowGPRModel  ...         1 -55.598498
4  GPSat.models.gpflow_models.GPflowGPRModel  ...         1 -56.582249

         lat         z  track  date_string satellite lead_mask  \
0  83.496633 -0.034818   1243   2020-01-01       cs2       1.0
1  83.701745 -0.005570   1243   2020-01-01       cs2       1.0
2  83.923938  0.000517   1243   2020-01-01       cs2       1.0
3  84.107068  0.049702   1243   2020-01-01       cs2       1.0
4  84.365197 -0.061733   1243   2020-01-01       cs2       1.0

   dist_along_track  z_track_avg
0       1502.990248     0.040157
1      25551.212003     0.040157
2      51704.152824     0.040157
3      73348.337332     0.040157
4     104011.745256     0.040157

[5 rows x 21 columns]

In [13]:
print(dfs.keys())

dict_keys(['expert_locs', 'expert_locs_SMOOTHED', 'kernel_variance', 'kernel_variance_SMOOTHED', 'lengthscales', 'lengthscales_SMOOTHED', 'likelihood_variance', 'likelihood_variance_SMOOTHED', 'oi_config', 'oi_config_SMOOTHED', 'preds', 'preds_SMOOTHED', 'run_details', 'run_details_SMOOTHED'])